### ISSUE TITLE
OpImageRead are not required to return 4-component vector per the spec

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#1007]
The validator requires that OpImageRead must return a vector of 4-component. That does not comply with the spec, which says:

> Result Type must be a scalar or vector of floating-point type or integer type. Its component type must be the same as Sampled Type of the OpTypeImage (unless that Sampled Type is OpTypeVoid).

**Comment by dneto0** [comment]
Fixed by #1010
