### ISSUE TITLE
OpImageRead can return scalar int/float types

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#1009]
The validator right now only allows int/float vector return types on OpImageRead. But the spec says it can also be scalar int/float types:

> Result Type must be a scalar or vector of floating-point type or integer type. Its component type must be the same as Sampled Type of the OpTypeImage (unless that Sampled Type is OpTypeVoid).

**Comment by dneto0** [comment]
Fixed by #1010
