### ISSUE TITLE
Validator should allow scalar int/float texel types for OpImageWrite

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#1011]
https://github.com/KhronosGroup/SPIRV-Tools/blob/e1a6f8d1c3ec4f814d6160ab46b8f397f89f8184/source/validate_image.cpp#L1072-L1077

**Comment by dneto0** [comment]
Fixed by https://github.com/KhronosGroup/SPIRV-Tools/pull/1014
