### ISSUE TITLE
OpSwitch not removed by ADCE

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#1021]
Found this in response to @alan-baker review for #985.  I added ir::Instruction::IsBranch and modified class AggressiveDCEPass to use it instead of its own definition.  In adding a new test, I realized that ADCE does not handle switch().

Attached is the test case I've added.  I'm expecting the whole switch() to be removed, but it isn't.

@greg-lunarg is the test OK?  Or am I missing something?  Thanks.

[00.diff.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1507675/00.diff.txt)

**Comment by greg-lunarg** [comment]
Empty switch removal has not been integrated yet. In fact, I have not yet even implemented it, although I expect it will be a fairly natural extension to empty if removal (already in ADCE) and should not be a lot of work.

Empty loop also has not been integrated, but I do have a version on a branch that I have tested. I have not integrated it as I have been pushing hard on some other DCE needed by a Vulkan development team I am working with. Hopefully this will be integrated soon.

**Comment by dnovillo** [comment]
OK, thanks.  I guess I'm confused as to why it needs to be handled in any particular way.  But I have not looked at the ADCE code, so I am sure I'm missing something obvious.  I will leave the test disabled so that you can use it when incorporating OpSwitch support.

**Comment by dneto0** [comment]
Fixed by #1201
