### ISSUE TITLE
Run clang-format on pull requests

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-Tools#1029]
It’s easy to forget running clang-format before submitting a pull request. Reviewers currently look for wrong formatting, but it could be checked for automatically by a build bot, or as part of an additional check being run on the pull request.

Do some of you have experience with some syntax formatting check being run along the other checks on pull requests?
Maybe something like [this](https://github.com/dokan-dev/dokany/commit/c8ffc494482e299ed025855214db839a561ceab7)? Though it seems like the test still appears as successful on GitHub, even if the formatting needed to be fixed.

**Comment by dneto0** [comment]
I try not to be too picky with formatting with pull requests.  Normally I find something else more important that I'd like fixed.  :-)

Hey @antiagainst what do you think?

I assume that's PowerShell. I've never learned PowerShell. :-)

**Comment by dnovillo** [comment]
I am *ALL* for something like this.  I am always using clang-format to keep my code formatted and I sometimes have tons of noise in my patches when editing existing files.

I'm also unfamiliar with this scripting language.  But if it does what it says, it's got my vote.

**Comment by antiagainst** [comment]
Oh, it suddenly comes to me that clang-format has a mode to only format the changed code: https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting. So it may be fine.

**Comment by dnovillo** [comment]
Yeah, I was going to suggest that option for clang-format.  I've also found that if your style file is stable, the output is stable.  Particularly when using a well-established format like the Google style

**Comment by antiagainst** [comment]
Yep.

We don't want to add more checks into Appveyor. Appveyor is running all jobs sequentially. It already takes more than 1 hour to run a push. Adding checks to Travis is better, IMHO.

**Comment by dnovillo** [comment]
@antiagainst, thanks.  Would you be able to make this change then?  I'm not sure where to start, but if you give me a couple of pointers I can get it done.

**Comment by antiagainst** [comment]
Not a problem. I can do it.

Before that, can we do a wholesale reformatting over the current codebase?
