### ISSUE TITLE
std::less on spvtools::opt::Edge is not a weak ordering

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1034]
This is causing Windows Debug build timeout failures.

**Comment by dnovillo** [comment]
Bug is due to laziness on my part.  Edge::operator<() is using pointer comparisons *and* it's an OR predicate.  *sigh*.

**Comment by dnovillo** [comment]
Fixed with commit 8cfa0c40e0afd5b6fcbedf622fd45afd2de2a055
