### ISSUE TITLE
Use a command-line flag parsing library for spirv-opt.

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#1060]
We are adding new flags, some flags already need additional arguments and more flags will need them too.

Parsing it with a flag parsing library like getopt() (https://www.gnu.org/software/libc/manual/html_node/Getopt.html) or gflags (https://gflags.github.io/gflags/) would simplify things greatly.

**Comment by dneto0** [comment]
The main issue is that whatever you do here will have to be incorporated into downstream builds.  For example:
- Android NDK
- Glslang 
- Shaderc

**Comment by s-perron** [comment]
@Keenuts implemented an internal library.

**Comment by Keenuts** [comment]
One nit: spirv-opt doesn't uses this.
Due to the way spirv-opt generates flags with the optimization passes, it wasn't migrated to the new code, and left as-is. Only the other tools uses it (-as, -val, -diff, ...)
