### ISSUE TITLE
Disable Travis MacOS build

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#1064]
Travis CI's MacOS support is quite flaky. They don't have enough MacOS builders and are frequently flooded by pending jobs: https://www.traviscistatus.com. It recently takes many hours to wait for a MacOS build job to start.

We have fair good testing on Windows and Linux already. So it should give us enough confidence that MacOS should work.

Unless somebody rejects, I'll disable the MacOS build and the automatic deployment for MacOS.

**Comment by danginsburg** [comment]
Do we do clang builds on Linux?  If not, this will likely lead to regressions on macOS.  We build spirv-tools on MacOS here and would be kind of inconvenient to lose this testing.  I'd feel better about it knowing there was at least clang testing on Linux.

**Comment by antiagainst** [comment]
@danginsburg: Yes. We test both clang and gcc on Linux, for both Debug and RelWithDebInfo: https://travis-ci.org/KhronosGroup/SPIRV-Tools.

The version of clang is 3.9.0.

**Comment by antiagainst** [comment]
It seems MacOS infrastructure on Travis is improving:

https://blog.travis-ci.com/2018-01-30-macos-update

And there are no huge backlogs for MacOS anymore:

https://www.traviscistatus.com/

So I'll close this.
