### ISSUE TITLE
Remove code from unreachable blocks that must remain in the CFG

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#1070]
Control flow merge blocks cannot be removed from the CFG (to preserve the control structure). However, code in these blocks is dead, so it should be removed by CFGCleanup.

**Comment by ratchetfreak** [comment]
The entire block can be replaced by opLabel+OpUnreachable

**Comment by s-perron** [comment]
Issue already opened #1027.
