### ISSUE TITLE
Image Operand Sample can only be used with OpImageFetch, OpImageRead and OpImageWrite: ImageSparseFetch

### ISSUE THREAD

**Issue by ehsannas** [KhronosGroup/SPIRV-Tools#1100]
I don't think this is a correct error to get:

```
Image Operand Sample can only be used with OpImageFetch, OpImageRead and OpImageWrite: ImageSparseFetch
```

My understanding is that the "Sparse" version of these instructions (OpImageSparseFetch, OpImageSparseRead, and OpImageSparseWrite) should also be OK.

CC @antiagainst: These errors show up if I upgrade spirv-tool in our codebase.

**Comment by antiagainst** [comment]
+1

**Comment by atgoo** [comment]
Well, that's because the spec says exactly that.

Sample
A following operand is the sample number of the sample to use. Only valid with OpImageFetch, OpImageRead, and OpImageWrite.

**Comment by ehsannas** [comment]
oh! All right, IIUC the spec should be fixed then. I'll report an issue.
