### ISSUE TITLE
Insufficient handling of capabilities

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1101]
In the module class, there is a function `HasCapability`.  It is suppose to return true of the module has a certain capability.  It is implemented by looking for the capability in question in the list of OpCapability instruction.  The problem is that this is not enough.

When one capability depends on another, the other is implicitly enabled, even if it is not explicitly present.  This needs to be improved.

**Comment by s-perron** [comment]
@alan-baker suggested we add this to the feature manager.  As we read each capability, the feature manger keeps track of all explicitly and implicitly enabled capabilities.

The name of the function on the module could change to `HasExplicitCapability` or something like that.

**Comment by dneto0** [comment]
The validator handles this transitive closure in ValidationState_t::RegisterCapability.

Agree the optimizer needs the transitive closure too.

**Comment by dneto0** [comment]
Fixed by #1122
