### ISSUE TITLE
Remove duplicates incorrectly removes non-duplicate decorations

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1108]
RemoveDuplicatesPass attempts to remove duplicate decorations by asking AreDecorationsTheSame(). DecorationManager::AreDecorationsTheSame() does not check the target operands (target id for OpDecorate and type and element for OpMemberDecorate).

**Comment by pierremoreau** [comment]
I’ll send a pull request shortly which reworks `DecorationManager::AreDecorationsTheSame()` and fixes this bug, as well as another one, and adds tests for remove duplicates and parts of the decoration manager.

**Comment by alan-baker** [comment]
@pierremoreau I don't think DecorationManager is incorrect. I plan to fix how RemoveDuplicatesPass determines which decorations are duplicates. I'm currently working on this. I forgot to move it to in progress.

**Comment by pierremoreau** [comment]
This should do it, I think: https://github.com/pierremoreau/SPIRV-Tools/commit/92364300ed07ac224976999ea99c7bfb5752b15b . I have more patches on https://github.com/pierremoreau/SPIRV-Tools/tree/decoration_manager_fixes and am currently adding test for RemoveDuplicatesPass.

**Comment by pierremoreau** [comment]
I submitted a pull request with my work. It contains another fix to AreDecorationsTheSame() as well as unit tests for that function and HaveTheSameDecorations(). I also added unit tests for the various part of RemoveDuplicatesPass. If you think anything is missing from it, feel free to add/comment  on it.

**Comment by alan-baker** [comment]
Fixed in 424f744db16879c09ce9c839de4954eca7580565
