### ISSUE TITLE
DecorationManager::HaveTheSameDecorations should be symmetric

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1112]
There is a TODO for this.  I'm filing an issue for this because the method name implies the check is symmetric, but it is not symmetric

Cc: @pierremoreau

**Comment by pierremoreau** [comment]
If no one started working on this one, I’ll give it a shot.

**Comment by dneto0** [comment]
Thanks.  I don't think anybody else has started it.

I will be on vacation the next week, so take your time.  :-)
