### ISSUE TITLE
Update the legalization passes

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1118]
For Spiregg, we want to try a different set of optimizations for legalization.  The idea is limit the number of optimization that are expected to be preformed on the illegal code.  The idea will be to do a thorough copy propagation.  All optimizations must be there to handle some specific problem related to copy propagation.

The new list of optimization will be:

1. Inlining - Place the definition and use in the same function to enable copy propagation.
1. Dead function elimination - remove references to private variables in function that are not used.  This will in general leave accesses to private variables in just 1 function.
1. Private to local - make private variables function scope to make it obvious that all uses are in a single function.
1. Scalar replacement - Split up aggregates so that copy propagation can act on each member individually.
1. Multi Store Elimination - Remove the loads and stores and keep values in the intermediate values.  They are easier to deal with because they are in ssa form.  This optimization also does a lot of it own copy propagation.
1. Insert-extract elimination - Scalar replacement can leave sequences of OpCompositConstruct that are then split up using OpCompositExtract.  This pass does the copy propagation through those.
1. CFG cleanup - remove branches that are know to always branch in one direction, and propagate the simplified Phi nodes.
1. Dead code elimination - Cleanup any unused code that could leave remnants of the illegal code.

**Comment by antiagainst** [comment]
To keep track of known issues:

* HS/DS/GS is not supported right now because of insufficient capability probing #1101
* Some pointer-to-pointer types are not cleaned because of lacking of dead type elimination #833

**Comment by antiagainst** [comment]
cc @ehsannas @chaoticbob

**Comment by s-perron** [comment]
@antiagainst  pointed out that I might want "Dead branch elimination":

```
if (true) {
a = ...
} else {
b = ...
}
c = phi(a, b)
```

I thought cfg cleanup was suppose to clean this up, but apparently not.  @greg-lunarg @dnovillo Can the two of you comment on exactly what each optimization is suppose to do or not do?  How will the constant propagator handle this?

**Comment by greg-lunarg** [comment]
Re --convert-local-access-chains, I am pretty sure that I can write a shader that will depend on this in order to legalize. Let me know if you would like me to write one.

**Comment by greg-lunarg** [comment]
I am not completely up on the capabilities of CFGCleanup or the constant propagator. I can tell you that DBE converts all OpBranchConditionals with a constant condition to the appropriate OpBranch (and removes any newly dead blocks).

**Comment by dnovillo** [comment]
On Wed, Dec 20, 2017 at 2:25 PM, Steven Perron <notifications@github.com>
wrote:

> @antiagainst <https://github.com/antiagainst> pointed out that I might
> want "Dead branch elimination":
>
> if (true) {
> a = ...
> } else {
> b = ...
> }
> c = phi(a, b)
>
> I thought cfg cleanup was suppose to clean this up, but apparently not.
> @greg-lunarg <https://github.com/greg-lunarg> @dnovillo
> <https://github.com/dnovillo> Can the two of you comment on exactly what
> each optimization is suppose to do or not do? How will the constant
> propagator handle this?
>

This is a task for CFG cleanup.  CCP leaves these around.  I'll augment CFG
cleanup. This is called for in #889.

**Comment by greg-lunarg** [comment]
What is the reason for "limiting" the number of optimizations for legalization? Is it to reduce compile time? If so, you may be interested in the following:

I took your recipe above (ok, I added --convert-local-access-chains). On my benchmark shader, spirv-opt averaged 0.26s.

I then added --eliminate-local-single-block --eliminate-local-single-store --eliminate-insert-extract --eliminate-dead-code-aggressive --eliminate-dead-branches before --eliminate-local-multi-store. The average time actually went down to 0.19s.

Your mileage may vary. The point is that these can all reduce the work needed to be done by --eliminate-local-multi-store (which is a more expensive algorithm) enough so they pay for themselves and more. LLVM also does single-store and single-block optimizations before doing putting things into SSA form.

**Comment by dneto0** [comment]
@s-perron: What's the status of this issue? 
 
Also, per @greg-lunarg's suggestion, it might help if you describe how you're determining whether you've gone far enough (and implictly not "too far").  E.g. it would be great if you said "fixes everything in my corpus and in Greg's corpus", however those corpora are defined.  (Yes I had to look up the plural of corpus!)

For the benefit of the ecosystem, it would be great if Glslang and Spiregg(DXC) would converge on the same set of transforms for HLSL legalization.  There would be less to explain.

**Comment by antiagainst** [comment]
We are still fixing a few front end defects that result in validation errors of other categories under `--relax-logical-pointer`. After that, legalization transformations will have input satisfying their expectations. Then we will run over our shader corpus to see whether the current list needs tweaking.
