### ISSUE TITLE
Extend CFG cleanup to simplify conditional and multiway branches

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#1124]
Transformations may leave conditional jumps that can be fully resolved at compile time.  For example, constant propagation (#1102) transforms

```
%9 = OpIAdd %int %int_4 %int_3
%6 = OpSGreaterThan %bool %9 %int_3
     OpSelectionMerge %25 None
     OpBranchConditional %6 %22 %23
```

into 

```
%9 = OpIAdd %int %int_4 %int_3
%6 = OpSGreaterThan %bool %int_7 %int_3
     OpSelectionMerge %25 None
     OpBranchConditional true %22 %23
```

CFG cleanup should straighten out that conditional into an unconditional branch, and perhaps even join the basic blocks.

**Comment by dneto0** [comment]
Dead branch elim does the straightening out.  With #1173 it even works for non-Shader modules.
