### ISSUE TITLE
Propagator engine: ignores OpKill and OpUnreachable

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1127]
The propagator engine adds edges to the pseudo-exit node to a block ending in OpReturn or OpReturnValue.  This ignores OpKill and OpUnreachable.  Those are block terminators that also lead nowhere in the control graph.

I think you want the same concept of pseudo-exit node that the validator uses for its augmented CFG.  See CFA<BB>::ComputeAugmentedCFG.

I'm not sure if this is a bug, but @dnovillo should investigate.

**Comment by dneto0** [comment]
Reading the code some more, I don't know why you want edges into the pseudo-exit node at all.

The only uses of bb_succs_ is to
- seed the edge list at the start, and
- follow real control edges.

Am I missing something?  At any rate the code could use better comments to avoid confusion like mine.

**Comment by dneto0** [comment]
Also, the bb_preds_ are created but unused.  I think we can delete that entirely.

**Comment by s-perron** [comment]
The propagator engine was meant to be general infra with the one initial use. We never used it for anything else. It is working now. We will do any clean up that is needed if we have to use it again.
