### ISSUE TITLE
Add support for integer arithmetic different than 32-bits in folder

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#1132]
FoldScalars() and FoldVectors() currently operate on 32-bit integers only.  They should be extended to handle 64-bit arithmetic as well.

**Comment by dneto0** [comment]
Make sure they work with 16bit ints and floats too, or refuse to fold.

**Comment by dnovillo** [comment]
Good point.  I've updated the mission statement for this issue.

**Comment by s-perron** [comment]
We have written a new folding infrastructure that can do this.
