### ISSUE TITLE
[InstCombine] Merge consecutive vector element extract and construct into one construct

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#1134]
In HLSL, the following code pattern is quite common:

```hlsl
float3 v1 = ...
float4 v2 = float4(v1, 1.0);
```

This translates into

```llvm
         %e0 = OpCompositeExtract %float %v1 0
         %e1 = OpCompositeExtract %float %v2 1
         %e2 = OpCompositeExtract %float %v3 2
         %v2 = OpCompositeConstruct %v4float %e0 %e1 %e2 %float_1
```

Which could be turned into

```llvm
         %v2 = OpCompositeConstruct %v4float %v1 %float_1
```

This results in less code.

**Comment by dneto0** [comment]
Wow, I don't think I've seen that case of using a vector operand for vector construction.  I checked and the validator does accept that.  I wonder what the CTS test coverage is like!

**Comment by antiagainst** [comment]
Yep. This may be a problem for some drivers.

The spec explicitly allows it so I am thinking why not using it? :)
