### ISSUE TITLE
Unused functions in type_manager_test.cpp

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-Tools#1135]
clang 5.0.1 complains about the following functions being defined but unused in “test/opt/type_manager_test.cpp”: “Validate()” and “GenerateAllTypes()”. Using the regular flags, the warning is being treated as an error and prevents from compiling the project.

Are those functions supposed to be used in the future, or can they be safely removed?

**Comment by antiagainst** [comment]
Fixed via #1141
