### ISSUE TITLE
Turn the two `Linker::link()` functions into free functions

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-Tools#1139]
From https://github.com/KhronosGroup/SPIRV-Tools/pull/693#discussion_r141394561

>  Given that not much state needs to be retained, another acceptable solution is that the external API could have been two free functions, where the target environment and message consumer would be two more arguments.

**Comment by dneto0** [comment]
WIP #1149

**Comment by dneto0** [comment]
Fixed by #1149
