### ISSUE TITLE
Inconsistent tabs/spaces in python files

### ISSUE THREAD

**Issue by xnoreq** [KhronosGroup/SPIRV-Tools#1140]
See for example generate_grammar_tables.py line 695:
![screenshot](https://user-images.githubusercontent.com/4028859/34325973-5e70e8c4-e8a2-11e7-87bf-ec54e99925bd.png)

It seems @dneto0 uses 8 spaces/tab (while the screenshot above uses 4). Please use a tool like `expand` to prevent python's “inconsistent use of tabs and spaces in indentation” TabError.

**Comment by antiagainst** [comment]
Done via #1142
