### ISSUE TITLE
Opt: --ccp (and -O and -Os) generates incorrect code for integer for-loops

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#1143]
Test case:

; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 3
; Bound: 43
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %o
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 430
               OpName %main "main"
               OpName %U_t "U_t"
               OpMemberName %U_t 0 "g_F"
               OpName %_ ""
               OpName %o "o"
               OpDecorate %_arr_float_uint_10 ArrayStride 4
               OpMemberDecorate %U_t 0 Offset 0
               OpDecorate %U_t BufferBlock
               OpDecorate %_ DescriptorSet 0
               OpDecorate %o Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
%_ptr_Function_float = OpTypePointer Function %float
    %float_0 = OpConstant %float 0
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
      %int_0 = OpConstant %int 0
     %int_10 = OpConstant %int 10
       %bool = OpTypeBool
       %uint = OpTypeInt 32 0
    %uint_10 = OpConstant %uint 10
%_arr_float_uint_10 = OpTypeArray %float %uint_10
        %U_t = OpTypeStruct %_arr_float_uint_10
%_ptr_Uniform_U_t = OpTypePointer Uniform %U_t
          %_ = OpVariable %_ptr_Uniform_U_t Uniform
%_ptr_Uniform_float = OpTypePointer Uniform %float
      %int_1 = OpConstant %int 1
%_ptr_Output_float = OpTypePointer Output %float
          %o = OpVariable %_ptr_Output_float Output
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpBranch %14
         %14 = OpLabel
         %41 = OpPhi %float %float_0 %5 %34 %17
         %42 = OpPhi %int %int_0 %5 %37 %17
               OpLoopMerge %16 %17 None
               OpBranch %18
         %18 = OpLabel
         %22 = OpSLessThan %bool %42 %int_10
               OpBranchConditional %22 %15 %16
         %15 = OpLabel
         %31 = OpAccessChain %_ptr_Uniform_float %_ %int_0 %42
         %32 = OpLoad %float %31
         %34 = OpFAdd %float %41 %32
               OpBranch %17
         %17 = OpLabel
         %37 = OpIAdd %int %42 %int_1
               OpBranch %14
         %16 = OpLabel
               OpStore %o %41
               OpReturn
               OpFunctionEnd

spirv-opt --ccp generates the following for the function:

       %main = OpFunction %void None %3
          %5 = OpLabel
               OpBranch %14
         %14 = OpLabel
         %41 = OpPhi %float %float_0 %5 %34 %17
         %42 = OpPhi %int %int_0 %5 %int_1 %17
               OpLoopMerge %16 %17 None
               OpBranch %18
         %18 = OpLabel
         %22 = OpSLessThan %bool %int_0 %int_10
               OpBranchConditional %true %15 %16
         %15 = OpLabel
         %31 = OpAccessChain %_ptr_Uniform_float %_ %int_0 %int_0
         %32 = OpLoad %float %31
         %34 = OpFAdd %float %float_0 %32
               OpBranch %17
         %17 = OpLabel
         %37 = OpIAdd %int %int_0 %int_1
               OpBranch %14
         %16 = OpLabel
               OpStore %o %float_0
               OpReturn
               OpFunctionEnd

This instruction is incorrect:

         %42 = OpPhi %int %int_0 %5 %int_1 %17

Specifically, the %int_1 value is wrong.

**Comment by greg-lunarg** [comment]
Here is the GLSL of the test case:

#version 430

layout(std430) buffer U_t
{
    float g_F[10];
};

layout(location = 0)out float o;

void main(void)
{
    float s = 0.0;
    for (int i=0; i<10; i++)
        s += g_F[i];
    o = s;
}

**Comment by dnovillo** [comment]
Thanks for the test case, @greg-lunarg.  I'll work on a fix.

**Comment by dneto0** [comment]
A quick look reveals also that the induction variable test and branch are also incorrect:

```
     %22 = OpSLessThan %bool %int_0 %int_10
           OpBranchConditional %true %15 %16
```

**Comment by dnovillo** [comment]
I think this may be somehow related to #1159.  The presence of self-referential Phi instructions is causing the propagator to add the same phi node onto its work list over and over again.  I'm building a test case manually.

**Comment by dnovillo** [comment]
It's related to #1159 but not the same.  I minimized the test case further.  Debugging now:

```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main"
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 430
               OpName %main "main"
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
      %int_0 = OpConstant %int 0
     %int_10 = OpConstant %int 10
       %bool = OpTypeBool
      %int_1 = OpConstant %int 1
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpBranch %11
         %11 = OpLabel
         %26 = OpPhi %int %int_0 %5 %22 %14
         %27 = OpPhi %int %int_0 %5 %25 %14
               OpLoopMerge %13 %14 None
               OpBranch %15
         %15 = OpLabel
         %19 = OpSLessThan %bool %27 %int_10
               OpBranchConditional %19 %12 %13
         %12 = OpLabel
         %22 = OpIAdd %int %26 %27
               OpBranch %14
         %14 = OpLabel
         %25 = OpIAdd %int %27 %int_1
               OpBranch %11
         %13 = OpLabel
               OpReturn
               OpFunctionEnd
```

As observed above, ee somehow fail to evaluate the meet for `%27` properly.  It's meeting `%int_0` and `%int_1` and somehow ending up with `%int_0` instead of `Varying` (which is 'bottom' in the original lattice).

**Comment by dnovillo** [comment]
Smaller test case to be included with the fix:

```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main"
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 430
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpName %main "main"
       %void = OpTypeVoid
          %5 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
      %int_0 = OpConstant %int 0
     %int_10 = OpConstant %int 10
       %bool = OpTypeBool
      %int_1 = OpConstant %int 1
       %main = OpFunction %void None %5
         %12 = OpLabel
               OpBranch %13
         %13 = OpLabel
         %22 = OpPhi %int %int_0 %12 %21 %15
               OpLoopMerge %14 %15 None
               OpBranch %16
         %16 = OpLabel
         %18 = OpSLessThan %bool %22 %int_10
               OpBranchConditional %18 %19 %14
         %19 = OpLabel
               OpBranch %15
         %15 = OpLabel
         %21 = OpIAdd %int %22 %int_1
               OpBranch %13
         %14 = OpLabel
               OpReturn
               OpFunctionEnd
```

**Comment by dnovillo** [comment]
Found the bug.  The way the meet operator for Phi instructions works is to only evaluate Phi arguments that arrive from executable edges.  This Phi instruction is visited twice.  On the first visit, the only executable argument is the first one, which carries %int_0.  We then save %int_0 in the values table as the value for that Phi.

On the second visit, it sees %int_10 which meets with %int_0 to produce Varying.  However, we never remove the value %int_0 from the values table.  So, the final replacement of values uses the stale value.  Sigh.

PR coming up shortly.

**Comment by dnovillo** [comment]
There is an additional wrinkle.  I think I need to actually model varying values in the value table.  The transition from constant to varying in the Phi node is not being reflected in the expressions that use its result.  The expressions find that the operand for the Phi now has no value, but they already had a value in them, so they don't drop to varying.
