### ISSUE TITLE
spirv-val does not catch when SampleMask is not declared as an array

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/SPIRV-Tools#1146]
The Vulkan specification 1.0.66 states:

"Any variable decorated with SampleMask must be declared as an array of 32-bit integers."

However, there was a bug in glslang where for HLSL it was outputting SampleMask as just a 32-bit integer, see: https://github.com/KhronosGroup/glslang/issues/1202

I think spirv-val should catch this error in the vr_standard_ps.spv attached to that bug.

**Comment by sfricke-samsung** [comment]
`VUID-SampleMask-SampleMask-04359` in the Vulkan spec cover this and was labeled (and has a test for it `SampleMaskNotArray`) in https://github.com/KhronosGroup/SPIRV-Tools/pull/3756 

So think can close here
