### ISSUE TITLE
Display Invalid Instruction

### ISSUE THREAD

**Issue by disks86** [KhronosGroup/SPIRV-Tools#1148]
Instead of just displaying the last valid instruction if the invalid instruction could be printed as well that would be very helpful. For example if you receive "error: 11979: Id is 0" you can't tell what Id is zero based on the output because the invalid instruction is not displayed.

**Comment by dneto0** [comment]
This is similar to an earlier complaint #670.

Yes, the error reporting is particularly bad.  Sorry about that.  I've been thinking about how to improve the situation and backport the change to all or most of the existing validation checks.

**Comment by doitsujin** [comment]
This is noticable not only in the validator but in spirv-dis as well. It would be helpful if the disassembler could ignore these errors if possible and display the numerical value of invalid IDs, unrecognized opcodes, flags etc.

**Comment by dneto0** [comment]
See #1221 for partial progress.  The validator will show the offending instruction during some parts of its processing (essentially the first scan of the module).  It's not yet what you want, but it might help.

**Comment by dj2** [comment]
I believe this should now be fixed. The error messages should be outputting the correct lines at this point, if they aren't please file new issues with examples.
