### ISSUE TITLE
Dead branch elim can generate invalid def use chains during processing

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1157]
If dead branch elim erases a section of code that is later referenced in a phi node, the pass may assert about missing definitions because because definition is removed before updating its uses.

**Comment by dneto0** [comment]
It looks like https://github.com/KhronosGroup/glslang/issues/1205 might be the same issue as this.  There is a test case there.

**Comment by greg-lunarg** [comment]
@alan-baker Have you looked at KhronosGroup/glslang#1205 yet? I will start with that unless you think you already have a solution.

**Comment by greg-lunarg** [comment]
If you have something for this issue, pass me a branch and I will see if it also fixes the other issue.

**Comment by alan-baker** [comment]
Here is a minimal testcase (run spirv-opt --eliminate-dead-branches in debug to trigger assertion).

>OpCapability Shader
>OpMemoryModel Logical GLSL450
>OpEntryPoint Fragment %func "main"
>OpExecutionMode %func OriginUpperLeft
>%void = OpTypeVoid
>%bool = OpTypeBool
>%1 = OpTypeFunction %void
>%false = OpConstantFalse %bool
>%true = OpConstantTrue %bool
>%bool_ptr = OpTypePointer Input %bool
>%var = OpVariable %bool_ptr Input
>%func = OpFunction %void None %1
>%entry = OpLabel
>OpSelectionMerge %outer_merge None
>OpBranchConditional %false %inner_header %else
>%inner_header = OpLabel
>%load = OpLoad %bool %var
>OpSelectionMerge %inner_merge None
>OpBranchConditional %load %inner_then %inner_merge
>%inner_then = OpLabel
>OpBranch %inner_merge
>%inner_merge = OpLabel
>%inner_phi = OpPhi %bool %false %inner_header %true %inner_then
>OpBranch %outer_merge
>%else = OpLabel
>OpBranch %outer_merge
>%outer_merge = OpLabel
>%outer_phi = OpPhi %bool %inner_phi %inner_merge %false %else
>OpReturn
>OpFunctionEnd

**Comment by alan-baker** [comment]
The above example attempts to delete only %inner_merge and not %inner_then or %inner_merge which creates invalid IR.

**Comment by alan-baker** [comment]
![minimal-cfg](https://user-images.githubusercontent.com/33432579/34578449-fb5a5536-f152-11e7-9927-3b10670b2d08.png)

Erases 11, but not 14 or 15.

**Comment by dneto0** [comment]
I'm attaching SPIR-V assembly for the input to dead branch elim, from original Glslang issue 1205.

[foo.spvasm.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1604982/foo.spvasm.txt)

Sometimes this is optimized correctly, other times the live remaining branch is deleted which is invalid.

Further investigation shows that the test for HasNonPhiNonBackedgeRef is returning inconsistent answers.  That points to def-use inconsistency.

**Comment by dneto0** [comment]
@alan-baker filed this issue for a test case he's still working on.
I have a fix for https://github.com/KhronosGroup/glslang/issues/1205 which might have a different underlying cause.  I'll file a separate issue for mine.

**Comment by dneto0** [comment]
I filed https://github.com/KhronosGroup/SPIRV-Tools/issues/1168  for my issue.

**Comment by dneto0** [comment]
@alan-baker is this resolved by #1173?

**Comment by alan-baker** [comment]
Yes, this is fixed by #1173 .
