### ISSUE TITLE
SSAPropagator::Run hangs on a complex shader

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Tools#1159]
Running the standard set of optimization passes:

			tools.RegisterSizePasses();
			tools.RegisterPerformancePasses();

On the attached shader hangs the optimizer; it looks like the loop in SSAPropagator::Run never terminates. This is most likely a semi-recent regression - the shader built & optimized fine with glslang & SPIRV-Tools around 1 month ago.

[test.spv.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1602027/test.spv.zip)

**Comment by dnovillo** [comment]
Thanks for the report.  Triaging.

**Comment by dneto0** [comment]
I just saw a hang with --ccp on the test case from  https://github.com/KhronosGroup/glslang/issues/1205 Let me know if you want me to attach it here.

**Comment by dnovillo** [comment]
Yes, please.  If it's not the same root cause, I'll create a new issue.

**Comment by dneto0** [comment]
Here's the test case from Glslang issue 1205. 
[glslang-1205.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1604318/glslang-1205.zip)

It hangs in spirv-opt just running --ccp

**Comment by dnovillo** [comment]
The propagator is getting into an infinite loop when analyzing phi instructions, the SSA edge list is getting populated with the same ssa edge over and over again:

```
(gdb) p ssa_edge_uses_
$6 = std::queue wrapping: std::deque with 78441 elements = {0xa787e0, 0xa787e0, 0xa787e0,
  0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0,
  0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0, 0xa787e0, [...]
```

Reducing for a smaller reproducer.
