### ISSUE TITLE
assert(base_inst->IsValidBasePointer()) in Instruction::GetBaseAddress()

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Tools#1160]
When running the optimization passes on the attached shader, this assertion fails:

```
  assert(base_inst->IsValidBasePointer() &&
         "We cannot have a base pointer come from this load");
```

[test.spv.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1602043/test.spv.zip)

**Comment by s-perron** [comment]
I'll take a look at this.
