### ISSUE TITLE
Folding non-constant expressions

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1164]
Many times there are expressions that can be simplified even if not all of the operands are constants.  A few of these are:

```
n+0
n*0
n*1
n / 1
b && true
b && false
b || true
b || false
```
It can be useful to simplify these, especially if they fold to a constant like `b && false`.

This issue will have a few different parts to it:

- [x] Write a utility that folds any instruction if possible.
- [x] Make use of this new utility in CCP
- [x] Make use of this new utility in GVN

**Comment by dnovillo** [comment]
This is already reported in #896.  I'll assign it to you, if you're ready to start working on this.

**Comment by s-perron** [comment]
We have done all of the main parts of this.  We still have lots of folding rules we can add, but separate issues should be opened for those that are needed.
