### ISSUE TITLE
Adapt C-Reduce to work on SPIR-V.

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#1165]
https://embed.cs.utah.edu/creduce/

This tool works on C/C++, but it can be adapted to work on other IRs.  I'm not sure how difficult this task is, but it is an extremely useful tool to minimize test cases.

**Comment by dneto0** [comment]
Thanks to @afd, SPIRV-Tools now has spirv-reduce (!)
