### ISSUE TITLE
spirv-dis can't output colour to non-tty

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/SPIRV-Tools#1170]
In [`tools/dis/dis.cpp`](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/tools/dis/dis.cpp#L155) it checks for `allow_color` (meaning `--no-color` _wasn't_ passed - i.e. the default as long as `SPIRV_COLOR_TERMINAL` is enabled) and `output_is_tty` before setting the `SPV_BINARY_TO_TEXT_OPTION_COLOR` option.

This is fine as a default behaviour so that you don't get control codes when piping to a file, however this means that if the output is **not** a TTY there is no way to get color output. This can be useful if you do e.g. `spirv-dis foo.spv | less -R` to tell `less` to pass through control codes and get coloured browsing.

For example I hacked in something locally:

```patch
diff --git a/tools/dis/dis.cpp b/tools/dis/dis.cpp
index 51ee4a0..f4aca45 100644
--- a/tools/dis/dis.cpp
+++ b/tools/dis/dis.cpp
@@ -65,6 +65,7 @@ int main(int argc, char** argv) {
   const char* outFile = nullptr;

   bool allow_color = false;
+  bool force_color = false;
 #ifdef SPIRV_COLOR_TERMINAL
   allow_color = true;
 #endif
@@ -79,6 +80,9 @@ int main(int argc, char** argv) {
         case 'h':
           print_usage(argv[0]);
           return 0;
+        case 'c':
+          force_color = true;
+          break;
         case 'o': {
           if (!outFile && argi + 1 < argc) {
             outFile = argv[++argi];
@@ -91,6 +95,8 @@ int main(int argc, char** argv) {
           // Long options
           if (0 == strcmp(argv[argi], "--no-color")) {
             allow_color = false;
+          } else if (0 == strcmp(argv[argi], "--force-color")) {
+            force_color = true;
           } else if (0 == strcmp(argv[argi], "--no-indent")) {
             allow_indent = false;
           } else if (0 == strcmp(argv[argi], "--offsets")) {
@@ -152,7 +158,7 @@ int main(int argc, char** argv) {
 #if defined(_POSIX_VERSION)
     output_is_tty = isatty(fileno(stdout));
 #endif
-    if (allow_color && output_is_tty) {
+    if (allow_color && (output_is_tty || force_color)) {
       options |= SPV_BINARY_TO_TEXT_OPTION_COLOR;
     }
   }
```

**Comment by dneto0** [comment]
Makes sense as a use case and the implementation looks right.
I'd make the option `--color` and have it negate any previous --no-color, and --no-color would negate any previous --color.

**Comment by baldurk** [comment]
Yeh I just put the diff there as what I hacked in locally to illustrate the logic I meant, I leave the actual implementation up to you :smile:.
