### ISSUE TITLE
DecorationManager does not properly handle decoration groups

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1174]
When decorations of an instruction are killed, only the leaf instruction are handled. Groups and group decorates are not properly removed. Additionally, since leaves are removed, we could incorrectly remove decorations for a live value (because OpGroupDecorate can specify multiple targets).

**Comment by pierremoreau** [comment]
The whole `RemoveDecoration()` needs to be redone, as it no longer works even for lead decorations (the mappings are removed within the manager, but the instructions remain). I’ll work on that

**Comment by alan-baker** [comment]
If you take a look at my PR #1147. You can see how I approach removing all dead decorations. You may find that useful for this.

**Comment by pierremoreau** [comment]
I have a WIP available at https://github.com/pierremoreau/SPIRV-Tools/tree/fix_removedecoration; I still need to do some cleanup and add more unit tests to it before submitting it.
I’ll have a look at your PR, thanks for the link.

**Comment by pierremoreau** [comment]
I was wondering, would it be okay to have `DecorationManager::RemoveDecorationFrom()` not remove decoration groups with no targets, and leave that to a later pass? Logic for that should already be part of ACDE thanks to @alan-baker’s work.

**Comment by pierremoreau** [comment]
(Note: this is assuming OpGroupDecorate can target other groups. If this is not the case, then everything’s fine.)
