### ISSUE TITLE
Add early return versions of ForEach* methods

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1192]
There are currently many cases where code could be more efficient if the ForEach* method took a functor with a boolean return value (as opposed to a void return). To avoid confusion, add early return versions as WhileEach* (e.g. ForEachInId -> WhileEachInId). The ForEach* method should be implemented in terms of the WhileEach* method. Example:

void WhileEachInId(std::function<bool(uint32_t id)> f);

void ForEachInId(std::function<void(uint32_t id)> f) {
  WhileEachInId([f](uint32_t id) {
    f(id);
    return true;
  }
}

**Comment by dneto0** [comment]
Fixed by #1196
