### ISSUE TITLE
Use unifed1 headers from SPIRV-Headers

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1195]
This is the way of the future.

It requires restructuring of grammar tables.  I'm taking this one.

**Comment by dneto0** [comment]
Since we're ingesting only one version of JSON file, we should have a single set of tables to represent the grammar.  We need to represent each token as either:  Reserved, Conditional, or Universal.

I plan to use the current representation of a token, but add a "min version" field so that:
 - Reservation uses min version of effectively SPV_ENV_UNIVERSAL_infinity
 - Conditional uses min version SPV_ENV_UNIVERSAL_1_2 for example when "version" in the grammar is "1.2"
 - Universal uses min version SPV_ENV_UNIVERSAL_1_0

Then you can have a total order for determining membership, where you select from SPV_ENV_UNIVERSAL_1_0, up through latest SPV_ENV_UNIVERSAL_1_2 and an internal-only "infinity" value.  A target env of a client API, e.g. SPV_ENV_VULKAN_1_0 would map to representative value SPV_ENV_UNIVERSAL_1_0 for the purposes of comparison in this total order.

**Comment by dneto0** [comment]
PR #1244 updates the #include directives to use the unified directories.

Still want to make unified grammar tables.

**Comment by antiagainst** [comment]
#1413 implements this.

**Comment by dj2** [comment]
Given #1413 landed, I'm going to close this as fixed.
