### ISSUE TITLE
Local redundancy elimination is copying value table

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1205]
The functor in EliminateRedundanciesInBB missed capturing the value table by reference.

When profiling an outlying shader, compile time for legalization and optimization dropped from ~90sec to ~23sec on Windows built in Release with debug info.

**Comment by dneto0** [comment]
Fixed by #1205

**Comment by alan-baker** [comment]
Fixed by #1206
