### ISSUE TITLE
Handle phi updates in block merge pass

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1224]
The block merge pass bails on merging blocks if there are phis that reference the block that will be deleted. This should not inhibit the optimization, instead the phi nodes should be updated to indicate the updated incoming block.

A possible alternative for the block merging would be to delete the block with the unconditional branch, but that might not significantly limit the problem.

**Comment by dneto0** [comment]
@alan-baker :  If this is fully fixed, then please close.
