### ISSUE TITLE
dead_branch_elim_pass.cpp doesn't check whether GetMergeInst returns null

### ISSUE THREAD

**Issue by sheredom** [KhronosGroup/SPIRV-Tools#1245]
I've had a report from a user that the following line https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/dead_branch_elim_pass.cpp#L156 causes a null pointer to be dereferenced as `GetMergeInst()` returns `nullptr`.

Naively a fix could be just to check that `mergeInst` is != `nullptr` before the remaining logic on the line.

**Comment by alan-baker** [comment]
Thanks for the report. I'll fix this.

**Comment by alan-baker** [comment]
Committed in bd6ba3fbb43c90ba273f1c9813b2d041b8a6f601
