### ISSUE TITLE
HLSL legalization: invalid opcode for shader stage.

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1247]
Another problem that has come up in the HLSL legalization area is the use of specific opcodes that are not legal for the given shader stage.  For example, an `OpImageSampleImplicitLod` instruction can only be used in  fragment shader.  The generic HLSL code that is written will contain instructions of these types in non-fragment shaders, but, on close examination, there result will not be used.

If the optimizer is able to do many optimizations, then these instructions can be removed.  The problem is that the users many not always want to optimize that much, or the optimizer may not be good enough to prove that the invalid instruction's results are not used.

The help with this problem, I would like to add a pass that will assume these invalid instructions are not used, and replace them with a constant value.

1. The instructions that will be replaced are those valid for shader, but not for the current shader stage.
1. They will be replaced by a specific constant.
1. A warning will be added to the message consumer for each instruction that is replaced, with file and line number when available.
1. If a module has multiple entry points for different shader stages, then the pass will do nothing.
    1. This limitation could be removed at a later time if we need to.

The advantages of this approach are:

1. Correct code will not see any behavior change, and will not have to wait for improvements to the optimizer in order to be able to run.
1. This allows the possibility of a non-optimized compile that makes debugging easier.

The disadvantages of this approach are:

1. For incorrect code, the compiler would have issued an error before.  Not the user will have to identify a possibly subtle error in the output of the shader.
    1. The ideal solution would be to have the shader "trap"; however, that type of instruction does not seem to be available.
    1.  These compiler errors will probably be false positives for the HLSL, so the error is not very useful anyway.
    1. This replacement will not be turned on by default, so users will be aware when this might be happening.
    1. The warnings can give an idea where the replacement is taking place allowing the user to at least look at those locations to see if they are a problem.

**Comment by s-perron** [comment]
@antiagainst @dneto0  @alan-baker @dnovillo

**Comment by zeux** [comment]
FWIW while we *currently* aren't running into this, it would be amazing to have an option to have the minimum amount of legalization code run.

We mostly use an optimized shader pack - legalization/performance passes, aggressive inlining, dead stripping, etc. - but for debugging it's sometimes convenient to get the original shader. We currently have packs without any optimizations that we use for this, and at some point they might start breaking because of issues like this.

**Comment by antiagainst** [comment]
@zeux: yes, that's what we are trying to do: minimizing the passes got run for legalization.

https://github.com/KhronosGroup/SPIRV-Tools/blob/0aa0ac52f773797a9bdf4b1b403757a68949de95/source/opt/optimizer.cpp#L90-L141

In DXC, we call `RegisterLegalizationPasses()` if legalization is needed and then further calling `RegisterPerformancePasses()` if the optimization level is not 0. If you want the raw output before any transformations, `dxc.exe -fcgl` will do the trick.
