### ISSUE TITLE
Should SROA eliminate structs in this shader?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Tools#1249]
My understanding is that there *is* a pass that does SROA (scalar_replacement_pass), so I'm somewhat surprised that in the attached shader it doesn't remove the struct

Here's a snippet from the shader:

        %152 = OpCompositeInsert %_struct_9 %123 %175 0
        %154 = OpCompositeInsert %_struct_9 %float_0 %152 0 2
        // snip
        %166 = OpCompositeExtract %v4float %154 0
        %168 = OpCompositeExtract %float %166 1
         %94 = OpFNegate %float %168
        %170 = OpCompositeInsert %v4float %94 %166 1
               OpStore %gl_Position %170

The shader has been compiled from HLSL via glslang, so the fact that the original shader has a struct makes sense - this is the struct for the vertex shader output - but it's odd that it's still there after all the optimizations.

[sky.spv.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1678826/sky.spv.zip)

**Comment by alan-baker** [comment]
Haven't looked at the attached testcase yet, but SROA will only scalarize Function storage class variables. You mention the above snippet is an output struct of the shader. SROA will not modify the interface of the shader.

**Comment by zeux** [comment]
I believe glslang flattens this struct onto individual variables for shader interface - the end of the shader looks like this:

               OpStore %gl_Position %170
               OpStore %100 %80
               OpStore %103 %140

The struct in question isn't used for output variables in the resulting SPIRV - it was there in the HLSL code only AFAICT.

**Comment by alan-baker** [comment]
%gl_Position, %100 and %103 are all listed as outputs for the entry point "main" in that module. The are all OpVariable with Output storage class. It is expected behaviour that they are not scalarized.

I can't speak for glslang, but it seems inappropriate to change the output interface of this stage. Perhaps I'm missing something?

**Comment by zeux** [comment]
I'm not expecting gl_Position to get scalarized - I'm expecting the struct that's used to compute the float4 output variables to get scalarized. To make sure we're talking about the same thing, here's the full shader:

               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %4 "main" %75 %79 %82 %gl_Position %100 %103
               OpMemberDecorate %_struct_23 0 ColMajor
               OpMemberDecorate %_struct_23 0 Offset 0
               OpMemberDecorate %_struct_23 0 MatrixStride 16
               OpMemberDecorate %_struct_23 1 Offset 64
               OpMemberDecorate %_struct_23 2 Offset 80
               OpMemberDecorate %_struct_24 0 Offset 0
               OpDecorate %_struct_24 Block
               OpDecorate %26 DescriptorSet 0
               OpDecorate %26 Binding 1
               OpMemberDecorate %_struct_35 0 ColMajor
               OpMemberDecorate %_struct_35 0 Offset 0
               OpMemberDecorate %_struct_35 0 MatrixStride 16
               OpMemberDecorate %_struct_35 1 Offset 64
               OpMemberDecorate %_struct_35 2 Offset 80
               OpMemberDecorate %_struct_35 3 Offset 96
               OpMemberDecorate %_struct_35 4 Offset 112
               OpMemberDecorate %_struct_35 5 Offset 128
               OpMemberDecorate %_struct_35 6 Offset 144
               OpMemberDecorate %_struct_35 7 Offset 160
               OpMemberDecorate %_struct_35 8 Offset 176
               OpMemberDecorate %_struct_35 9 Offset 192
               OpMemberDecorate %_struct_35 10 Offset 208
               OpMemberDecorate %_struct_35 11 Offset 224
               OpMemberDecorate %_struct_35 12 Offset 240
               OpMemberDecorate %_struct_35 13 Offset 256
               OpMemberDecorate %_struct_35 14 Offset 272
               OpMemberDecorate %_struct_35 15 Offset 288
               OpMemberDecorate %_struct_35 16 Offset 304
               OpMemberDecorate %_struct_35 17 Offset 320
               OpMemberDecorate %_struct_35 18 Offset 336
               OpMemberDecorate %_struct_35 19 Offset 352
               OpMemberDecorate %_struct_35 20 Offset 368
               OpMemberDecorate %_struct_36 0 Offset 0
               OpDecorate %_struct_36 Block
               OpDecorate %38 DescriptorSet 0
               OpDecorate %38 Binding 0
               OpDecorate %75 Location 0
               OpDecorate %79 Location 4
               OpDecorate %82 Location 2
               OpDecorate %gl_Position BuiltIn Position
               OpDecorate %100 Location 0
               OpDecorate %103 Location 1
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
    %v2float = OpTypeVector %float 2
  %_struct_9 = OpTypeStruct %v4float %v2float %v4float
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
%mat4v4float = OpTypeMatrix %v4float 4
 %_struct_23 = OpTypeStruct %mat4v4float %v4float %v4float
 %_struct_24 = OpTypeStruct %_struct_23
%_ptr_Uniform__struct_24 = OpTypePointer Uniform %_struct_24
         %26 = OpVariable %_ptr_Uniform__struct_24 Uniform
%_ptr_Uniform_mat4v4float = OpTypePointer Uniform %mat4v4float
    %v3float = OpTypeVector %float 3
 %_struct_35 = OpTypeStruct %mat4v4float %v4float %v4float %v4float %v3float %v3float %v3float %v3float %v3float %v4float %v3float %v4float %v4float %v4float %v4float %v4float %v4float %v4float %v4float %v4float %v4float
 %_struct_36 = OpTypeStruct %_struct_35
%_ptr_Uniform__struct_36 = OpTypePointer Uniform %_struct_36
         %38 = OpVariable %_ptr_Uniform__struct_36 Uniform
    %float_0 = OpConstant %float 0
      %int_1 = OpConstant %int 1
      %int_2 = OpConstant %int 2
%_ptr_Uniform_v4float = OpTypePointer Uniform %v4float
 %float_1700 = OpConstant %float 1700
%_ptr_Input_v4float = OpTypePointer Input %v4float
         %75 = OpVariable %_ptr_Input_v4float Input
%_ptr_Input_v2float = OpTypePointer Input %v2float
         %79 = OpVariable %_ptr_Input_v2float Input
         %82 = OpVariable %_ptr_Input_v4float Input
%_ptr_Output_v4float = OpTypePointer Output %v4float
%gl_Position = OpVariable %_ptr_Output_v4float Output
%_ptr_Output_v2float = OpTypePointer Output %v2float
        %100 = OpVariable %_ptr_Output_v2float Output
        %103 = OpVariable %_ptr_Output_v4float Output
        %175 = OpUndef %_struct_9
          %4 = OpFunction %void None %3
          %5 = OpLabel
         %76 = OpLoad %v4float %75
         %80 = OpLoad %v2float %79
         %83 = OpLoad %v4float %82
        %117 = OpAccessChain %_ptr_Uniform_mat4v4float %26 %int_0 %int_0
        %118 = OpLoad %mat4v4float %117
        %119 = OpVectorTimesMatrix %v4float %76 %118
        %121 = OpAccessChain %_ptr_Uniform_mat4v4float %38 %int_0 %int_0
        %122 = OpLoad %mat4v4float %121
        %123 = OpVectorTimesMatrix %v4float %119 %122
        %152 = OpCompositeInsert %_struct_9 %123 %175 0
        %154 = OpCompositeInsert %_struct_9 %float_0 %152 0 2
        %131 = OpAccessChain %_ptr_Uniform_v4float %26 %int_0 %int_2
        %132 = OpLoad %v4float %131
        %133 = OpAccessChain %_ptr_Uniform_v4float %26 %int_0 %int_1
        %134 = OpLoad %v4float %133
        %162 = OpCompositeExtract %float %119 1
        %137 = OpFDiv %float %162 %float_1700
        %138 = OpCompositeConstruct %v4float %137 %137 %137 %137
        %139 = OpExtInst %v4float %1 FMix %132 %134 %138
        %140 = OpFMul %v4float %83 %139
        %166 = OpCompositeExtract %v4float %154 0
        %168 = OpCompositeExtract %float %166 1
         %94 = OpFNegate %float %168
        %170 = OpCompositeInsert %v4float %94 %166 1
               OpStore %gl_Position %170
               OpStore %100 %80
               OpStore %103 %140
               OpReturn
               OpFunctionEnd

I'm expecting SROA to remove variables of `_struct_9` type as well as some composite insert/extract insns, specifically this:

        %175 = OpUndef %_struct_9
        %152 = OpCompositeInsert %_struct_9 %123 %175 0
        %154 = OpCompositeInsert %_struct_9 %float_0 %152 0 2
        %166 = OpCompositeExtract %v4float %154 0

**Comment by alan-baker** [comment]
I see what you mean now, sorry for the confusion. I agree that there is an optimization to be performed, but SROA won't do that. What I would expect to be the result is:
```
%123 = OpVectorTimesMatrix %v4float %119 %122
%154_replacement = OpCompsiteInsert %v4float %float_0 %123 2
; replace %166 with %154_replacement
```
This would cause %_struct_9 to become dead as you expect. This seems like something dead insert/extract or instruction folding should do I think.

**Comment by zeux** [comment]
Yeah, I'm not sure what SROA does right now and what it should do - maybe this needs a pass that can forward values from composite inserts to composite extracts, which will make composit inserts dead...

**Comment by alan-baker** [comment]
I will investigate getting this optimization performed.

**Comment by greg-lunarg** [comment]
Yes, the current InsertExtractElim is currently not this sophisticated.

Is the "full" shader above the original shader without any optimizations performed on it?

**Comment by zeux** [comment]
No - that's the optimized shader. If you want I can attach the original SPIRV output without *any* legalization or optimization passes applied.

**Comment by greg-lunarg** [comment]
I think that would be helpful. I am wondering why the struct_9 did not broken down by SROA. Having the original would let us see that.

**Comment by zeux** [comment]
Sure thing; attaching the debug version of the shader. The struct in question is `%VertexOutput` (there's also `struct %Appdata` but that one looks like it has been optimized away).

This is before any legalization/optimization passes.

[sky-debug.spv.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1679520/sky-debug.spv.zip)

**Comment by greg-lunarg** [comment]
With the current spirv-tools top of tree and the following recipe:

--inline-entry-points-exhaustive --eliminate-dead-functions
--scalar-replacement --convert-local-access-chains
--eliminate-local-single-block --eliminate-local-single-store
--eliminate-insert-extract --eliminate-dead-code-aggressive
--eliminate-dead-branches --merge-blocks --eliminate-local-multi-store
--eliminate-insert-extract --eliminate-dead-code-aggressive

I am no longer seeing inserts into structs:

       %main = OpFunction %void None %3
          %5 = OpLabel
         %76 = OpLoad %v4float %IN_Position
         %80 = OpLoad %v2float %IN_Uv
         %83 = OpLoad %v4float %IN_Color
        %117 = OpAccessChain %_ptr_Uniform_mat4v4float %_ %int_0 %int_0
        %118 = OpLoad %mat4v4float %117
        %119 = OpVectorTimesMatrix %v4float %76 %118
        %121 = OpAccessChain %_ptr_Uniform_mat4v4float %__0 %int_0 %int_0
        %122 = OpLoad %mat4v4float %121
        %123 = OpVectorTimesMatrix %v4float %119 %122
        %171 = OpCompositeInsert %v4float %float_0 %123 2
        %131 = OpAccessChain %_ptr_Uniform_v4float %_ %int_0 %int_2
        %132 = OpLoad %v4float %131
        %133 = OpAccessChain %_ptr_Uniform_v4float %_ %int_0 %int_1
        %134 = OpLoad %v4float %133
        %173 = OpCompositeExtract %float %119 1
        %137 = OpFDiv %float %173 %float_1700
        %138 = OpCompositeConstruct %v4float %137 %137 %137 %137
        %139 = OpExtInst %v4float %1 FMix %132 %134 %138
        %140 = OpFMul %v4float %83 %139
        %175 = OpCompositeExtract %float %171 1
         %94 = OpFNegate %float %175
        %177 = OpCompositeInsert %v4float %94 %171 1
               OpStore %_entryPointOutput_HPosition %177
               OpStore %_entryPointOutput_Uv %80
               OpStore %_entryPointOutput_Color %140
               OpReturn
               OpFunctionEnd

ie. I think SROA is doing its job correctly.

Not sure why glslang was giving you something different. Will look into
that next.


Greg Fischer

Project Manager and Senior Engineer

LunarG, Inc. - 3D Driver Innovations

greg@lunarg.com <alan@lunarg.com>

On Tue, Jan 30, 2018 at 2:51 PM, Arseny Kapoulkine <notifications@github.com

**Comment by zeux** [comment]
This is interesting. Maybe we are missing some passes... The way we get from the debug SPIRV I attached to the final SPIRV is by running this:

			tools.RegisterSizePasses();
			tools.RegisterPerformancePasses();
			if (tools.Run(spirv_copy.data(), spirv_copy.size(), &spirv) == false)
				throw std::runtime_error("SPIRV optimization failed:\n" + str.str());

Followed by this:

            spv::spirvbin_t Remapper;
            Remapper.remap(spirv, spv::spirvbin_t::DCE_ALL | spv::spirvbin_t::STRIP);

I'll check with the latest SPIRV-Tools but I believe the one I used was almost latest...

**Comment by zeux** [comment]
Okay - RegisterSizePasses was the issue. If I remove that and only register performance passes, I get the struct removed; with the configuration from the previous comment with latest SPIRV-Tools I still get the struct in the output.

I'm assuming that this is a pass mis-configuration that shouldn't really happen - feel free to close this issue if this is correct...

**Comment by greg-lunarg** [comment]
I see the problem: RegisterSizePasses does not have scalar replacement. By the time RegisterPerformancePasses gets to it, things have been transformed too much for scalar replacement to be effective.

I will work on getting scalar replacement into RegisterSizePasses.

**Comment by greg-lunarg** [comment]
I think we still want ScalarReplacement in RegisterSizePasses, so I am going to work on that and use this issue in part to justify it.

I guess the question is: what is your goal? Are you trying to improve performance or reduce size? Optimizing for performance may reduce size, but it may not give you the smallest size and also could increase size, for example, loop unrolling.

**Comment by zeux** [comment]
I'm perfectly content to use RegisterPerformancePasses (they generate slightly smaller binaries as well, which is nice).

This might come as a surprise, but my main goal is to get shaders that are simple enough to not hit the driver issues with shader compilation... We are currently successfully using glsl->glsl-optimizer->spirv pipeline which doesn't end up using structs, function calls, etc. and that works on vendors we've tested this with. Trying to get HLSL->glslang->spirv-opt to run - we've hit multiple issues on all vendors :) but the ongoing SPIRV-Tools work helps, the shader I posted above wasn't working on Adreno a month or so ago (not sure if it was the same binary); with newest SPIRV-Tools and performance passes (w/out size passes) this and most other shaders we have seem to compile fine... (still have at least one that doesn't, will have to try to figure out why).

**Comment by dneto0** [comment]
> Optimizing for performance may reduce size, but it may not give you the smallest size and also could increase size, for example, loop unrolling.

To be clear, the performance passes currently don't do loop unrolling.  In the near term I could see adding a pass to honour explicit loop unroll hints (https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_loop_control_a_loop_control and being implemented in Glslang https://github.com/KhronosGroup/glslang/pull/1232 ).
I think we're quite far from having _good_ heuristics for knowing when to unroll a loop in a graphics shader, so I don't anticipate it being added to a default "performance" optimization recipe.

**Comment by zeux** [comment]
@dneto0 yeah unrolling based on explicit hints would make sense, this is what our expectations are for fxc.

**Comment by dnovillo** [comment]
On Thu, Feb 1, 2018 at 11:11 AM, Arseny Kapoulkine <notifications@github.com
> wrote:

> @dneto0 <https://github.com/dneto0> yeah unrolling based on explicit
> hints would make sense, this is what our expectations are for fxc.
>

It's 2018 and we are still giving compilers explicit hints.  This makes me
sad ;)

Mostly joking, of course.  I don't expect the compiler to have enough
information about loop unrolling until we can at least do profile-driven
transformations.  This is a ways off still.

**Comment by greg-lunarg** [comment]
> To be clear, the performance passes currently don't do loop unrolling.

Yes. It was just meant as an example of how "performance" and "size"
optimizations can be at cross-purposes.
