### ISSUE TITLE
constexpr causing headaches downstream in Glslsang

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1252]
https://github.com/KhronosGroup/glslang/pull/1227  

Glslang tries to work with VS 2013.  But recently introduced constexpr in SPIRV-Tools caused it to fail compilation.

**Comment by alan-baker** [comment]
In order to do this, the instruction builder can no longer be templated on an Analysis enumerator. Instead I am planning to change it to a constructor argument.

**Comment by dneto0** [comment]
Fixed with #1254
