### ISSUE TITLE
spirv-as fails to recognize spec example

### ISSUE THREAD

**Issue by httpdigest** [KhronosGroup/SPIRV-Tools#127]
The SPIR-V example on the [SPIR-V specification](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_example) (under 'Corresponding SPIR-V:') is rejected with saying `error: 123: 16: Invalid Opcode name '; Magic:     0x07230203 (SPIR-V)`.

When I remove the comment lines starting with a semicolon, then I get the following output:
`error: 119: 16: Invalid Opcode name '`
the source file has as very last line `OpFunctionEnd`

If I add a single line break to the file, it works. I think that line break problem is described by https://github.com/KhronosGroup/SPIRV-Tools/issues/126.

**Comment by httpdigest** [comment]
Okay, if I just take the original source code from the spec and just add a line break at the end, that works, too.
So, the spirv-as tools just seems to have a problem with when the file does not have a single empty line at the end, as described by #126.

**Comment by antiagainst** [comment]
Done via #131.
