### ISSUE TITLE
Scalar replacement improvements

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1277]
#1274 provided evidence of some cases where the base SROA implementation did not have ideal results. In an effort to not blindly care whether or not aggregates are partially accessed, some improvements are detailed  below.

@s-perron suggests tracking equivalence classes where (assuming it is legal) scalarizing any member of the equivalence class would cause all members to be scalarized. Equivalence classes could be built out of copies of variables.

To further identify partial accesses better, we could fold inserts/extracts into access chains before SROA (this would effectively be the reverse of local access chain convert).

**Comment by s-perron** [comment]
Scalar replacement seems to be working well for its current uses. These ideas are no longer needed.
