### ISSUE TITLE
Optimization results in invalid SPIRV (where a value from a non-dominating block is used)

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Tools#1307]
This is related to #1294 - several shaders we have have a valid CFG SPIRV before optimization, but after running through performance passes they get a CFG that - as far as I understand - is invalid; specifically, one of the blocks ends up using a value from a block that doesn't dominate it due to a continue branch.

Attaching the shaders before/after optimization.

The CFG of the shader in question:

![](https://user-images.githubusercontent.com/1106629/36106255-abbab1fa-0fcb-11e8-8118-fc8b4f7bd819.png)

Block 3251 uses a value (7127) computed in block 3221, which should not be valid due to a continue branch from 3128 to 3221. This happens with SPIRV-Tools master.

[shader32.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1725947/shader32.zip)

**Comment by greg-lunarg** [comment]
I can take a look at this.

Can you please send the spriv-opt command line used to produce the SPIR-V in question?

**Comment by zeux** [comment]
This was generated while using SPIRV-Tools as a library with this:

    tools.RegisterPerformancePasses();

Which should be equivalent to -O as far as I understand.

**Comment by zeux** [comment]
Yeah - reproduces on master with `spirv-opt -O shader32-beforeopt.spv -o shader32-afteropt.spv`; with the master the value used in block 3251 is 7167, not 7127 (I believe the .zip file has optimized shader from a slightly earlier version), but the problem is the same.

**Comment by greg-lunarg** [comment]
3221 does indeed dominate 3251. "continue" and "merge" arcs in these CFGs are not branches. They are just relationship indicators.

A dominates B means that there there is no path from the first node in the CFG  to B that does not go through A. I think you will then agree that 3221 dominates 3251.

Let me know if I am missing something.

**Comment by zeux** [comment]
Oh - I was misreading the CFG then. This originally came up as a SPIRV-Cross issue that was suspected to be a SPIRV-Tools bug, but that would make sense. If so this (and #1294) are invalid. I'll close these for now - looks like this needs further investigation on SPIRV-Cross side...

**Comment by zeux** [comment]
@greg-lunarg Just to be clear I understand this before closing this:

3128 is a loop block; it has the "continue target" set to 3251
This means block 3251 is the block that executes last in a loop and branches back to the beginning of the loop (so from 3251 to 3128)
The value that's computed in 3221 and used in 3251 is safe to use because there are no branches *from* 3128 to 3251 - the branch goes in backwards direction
The continue arc is there to signify the special relationship between 3128 and 3251 that's established by OpLoopMerge - it's expected that in any loop, there'll be a branch from the continue target to the beginning of the loop, and a continue arc that marks this relationship.

Does this sound accurate?

**Comment by greg-lunarg** [comment]
Yes. This is all true for this loop and 99.999% of all loops.

One thing I will point out is that while for 99.999% of loops the continue block is the "last" block in the loop and contains the instruction that branches back to the loop header, there are rare times when this is not true. However, the continue block is required to dominate the back-edge block and the back-edge block is require to post-dominate the continue block, so they are very tightly linked if they are not the same block. Just wanted to let you know in case you run into it.

**Comment by zeux** [comment]
Ok - this makes sense. Thanks for the explanation! Closing this and #1294 as invalid.
