### ISSUE TITLE
Unit tests failing because of capability dependency bugifx

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1318]
Capability dependencies are updated to allow SubgroupSize and SubgroupLocalInvocationId with SubgroupBallotKHR:  
https://github.com/KhronosGroup/SPIRV-Headers/pull/57 
I believe this is the cause of unit test failures like:

[ RUN      ] BuiltIn/EnumCapabilityTest.Sample/33
/home/travis/build/KhronosGroup/SPIRV-Tools/test/operand_capabilities_test.cpp:56: Failure
Value of: ElementsIn(CapabilitySet(entry->numCapabilities, entry->capabilities))
Expected: is equal to { 6 }
  Actual: { 6, 4423 }
 capability value 36

(Kernel is 6, and SubgroupBallotKHR is 4423)

**Comment by dneto0** [comment]
FYI @s-perron @antiagainst

**Comment by antiagainst** [comment]
#1319 for fixing this
