### ISSUE TITLE
Improve the compile time of spirv-opt.

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1328]
We have come across a number of places where spirv-opt takes much longer that it needs to.  This will be a catch all issue for all compile time changes.

**Comment by dnovillo** [comment]
Currently implementing a new SSA rewriting algorithm to improve compile time during Phi insertion.

**Comment by dnovillo** [comment]
New SSA rewriting algorithm merged #1369.  Observing speedups of up to 7x on windows builds.

**Comment by s-perron** [comment]
The next issue I want to look into is the reduce the number of times we kill analyzes.  In particular, the def-use manger and the inst-to-block mapping.  They are both used very often, and are expensive to kill on Windows.  In one profile that I did, kill those two account for almost 1/3 of the time spend compiling the shader.  I'll open another issue to group all of those changes together.

**Comment by ratchetfreak** [comment]
Is that time spent in actual killing or in rebuilding?

If in killing because of recursive destructors, then that can be optimized but using something like a dedicated allocation to kill everything in one go and nulling out the references in each instruction/block (or maybe a analysis generation number which if doesn't match means it's effectively null)?

**Comment by s-perron** [comment]
On Windows the time is spent mostly in killing the data structures, but build takes time as well.

Those are interesting ideas, and I'll keep them in mind.  For now we already do the work to keep the analyses up-to-date, but just did not set the bit on a number of optimizations to say that they are still valid.  That is most of the work, and it is pretty simple.  So we will get that done.  The next step would be to try to change the implementation of the analyses.  That is where we may use some of your ideas.  Thanks @ratchetfreak.

**Comment by s-perron** [comment]
This issue has been tracking the long compile time on Windows when using DXC.  A large improvement should be coming with https://github.com/Microsoft/DirectXShaderCompiler/pull/1729.  Once that is through, we will consider this done.
