### ISSUE TITLE
OpEntryPoint could use cleanup of unused inputs

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Tools#1337]
I didn't find any passes that remove dead inputs from entrypoints; when trying to use HLSL input to glslang, the resulting shaders have several cases where dead inputs arise:

- Notably, most of our shaders have gl_FragCoord (translated from SV_Position) as an input even though we aren't actually reading it... (this is common for VS/PS that share one struct)
- Some of our fragment shaders have unused inputs that are written by VS; I currently suspect that one such case causes a miscompilation of one of our shaders on Qualcomm drivers

Would it make sense to implement it and if so, where? I quickly hacked this together as a change to dead variable elimination pass but since this pass isn't currently active it's likely the wrong thing to do. I could write a separate pass for this?

Still need to figure out two other things:

- Does pruning inputs in this fashion actually fix the issues with Qualcomm we have without introducing new ones?
- Validation layers have an annoying warning that tells you that vertex shader writes to an output that isn't read by the fragment shader; does this warning get even more annoying if you do this?

**Comment by alan-baker** [comment]
I have a patch for something like this to be included in ADCE; however, it strikes me an unsafe optimization. Vulkan interface matching rules are rather strict, so this seem more appropriate as optimization on the whole pipeline. We debated this internally. I'm not sure which way we should cater here. We also discussed having a "workaround" pass (similar to #1209).

**Comment by zeux** [comment]
@alan-baker The pass I'm thinking of only removes entire variables if unused, it doesn't attempt to clean up interface struct fields; I believe this is safe because the matching is location-based?

Separately, cleaning up builtins should be safe and harmless - this can slightly reduce the shader size for HLSL inputs because of gl_FragCoord as mentioned above.

**Comment by antiagainst** [comment]
I don't think we can remove stage IO variables freely, even if they are unused. Vulkan spec 14.1.3 says:

> A user-defined output variable is considered to match an input variable in the subsequent stage if the two variables are declared with the same Location and Component decoration and match in type and decoration, except that interpolation decorations are not required to match. ...

> Variables or block members declared as structures are considered to match in type if and only if the structure members match in type, decoration, number, and declaration order. Variables or block members declared as arrays are considered to match in type only if both declarations specify the same element type and size.

> At an interface between two non-fragment shader stages, the built-in interface block must match exactly, as described above. At an interface involving the fragment shader inputs, the presence or absence of any built-in output does not affect the interface matching.

> At an interface between two shader stages, the user-defined variable interface must match exactly, as described above.

Please definitely correct me if I'm wrong. But my reading of it is that the only thing we can do maybe is just removing unused builtin variables in fragment shader. For others, they must match exactly.

**Comment by zeux** [comment]
@antiagainst This is surprising to me. OTOH in our current shader compilation pipeline (that doesn't use SPIRV-Tools and is based on HLSL->GLSL AST conversion and glsl-optimizer which aggressively prunes unused inputs) we have several pairs where VS output is a superset of FS input, and a few shaders where vertex input declaration on the C++ side is a superset of vertex shader inputs, and that works perfectly fine without issues on 3 mobile & 3 desktop vendors... The issue we're hitting with Qualcomm (I believe - I will update this thread when checking again) is with an unused fragment shader input that is still present in the entrypoint declaration.

Validation layers emit a performance warning for vertex shader outputs that don't have a corresponding fragment shader input here: 

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/shader_validation.cpp#L1423-L1426

Which makes me think it's valid? :) Obviously the spec text must take precedence over what's mentioned above, and 14.1.3 does seem like it says "you have to have an input in a stage for any output in the previous stage", but this might be unclear wording? (or a spec bug)

This needs a followup from Khronos - this is definitively different from GLSL, HLSL and MSL rules so if you actually have to have a redundant input for any output, that can be a problem.

**Comment by antiagainst** [comment]
> that works perfectly fine without issues on 3 mobile & 3 desktop vendors...

Sometimes drivers are more permissible than the spec. Using the same machine-level fundamentals to support multiple APIs will sometimes "leak" the behavior of one API into others, I think. They may also contain hotfixes for certain commonly seen confusions/errors.

> Obviously the spec text must take precedence over what's mentioned above, and 14.1.3 does seem like it says "you have to have an input in a stage for any output in the previous stage", but this might be unclear wording? (or a spec bug)

+1

Yep. The Vulkan shader interface matching section could use some improvements for sure. It caused quite some confusion for me previously when translating HS/DS/GS builtins.

One nice thing about the spec is that we have an authoritative definition of a certain API, instead of trying to feed the source code into the driver and adjust according to the implementation's response. Implementations certainly influence the spec; but we may want to base SPIRV-Tools on the spec.

**Comment by zeux** [comment]
Yeah - I agree the spec comes first. However, we're in a very weird spot atm:

- It's not clear what the spec says; different people seem to disagree on whether not using an input value is allowed
- For shader portability reasons, it's important to support omitting input values since that is more or less how HLSL/GLSL/MSL work (HLSL rules for DX10-12 are somewhat more strict, mostly because compiler auto-assigns "register" indices, but they are still more relaxed than "all in/out variables must match one to one")
- For driver simplicity, I could imagine it's important to require one-to-one matching since this can make separate shader compilation possible - if you compile final bytecode when creating the pipeline state this is irrelevant, but otherwise it helps.
- Validation layers don't produce errors on mismatches between different stages.

I will file an issue on Vulkan-Docs; I believe this has to be resolved one way or the other, either by explicitly spelling out allowed omissions, or explicitly banning them (which will take a toll on the community because it's likely that most existing games do use partial interfaces in at least one shader...).

**Comment by zeux** [comment]
I've filed a Vulkan-Docs issue (uh... https://github.com/KhronosGroup/Vulkan-Docs/issues/666). Also it looks like pruning unused inputs doesn't resolve our issues with Qualcomm, I'll need to get more data on that.

**Comment by zeux** [comment]
FWIW the issues we had with Qualcomm drivers were unrelated to unused inputs per se. Their driver seems to use OpName and, in absence of OpName, generated names from SPIRV ids (yes, really) to match VS & FS signatures. So we had to implement a pass that remaps VS output & FS input variables to have a matching SPIRV id to fix issues we've encountered :-/ I'll keep this open for now since pruning unused inputs/outputs reduces the binary size a bit, so it might still be a good idea *if* the spec allows for it.

**Comment by zeux** [comment]
Closing this due to ambiguous spec status and this not being required to solve driver issues.

**Comment by sindney** [comment]
> 
> 
> I have a patch for something like this to be included in ADCE; however, it strikes me an unsafe optimization. Vulkan interface matching rules are rather strict, so this seem more appropriate as optimization on the whole pipeline. We debated this internally. I'm not sure which way we should cater here. We also discussed having a "workaround" pass (similar to #1209).

Hi, alan. Since the [specs](https://github.com/KhronosGroup/Vulkan-Docs/issues/666#issuecomment-869491481) has been updated, can you add this input cleanup patch to ADCE?
