### ISSUE TITLE
Opt: Atomics (and other instructions with side-effects) being eliminated

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#1341]
This is happening in DCEInst() which is used to cleanup after other optimizations. It isn't checking that instructions are combinators (no side-effects) before deleting.

I am claiming this and will be submitting a PR shortly.

**Comment by danginsburg** [comment]
I can confirm that PR #1342 fixes the issue.  The attached SPIR-V reproduces the bug, but is fixed by the PR.

[cs_no_opt_good.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1748345/cs_no_opt_good.zip)
