### ISSUE TITLE
spirv-opt -Oconfig does not support comment lines properly

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#1345]
Given a configuration input file:

$ cat opt.cfg
\# This is a comment
--eliminate-local-multi-store
--ccp

$ spirv-opt -Oconfig=opt.cfg for.frag.spv
error: More than one input file specified

The comment line is being parsed as additional input files, instead of being ignored.

**Comment by s-perron** [comment]
I don't think that anyone uses the config file. Most spirv-opt users are using it as a library, so I don't think there is value in improve the feature. Closing this issue.
