### ISSUE TITLE
Find better way to handle OpConstantNull

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1359]
Our constants infrastructure separates `OpConstantNull <type>` from `OpConstant/OpConstantComposite <type>`. This has led to several bugs (e.g. #1357 and #1338). We should reconsider how best to represent null constants.

One option would be to convert null constants on creation and generate a new defining instruction for them. So if we did `constant_manager->GetConstant(<type>, {})`, we could generate `Constant<type>` with appropriately filled null equivalent values. The unused null constants would then be DCE'd eventually in the natural course of things.

**Comment by alan-baker** [comment]
@s-perron and @dnovillo please comment if you have any ideas about better handling of `OpConstantNull`.

**Comment by alan-baker** [comment]
https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.html#OpConstantNull

Null is not well defined for all types. That sort of precludes completely removing NullConstant. Is is enough to eliminate it for numeric types and bool?

**Comment by s-perron** [comment]
We now use "IsZero()" that checks both. We still get some errors, but they are fewer.
