### ISSUE TITLE
Validator disallows Float16 capability even when the necessary extension is present

### ISSUE THREAD

**Issue by ehsannas** [KhronosGroup/SPIRV-Tools#1375]
I am trying to validate a SPIR-V file that includes usages of 16-bit float.

The validator complains that:
```
Capability Float16 is not allowed by Vulkan 1.0 specification (or requires extension)
```

However, my SPIR-V contains ``OpExtension "SPV_AMD_gpu_shader_half_float"`` which is the extension that enables this capability. Attached is the SPIR-V source.

[float16.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1781526/float16.txt)

**Comment by atgoo** [comment]
The validator simply ignores this extension since it's not in the grammar, so there are no rules for it.

I could hardcode this particular case somewhere, but I think it's more of a question for @dneto0.

**Comment by ehsannas** [comment]
It turns out that specifying the "SPV_AMD_gpu_shader_half_float" extension does not necessarily mean Float16 capability should be enabled. Nothing needs to be done. Sorry for the confusion.

**Comment by ehsannas** [comment]
Ok, so there **is** still some work that needs to be done.

If ``Float16`` capability is **not** specified, you will get this error:
```
Using a 16-bit floating point type requires the Float16 or Float16Buffer capability, or an extension that explicitly enables 16-bit floating point.
```

But we should not get this validation error if the "SPV_AMD_gpu_shader_half_float" extension is specified.

**Comment by ehsannas** [comment]
conclusion of my talk with @dneto0 was that we should tell the validator about this extension and the fact that it enabled 16bit floats by adding it to the ``Features`` in the validation state.

**Comment by oscarbg** [comment]
just let me join the discussion and say that it is strange as with SPIRV-tools from Vulkan SDK 1.0.68 all works OK:

    spirv-val --version
    SPIRV-Tools v2018.1-dev v2018.0-6-g9e19fc0

    spirv-val doesn't catch any issues with the generated SPIR-V with Float16 cap:
    spirv-as test.spv.txt -o test.spv
    I run spirv-dis just to check spirv-as has mantained Float16 and SPV_AMD_.. ext:
    spirv-dis test.spv -o testdis.spv.txt
    spirv-val test.spv
    no errors and also
    spirv-opt test.spv -O -o test2.spv
    optimzes spir-v correctly seeing textual form:
    spirv-dis test2.spv -o test2dis.spv.txt
    I attach all generated files in case helpful:

[tests.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1783798/tests.zip)
