### ISSUE TITLE
Optimizer internal error on float16 usage

### ISSUE THREAD

**Issue by ehsannas** [KhronosGroup/SPIRV-Tools#1376]
I have a SPIR-V source that uses float16 (below):

[float16.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1781904/float16.txt)

If you assemble and run the optimizer on it, you'll get an internal error.
```
C:\spirv-tools\build\tools\spirv-as.exe float16.txt -o float16.spv
C:\spirv-tools\build\tools\spirv-opt.exe -O -o float16_after_optimization.spv float16.spv
```

You get this assertion failure:
```
Assertion failed: type()->AsFloat()->width() == 32 && "Not a 32-bit floating point value.", file c:\spirv-tools\source\opt\constants.h, line 222
```
cc @antiagainst @alan-baker  @s-perron @dnovillo

**Comment by ehsannas** [comment]
I have used Windows (Debug), but it might happen on other platform/configuration as well.

**Comment by oscarbg** [comment]
just let me join the discussion and say that it is strange as with SPIRV-tools from Vulkan SDK 1.0.68 all works OK:

> 
> 
> spirv-val --version
> SPIRV-Tools v2018.1-dev v2018.0-6-g9e19fc0
> 
> spirv-val doesn't catch any issues with the generated SPIR-V with Float16 cap:
> spirv-as test.spv.txt -o test.spv
 I run spirv-dis just to check spirv-as has mantained Float16 and SPV_AMD_.. ext:
> spirv-dis test.spv -o testdis.spv.txt
> spirv-val test.spv
> no errors and also
> spirv-opt test.spv -O -o test2.spv
> optimzes spir-v correctly seeing textual form:
> spirv-dis test2.spv -o test2dis.spv.txt
> I attach all generated files in case helpful:

[tests.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1783794/tests.zip)
