### ISSUE TITLE
Documentation about build and test

### ISSUE THREAD

**Issue by jaebaek** [KhronosGroup/SPIRV-Tools#1379]
I tried to build this tool using ninja and realized that there is no explicit explanation.
If a short documentation exists, it would be better.

For someone who will search the "ninja" keyword .. I am not sure it is correct but maybe we can use the following commands:
```
$ cd path/to/SPIRV-Tools
$ git clone https://github.com/KhronosGroup/SPIRV-Headers.git external/spirv-headers
$ git clone https://github.com/google/googletest.git external/googletest # optional
$ mkdir build && cd build
$ cmake -G Ninja ..
$ ninja
$ ninja test
```
In addition, I wonder if there are other ways to test this tool.

**Comment by s-perron** [comment]
The existing documentation has

```
cmake [-G <platform-generator>] <spirv-dir>
cmake --build . [--config Debug]  # runs `make` or `ninja` or `msbuild` etc.
```

for the build instructions, which includes `ninja`.

The testing section says

```
ctest -j <num threads>
```

which again includes ninja.

I don't think we should have to document every method for every generator, so I will close this.
