### ISSUE TITLE
"struct spv_context_t" misses a typedef for C compilation

### ISSUE THREAD

**Issue by yoanlcq** [KhronosGroup/SPIRV-Tools#138]
Including `libspirv.h` in a C project causes an error at this line : 
https://github.com/KhronosGroup/SPIRV-Tools/blob/master/include/spirv-tools/libspirv.h#L344
because `spv_context_t` isn't a known type, but `struct spv_context_t` is.

Since libspirv is intended as a C API, this should be fixed by adding
`typedef struct spv_context_t spv_context_t;` just here : 
https://github.com/KhronosGroup/SPIRV-Tools/blob/master/include/spirv-tools/libspirv.h#L334

**Comment by dekimir** [comment]
Will fix, but `libspirv.h` is currently far from being C friendly.  It has several other non-C constructs, such as `bool` and `namespace` in `OpenCL.std.h`.

**Comment by dekimir** [comment]
Fixed via c31a319.
