### ISSUE TITLE
SPIR-V optimizer breaks SMAA shaders

### ISSUE THREAD

**Issue by turol** [KhronosGroup/SPIRV-Tools#1385]
Latest SPIR-V optimizer breaks SMAA shaders. The blend weights pass shader produces broken output resulting in the final output being not antialiased and having nasty line artifacts instead.
2018.1 and latest master are broken.
Using default speed optimizations.
I've bisected it to e661da7941e12cbc6a9100bd8cadbc0d61dd8b7a.
[Good shader](https://gist.github.com/turol/7970f90b1fc3f3c8c6709a5c552b1101)
[Broken shader](https://gist.github.com/turol/3797e98dddfaae70385f38e78dc74626)

My [SMAA demo](https://github.com/turol/smaaDemo) can be used to test this.
It currently ships with the last working SPIRV-tools built in.
Both Vulkan and OpenGL versions are affected.
Beware that there appears to be a an unrelated problem with MSVC and OpenGL and that version doesn't work. Either use only Vulkan under MSVC, compile with mingw or use Linux.
Shader SPIR-V is cached in `~/.local/share/SMAADemo` on Linux and
`C:\Users\<username>\AppData\Roaming\SMAADemo` on Windows.
The breaking shader is smaaBlendWeight.frag_SMAA_PRESET_ULTRA=1.spv.
Running the latest optimizer on this shader and running the demo again can be used to test this.

If you want to compile a version with modified SPIRV-Tools, on Windows just update the source under foreign and recompile using the provided .bat. On Linux you can add the following to local.mk to use an external build of SPIRV-Tools
```
INTERNAL_spirv-tools:=n
LDLIBS_spirv-tools:=-lSPIRV-Tools -lSPIRV-Tools-opt
LDFLAGS+=-L/path/to/SPIRV-Tools/build/source
LDFLAGS+=-L/path/to/SPIRV-Tools/build/source/opt
CFLAGS+=-isystem/path/to/SPIRV-Tools/include
CFLAGS+=-isystem/path/to/SPIRV-Tools/build
```

**Comment by alan-baker** [comment]
I think this is a bug in some arithmetic folding.

**Comment by alan-baker** [comment]
Looking a little further, there appears to be a bad fold.

From good:
```
      %14248 = OpPhi %v4float %14676 %24046 %21595 %21240
      %17548 = OpVectorShuffle %v2float %14248 %14248 2 3
      %16543 = OpVectorShuffle %v4float %13336 %17548 0 4 2 5
      %17776 = OpCompositeExtract %float %16543 1
```
From bad:
```
      %14248 = OpPhi %v4float %14676 %24046 %21595 %21240
      %17776 = OpCompositeExtract %float %14248 0
```

The extract should be grabbing element 2 from `%14248`.
