### ISSUE TITLE
Missing fp const folding for std.450 extended instructions

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Tools#1390]
We have some shaders that have instructions from the extended set that could be folded but aren't, specifically:

- FMin/FMax
- Pow/Exp/Log/Log2
- Sin/Cos

(I won't have time to look into this up until after GDC so filing an issue for now, maybe somebody gets to this first!)

**Comment by dneto0** [comment]
Thanks for the suggestion.  I put it at the top of the "Suggested to start" list.
I can't guarantee we'll get to it soon either.  :-)

**Comment by Trass3r** [comment]
Yes also normalize and cross: http://shader-playground.timjones.io/06d95d58a040a9d589626db8d042a377

**Comment by zeux** [comment]
I guess I have to do it myself 😅 I'm going to implement this for scalar transcendentals and submit a PR to close this - fmin/fmax are already supported, and somebody else can implement vector folding...
