### ISSUE TITLE
Add SPV_GOOGLE_decorate_string and SPV_GOOGLE_hlsl_functionality1 to optimizer whitelists

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1391]

**Comment by dneto0** [comment]
Many parts of HLSL legalization won't work until we do this.
That would be ironic, because hlsl_functionality1 is expressly for HLSL support.

**Comment by antiagainst** [comment]
I'll handle this once #1395 is merged.

**Comment by dneto0** [comment]
I already had this coded up.  :-)
