### ISSUE TITLE
DecorationManager doesn't understand OpDecorateStringGOOGLE

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1396]
E.g. need to fill out places where things like SpvOpDecorateId are used.
see HaveTheSameDecoration, AreDecorationsTheSame, etc.

**Comment by dneto0** [comment]
Hey @antiagainst do you want to take a look?

**Comment by antiagainst** [comment]
I see there is an rewriting coming for DecorationManager: #1373. I think maybe I should wait until that is landed?

**Comment by dneto0** [comment]
Now that #1373 has landed I've started this.

**Comment by dneto0** [comment]
Fixed by #1410
