### ISSUE TITLE
SPIR-V module segfaults spirv-opt -O

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Tools#1401]
[segfault.asm.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1802703/segfault.asm.txt)

Commit: Current master as of this time.

**Comment by greg-lunarg** [comment]
I believe I have fixed this with #1406.

**Comment by alan-baker** [comment]
Confirmed fixed.
