### ISSUE TITLE
spirv-opt falsely removes specialized WorkGroupSize

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Tools#1404]
Before: 
[before.asm.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1802915/before.asm.txt)
After `spirv-opt -O`:
[after.asm.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1802918/after.asm.txt)

**Comment by alan-baker** [comment]
Requires a fix in ADCE.
