### ISSUE TITLE
spirv-val does not validate OpTypeBool inside Blocks

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Tools#1405]
Reference: https://github.com/KhronosGroup/SPIRV-Cross/issues/504
spirv-val does not catch when OpTypeBools are placed in buffer blocks, which is illegal.

**Comment by dneto0** [comment]
Agreed we should check this.

Would be an application of this clause in OpTypeBool
"If they are stored (in conjunction with OpVariable), they can only be used with logical addressing operations, not physical, and only with non-externally visible shader Storage Classes: Workgroup, CrossWorkgroup, Private, and Function."

**Comment by jaebaek** [comment]
2c2fee7 solves this issue.
