### ISSUE TITLE
Copy propagate arrays with a single store.

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1416]
The code generated by the FE around function calls creates a lot of copies of objects.  To get optimize these shaders properly, we have to be able to propagate through all of the temporary symbols.  We have code that can do that very well when as long as all accesses of the structure have constant offset.

However, if we have an array that is accessed using a variable index, we are not able to optimize the code.  Consider the following example:

```
cbuffer MyCBuffer {
  float4 Data[8];
};

float4 fetch(float4 data[8], int index) {
  return data[index];
}

float4 main(int index : INDEX) : SV_Target {
  return fetch(Data, index);
}
```

Currently, dxc generates the follow spir-v just before the call:

```
         %31 = OpAccessChain %_ptr_Uniform__arr_v4float_uint_8 %MyCBuffer %int_0
         %32 = OpLoad %_arr_v4float_uint_8 %31
         %33 = OpCompositeExtract %v4float %32 0
         %36 = OpAccessChain %_ptr_Function_v4float %param_var_data %uint_0
               OpStore %36 %33
         %37 = OpCompositeExtract %v4float %32 1
         %39 = OpAccessChain %_ptr_Function_v4float %param_var_data %uint_1
               OpStore %39 %37
         %40 = OpCompositeExtract %v4float %32 2
         %42 = OpAccessChain %_ptr_Function_v4float %param_var_data %uint_2                                                                                                                                                                   
               OpStore %42 %40
         %43 = OpCompositeExtract %v4float %32 3
         %45 = OpAccessChain %_ptr_Function_v4float %param_var_data %uint_3
               OpStore %45 %43
         %46 = OpCompositeExtract %v4float %32 4
         %48 = OpAccessChain %_ptr_Function_v4float %param_var_data %uint_4
               OpStore %48 %46
         %49 = OpCompositeExtract %v4float %32 5
         %51 = OpAccessChain %_ptr_Function_v4float %param_var_data %uint_5
               OpStore %51 %49
         %52 = OpCompositeExtract %v4float %32 6
         %54 = OpAccessChain %_ptr_Function_v4float %param_var_data %uint_6
               OpStore %54 %52
         %55 = OpCompositeExtract %v4float %32 7
         %57 = OpAccessChain %_ptr_Function_v4float %param_var_data %uint_7
               OpStore %57 %55
```
Notice this code loads the entire array, copies the array one element at a time to the function scope symbol `%param_var_data`.  Then in the end only 1 element gets loaded.  Even after inlining and other optimizations, we do not clean up the code.

This is bad for a couple reasons.  First this is slow.  We loading and storing more memory than needed.  The second issues is that some drivers do not like a single large load like this (especially for arrays of 2048 elements), and those driver are not able to run these shaders.

The solution we will work on is to get implement a memory based copy propagation.  This cannot be done through the SSA variables.  We will identify the symbols with the following properties:

1. Variable `a` is a function scope array.
1. `a` is stored to exactly once.
1. The store to `a` dominates all of its loads.
1. The value being stored to `a` is a copy of another variable or member of another variable `b`.
1. `b` is never stored to.

The only difficult part will be how to identify the copy.  The current pattern being generated is not very easy to identify because it has lots of stores, and they need to be grouped and lots of conditions checked.  We will ask the FE to generate the following code pattern instead:

1. Load the array being copied.
1. Extract each element using a series of OpCompositeExtract instructions.
1. Combine the results of the extracts using an OpCompositeConstruct.
1. Store the result of the OpCompositeConstruct to the local variable.

**Comment by s-perron** [comment]
In case people are wondering why we do not simple load the original object and then store that directly to the local copy, it is because they have different types.  One will be an array with an array stride decoration.  The other is an array with no decorations.

**Comment by antiagainst** [comment]
FYI: I've made the change in DXC SPIR-V CodeGen to emit the new code pattern as described in the above: https://github.com/Microsoft/DirectXShaderCompiler/pull/1158
