### ISSUE TITLE
Need an internal compiler error facility

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#1418]
Assertions are useful, but when they trigger in a Release build, they are ignored.  This means that released code may generate bad code and it will only be caught at runtime, making it difficult to debug.

We need an ICE (internal compiler error) facility that reliably triggers in all release configurations.

@dneto0 is this something that could be tied to the error/warning reporting machinery?

**Comment by dneto0** [comment]
Yes.  Every spv_context object has a message-consumer that is used to absorb diagnostic output.
The "message level" type has an SPV_MSG_INTERNAL_ERROR entry.

**Comment by dneto0** [comment]
I think it's bad form to intercept those errors to abend.  I think we should report them, and pass them through.  That makes it testable and composable.

**Comment by jfroy** [comment]
Yes, in particular we'd want to compose that with debug report / debug util extensions when running live in a driver. Engines would also likely want to capture errors when embedding a compiler.

**Comment by s-perron** [comment]
We will not be doing this. Many of our users do not want us halt the program because the compiler failed in some way. It will halt their program too.
