### ISSUE TITLE
If validating for an environment defined for SPIR-V N, then reject a module with SPIR-V version M where  M > N

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1433]

**Comment by dneto0** [comment]
Test OpenCL 1.2 cases.  See comments in #1462

**Comment by alan-baker** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/commit/3020104ff25a0f661e7818bd49fbf5f23e0b0e98 adds the remaining tests.
