### ISSUE TITLE
spirv-val requires SPV_KHR_16bit_storage even in Vulkan 1.1 environment

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Tools#1466]
Using `spirv-val --target-env vulkan1.1 foo.spv` on a shader module compiled with 1.1 environment in glslang fails on:

`error: 5: 1st operand of Capability: operand 4436 requires one of these extensions: SPV_KHR_16bit_storage`

**Comment by HansKristian-ARM** [comment]
Commit: fe9121f72144f1e1657cd21a55a1fec07c940e56

**Comment by antiagainst** [comment]
Hey @HansKristian-ARM, thanks for the report! I think we've already fixed the issue via https://github.com/KhronosGroup/SPIRV-Tools/commit/43ca2112b8fb3269a78ce0b9807ca6925adc222d. Please check the latest SPIRV-Tools and report otherwise.

**Comment by HansKristian-ARM** [comment]
Yes, this is fixed on master.
