### ISSUE TITLE
spirv-val fails on array of Position in Control shader.

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Tools#1472]
[test.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1897802/test.spv.txt)
`error: 243: According to the Vulkan spec BuiltIn Position variable needs to be a 4-component 32-bit float vector. ID <3> (OpVariable) is not a float vector.`

Spec is a bit vague here, because some kind of array of Position must be allowed (but perhaps only as part of a block).

**Comment by dneto0** [comment]
With SPIRV-Tools top-of-master I do not get that validation error.  What version of the code are you using?

Both Vulkan 1.0 and 1.1 say:

> Any variable decorated with Position must be declared as a four-component vector of 32-bit floating-point values. 

That seems clear to me.  It *should* fail validation in the way you report.

**Comment by dneto0** [comment]
Perhaps the Vulkan spec is wrong / out of date?

**Comment by dneto0** [comment]
For the record: 

```
 OpDecorate %3 BuiltIn Position
...
      %31 = OpTypeFloat 32
      %32 = OpTypeVector %31 4
...
      %34 = OpTypeInt 32 0
      %35 = OpConstant %34 3
...
      %48 = OpTypeArray %32 %35
      %49 = OpTypePointer Input %48


        %3 = OpVariable %49 Input

```

**Comment by dneto0** [comment]
Wait, I ran the validator incorrectly.  We have to specify --target-env vulkan1.1 to get the error.

So:  Yes, I get the error.  Also, the validator is implementing the Vulkan spec as-is. 

I understand there is a Khronos-internal issue related to this rule. https://gitlab.khronos.org/vulkan/vulkan/issues/1067

**Comment by johnkslang** [comment]
Generally, these rules intended as "after removing the level implicit arrayness that some interfaces add, the type must....".  Maybe there is a place this needs to be more clear?  But, obviously, in practice, for these interfaces that add a level of arrayness, one cannot give an error because the level of arrayness is present.

**Comment by johnkslang** [comment]
The competing statement is:

> Tessellation control shader per-vertex output variables and blocks, and tessellation control, tessellation evaluation, and geometry shader per-vertex input variables and blocks are required to be declared as arrays, with each element representing input or output values for a single vertex of a multi-vertex primitive. For the purposes of interface matching, the outermost array dimension of such variables and blocks is ignored.

I'm sympathetic if somehow not everything is hooked up right the spec, and that can be clarified, but I don't think there is any question the spec expects this.

**Comment by johnkslang** [comment]
Per-vertex don't include per-patch. The ones in question can only be non-per-patch geometry in, tess-control in/out, and tess-evaluation in.  Original/core Vulkan only has the four Position, PointSize, ClipDistance, and CullDistance, but several extensions expand the list.

PrimitiveId, InvocationId, PatchVertices, Layer, TessCoord, and ViewportIndex are not treated this way.
