### ISSUE TITLE
Bad optimization: LocalMultiStoreElim causes infinite loop?

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1487]
See details in https://github.com/google/shaderc/issues/450 and https://github.com/mpv-player/mpv/issues/5695 

Symptom is a bad transformation in LocalMultiStoreElim, very likely in SSA rewriter.

Behaviour seems like an infinite loop when that transform is applied, but works correctly without that transform.

Sending to @dnovillo

**Comment by dneto0** [comment]
Oh wait, the report might be saying that running the transform itself is taking "infinite" time, not that the generated shader does.
See https://github.com/mpv-player/mpv/issues/5695#issuecomment-379083051

**Comment by dnovillo** [comment]
Thanks. I will take a look.  Is there a test case though?  I've clicked through but quickly got lost without getting to a file I could try compiling.

**Comment by dneto0** [comment]
Test shader in source form is attached to the Shaderc bug.
Original Shaderc bug filed by @papricajim

**Comment by dneto0** [comment]
Hi @haasn : Is the problem in https://github.com/mpv-player/mpv/issues/5695  that the compiler hangs while running or the generated shader hangs?

I compiled example shader you provided in https://github.com/google/shaderc/issues/450#issuecomment-380657652 
With top-of-tree SPIRV-Tools it takes about 95ms to compile on my machine, and takes about 100ms with the commit (3020104ff2) that @papricajim tried from a few days back.

**Comment by haasn** [comment]
I'm not entirely sure, I'm still trying to reproduce the bug. It's probably best to ask @quilloss on this. But from the descriptions on #5695, it sounds like the compiler itself was taking a long time to complete, rather than the executed shader.

Of course, this is hard to tell unless isolated, since a hung GPU can lead to any manner of freezes that seem like the CPU has hung.

**Comment by DeadSix27** [comment]
@haasn Leaving the player running eventually made it play, after like 5minutes, wouldn't that speak against a infinite loop?

**Comment by xnoreq** [comment]
@DeadSix27  @dneto0 
I've added some debug messages locally, and it's stuck when it passes this compute shader
https://0x0.st/suYo.txt
to shaderc_compile (mpv/spirv_shader.c).
So it never returns from that method with 100% cpu load.

**Comment by quilloss** [comment]
It is not infinite, it just takes way to long to complete `DeadInsertElimPass::EliminateDeadInsertsOnePass`. As stated in the mpv bug report the loop `Mark all live inserts` cause the freeze.

Removing either `CreateLocalMultiStoreElimPass` or `CreateDeadInsertElimPass` from the optimization list prevents a freeze. I think it is not related to the GPU as the shader is still undergoing optimization during the freeze.

**Comment by greg-lunarg** [comment]
I will claim this as it appears to be against the Dead Insert pass.

**Comment by greg-lunarg** [comment]
It looks like I am unnecessarily doing exponential revisiting of phis during MarkInsertChain. I have a PR that avoids this and completes nearly instantaneously. I just need to do a some testing and I will submit.

**Comment by xnoreq** [comment]
@greg-lunarg Tested it with mpv and it now compiles in a very reasonable <10ms now instead of several minutes.

**Comment by DeadSix27** [comment]
That PR does work fine for me too, not as fast (in mpv) as it is for @xnoreq but definitely not minutes (is that because of me using the logs to measure it?)

using D3D11:
```
[   0.489][v][vo/gpu/d3d11] Compiled a compute shader in 334333us
[   0.489][v][vo/gpu/d3d11] shaderc: 83269us, SPIRV-Cross: 6450us, D3DCompile: 244614us
```
using Vulkan:
```
[   0.182][t][vo/gpu/vulkan] vk_compile_glsl(ra, tmp, GLSL_SHADER_COMPUTE, params->compute_shader, &comp)
[   0.220][v][vo/gpu/vulkan] shaderc compile status 'success' (0 errors, 0 warnings)
38ms
```
