### ISSUE TITLE
Possible locale dependency in strtod()

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/SPIRV-Tools#1491]
This is possibly analogous to https://github.com/KhronosGroup/glslang/issues/1228.

I also see a strtod() in this repository, whose behavior would be affected by setlocale(), and could get unexpected results.

I found making libraries calls in this setlocale() space to measurable impact performance, so do so very cautiously, sparingly, if needed.

**Comment by dneto0** [comment]
There is one use of strtod in SPIRV-Tools, and it's in the assembler.  It's used to parse a floating point number.  See https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/text.cpp#L121

It looks like we're not triggering the locale-sensitivity:
```
$ cat locale.spvasm
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint Fragment %main "main"
%void = OpTypeVoid
%void_fn = OpTypeFunction %void
%float = OpTypeFloat 32
%onep25 = OpConstant %float 1.25
%main = OpFunction %void None %void_fn
%entry = OpLabel
OpReturn
OpFunctionEnd

$ echo $LC_NUMERIC
de_DE.utf8
$ spirv-as locale.spvasm -o locale.spv
$ spirv-dis locale.spv
; SPIR-V
; Version: 1.3
; Generator: Khronos SPIR-V Tools Assembler; 0
; Bound: 7
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %1 "main"
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
 %float_1_25 = OpConstant %float 1.25
          %1 = OpFunction %void None %3
          %6 = OpLabel
               OpReturn
               OpFunctionEnd
```

Other facts:
-  Our code explicitly looks for a period (.) to recognize a floating point number literal.  
- Our code rejects a "1,25" as a floating point literal even in the de_DE.utf8 locale

```
$ spirv-as localecomma.spvasm -o localecomma.spv
error: 7: 29: Invalid 32-bit float literal: 1,25
$ echo $LC_ALL $LC_NUMERIC
de_DE.utf8 de_DE.utf8
$ cat local.spvasm
cat: local.spvasm: Datei oder Verzeichnis nicht gefunden
$ cat localecomma.spvasm
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint Fragment %main "main"
%void = OpTypeVoid
%void_fn = OpTypeFunction %void
%float = OpTypeFloat 32
%onep25 = OpConstant %float 1,25
%main = OpFunction %void None %void_fn
%entry = OpLabel
OpReturn
OpFunctionEnd
```

I think there is no bug here.   I could see asking for this to be tested.  However, setlocale is not defined to be thread-safe.

**Comment by johnkslang** [comment]
> Other facts:
>
>- Our code explicitly looks for a period (.) to recognize a floating point number literal.
>- Our code rejects a "1,25" as a floating point literal even in the de_DE.utf8 locale

It's worth noting that glslang also does not rely strtod() or locale to decide something is floating point, and does proper rejection/acceptance of syntax, explicitly, having nothing to do with setLocale(). It is only after all that is done, that it then uses strtod() to actually create the numeric value.
