### ISSUE TITLE
Incorrect Op*AccessChain instruction for vec ptr to scalar ptr casts

### ISSUE THREAD

**Issue by robclark** [KhronosGroup/SPIRV-Tools#1498]
I was debugging an issue w/ vstore_local cl cts tests, which does something like:
```
    vstore2( srcValues[ tid ], offsets[ tid ], ( (__local char *)sSharedStorage ) + alignmentOffset );
```

I've simplified this to a more trivial example:
```
__kernel void test_fn(__global int *res, __global int2 *v)
{
    *res = ((__global int *)v)[1];
}
```
This generates an `AccessChain` instruction like:
```
         %10 = OpFunctionParameter %_ptr_CrossWorkgroup_v2uint
         %15 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_uint %10 %uint_0 %uint_1
```
I believe this should have been an `OpInBoundsAccessChain` instead, or equivalently:
```
         %15 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_uint %10 %uint_0 %uint_0 %uint_1
```
given that for the Ptr access chain variants:
> The type of Base after being dereferenced with Element is still the same as the original type of Base.

Note also spirv-val doesn't seem to be checking the resulting type of the AccessChain instruction, since it doesn't seem to complain about this.  Perhaps a separate bug?

**Comment by robclark** [comment]
this might be the wrong place, I've copied it to: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/10

(but might be worth keeping this bug for spirv-val?)

**Comment by dneto0** [comment]
> The type of Base after being dereferenced with Element is still the same as the original type of Base.

That holds only after indexing with the first index, i.e. Element.

So for example the following is sensible:
```
 %number = .... some 32-bit int scalar value
 %base = OpFunctionParameter %_ptr_CrossWorkgroup_v2uint
 %foo = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_v2uint %base %number
```
In the expression for %15, there is a second index that then gives you a pointer to one of the scalar elements inside the v2uint.

So in fact the following is valid.  And %15 points to the second uint of the uint2 that the function parameter points to.
```
         %10 = OpFunctionParameter %_ptr_CrossWorkgroup_v2uint
         %15 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_uint %10 %uint_0 %uint_1
```

The validator is correct here in not triggering an error.
