### ISSUE TITLE
Local Single Block Elim is not eliminating stores

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#1500]
In local-single-block-elim, the propagation and elimination of the loads are happening, but the elimination of the stores and the variables are not.

These stores are preventing propagation of some values that could be propagated, resulting in a possible loss of optimization and legalization.

This is also a bit of a waste because this is leaving variables and stores to be re-analyzed by following passes, specifically local-single-store-elim and local-multi-store-elim.

For example, I have a real-live shader where a variable is stored-loaded-store-loaded-stored in the same block and then loaded in a subsequent block.  Since the stores are not eliminated, it prevents single-store-elim from  propagating a value that could have been propagated if the stores had been eliminated. This could make a difference for optimization and legalization.

In addition, the analysis by single-store-elim is wasted and has to be repeated by multi-store-elim, which ultimately propagates the value, but possibly too late.

ADCE does not remove these stores because it does not do Write-after-Write elimination.

It feels like a little additional work in this pass could cost-effectively eliminate these stores and enhance subsequent analysis.

**Comment by dneto0** [comment]
I haven't looked at SSA-rewriter in detail, but doesn't its back-to-front conversion to SSA registers cause the first two stores to look dead?  I guess a concrete example would help think this one through.

**Comment by greg-lunarg** [comment]
Yes, SSA rewrite will eventually propagate the value in this example, remove the final load and enable these stores to be removed. But SSA rewrite is much farther down the recipe. If this propagation can be done earlier by single-store, it potentially can enable other optimizations.

Here is a quick C example:

int a,b,c;
int x,y;

main() {
   int i;
   i += a;
   i += b;
   if (c > 0)
     x = i;
   else
     y = i;
}

**Comment by greg-lunarg** [comment]
And a similar shader:

```
layout(location=0) in float a;

layout(location=0) out float x;
layout(location=1) out float y;

main() {
   float f = 0.0;
   f += 0.1;
   f += 0.1;
   if (a > 0.0)
      x = f;
   else
      y = f;
}
```

**Comment by s-perron** [comment]
I believe this is done.
