### ISSUE TITLE
Support for "compatibility transforms"

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/SPIRV-Tools#1503]
I have a few cases now in SPIRV-Cross, where it's a bit unclear where the functionality should lie.

https://github.com/KhronosGroup/SPIRV-Cross/issues/535
https://github.com/KhronosGroup/SPIRV-Cross/issues/527

Mapping FP16 -> FP32 + RelaxedPrecision, converting FP64 code to FP32, uint to int are all SPIR-V -> SPIR-V transformations which improve compatibility with older targets (even though they don't give exact same results), and doing these transforms in SPIRV-Cross is a bit out of place.

What is SPIRV-Tools stance on these kinds of transforms?

**Comment by dneto0** [comment]
I agree those transforms belong in SPIRV-Tools in the "optimization" library.  I view the library as a toolbox of transforms that a user (developer) combines how they like.
I'd happily incorporate correct implementations.

**Comment by HansKristian-ARM** [comment]
Sounds good.

For complete beginners to SPIRV-Tools internals, what's the simplest way to get started writing some transformation passes?

**Comment by s-perron** [comment]
I'm guessing these will not get done, so I will close this issue.
