### ISSUE TITLE
spirv-as reports whole program as the invalid opcode

### ISSUE THREAD

**Issue by dekimir** [KhronosGroup/SPIRV-Tools#152]
I assemble a simple program with an incorrect opcode at the end.  `spirv-as` should report just that opcode as invalid, but instead it reports the whole program as the opcode name:

```
deki@deki-macbookpro>cat bug.spvasm 
OpCapability Shader
OpMemoryModel Logical GLSL450
OpXYZ
deki@deki-macbookpro>./spirv-as bug.spvasm 
error: 3: 1: Invalid Opcode name 'OpCapability Shader
OpMemoryModel Logical GLSL450
OpXYZ'
```

**Comment by antiagainst** [comment]
Interesting. The symptom is the same as #126. But this time EOL is there...
