### ISSUE TITLE
Vulkan: at most one level of arrays are permitted at the descriptor interface

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1522]
Vulkan internal issue 1192.

SPV_EXT_descriptor_indexing introduces the ability to use arrays of descriptors.  GLSL permits arrays of arrays, but Vulkan (will) only accept SPIR-V having a single level of array at the descriptor interface.  Front ends (like Glslang) are free to flatten arrays of arrays into a single level array.

**Comment by dj2** [comment]
I reverted the linked CL, so re-opening this issue.
