### ISSUE TITLE
Storing result of OpSampledImage

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Tools#1528]
From my understanding of the spec, the result id of OpSampledImage can only be consumed by an instruction specified to take the type OpTypeSampledImage. However I can currently store the result of OpSampledImage into a variable with no validation errors. I assume this is missing validation logic and not actually a valid instruction?

**Comment by alan-baker** [comment]
Yes, according to the spec (in 2.16 Universal validation rules):
```
All OpSampledImage instructions must be in the same block in which their Result <id> 
are consumed. Result <id> from OpSampledImage instructions must not appear as 
operands to OpPhi instructions or OpSelect instructions, or any instructions other 
than the image lookup and query instructions specified to take an operand whose 
type is OpTypeSampledImage.
```
This is a missing validation check.

**Comment by jodavis42** [comment]
Is the same also true for image/samplers? I don't see anything in the univeral validation rules about this but glslang has the warning "AST will form illegal SPIR-V; need to transform to legalize" when it generates this code.

In case your curious, I was writing hlsl code that copied a texture into a local to see what spir-v code was generated and this was the warning I got from glslang.

**Comment by jodavis42** [comment]
So is the general rule of thumb that no opaque types should be able to be stored/copied?

As a small note these should probably also be illegal to OpCopyMemory.

**Comment by alan-baker** [comment]
Yes, that's a good rule of thumb. Some frontends will need to perform some optimizations to get code into a valid state.

**Comment by alan-baker** [comment]
Vulkan spec was updated to include text that Image, Sampler and SampledImage types must not be stored to.

**Comment by zoddicus** [comment]
FYI, the specific code for the check of OpSampledImage is in ValidateSampledImage.
