### ISSUE TITLE
include/spirv/OpenCL.std.h:271:2: error: extra ‘;’ [-Werror=pedantic]

### ISSUE THREAD

**Issue by azur3** [KhronosGroup/SPIRV-Tools#153]
Building on Ubuntu and getting this message.

Need to fix the code or remove pedantic?

Thanks

**Comment by dekimir** [comment]
Hi, @azur3.  Sorry about the trouble.

Could you provide the whole build log?  How closely are you following the README instructions?

**Comment by dneto0** [comment]
This is a problem with the OpenCL header as published in the SPIR-V Registry.

**Comment by dneto0** [comment]
I've filed a bug on the Khronos public bugzilla to track this at the working group level.
https://www.khronos.org/bugzilla/show_bug.cgi?id=1476

**Comment by dekimir** [comment]
@dneto0 agreed, but:

1. if @azur3 is getting this error by turning on `SPIRV_WARN_EVERYTHING`, they can work around the problem by turning it off
2. we can fix `SPIRV_WARN_EVERYTHING` by disabling certain warnings for files we can't control that have known problems

**Comment by dneto0** [comment]
Correct.  I don't want to turn off things in SPIRV_WARN_EVERYTHING because that's how I noticed the pedantic problem in the first place.
Recommend action: don't use SPIRV_WARN_EVERYTHING or -pedantic right now.  Use those only after we get a fixed header file from upstream.

**Comment by AWoloszyn** [comment]
This should now be fixed.
