### ISSUE TITLE
Validator incorrectly says PrimitiveId can't be used if the Fragment execution model

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Tools#1530]
Sorry if I'm filing this wrong, but I filed this on the headers repository (https://github.com/KhronosGroup/SPIRV-Headers/issues/65) a month back but I haven't heard any reply so I decided to file this here.

Currently the usage of PrimitiveId in the Fragment execution model throws an error in the validator. According to the Vulkan spec it should be an allowed input to the Fragment stage though (and a few of the tessellation stages I believe too).

**Comment by alan-baker** [comment]
The code allows PrimitiveId in fragment and tessellation shader only in the input storage class. Do you have a code sample where that is not the case?

**Comment by jodavis42** [comment]
Ok, so the issue is that you have to declare the capability of Geometry or Tessellation when decorating PrimitiveId even though the execution mode is Fragment (and Geometry implies execution mode of Geometry). It looks like glslang adds the Geometry capability to get around this which feels wrong to me (correct me if I'm wrong).
Here's an example
[TestBed.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1952390/TestBed.txt)
