### ISSUE TITLE
Parsing SPIR-V binary to fill VkPipelineLayoutCreateInfo struct

### ISSUE THREAD

**Issue by LukasBanana** [KhronosGroup/SPIRV-Tools#1532]
This is more of a question than an issue with the libraries.

Is it sensible to parse a SPIR-V binary module with the `spvBinaryParse` to fill the `VkPipelineLayoutCreateInfo` structure?

I'd like to avoid forcing a user of my 3D framework fill in a pipeline layout descriptor all the time, since all these information are already available inside the shaders (e.g. which binding slots and resources are used).

Thanks and kind regards,
Lukas

**Comment by LukasBanana** [comment]
That looks indeed like what I am looking for.
However, I thought I could find something like this in the official Khronos repositories.

**Comment by zzag** [comment]
There's a thing called SPIRV-Cross. It might be what you're looking for.
