### ISSUE TITLE
Static arrays in HLSL need to be merged into one array

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#1534]
I have a real-life HLSL compute shader with two initialized static arrays, one with scalar uint components, the other with uvec3. fxc merges these into one array, shifting the uint3 components into the yzw fields of the new array. If this merging is not done for Vulkan, at least one IHV driver will reject the shader.

This merging is done by fxc to keep the total length of the immediateConstantBuffer (icb[]) below a certain threshhold, apparently 512 by default. The function instructions are transformed to deal with the relocation of all the static arrays into the single new array.

I propose that we add such a pass to spirv-opt.

If there is apprehension in adding this to legalization, I propose we create an "fxc equivalence" option to spirv-opt, glslangValidator, etc which emulates as much as possible the transformations done by fxc.

The packing algorithm looks to be a classic greedy algorithm. The arrays are sorted first by the vector length of the array component (one having precedence), then by the length of the arrays, larger having precedence. Then the arrays are packed into a one-dimensional array of vec4s such that the x column is filled first (followed by y, z and w) and the total required length of the new array is minimized.

For example, consider the following arrays:

static const uint3 arr_in[4] =
{
    uint3(0x2, 0x2, 0x2), uint3(0x3, 0x3, 0x3), uint3(0x4, 0x4, 0x4), uint3(0x5, 0x5, 0x5)
}

static const uint arr_in2[4] = {
        0x1, 0x1, 0x1, 0x1
}

They would be merged into the following array:

static const uint3 arr_out[16] =
{
    uint3(0x1, 0x2, 0x2, 0x2), uint3(0x1, 0x3, 0x3, 0x3), uint3(0x1, 0x4, 0x4, 0x4), uint3(0x1, 0x5, 0x5, 0x5)
}

All references to arr_in[i] would become references to arr_out[i].x. All references to arr_in2[i].x would become references to arr_out[i].y.

glslangValidator currently puts such static arrays into Function scope. I haven't looked at dxc yet. It could do things differently, but even so, much of the algorithms would be similar to transform its SPIR-V  to get a similar effect.

I am claiming this issue.

**Comment by dneto0** [comment]
Thanks for the clear explanation.  

How are the arrays selected for this transform?  Is it only done conditionally, to meet the size target?
Do you think there is any performance tradeoff when accessing the uvec3's?

FYI @antiagainst , who has been seeing cases that require more massaging than we're used to,.

**Comment by greg-lunarg** [comment]
With just a handful of experiments, it looks that the compiler always attempts to merge arrays, no matter the size. I have only looked at 1-D arrays and 32-bit types.

I haven't done any performance tests. Would be good to get some comments from IHV folks who are a little more familiar with their own hardware performance.

**Comment by antiagainst** [comment]
Interesting. I haven't seen such a real-world case thus far, but I put @greg-lunarg's example through fxc and can confirm fxc does merge them. But my experience is that the uint3 array takes .xyz, and int array takes .z. Presumably this is better for performance than letting uint3 array taking .yzw since more aligned?

In DXC, static global variables are put into `Private` scope. They may be changed to `Function` scope b/c of PrivateToLocalPass. 

@greg-lunarg: I'm curious how large your original arrays are that they cannot be put in the `Private` or `Function` storage separately. 512 (scalars?) sounds like a limit with some history that I'm not sure we are still subject to it.

**Comment by greg-lunarg** [comment]
The placement may also be related to the access patterns. I haven't correlated with that yet.

Yes, we are seeing 512 on a fairly capable piece of hardware with its latest driver. The limit could be related to glslang putting the array in Function scope. Maybe Private scope would work. This should be investigated.

**Comment by s-perron** [comment]
As for where this optimization can be placed, I would suggest it goes into "-O" and possibly "-Os".  I want to keep the legalization passes as the thing need to generate legal vulkan spir-v.  For example, we want to remove the local copies of opaque object or the variable pointer that dxc generates.

I don't want to create another option.  The fxc equivalence sould be "--lelgalize-hlsl -O".

**Comment by s-perron** [comment]
@greg-lunarg are you actively working on this?  I have a few more questions about it.

1) Does the private to local optimization get run in the receipt that is being used on it?  If not, does it make a difference? 

2) Is it a problem for this IHV if you have 4 float arrays of the same size?  This could effect the heuristics.  Maybe we just want to merge vectors that are less than 128B with something to make it that size.

3) Do these arrays have an array stride decoration?  Does adding one make a difference in the acceptance of the shader (even if it might be bad for performance)?

I just want to collect some extra information.

Also, I'm actively working on some data reorganization stuff.  This might be able to be incorporated into that optimization.  I can see how it will fit into my implementation without too much extra code.
