### ISSUE TITLE
spirv-val does not validate OpImageQuerySize doesn't have LOD

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Tools#1538]
Here's a shader:
[test.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1966244/test.txt)

It uses OpImageQuerySize with a sampled 2D image, which is not allowed, but does not trip validator.

**Comment by jaebaek** [comment]
Rebased and pushed into master as 37c99ab
