### ISSUE TITLE
Incorrect optimization due to OpCopyMemory

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Tools#1556]
There seems to be a bug when using OpCopyMemory where the optimizer incorrectly removes code. Attached is a sample

[CopyMemoryOptimizerBug.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1993464/CopyMemoryOptimizerBug.txt)

If the line "OpCopyMemory %32 %25" is replaced with "OpStore %32 %30" then the optimizer will produce valid code (it'll store the input to the output).

Unless I'm mistaken and OpCopyMemory isn't valid here. The spec says: "Matching Storage Class is not required" so I would assume this code is valid.

**Comment by s-perron** [comment]
Looks like ADCE does not recognize the OpCopyObject as a read of the memory location.
