### ISSUE TITLE
Assertion/crash in ReduceLoadSize pass

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Tools#1559]
I get an assertion / crash in release when optimizing shaders in ReduceLoadSize, GetSingleWordInOperand(1) is invalid for some instructions like SpvOpConvertUToF with float3 I think... Not sure if this is missing an `else`? Will attach a repro case shortly.

```
  def_use_mgr->ForEachUser(
      op_inst, [&elements_used, &all_elements_used](ir::Instruction* use) {
        if (use->opcode() != SpvOpCompositeExtract) {
          all_elements_used = true;
        }
        elements_used.insert(use->GetSingleWordInOperand(1));
      });
```

**Comment by zeux** [comment]
Here's the shader that triggers this.

[spirv18.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2002705/spirv18.zip)

**Comment by s-perron** [comment]
This should be a `WhileEachUser` and a return in the if statement.  I'll fix it up.  Thanks for letting us know.
