### ISSUE TITLE
Replace insert-extract elimination by the simplification pass.

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1570]
The insert-extract elimination pass is really a special purpose instruction folding pass.  This is the same thing that is implemented in the simplification pass, so we should be able to replace the former by the latter.

However, the simplification pass is missing some rules that are implemented in the insert-extract elimination pass.

For this to be considered done we will need to

- [x] Have folding rules that cover everything in the insert-extract elimination pass.
- [x] Replace the instances of insert-extract-elim in the standard optimizations sets by the simplification pass.
- [ ] Change the option `--eliminate-insert-extract` to call enable the simplification pass instead with documentation changes to deprecate the option.
- [ ] Delete all code that is not unused because of the first three changes.

**Comment by greg-lunarg** [comment]
I can certainly imagine value in using the simplification infrastructure to do extract elimination, but I am slightly concerned with conflating all the other simplifications with it (x + 0.0 => x, etc). My concern is mostly around compile time. My instincts suggest we might want to do have these done separately as it feels like they would be useful at different points in an optimization recipe. Do we have data on simplification time together and separately?

**Comment by s-perron** [comment]
About the conflation, what do you think should be kept separate?  When I think of the simplifications that are done, the only ones that I think we might want independent control of are the floating point folding rules like the one you mentioned above.  However, that can be turned off with the "NoContraction" decoration.  This is really a  FE issue.  If the user tell the FE that generates the spir-v that they don't want floating point operations folded, then they should add the decoration.

I'll try to collect some compile time numbers.  I expect the compile time will be higher, but the question is whether or not the compile time is worth it.

Do you have customer who actually do not want the extra folding, or is it just hypothetical?  For now the extra simplification is mostly just fold arithmetic (fix-point and floating-point).  However, I have see the OpPhi and OpSelect folding rules make a big difference.

**Comment by greg-lunarg** [comment]
I would seperate the extract elimination and any other "vector" simplification (for example, OpVectorShuffle) from everything else.

The concern is strictly compile time. Someone may wish to create a recipe which does both kinds of simplfication, but at different frequencies and different points in the recipe.

**Comment by s-perron** [comment]
I did some compile time test.  I compared three different optimization orders.  "current" is what we currently have for `--legalize-hlsl -O`.  Proposed is what I have implemented in #1571.  "other" is the same as current except I reordered the simplification pass and the insert-extract-elim pass in the legalization set.  I have attached the config file.  
[current.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2033012/current.txt)
[other.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2033013/other.txt)
[proposed.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2033014/proposed.txt)

I ran on three set of shaders:

Set   | current | other | proposed
---------|------------ | ------------- | ---------
1 | 54m54.964s | 53m39.241s | 53m19.604s
2 | 1m49.499s | 1m48.566s | 1m48.538s
3 | 11m31.534s | 11m22.115s | 11m35.725s

The only set that can be improved by using insert-extract-elim is set 3.  That set is one that has a lot of really large structures (we are looking at thousands of members), and even in that extreme we only get a 2% improvement in compile time.

@greg-lunarg Do you have any other experiments you want me to run?  It seems like in extreme situation we can see a small improvement, but I do not feel like it is work the extra technical debt.

**Comment by greg-lunarg** [comment]
Thanks Steven. I am looking at this now and should have an answer shortly.

**Comment by greg-lunarg** [comment]
I agree that combining these will work ok. Thanks!
