### ISSUE TITLE
spirv-val reports "Duplicate non-aggregate type declarations..." error for pointer types

### ISSUE THREAD

**Issue by karolherbst** [KhronosGroup/SPIRV-Tools#1577]
According to the 1.3 specification section 2.8:
`
[...] Pointer types are also allowed to have multiple <id>s for the same opcode and operands, to allow for differing decorations (e.g., Volatile) or different decoration values (e.g., different Array Stride values for the ArrayStride). [...] Non-aggregate non-pointer types are different: It is invalid to declare multiple type <id>s for the same scalar, vector, or matrix type. That is, non-aggregate non-pointer type declarations must all have different opcodes or operands. [...]
`

Which means spirv-val shouldn't check for duplicate pointer types.

**Comment by alan-baker** [comment]
Thanks for the report. This check did not get updated with the release of 1.3 which pulled variable pointers into core.
