### ISSUE TITLE
analysis::Image incorrectly applies an Access Qualifier even if none is supplied.

### ISSUE THREAD

**Issue by AWoloszyn** [KhronosGroup/SPIRV-Tools#1582]
If I create an anaylsis::Image for use with the TypeManager, it is given an Access Qualifier of ReadOnly. This is incorrect, since the AccessQualifier is optional, and if we are not using the Kernel Capability, must not be present.

3.18 Access Qualifier
```
0   | ReadOnly            | Kernel
    | A read-only object  |
```

**Comment by s-perron** [comment]
Without a sample to reproduce I cannot check it. However, we have not see this be a problem, so I will simply close.
