### ISSUE TITLE
validate: (data) Block can't appear within a Block

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1587]
Explicitly say (data) Block cannot be nested in another Block
SPIR-V internal issue 295.

**Comment by sarahM0** [comment]
As mentioned in SPIR-V internal issue 295: To be more explicit...  Under
2.16.2. Validation Rules for Shader Capabilities
- Decorations
Add one more subbullet: 
Block or BufferBlock cannot decorate a structure type that is nested at any level inside another structure type decorated with Block or BufferBlock.
