### ISSUE TITLE
Can't assemble ViewportRelativeNV

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1596]
There's something weird with operand lookup.  Trying to assemble the following:
```
OpDecorateId %1 HlslCounterBufferGOOGLE %2
OpDecorate %1 ViewportRelativeNV
```
Fails with:
```
error: 2: 15: Invalid decoration 'ViewportRelativeNV'.
```
This seems to be related to the fact that that token is defined in the grammar with `version : "None"` to indicate a "Reserved" token, and hence not defined by any SPIR-V version.

But that's weird because I can assemble the HlslCounterBufferGOOGLE line. 

Something weird is going on.

**Comment by antiagainst** [comment]
I think it's because the grammar rules for `ViewportRelativeNV` is missing `extensions` field right now.

**Comment by antiagainst** [comment]
I fixed missing `extensions` field for multiple SPIR-V extensions with multiple PRs, but seems missing this one.
