### ISSUE TITLE
CapabilityPass() does not validate capabilities for SPV_ENV_VULKAN_1_1

### ISSUE THREAD

**Issue by daveh-lunarg** [KhronosGroup/SPIRV-Tools#1597]
When passing a shader to spvValidate() with a context of SPV_ENV_VULKAN_1_1 there is no handler implemented, so all capabilities are allowed by default.

**Comment by dneto0** [comment]
Acknowledged.    I'd like to triage this as "suggested to start" but GitHubs project feature is not allowing me to do this right now. :-(
