### ISSUE TITLE
Opt: Implement Code Sinking?

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#1611]
During recent comparison of SPIR-V to DX assembly, it seemed that fxc was performing an optimization that I will call "code sinking". The process of sinking is to move an instruction as deep as possible into conditional control flow. The reason to do this is that, for uniform control flow, execution of code under control flow may be avoided, thus potentially optimizing execution time of the shader. 

Analysis suggests that code sinking in spirv-opt could have performance benefit. And if code is not replicated, such sinking should generally do no harm to performance.

Evidence

Using renderdoc profiling of a SPIR-V shader in a real life Vulkan capture on a prominent graphics platform, I performed several different experiments.

First, I did sinking on the SPIR-V as much as possible manually. Even though the opportunities were not huge, about a 1% improvement was achieved in the shader execution time.

Then I reversed the optimization. I pulled as much code out of conditional control flow as I could and placed it just before the control flow divergence. The time for the shader increased by 20%.

These two results suggest two things: the platform I was using was performance sensitive to the placement of code relative to conditional control flow, and the driver's shader compiler was not doing this optimization.

Initial Restrictions

I think we can probably come up with a set of restrictions for this optimization that capture the lion's share of the benefit and keep the algorithm fairly simple. The algorithm can be made more sophisticated as is needed.

One almost obvious restriction is to not push code into loops. Most shader loops execute at least once so at best this will be a wash and at worst it will increase execution time.

Another restriction is to only push combinator operations (add, mul, etc) and non-indexed loads which shader compilers can hoist back out if they wish. In general pushing sample instructions is safe if the control flow is uniform, but it does require that analysis. For the several cases I looked at, most benefit could still be achieved without pushing samples. Removal of this restriction can be done at a later time as it is needed.

Finally, only push instructions whose results are used in just a single block. This trivially avoids duplication. This may mean we miss some opportunities, but it makes the algorithm much simpler. For the several cases I looked at, most benefit could still be achieved with this restriction. Removal of this restriction can be done at a later time as it is needed.

Other Algorithmic Details

A phi function use will count as a use for the block with which the value is associated through the phi function.

Other Optimization Implications

This optimization may reduce opportunities for if-conversion. But while this may slightly increase the shader size comparatively, its performance should be no worse and likely better as more code is under conditional execution. It is therefore recommended that this be done before if-conversion.

Theoretically this could undo opportunities for common subexpression elimination and have negative size and performance implications. It may be desirable to execute CSE first.

IHV Implications

Since fxc does this optimization as well, it is likely that implementing this optimization in spirv-opt will not do harm, at least relative to DX.

**Comment by greg-lunarg** [comment]
I will claim this issue for the moment.

**Comment by s-perron** [comment]
I would like to be able to move loads from global resources.  When we have a function call with a value parameter that is inlined, we will usually end up with a load at the "start" of the inlinined function even if it used much later.

The other way this optimization can help is in trying to reduce the live range of a value, which should help reduce register pressure.  I think we should consider being fairly aggressive with this for experimentation.

**Comment by s-perron** [comment]
The algorithm has been implemented.  For any further improvements, we should open a new issue.
