### ISSUE TITLE
Spurious AppVeyor failures

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1615]
Example: https://ci.appveyor.com/project/Khronoswebmaster/spirv-tools/branch/master/job/8ucofc97wrgi9359 

I think we're running into a resource exhaustion condition.  

See @dj2 's note at https://github.com/KhronosGroup/SPIRV-Tools/pull/1604#issuecomment-395113175 
 where it might be disk space issue.

MSVC debug builds are rather large.

Let's fix this because it's getting in the way of the progress of the project.

**Comment by dj2** [comment]
I believe this is now fixed by @dneto0 with PR #1616 so I'm going to close this issue.
