### ISSUE TITLE
Optimizer Crash

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Tools#1634]
[OptimizerCrash.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2128250/OptimizerCrash.txt)

In the attached file the optimizer will crash when optimizing for speed (-O) in the latest source.

I attempted to make the example as small as I could to isolate it but this is as far as I got. It also looks like the crash is on an id not present in the original file, so I assume new instructions added by the optimizer.

**Comment by jodavis42** [comment]
I should note that optimizing for size doesn't crash though.

**Comment by alan-baker** [comment]
Segfaults at line 203 of vector_dce.cpp. Looks like the code is using op_inst->result_id() instead of op_inst->type_id().
