### ISSUE TITLE
spirv-val incorrectly lints a bitcast from int to bool

### ISSUE THREAD

**Issue by MaikKlein** [KhronosGroup/SPIRV-Tools#1647]
https://gist.github.com/MaikKlein/da94caa05105c13d1cb7782e946805a0#file-shader-spv-L85
```
         %52 = OpIAddCarry %_struct_51 %uint_1 %uint_1
         %53 = OpCompositeExtract %uint %52 0
         %54 = OpCompositeExtract %uint %52 1
         %55 = OpBitcast %bool %54
```
>Result Type must be an OpTypePointer, or a scalar or vector of numerical-type.

And a scalar is defined as

> Scalar: A single instance of a numerical type or Boolean type. Scalars will also be called components when being discussed either by themselves or in the context of the contents of a vector.

But it lints with 

> error: 80: Expected Result Type to be a pointer or int or float vector or scalar type: Bitcast

Version:

> SPIRV-Tools v2018.4-dev unknown hash, 2018-06-24

**Comment by alan-baker** [comment]
> Result Type must be an OpTypePointer, or a scalar or vector of numerical-type.

This should be read as two possibilities:
1. OpTypePointer
2. Numerical type (integer or floating point) that is either a scalar or a vector

**Comment by MaikKlein** [comment]
I see, thanks for correcting me. I guess I should have read it more carefully.
