### ISSUE TITLE
Assert in Compact IDs optimization pass

### ISSUE THREAD

**Issue by pow2clk** [KhronosGroup/SPIRV-Tools#1648]
This was originally found in dxc and filed as https://github.com/google/DirectXShaderCompiler/issues/264 . Since I've confirmed it's entirely constrained to SPIRV-Tools, I'm opening this issue and closing that one. I'll copy an edited version of the explanation from there.

a1f9e1342e77e47251e2f001d95f8af8a523745a recently altered which Analyses were preserved for the compact IDs pass. Instead of preserving nothing, it preserved a list of things including `ir::IRContext::kAnalysisCFG` . This last is a problem because as potentially changes the result IDs, it can change the basic block ID predecessors. `IRContext::CheckCFG()` uses a stale basic block ID to index predecessors and fires an assert. This function is only called inside an assert itself, so this is entirely a debug issue as manifest here. Though I wouldn't say for certain it doesn't have other effects.

The way to observe this issue is to build spirv-opt with debug symbols and run it on the .spv file included in the attached zip since github won't let me upload mysterious file extensions, but zipped mysterious files are a-okay. Any unoptimized spir-v file will probably work.
[ppass.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2142599/ppass.zip)

Simply running `spirv-opt  --compact-ids ppass.mO.spv -o ppass.spv` is insufficient because the CFG has to be valid at the start of the compact IDs pass or it will get validated as soon as `cfg()` is called in `CheckCFG()` anyway. So you have to do some other optimization pass first. I did: `spirv-opt  --redundancy-elimination --compact-ids ppass.mO.spv -o ppass.spv`

I have a fix for the problem. I hoped to have a test to prevent regressions, but I was looking over the existing compact_ids_test and I'm unsure that the issue can be reproduced unless I can be sure that another pass is run before it. Maybe I can work it into the pass_manager_test. I'm open to suggestions though.

**Comment by s-perron** [comment]
Here is a snippet you can use when writing a test:

```
  BuildModule(SPV_ENV_UNIVERSAL_1_1, nullptr, test, SPV_TEXT_TO_BINARY_OPTION_PRESERVE_NUMERIC_IDS);
  ASSERT_NE(nullptr, context);
  auto pass = CreateCompactIdsPass();

  opt::CompactIdsPass compact_id_pass;
  context->BuildInvalidAnalyses(compact_id_pass.GetPreservedAnalyses());
  compact_id_pass.Run(context.get());
  EXPECT_TRUE(context->IsConsistent());
```
