### ISSUE TITLE
Request more useful coloration in disassembly

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/SPIRV-Tools#1658]
It would help greatly speed up reading this form of SPIR-V (types on the right, with the operands) if:

- types were a different color than non types
- color for thing X is the same on both sides of the `=` (note the side of the `=` is already trivially visually discernible)

**Comment by dneto0** [comment]
> color for thing X is the same on both sides of the = (note the side of the = is already trivially visually discernible)

Right now definitions are blue and uses are yellow.   This is a hold-over from when the assembly syntax didn't use the equality sign and result ids were in place as specified by the binary format.  It enhanced readability to make result-ids a different colour from other IDs.   

If we change to make result IDs the same as uses, then (except for your first suggestion), all IDs would be the same colour.  Is that what you mean?

**Comment by johnkslang** [comment]
Yes. It is easier to visually match up the same thing if it is rendered the same way. It seems better to have color carry an additional meaning. Currently, it is harder to pick out types than left/right of the =.

(I have no criticism or complaints about how we got here.)

**Comment by s-perron** [comment]
Unlikely that we will change this.
