### ISSUE TITLE
Optimizer memory leaks

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Tools#1659]
The optimizer has two fairly obvious memory leaks, both in fold.cpp.
One is line 202 in the function FoldInstructionInternal and the other is on line 214 in the function GetConstantFoldingRules.

Both of these could be turned into static non-pointers to get rid of the leaks from my quick tests.

**Comment by dneto0** [comment]
I'd suggest these objects belong to the IRContext object.

**Comment by s-perron** [comment]
When I wrote this code I did not want to make the object static to avoid issues with static variable construction and destruction order. See our style guide: https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables.

I had considered placing it in the IRContext, but decided against that.  This would expose the folding rules to anybody who has access to the IRContext.  I don't want that.  I want the internal implementation of the folding functions to remain hidden.

That is why I opted for this pattern.  Notice this is the last bullet point in the section on static and global variables in the style guide:

> If all else fails, you can create an object dynamically and never delete it by binding the pointer to a function-local static pointer variable: static const auto* const impl = new T(args...); (If the initialization is more complex, it can be moved into a function or lambda expression.)

Let me know if there are other issues I have not considered.

**Comment by jodavis42** [comment]
So while I agree with using a static pointer instead of a static instance I feel that letting this leak isn't a good alternative.

In the application I'm working on, we try to make sure we don't have any memory leaks. However now that I'm using the spir-v optimizer I get false leak reports that make it significantly harder to track down leaks in our own code base as well as near impossible to set up automated leak tests. I imagine as spir-v gains more traction that this will be an issue for other users too.

Would it be possible to for you to register an atexit callback to clean this up? Or at least add a global Shutdown/Cleanup function so I can manually invoke cleanup?

**Comment by s-perron** [comment]
Okay.  What I did was move the folding routines into a class, and that class owns the memory that is being leaked.  Then the context owns an instance of that class.  It should get destroyed when the context is destroyed.
