### ISSUE TITLE
spvTextToBinary cannot handle CR+LF unless fread is used by client

### ISSUE THREAD

**Issue by httpdigest** [KhronosGroup/SPIRV-Tools#166]
I built a small DLL using the SPIRV-Tools.lib library to allow another language to call into SPIRV-Tools using a foreign-function interface of that language to call into C libraries.
The function in the DLL accepted a single memory pointer to the assembly text, which was loaded by the client program before calling into the DLL and eventually into spvTextToBinary.
This assembly text was read from a file as is, and not via fread, which in "r" text mode apparently converts CR+LF to LF under msvc 14.
The function spvTextToBinary() seems to be unable to handle CR+LF linebreaks in the source assembly text.
The spirv-as assembly tool works flawlessly, though, because fread (in "r" text mode) converts CR+LF to LF (\n).
But it does not work when using other mechanism that read the file as is without any conversion of line-breaks.

So the current workaround is to force the client of spvTextToBinary() to convert CR+LF to LF before handing the assembly text to spvTextToBinary.

Error message I am getting for [the example](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_example) in the SPIR-V specification:
```
error: 6: 1: Expected <opcode> or <result-id> at the beginning of an instruction, found '
'.
```

**Comment by dekimir** [comment]
We could broaden our definition of whitespace, assuming there are no unexpected side-effects.

**Comment by dneto0** [comment]
Thanks for the bug report.  Yes, we should handle this.  The only tricky part is recognizing that \r\n advances only a single line forward, for line counting.

It's also nice to see someone using the fact that SPIRV-Tools is a C API.  :-)

**Comment by httpdigest** [comment]
Thanks for noting and for wanting to fix this! Yes, SPIRV-Tools as a library is a very useful tool to assembly spir-v at runtime!
The C fread() function btw. is horrible. :)
With a libc on linux it does not even convert CR+LF to LF but just treats "r" mode the same as "rb" mode. So it would currently not be possible to read assembly on Linux that was written on Windows (i.e. with CR+LF line endines). Not even with the "as" tool using fread() "r".
I'd definitely be in favor of handling different line breaks in the library itself.

**Comment by dekimir** [comment]
@httpdigest should be fixed now, please give it a whirl...

**Comment by httpdigest** [comment]
Confirmed. Works fine! :) Thanks.
