### ISSUE TITLE
Disable Kokoro VS2017 Debug build until we can use an updated VS2017 compiler

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1677]

**Comment by dneto0** [comment]
The build is failing due to known issue. It's distracting to see the failures which we should ignore.

**Comment by ehsannas** [comment]
Put up the change for your review.

**Comment by dneto0** [comment]
> Put up the change for your review.

Sorry, I don't see it.

**Comment by dneto0** [comment]
Fixed with a Google-internal CL.
