### ISSUE TITLE
spirv-dis succeeds with a filename but fails when reading from stdin 

### ISSUE THREAD

**Issue by allanmac** [KhronosGroup/SPIRV-Tools#1688]
`spirv-dis < foo.spv`
`...`
`error: 130: End of input reached while decoding OpDecorate starting at word 129: missing ID operand at word offset 1.`

As noted above, `spirv-dis <filename>` succeeds.

After inspecting `tools/io.h:ReadFile()`, this might be a case where you want to reopen stdin with `freopen(NULL,"rb",stdin)`?

I'm using the prebuilt Vulkan SDK 1.1.77.0 on Win10.

Example .spv attached.

[comp.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2178208/comp.zip)

**Comment by dneto0** [comment]
Ah. The dreaded cr/lf problem. Thanks for clues.
I'm in the middle of reproducing the issue.

**Comment by allanmac** [comment]
This appears to be broken on Windows:

FAIL:
```
...\vulkansdk\1.1.101.0\bin\spirv-dis < hs_bc_0.spv
error: file does not exist '(null)'
```
OK:
```
c:\vulkansdk\1.1.101.0\bin\spirv-dis  hs_bc_0.spv
; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 788
; Schema: 0
...
```
The now stale ToT `spirv-dis` has a different failure mode:

FAIL:
```
spirv-dis --version
SPIRV-Tools v2018.5-dev a3e3869540b7c2d2f01c846fc76453be55d1ac34
spirv-dis < hs_bc_0.spv
; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 788
; Schema: 0
...
error: 1489: End of input reached while decoding OpBitcast starting at word 1487: missing result ID operand at word offset 2.
```

OK
```
spirv-dis  hs_bc_0.spv
; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 788
; Schema: 0
...
```
