### ISSUE TITLE
Dead branch elimination can produce invalid block orders

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1727]
```
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint Fragment %func "func"
%void = OpTypeVoid
%bool = OpTypeBool
%true = OpConstantTrue %bool
%func_ty = OpTypeFunction %void
%func = OpFunction %void None %func_ty
%1 = OpLabel
OpSelectionMerge %3 None
OpBranchConditional %true %2 %3
%3 = OpLabel
OpReturn
%2 = OpLabel
%not = OpLogicalNot %bool %true
OpBranch %3
OpFunctionEnd
```

Dead branch elimination correctly reduces this case to straight line code, but it fails to fix the block ordering. `%2` must precede `%3` post-optimization since it dominates `%3`.

**Comment by dneto0** [comment]
I think we don't normally see this kind of code because compilers like Glslang and DXC generate code blocks in AST-order, which would not expose this pattern.
