### ISSUE TITLE
Correct std140 Uniform Buffer layout flagged as incorrect

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/SPIRV-Tools#1734]
As seen in: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/252

The struct 'S' is a perfectly valid std140 layout
struct S
{
mat4 m1;
mat4 m2;
mat4 m3;
vec3 v;
float f;
};
But when trying to use it I get a warning:

UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: -1 - SPIR-V module not valid: Structure id 13 decorated as Block must follow standard uniform buffer layout rules: member 4 at offset 204 overlaps previous member ending at offset 207
OpFunctionEnd

Objects: 1
   [0] 0x0, type: 0, name: (null)

Which is incorrect for this struct.
The fact that vec3 has a 16-byte alignment does not mean it requires padding, it just means that it needs to be at at 16-byte alignment boundary. The extra padding may (and is encouraged to) be used by another 4-byte aligned variable (a float in this case).

**Comment by danielmaciel** [comment]
"By the rules of std140, each vec3 must start on a 16-byte boundary. But vec3 does not consume 16 bytes of storage; it only consumes 12. And since float can start on a 4-byte boundary, a vec3 followed by a float will take up 16 bytes."

**Comment by asuonpaa** [comment]
@danielmaciel have you tried this with the ToT SPIRV-Tools from this repo? Maybe this has been fixed upstream but Vulkan-ValidationLayers hasn't picked it up yet?

I tried to reproduce the issue using spirv-val compiled from the fresh repo. I was using the following GLSL code:
```
#version 450
layout (set = 0, binding = 0) uniform S
{
    mat4 m1;
    mat4 m2;
    mat4 m3;
    vec3 v;
    float f;
};

void main()
{
}
```
And then compiling and validating the results show no errors:
`glslangValidator -V test.vert && spirv-val vert.spv`

Just to make sure I also added the resulting SPIR-V into validator test suite and it doesn't complain there either.

**Comment by danielmaciel** [comment]
I have attached a .spvasm which generate the warning. Please let me know if you want me to send the .spv file to some email. 

Best regards,
Daniel

[light.frag.spvasm.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2275431/light.frag.spvasm.txt)

**Comment by baldurk** [comment]
This bug seems to be present in the Vulkan SDK 1.1.82.0 from my testing:

```
$ which glslangValidator.exe
/c/VulkanSDK/1.1.82.0/Bin/glslangValidator.exe
$ which spirv-val
/c/VulkanSDK/1.1.82.0/Bin/spirv-val
$ cat a.frag
#version 450

layout (binding = 0) uniform UBO { vec3 a; float b; } ubo;
layout (location = 0) out vec4 col;

void main() { col = vec4(ubo.a, ubo.b); }
$ glslangValidator.exe -V a.frag -o a.spv
a.frag
$ spirv-val a.spv
error: line 46: Structure id 11 decorated as Block must follow standard uniform buffer layout rules: member 1 at offset 12 overlaps previous member ending at offset 15
  OpFunctionEnd
$ spirv-as light.frag.spvasm -o a.spv # From the attachment above
$ spirv-val a.spv
error: line 233: Structure id 11 decorated as Block must follow standard uniform buffer layout rules: member 4 at offset 204 overlaps previous member ending at offset 207
  OpFunctionEnd
```

This affects some of the shaders in Sascha Willems' samples (which is how I found it, via a fork which passes through spirv-opt/spirv-val during compilation).

**Comment by asuonpaa** [comment]
Tried the a.frag on my end. No errors.

Here's the tool versions I'm using:
```
spirv-val --version
SPIRV-Tools v2018.5-dev v2018.4-103-g3a20879

glslangValidator --version
Glslang Version: 6.7.2743
```

**Comment by danielmaciel** [comment]
Maybe you are using an older version?

spirv-val --version
SPIRV-Tools v2018.5-dev v2018.4-110-gb6319c3a

glslangValidator --version
Glslang Version: 7.8.2850

**Comment by danielmaciel** [comment]
Maybe @baldurk has some more info? I am a little bit out of ideas at the moment. I guess I could check the code at some point

**Comment by danielmaciel** [comment]
I don't know how you are not able to reproduce the problem there, but this code is wrong. Maybe wipe your environment and try again?
Anyhow, the problem is here:
```
480    nextValidOffset = offset + size;
481    if (blockRules && (SpvOpTypeArray == opcode || SpvOpTypeStruct == opcode)) {
482      // Uniform block rules don't permit anything in the padding of a struct
483      // or array.
484      nextValidOffset = align(nextValidOffset, **alignment**);
485    }
```
It is computing the *next* valid offset by aligning it using the *current* item's alignment requirement when it should use the *next* item's alignment requirement - unless the current item is a *struct* or an *array*.
As seen in:
```      
482    // Uniform block rules don't permit anything in the padding of a struct
483    // or array.
```
It applies to *structs* and *arrays* but not for *vector* nor *float* types.
Please read this discussion:
https://github.com/KhronosGroup/Vulkan-Docs/issues/274
And this section:
https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#interfaces-resources-layout
I hope this helps.

**Comment by karl-lunarg** [comment]
LunarG has released [SDK Version 1.1.82.1](https://vulkan.lunarg.com/sdk/home) to address this problem.

And the glslang known-good has been updated.

This issue can be closed.

**Comment by danielmaciel** [comment]
Thank you! :)

**Comment by dneto0** [comment]
Thanks all for getting to the bottom of this.  I think I may have introduced the bug in the layout verification, and then fixed it about a week later.  We're looking at improving our processes to catch or prevent this kind of problem in the future.

**Comment by dneto0** [comment]
I verified that light.frag.spvasm.txt validates correctly when validating to target-env vulkan1.1
