### ISSUE TITLE
Unnecessary promotion to highp with "merge return" optimization pass

### ISSUE THREAD

**Issue by romainguy** [KhronosGroup/SPIRV-Tools#1736]
When compiling the attached fragment shader to SPIRV and running the optimization passes listed below, a bunch of operations are promoted to highp (they lose the relaxed precision decoration in spirv). This can be easily observed on the `textureLod()` calls. They are marked `highp` even though the sampler and the default precision are both set to `mediump`.

See `postprocess-mergereturn.vkglsl.txt` for the generated code with the merge return pass and `postprocess-nomergereturn.vkglsl.txt` without the merge return pass. Observe the last 4 `textureLod` calls.

[postprocess-mergereturn.vkglsl.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2233863/postprocess-mergereturn.vkglsl.txt)
[postprocess-nomergereturn.vkglsl.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2233864/postprocess-nomergereturn.vkglsl.txt)

Source shaders:

[postprocess.vert.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2233844/postprocess.vert.txt)
[postprocess.frag.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2233845/postprocess.frag.txt)

Optimization passes used:
```
optimizer
            .RegisterPass(CreateMergeReturnPass())
            .RegisterPass(CreateInlineExhaustivePass())
            .RegisterPass(CreateAggressiveDCEPass())
            .RegisterPass(CreatePrivateToLocalPass())
            .RegisterPass(CreateLocalSingleBlockLoadStoreElimPass())
            .RegisterPass(CreateLocalSingleStoreElimPass())
            .RegisterPass(CreateAggressiveDCEPass())
            .RegisterPass(CreateScalarReplacementPass())
            .RegisterPass(CreateLocalAccessChainConvertPass())
            .RegisterPass(CreateLocalSingleBlockLoadStoreElimPass())
            .RegisterPass(CreateLocalSingleStoreElimPass())
            .RegisterPass(CreateAggressiveDCEPass())
            .RegisterPass(CreateLocalMultiStoreElimPass())
            .RegisterPass(CreateAggressiveDCEPass())
            .RegisterPass(CreateCCPPass())
            .RegisterPass(CreateAggressiveDCEPass())
            .RegisterPass(CreateRedundancyEliminationPass())
            .RegisterPass(CreateSimplificationPass())
            .RegisterPass(CreateVectorDCEPass())
            .RegisterPass(CreateDeadInsertElimPass())
            .RegisterPass(CreateDeadBranchElimPass())
            .RegisterPass(CreateSimplificationPass())
            .RegisterPass(CreateIfConversionPass())
            .RegisterPass(CreateCopyPropagateArraysPass())
            .RegisterPass(CreateReduceLoadSizePass())
            .RegisterPass(CreateAggressiveDCEPass())
            .RegisterPass(CreateBlockMergePass())
            .RegisterPass(CreateRedundancyEliminationPass())
            .RegisterPass(CreateDeadBranchElimPass())
            .RegisterPass(CreateBlockMergePass())
            .RegisterPass(CreateSimplificationPass());
```

Removing the first pass (`CreateMergeReturnPass()`) fixes the problem.

**Comment by romainguy** [comment]
Note there's another unnecessary promotion at the end of both shaders:

```
    highp vec4 _860 = _865;
    _860.w = 1.0;
    fragColor = _860;
```

`fragColor` is `mediump` and `_865` is `mediump`. A promotion is used just to set the `w` component to `1.0`.

I haven't tracked down the root cause of this promotion though.

**Comment by s-perron** [comment]
You're welcome, but I believe there might be another bug in merge return that is exposed by your test case. 
 If you run merge return on your example and then run the validator, there is an error:

> error: line 314: ID 577 defined in block 573 does not dominate its use in block 572

I will continue looking into that.

**Comment by romainguy** [comment]
Thanks for the heads up. I'll wait for the next fix then.

**Comment by s-perron** [comment]
@romainguy It looks good to me now.  Let me know if there are any other problems.
