### ISSUE TITLE
Question regarding specialization constants

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Tools#1812]
First of all, I'm not sure if this is the appropriate place to ask this question, if not just let me know where to go.

I'm trying to understand the most appropriate usage of specialization constants and I'm unsure of the "best" practice when it comes to setting them. From my understanding there's two main ways to override specialization constants: one is by setting/freezing them with a tool like the optimizer and the other is an api that actually supports them (like vulkan).

So my main question is this: what are the pros/cons of setting specialization constants in one of these vs. the other. From my understanding one of the goals of vulkan/spir-v is to make optimizations something that can be done offline so drivers have less to do and you don't have to worry about bad driver optimizations as much. I would assume that any driver/api that allows setting specialization constants effectively has to re-compile the shader each time which could require a full optimization pass. So would it be correct to assume that it's "best" to set them up-front with a tool so that the optimizer can be run without relying on various driver implementations? Or are there reasons this is best left up to the driver, whether it be in terms of optimizations or compilation speeds or something.

**Comment by jodavis42** [comment]
I guess I didn't word that quite correct.

Imagine I have a system in place where I have the optimizer packed in the run-time executable and I have whatever shader caching mechanisms in place to prevent optimizing the same specialization constant twice. Also imagine I do what offline optimizations I can, leaving specialization constants alone.

What I really want to know is what are the pros/cons of running the optimizer right before creating a pipeline to freeze out specialization constants compared to using Vulkan's (or any other language's) built-in functionality.

I've personally had to deal with less than ideal driver optimizers before (to be fair, with glsl) so I would assume running the spir-v optimizer at run-time is the safest way to guarantee a "good" shader after constants are frozen. Am I mistaken in this or are there scenarios where leaving this to the driver would produce a better shader or potentially do this faster?

**Comment by s-perron** [comment]
You might get a more of a discussion in https://forums.khronos.org/forumdisplay.php/114-Vulkan, but I'm not sure.
