### ISSUE TITLE
Validator: Do not check for increasing buffer offsets

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/SPIRV-Tools#1822]
Vulkan has accepted out-of-order for a long time, and an overlooked statement about this was just removed from the SPIR-V specification (rev. 3):

> * Khronos SPIR-V Issue #346: Remove ordered rule for structures in the memory layout: Vulkan allows out-of-order Offset layouts.

**Comment by johnkslang** [comment]
See https://github.com/KhronosGroup/SPIRV-Tools/pull/1693.

**Comment by johnkslang** [comment]
It looks already done at the SPIR-V level.

I didn't know if the rule needed visiting in general, or just for OpenGL. To be clear, OpenGL has agreed to match Vulkan, so there should be no environment checking offset order.

**Comment by dneto0** [comment]
Ok.  So the new thing is that no environment requires the offset order check.  We'll use this issue to track deleting that code from the validator.
