### ISSUE TITLE
Prefix binary output (-x) with number of 32-bit words (or make it an option)

### ISSUE THREAD

**Issue by allanmac** [KhronosGroup/SPIRV-Tools#1855]
My use case is that I need to pack more than one compute shader into a single const array of 32-bit words at _compile time_.  

Currently, I convert each `.spv` image into a length and a byte stream with `wc -c` and the `xxd` utility.  Later, the shaders are iteratively unpacked into `VkShaderModuleCreateInfo` instances. 

I could stop using these utilities if `spirv-opt` or a new SPIR-V tool emitted the number of words in the binary followed by the SPIR-V words.

Note that (IMHO) the `-x` option in `glslangValidator` doesn't prepend the number of words in the binary and also precludes later use of `spirv-opt`.

**Comment by dneto0** [comment]
This feels a bit out of scope for SPIRV-Tools.

This Perl script does what you want, transforming a .spv on standard input to text on standard output:
```perl
#!/usr/bin/env perl

use strict;

binmode STDIN;
my @parts = (<STDIN>);
my $binary = join('',@parts);
my @words = unpack("(V)*", $binary);
my $num_words = $#words +1;
printf "0x%x\n", $num_words;
for my $word (@words) {
        printf(", 0x%x\n", $word);
}
```

The unpack grouping option requires Perl 5.8, which is fairly old by now.

**Comment by dneto0** [comment]
Gosh I miss Perl.  :-)

**Comment by allanmac** [comment]
I agree, it feels out of scope.  I was just trying to get rid of my scripts! :-)

**Comment by dneto0** [comment]
Now, glslc has a -mfmt option that we could expand to include your functionality.  It already has -mfmt=num which is the sequence of raw words.  Maybe we can add a -mfmt=countednum  to do what you want.
But that only works for GLSL, and you get the extra OpSourceExtension lines that glslc adds... :-(

**Comment by allanmac** [comment]
But that precludes running spirv-opt as part of my shader pipeline, right?
