### ISSUE TITLE
SPIR-V command line tests fail with python 3

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#1856]
Tests pass with python 2.7, but fail with python 3. Example output:
```
      Start  4: spirv-tools-test_spirv_unit_tests
 1/92 Test #85: spirv_opt_tests ......................................***Failed    0.47 sec
SPIRV tool test suite: "SpirvOptBase"
1/18       TestAssemblyFileAsOnlyParameter          -Failed-
<root>/SPIRV-Tools/build/tools/spirv-opt <root>/SPIRV-Tools/build/test/tools/opt/tmpz4a8om9u/tmphbnvkvsk.spvasm.spv -o <root>/SPIRV-Tools/build/test/tools/opt/tmpz4a8om9u/output.spv
name 'reduce' is not defined
STDOUT:
b''
STDERR:
b''
```

**Comment by antiagainst** [comment]
Yes, similar as https://github.com/google/shaderc/issues/474.

**Comment by s-perron** [comment]
I'll take this issue.  With python2 going out of service on Jan 1, 2019, see [here](https://www.python.org/dev/peps/pep-0373/#update), we will need to move to python3 very soon.  The avoid making things harder for ourselves, we will not require the scripts to work with python2, it will be dropped completely.

**Comment by keryell** [comment]
Actually it is Jan 1, 2020.
But this is not a reason for not upgrading right now...

**Comment by s-perron** [comment]
Right typo, I meant to write 2020.  I agree.  I am working on this right now.
