### ISSUE TITLE
MinGW can't link libs undefined reference to `spvtools::SpirvTools::SpirvTools(spv_target_env)'

### ISSUE THREAD

**Issue by exellian** [KhronosGroup/SPIRV-Tools#1888]
I am trying to solve this problem for two days now. And i can't get spirv-tools to work on mingw on windows. I include #include <spirv-tools/libspirv.hpp> and linking against SPIRV-Tools.lib, but i don't know why I am getting undefined reference to `spvtools::SpirvTools::SpirvTools(spv_target_env). I even checked if it has something to do with 32bit, so i changed the compiler to 64bit. Please give me some advise!

**Comment by dj2** [comment]
What is the command you're using to link and what is the error you're getting? Did this work before and now it doesn't or is this the first time you've tried it?

**Comment by exellian** [comment]
I found out that the libaries for windows are only for visual studio, so i cant link them with mingw on windows. So are there any mingw64 builts for windows?

**Comment by dj2** [comment]
I don't know of any MingW builds off hand. You can always check out the source and build it yourself. Sounds like this issue can be closed?

**Comment by exellian** [comment]
i tried

**Comment by jiapei-nexera** [comment]
Any solution????
