### ISSUE TITLE
Remove #ifdef EFFCEE guards in tests

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1912]
Those guards were only added because we could still run most of our googletest tests but not the effcee tests.  That's because effcee (and its re2) could not build with VS2013, but googletest could build with VS2013.

But recently googletest stopped building under VS2013.  So there's no point in having the #ifdefs which just broke things.
(See https://github.com/KhronosGroup/SPIRV-Tools/pull/1910 and related break in https://github.com/google/shaderc/issues/477 )

This change should:
- [ ] remove the Effcee #ifdef guards
- [ ] update the README and bots to say we now required Effcee in the source tree
- [ ] be accompanied by an email to the developer mailing list about the change.

**Comment by s-perron** [comment]
The e-mail to the dev mailing list was just sent.
