### ISSUE TITLE
Missing GeometryStreams capability validation?

### ISSUE THREAD

**Issue by llyzs** [KhronosGroup/SPIRV-Tools#1913]
I saw the following error when trying to use GeometryStreams capability:

SPIR-V module not valid: Capability GeometryStreams is not allowed by Vulkan 1.0 specification (or requires extension)

I checked the spec, GeometryStreams is defined in SPIR-V 1.0 and does not mention any extension required to use it; the 1.0 Vulkan driver also works fine despite the error.

There seems to be no GeometryStreams in source/val/validate_capability.cpp.

**Comment by alan-baker** [comment]
I assume you were using `--target-env vulkan1.0` for validation? This is a restriction added by the Vulkan environment specification. See https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#spirvenv-capabilities.

**Comment by llyzs** [comment]
I am using the library API and pass environment 1.3 to validate. The code is as below:
```
	spv_context spvc = spvContextCreate(SPV_ENV_UNIVERSAL_1_3);
	spv_diagnostic spvdiag = NULL;
	spv_result_t error;
	spv_const_binary_t binary = { words.data(), words.size() };
	error = spvValidate(spvc, &binary, &spvdiag);
	if (error) {
		spvDiagnosticPrint(spvdiag);
		spvDiagnosticDestroy(spvdiag);
		spvdiag = NULL;
	}
	spvContextDestroy(spvc);
```

This seems to be also a Vulkan spec issue, because there is no "GeometryStreams" listed in the SPIR-V Capabilities table that you have pointed out, neither 1.0 spec nor 1.1 spec.

**Comment by alan-baker** [comment]
Just want to double check what your reporting. I have tried the following:
```
OpCapability Shader
OpCapability GeometryStreams
OpCapability Linkage
OpMemoryModel Logical GLSL450
```
This code validates with SPV_ENV_UNIVERSAL_1_3, but fails with Vulkan1.0 due to GeometryStreams (also would fail due to Linkage). I think you agree that this issue is a problem due to the Vulkan spec.

**Comment by llyzs** [comment]
Ah ok, I just realized that the issue was thrown by vkCreateShaderModule but not when I call spvValidate so this is because my Vulkan validation layer is indeed validating against Vulkan 1.0 env.

So I think this looks like a spec issue. I will close this and open a spec issue instead. Thanks.
