### ISSUE TITLE
Optimizer asserts on dEQP-VK.spirv_assembly.instruction.graphics.opspecconstantop.*convert_*

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/SPIRV-Tools#1915]
Running the Vulkan CTS with optimizations fails in spirv-opt:

    ./deqp-vk --deqp-optimize-spirv=enable --deqp-optimization-recipe=1 -n \
    dEQP-VK.spirv_assembly.instruction.graphics.opspecconstantop.sconvert_vert

yields

    deqp-vk: external/spirv-tools/src/source/opt/def_use_manager.cpp:61: void
    spvtools::opt::analysis::DefUseManager::AnalyzeInstUse(spvtools::ir::Instruction*):
    Assertion `def && "Definition is not registered."' failed

**Comment by jekstrand** [comment]
I'm also seeing an identical assert in dEQP-VK.spirv_assembly.instruction.graphics.variable_init.private.*

**Comment by s-perron** [comment]
The input in dEQP-VK.spirv_assembly.instruction.graphics.opspecconstantop.sconvert_vert is invalid.  When I dump the spir-v that is being passed in to the optimizer, I see the following:

```
         %90 = OpFunction %v4float None %26
         %95 = OpFunctionParameter %v4float
         %96 = OpLabel
         %97 = OpSConvert %int %84
         **%98 = OpVariable %_ptr_Function_v4float Function**
               OpStore %98 %95
```

Note that the OpVariable instruction is not at the start of the first block.  The `OpSConvert` comes first.  This is invalid.  See https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#LogicalLayout.

**Comment by dj2** [comment]
Can we update the validator to catch this earlier?

**Comment by s-perron** [comment]
I see the same thing when I run `dEQP-VK.spirv_assembly.instruction.graphics.variable_init.private.*`.

**Comment by s-perron** [comment]
Yes, the validator should be able to identify this.

**Comment by s-perron** [comment]
While looking at this I see a couple things missing from the validator:

- [ ] We do not validate that function scope variable are declared at the start of the entry block.
- [ ] If there is an OpLine before the OpPhi we do not recognize that the OpPhi is not at the start of the basic block.

We seem to correctly verify that function-scope OpVariable instructions are defined in the entry block.

**Comment by dj2** [comment]
OpLine can be mixed freely with OpPhi, so I think the OpPhi is still at the beginning of the block even if OpLines are in there.

From the OpPhi section of the spec:

"Within a block, this instruction must appear before all non-OpPhi instructions (except for OpLine, which can be mixed with OpPhi)."

**Comment by s-perron** [comment]
Yes, but this code is wrong, and the validator will not identify the problem:

```
         %12 = OpLabel
         %15 = OpUndef %v4float
	       OpLine %file 1 1
         %16 = OpPhi %v4float %11 %8 %14 %13
```

To check if the OpPhi is at the start it looks at the immediately preceding instruction only. If it is OpLine, the validator thinks everything is fine and then moves on.

**Comment by dj2** [comment]
Ah, yea that makes sense. Want to file two bugs for this against the validator, one to fix the OpPhi check to ignore OpLine as it looks to see if it's at the start and a second to deal with the variable scope declarations?

We should then file bugs against CTS to fixup the invalid SPIRV.

**Comment by s-perron** [comment]
Opened https://gitlab.khronos.org/Tracker/vk-gl-cts/issues/1382 to get the test case fixed.

**Comment by s-perron** [comment]
I've opened #1922 and #1923 to track these issues.  Nothing left for this issue.
