### ISSUE TITLE
Optimizer segfaults on dEQP-VK.spirv_assembly.instruction.graphics.decoration_group tests

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/SPIRV-Tools#1916]
Running the Vulkan CTS with optimization group zero enabled segfaults in the following tests:

 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.empty_decoration_group_frag
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.empty_decoration_group_geom
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.empty_decoration_group_tessc
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.empty_decoration_group_tesse
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.empty_decoration_group_vert
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_decoration_groups_on_same_variable_frag
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_decoration_groups_on_same_variable_geom
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_decoration_groups_on_same_variable_tessc
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_decoration_groups_on_same_variable_tesse
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_decoration_groups_on_same_variable_vert
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_elements_decoration_group_frag
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_elements_decoration_group_geom
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_elements_decoration_group_tessc
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_elements_decoration_group_tesse
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.multiple_elements_decoration_group_vert
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_multiple_times_frag
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_multiple_times_geom
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_multiple_times_tessc
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_multiple_times_tesse
 * dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_multiple_times_vert

**Comment by s-perron** [comment]
dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.empty_decoration_group_frag

This test looks like a bug in ADCE.  My guess is that it is related to OpGroupDecorate.  A variable in a dead function is used in an OpGroupDecorate instruction.  There is a segfault when the code asks for the definition of the id for the variable, but it cannot be found.

**Comment by s-perron** [comment]
I think these are all fixed.  @jekstrand Can you double check?
