### ISSUE TITLE
Loop unrolling increases compile time

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1928]
We recently added loop unrolling to the set of legalization passes.  This is increasing the compile time a significant amount.  The problem seems to be that the def-use manager is constantly invalidated and rebuilt.  In the case that I am looking at, the def-use manger is rebuilt twice for every loop that gets unrolled.  In one shader, this means that the def-use manger is rebuilt 37 times during unrolling alone.

We know that this is a slow process.

**Comment by antiagainst** [comment]
I'm thinking whether it's possible to limit the unrolling to only those loops selecting resources. Not sure how hard it is to detect them though.
