### ISSUE TITLE
spirv-val doesn't validate Vulkan restrictions for  OpTypeRuntimeArray

### ISSUE THREAD

**Issue by alegal-arm** [KhronosGroup/SPIRV-Tools#1936]
Vulkan spec says:

OpTypeRuntimeArray must only be used for:
◦ the last member of an OpTypeStruct that is in the StorageBuffer storage class decorated as
Block, or that is in the Uniform storage class decorated as BufferBlock.

This CTS tests violates it  dEQP-VK.spirv_assembly.instruction.compute.pointer_parameter.workgroup_memory_variable_pointers contains

**Comment by zoddicus** [comment]
I have a rule for WebGPU that is a restriction on this rule, so I will implement this first.
