### ISSUE TITLE
SPIRV-Tools and SPIRV-Tools-shared libraries generate the same files and break parallel builds

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/SPIRV-Tools#1941]
Here's a snippet from a parallel build of Vulkan CTS using MSVC:

```
9>------ Build started: Project: SPIRV-Tools, Configuration: Release x64 ------
...
9>  Generate extended instruction tables for spv-amd-shader-trinary-minmax.
...
23>------ Build started: Project: SPIRV-Tools-shared, Configuration: Release x64 ------
...
23>  Generate extended instruction tables for spv-amd-shader-explicit-vertex-parameter.
23>  Generate extended instruction tables for spv-amd-shader-trinary-minmax.
9>  extensions.cpp
9>C:\vulkancts\vk-gl-cts\external\spirv-tools\src\source\ext_inst.cpp(37): fatal error C1083: Cannot open include file: 'spv-amd-shader-trinary-minmax.insts.inc': No such file or directory
23>  Generate extended instruction tables for spv-amd-gcn-shader.
```

What's happening is that SPIRV-Tools (number 9) had already generated spv-amd-shader-trinary-minmax, but SPIRV-Tools-shared (number 23) is rebuilding it at the same time that SPIRV-Tools is compiling ext_inst.cpp that includes it. This happens maybe once in every 10-20 times I build.

This is exactly the issue described here: https://public.kitware.com/Bug/view.php?id=12311, and it is considered not a CMake bug but a bug in the makefiles. They resolved that issue by adding this documentation:

```
+      "Do not list the output in more than one independent target that may "
+      "build in parallel or the two instances of the rule may conflict "
+      "(instead use add_custom_target to drive the command and make the "
+      "other targets depend on that one).  "
```

But the SPIRV-Tools cmakefile intentionally (without realizing the consequences?) doesn't use add_custom_target, with this comment:

```
# The following .cpp files include the above generated .inc files.
# Add those .inc files as their dependencies.
#
# Why using such an awkward way?
# * If we use add_custom_target() to define a target to generate all .inc files
#   and let ${SPIRV_TOOLS} depend on it, then we need to run ninja twice every
#   time the grammar is updated: the first time is for generating those .inc
#   files, and the second time is for rebuilding .cpp files, when ninja finds
#   out that .inc files are updated.
# * If we use add_custom_command() with PRE_BUILD, then the grammar processing
#   script will always run no matter whether the grammar is updated.
# * add_dependencies() is used to add *target* dependencies to a target.
# * The following solution only generates .inc files when the script or the
#   grammar files is updated, and in a single ninja run.
```

I'm not an expert on cmake (and don't fully understand the ninja issue), but it seems to me that the "right" way to do this in cmake is to use add_custom_target and to find some other way to deal with the ninja issue.

**Comment by s-perron** [comment]
@antiagainst, do you have any insight into why we don't use `add_custom_target`.

**Comment by antiagainst** [comment]
I remember the reason was to solve the "running ninja twice" problem.

I didn't know that it can break parallel builds. Agreed that we should find some better way.

**Comment by s-perron** [comment]
I don't think there is a good solution for this.  The seems like a deficiency in cmake.  Just consider their documentation.  For [add_custom_target](https://cmake.org/cmake/help/latest/command/add_custom_target.html) they say:

> The target has no output file and is always considered out of date even if the commands try to create a file with the name of the target. Use the add_custom_command() command to generate a file with dependencies.

That is true for this case.  If we use `add_custom_target`, these files and everything that depends on them will be rebuilt every time ninja, make, etc. is called.  This will increase the time for active developers to makes small changes and test them.  This is not an acceptable solution.

However, if we use `add_custom_command` as they suggest, then we get into the error that we are currently getting.

**Comment by s-perron** [comment]
Discussed with a @antiagainst  and @dj2.  The new idea is to see if we can change to python script to not delete the file while it is working on it.  Don't know if this is a reasonable solution yet.  Will look into it.

**Comment by dneto0** [comment]
Hm.  This seems like incorrect dependency setup.
CMake custom commands should always be wrapped by a custom target.  Unfortunately that pattern is not obvious from their documentation.

I solved a similar-sounding problem in Clspv. See https://github.com/google/clspv/commit/ccc85d3387dc1f3d23bbf325e5995b303505a5cd

**Comment by s-perron** [comment]
My solution breaks the build when using makefiles.

**Comment by dneto0** [comment]
Dang.
