### ISSUE TITLE
Validator does not check type of Uniform/StorageBuffer variables

### ISSUE THREAD

**Issue by jrprice** [KhronosGroup/SPIRV-Tools#1949]
The Vulkan spec requires that all variables in the `Uniform` and `StorageBuffer` storage classes be structures (or arrays of structures) that are decorated with `Block` or `BufferBlock` (see 14.5.2. Descriptor Set Interface).

The following shader declares a variable in the Uniform storage class that points directly to an integer, which should not validate. Same issue occurs when replacing `Uniform` with `StorageBuffer`.

```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %kernel "main"
               OpExecutionMode %kernel LocalSize 1 1 1

               OpDecorate %var DescriptorSet 0
               OpDecorate %var Binding 0

     %voidty = OpTypeVoid
   %kernelty = OpTypeFunction %voidty
      %intty = OpTypeInt 32 0
      %varty = OpTypePointer Uniform %intty
      %value = OpConstant %intty 42

        %var = OpVariable %varty Uniform

     %kernel = OpFunction %voidty None %kernelty
      %label = OpLabel
               OpStore %var %value
               OpReturn
               OpFunctionEnd
```

**Comment by alan-baker** [comment]
This should also check variables in UniformConstant storage class.

**Comment by fjhenigman** [comment]
I've got this working, but it jumps in front of the "array of arrays" check that @dj2 added in response to #1522, opened by @dneto0 .  Is there any reason to keep the "array of arrays" code?  I think it would be nice if we cite the spec for everything we do.

**Comment by alan-baker** [comment]
If this covers all the offending cases then we can remove the other check and update the tests.
