### ISSUE TITLE
spirv-opt complains about dead branch elimination not having been performed when it has

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#1978]
[This archive](https://github.com/KhronosGroup/SPIRV-Tools/files/2488442/files.zip) contains the files necessary to reproduce the issue.

minified.spv was generated from minified.frag using glslang version 7.10.2904.

Running:

spirv-opt --eliminate-dead-branches --merge-return minified.spv -o temp.spv

leads to this error:

error: line 0: Module contains unreachable blocks during merge return.  Run dead
 branch elimination before merge return.

Looks like an incorrect error as the order of flags has dead branch elimination before merge return.

Version of spirv-opt used:

SPIRV-Tools v2018.6-dev v2018.5-66-gab45d691

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz)

**Comment by s-perron** [comment]
Fixed by #1983.  Typo in the comment for that commit did not link it to this issue correctly.
