### ISSUE TITLE
spirv-opt does what looks like an incorrect transformation with --if-conversion

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#1991]
[This archive](https://github.com/KhronosGroup/SPIRV-Tools/files/2495919/tofile.zip) contains the files necessary to reproduce the issue.

**The problem**

Applying "spirv-opt --if-conversion to" someopts.spv leads to a .spv file that appears to have different semantics - i.e. it looks like there is a bug related to if-conversion.

**In more detail**

shader.spv was generated from shader.frag using glslangValidator:

`glslangValidator -V shader.frag -o shader.spv
`

someopts.spv was generated from shader.spv using spirv-opt with a number of flags (a subset of the -O flags):

`spirv-opt shader.spv -o someopts.spv --eliminate-dead-branches --merge-return --eliminate-local-multi-store --eliminate-dead-branches
`

withifconversion.spv was generated from someopts.spv using spirv-opt with the --if-conversion flag:

`spirv-opt someopts.spv -o withifconversion.spv --if-conversion
`

The two assembly files someopts.asm and withifconversion.asm were generated from their associated .spv files using spirv-dis, and then tidied up a bit so that as many of the ids in them match up.

In someopts.asm we have this block:

```
         %32 = OpLabel
          %A = OpPhi %float %29 %53 %109 %33
          %B = OpPhi %bool %true %53 %93 %33
               ...
```

In withifconversion.asm we have instead:

```
         %32 = OpLabel
          %A = OpSelect %float %45 %109 %29
          %B = OpSelect %bool %45 %93 %true
               ...
```

For this to be valid, we would require %45 to be true if and only if control had branched from %53, and %45 to be false if and only if control had branched from %33.

However, the following CFG paths are both (at least statically) possible:

 %45 holds: %31 -> %46 -> %47 -> %33 -> %32

!%45 holds: %31 -> %46 -> %54 -> %47 -> %33 -> %32

So it seems the conditions for the if conversion do not hold.

When the shader is used to render a quad, with %buf2 set to (0.0, 1.0), the if conversion drastically changes what is rendered (the .png files in the archive illustrate what is rendered on a Galaxy S9 device).

**Comment by alan-baker** [comment]
I see the problem. Results from a bad assumption in the pass. Working on a fix.
