### ISSUE TITLE
spirv-opt transform: remove duplicates from list of interface IDs in OpEntryPoint instruction

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#2002]
The interface IDs in OpEntryPoint may have duplicates.  But it would be nicer for consumers if duplicates were removed.

Cc: @sheredom

**Comment by dneto0** [comment]
This isn't much work to do for a single transform.  Perhaps it can be added to some other cleanup passes like dead code elimination or global value numbering.

**Comment by s-perron** [comment]
This should be done in the instruction folder.  I'll see if I can get it done tomorrow.
