### ISSUE TITLE
spirv-opt does not terminate with --eliminate-dead-branches

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2004]
[This archive](https://github.com/KhronosGroup/SPIRV-Tools/files/2505293/tofile.zip) contains the files necessary to reproduce the issue.

shader.spv was generated from shader.frag using glslangValidator.

Running:

spirv-opt --eliminate-dead-branches --merge-return --inline-entry-points-exhaustive --eliminate-local-multi-store --ccp --eliminate-dead-branches shader.spv -o temp.spv

sends spirv-opt into a seemingly infinite loop.

spirv-opt --version
SPIRV-Tools v2018.6-dev v2018.5-81-g07d0f9df

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
We do not handle branches to the continue target of the containing loop in `FindFirstExitFromSelectionMerge`.
