### ISSUE TITLE
Vulkan UniformConstant variables only support opaque types

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#2008]
> Variables identified with the UniformConstant storage class are used only as handles to refer to opaque resources. Such variables must be typed as OpTypeImage, OpTypeSampler, OpTypeSampledImage, or an array of one of these types.

**Comment by dneto0** [comment]
Glslang tests fail validation with this code.  I think they should not fail (but check)

- RuntimeArray must be permitted  (Glslang test spv.nonuniform.frag)
- OpTypeAccelerationStructureNV is opaque (from http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/NV/SPV_NV_ray_tracing.html )

**Comment by dneto0** [comment]
See https://github.com/KhronosGroup/SPIRV-Tools/pull/2054 for a patch for those two issues.

**Comment by zoddicus** [comment]
With #2054 merged, is there anymore work that is needed on this issue?
