### ISSUE TITLE
Compression codec (MARK-V) fails on some shaders

### ISSUE THREAD

**Issue by aras-p** [KhronosGroup/SPIRV-Tools#2015]
I was trying to compare SMOL-V with MARK-V, and hit failures in MARK-V part where it tries to decode the shader. Seems to happen on: all Hull shaders I try, and most of Shadertoy shaders I try. Only seems to happen with the "Max" compression model type.

The assert that it hits is of `Assertion failed: (multi_mtf_.GetSize(mtf) > 0), function DecodeExistingId, file spirv-tools/source/comp/markv_decoder.cpp, line 168.` type.

I'm testing with revision `1c1e749f0b`, built on Mac.

Attaching the SPIR-V shaders that I have it failing on - basically; compress with Max model, try to decompress it; fails during decompression.

[shaders-repro.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2521822/shaders-repro.zip)

**Comment by dj2** [comment]
Closing, MarkV was removed in #2576
