### ISSUE TITLE
spirv-opt: --eliminate-dead-code-aggressive can make OpUnreachable reachable

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2018]
[This archive](https://github.com/KhronosGroup/SPIRV-Tools/files/2529819/spirvopt-bug.zip) contains the files necessary to reproduce the bug.

Files were generated as follows:

```
glslangValidator -V shader.frag -o shader.spv
spirv-opt shader.spv -o partlyoptimized.spv --eliminate-dead-branches --inline-entry-points-exhaustive
spirv-opt partlyoptimized.spv -o bad.spv --eliminate-dead-code-aggressive
```

Applying spirv-dis to bad.spv, we see that this block:

```
         %43 = OpLabel
               OpUnreachable
```

is reachable.  It was not reachable in partlyoptimized.spv (in that binary it exists but has no incoming edges).

```
spirv-opt --version
SPIRV-Tools v2018.6-dev v2018.5-83-g1c1e749f
```

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by greg-lunarg** [comment]
I can look at this since I touched this last.

**Comment by greg-lunarg** [comment]
Pretty sure that partlyoptimized.spv is invalid: it contains a branch in a loop to a block outside the loop (%46) that is not the loop's merge block.

(Note that the most recent stable version of spirv-val does not catch this problem. This should probably be filed as an issue).

Next I will look at how partlyoptimized.spv is created and see where the invalid code is created.

**Comment by greg-lunarg** [comment]
So it appears that inlining is generating the invalid code.

This inliner was not designed to handle this particular case: where the inlined routine had a return in a loop. That is why the merge-return pass was designed: to run before the inliner and get rid of this case.

Still, the inliner is supposed to check for this case and just not inline. I will check and see why that is not happening.

**Comment by s-perron** [comment]
If we add merge return before inlining does it fix this problem?  I don't think it will.  Like inlining, it is looking for multiple OpReturn instructions.  We should open an separate issue for merge-return.

**Comment by afd** [comment]
> Pretty sure that partlyoptimized.spv is invalid: it contains a branch in a loop to a block outside the loop (%46) that is not the loop's merge block.
> 
> (Note that the most recent stable version of spirv-val does not catch this problem. This should probably be filed as an issue).

Done: #2028.

**Comment by s-perron** [comment]
Opened #2038 to handle the merge return improvement.  This issue can be closed now.
