### ISSUE TITLE
strip-reflect-info pass produces invalid byte code

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/SPIRV-Tools#2019]
I use glslang to compile HLSL shaders and enable HLSL functionality 1 to be able to get HLSL semantics. Everything works fine except validation layers complain about DecorateStringGOOGLE:
`SPIR-V module not valid: DecorateStringGOOGLE requires one of the following extensions: SPV_GOOGLE_decorate_string`
I was suggested (https://github.com/KhronosGroup/glslang/issues/1555) to use SPIRV-tools to strip reflection information, below is the code that I use:
```cpp
spvtools::Optimizer SpirvOptimizer(SPV_ENV_VULKAN_1_0);
// Decorations defined in SPV_GOOGLE_hlsl_functionality1 are the only instructions
// removed by strip-reflect-info pass. All SPIRV offsets remain valid after this operation.
auto StripReflectInfoPass = spvtools::CreateStripReflectInfoPass();
SpirvOptimizer.RegisterPass(std::move(StripReflectInfoPass));
std::vector<uint32_t> StrippedSPIRV;
auto res = SpirvOptimizer.Run(m_SPIRV.data(), m_SPIRV.size(), &StrippedSPIRV);
VERIFY_EXPR(res);
m_SPIRV.swap(StrippedSPIRV);
```
However, this results in multiple shader modules being invalid and the app fails to start completely. Below are few errors resulting from stripping the reflection info:
`SPIR-V module not valid: 3rd operand of MemberDecorateStringGOOGLE: operand 5635 requires one of these extensions: SPV_GOOGLE_hlsl_functionality1 `
`SPIR-V module not valid: Invalid instruction word count: 0`

**Comment by s-perron** [comment]
The strip-reflect pass does not remove OpMemberDecorateStringGOOGLE instructions.  They should be removed.

**Comment by s-perron** [comment]
@DiligentGraphics I may have a fix for your problem.  I am guessing at the actual problem because I do not have a reproducer.  Let me know if it fixes your problem.

**Comment by DiligentGraphics** [comment]
@s-perron That fixes the first error, thanks!
The reason for the second problem was this: I use reflection information to store decoration offsets in the original byte code. As I was told elsewhere (https://github.com/KhronosGroup/glslang/issues/1555), stripping reflection information would not change the offsets, but apparently it does. So after the stripping, the offsets become invalid and I was corrupting byte code producing invalid SPIRV.

**Comment by s-perron** [comment]
Hey, can you give me an example of the invalid spir-v?  I don't know what the problem is and which offsets you are refering to.  If possible, can you provide the valid spir-v file before stripping the reflection information, the command used to run it through spirv-opt, and instructions on how to spot the problem?

At this point, I do not know how to move forward.

**Comment by DiligentGraphics** [comment]
@s-perron I am talking about offsets of `DecorationBinding` and `DecorationDescriptorSet` decorations that I use to set bindings and descriptor sets in the compiled byte code. As I said, I was assuming that these offsets do not change after stripping reflection information, but apparently they do. So I now strip reflection after I change the decorations and everything works fine

**Comment by s-perron** [comment]
Those decorations should not be changed by strip-reflect.  Do you have an example that shows this happening?
