### ISSUE TITLE
ValidateVulkanCombineBuiltInExecutionModelDataTypeResult tries invalid shader

### ISSUE THREAD

**Issue by fjhenigman** [KhronosGroup/SPIRV-Tools#2035]
When this test is instantiated with storage class UniformConstant it generates an invalid shader - here's an excerpt:
%built_in_type = OpTypeStruct %u32arr2
%built_in_ptr = OpTypePointer UniformConstant %built_in_type
%built_in_var = OpVariable %built_in_ptr UniformConstant
%data_ptr = OpTypePointer UniformConstant %u32arr2

Vulkan 14.5.2 says the type of a UniformConstant must be "OpTypeImage, OpTypeSampler, OpTypeSampledImage, or an array of one of these types."  The validator hasn't checked this until now but I'm adding that for #1949.
Can I remove the problem instantiation, or do I need to fix it?

**Comment by fjhenigman** [comment]
I can save this test my making a special case for UniformConstant.
Does that sound worth doing @alan-baker ?

**Comment by alan-baker** [comment]
Can you change the storage class to Uniform and maintain the spirit of the test?

**Comment by fjhenigman** [comment]
yep, that's what happened in a362e60d5acecd9592bf4ae67a60ac2da9da1a07
