### ISSUE TITLE
Invariant decorator ignored by aggressive dead code elimination

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/SPIRV-Tools#2042]
When computing the value of an output marked as `invariant`, all intermediary variables should be preserved.

**Comment by prideout** [comment]
I think this could be fixed in `IsDead` by finding all leaves in the use-chain and looking for `SpvDecorationInvariant`.

**Comment by alan-baker** [comment]
Do you have an example shader you could share? Preferably before any optimizations have occurred. This sounds like it might be more subtle than just not-DCE'ing a variable. By that point the compiler has likely eliminated all the uses of the variable so it would help to leave it around. This probably needs addressed earlier in the pipeline.

**Comment by prideout** [comment]
Sure, [here](https://gist.github.com/prideout/d0cc3c990c5358724cd4ac2f71373013) is a gist of a small shader which uses a variable called `_187` for computing an invariant.  The `_187` variable mistakenly gets removed by optimization.  This is demonstrated as follows.

    glslc -std=310es -fshader-stage=vertex before_dce.glsl
    spirv-opt -Os a.spv -o b.spv

a.spv has a `_187` temporary, but b.spv does not.

**Comment by johnkslang** [comment]
Ah, you are comparing it against itself, but using the tool chain differently?  Sorry, missed that.

**Comment by greg-lunarg** [comment]
While _187 has indeed been eliminated in b.spv, I believe the actual computation of gl_Position has not changed mathematically. Of particular note, the greatest potential of mathematical change for this shader is a re-ordering of the vec4 (floating point) adds in the first statement. Yet the order appears to be the same before and after optimization.

I don't think **invariant** guarantees that intermediate memory operations are preserved, so I think it is valid here for the optimizer to eliminate not only the store/load of _187, but the variable as well. My reading of the spec is that **invariant** allows any changes that do not change the value of the output variable.

That said, I could not guarantee that spirv-opt does not do some optimizations which could violate **invariant**. In particular, --simplify-instructions could likely have some such tranformations. A cursory check of spirv-opt source shows very little checking for **invariant**, and none in simplification. If the authors of simplification could chime in on this question, that would be helpful. In the meantime, I will do a survey to see if I can find any transformations in spirv-opt that need to consider **invariant** but don't.

**Comment by greg-lunarg** [comment]
One case comes to mind almost immediately: floating point constant folding. By my understanding, floating point operations on the GPU are not guaranteed invariant with the same operation on the CPU. So it seems that this optimization is not valid in an invariant computation.

Anyone disagree?

**Comment by greg-lunarg** [comment]
I should qualify one of my previous statements: **some** floating point operations on the GPU are not guaranteed invariant with the same operation on the CPU. There are probably some that are OK, for example, I think almost any constant floating point comparison, such as 0.0 < 1.0 can be safely folded to true. And I think any adding of 0.0 or multiplying by 1.0 can be eliminated as well. But there are certainly some, and probably many constant folds that probably can't be legally done in an invariant computation.

**Comment by greg-lunarg** [comment]
And if we have indeed established that spirv-opt does some optimizations that are not valid for **invariant**, I just wanted to point out that performing a true **invariant** closure on a module is probably a very similar computation what we do in aggressive dce, starting with a set of live (or invariant) instructions and then propagating liveness (or invariance) out not only to its contributing operations, but also to enclosing control flow structures, and through any called functions (if not already inlined).

It is probably a valid first approximation, if heavy-handed, to just assume everything in a function is **invariant** if an **invariant** output variable is set, if we think we need to fix this quickly. Full invariant closure can be added afterward as an optimization.

**Comment by greg-lunarg** [comment]
It does appear that Simplification does do general floating point constant folding. It does not appear to take invariant into account.

One thing folding does look for is a NoContraction decoration on the instruction and will not fold if found. This is done in the method Instruction::IsFloatingPointFoldingAllowed(). This is an interesting interpretation of NoContraction, but I think it makes sense.

Still, Simplification should take invariant into account as well. It would be overkill to not do any Simplification in the presence of invariant as Simplification does a number of important things that are not related to invariant. So something more surgical should be done.

Simplification might make some other tranformations that would violate the invariant directive, so someone will need to comb through everything it does taking invariant into account.

There is only one other pass that appears to require similar attention: CCP. It also appears to do floating point constant folding. It uses the same InstructionFolder class that Simplification does. Perhaps if the invariant analysis can be applied to this folding class (or below), we could benefit both Simplification and CCP passes with one fix.

No other passes appear to make transformations relevant to invariant.

**Comment by greg-lunarg** [comment]
Inviting @s-perron as one of the main contributors to Simplification

**Comment by prideout** [comment]
Regarding Greg's first comment: while the elimination of _187 does not change gl_Position mathematically, `invariant` has more to do with concrete data flow than with mathematical equivalence.

Here's the use case that motivated this issue: we have two vertex shaders, one for a depth pass and one for a color pass.  We carefully authored these two shaders to compute gl_Position in the same way.  However the optimizer is removing an intermediate memory operation in the depth shader, which is causing floating-point variance on some GPU's, leading to depth artifacts.

**Comment by alan-baker** [comment]
After reading the GLES spec, it seems only Input and Output variables can be decorated with Invariant and it has no meaning on Input.

**Comment by s-perron** [comment]
I was letting Alan handle this, but, since Greg mentioned my specifically, I chime in.  I'm still not clear on the exact meaning of the invariant decoration, so I don't want to do anything too hasty.

@prideout, can you give us the two vertex shaders that give you the different results?  If we optimize both of them the same way, then they should still be invariant.

The second issue is that you mentioned the last pass of ADCE specifically making the difference.  Can you give us the two commands (or list of optimizations) there were used.  The good one and the bad one.  I want to know if the difference is caused by ADCE or is is possible that other optimization are run after ADCE that now have a different input.

From what I can tell, we just need to ensure that the computation of the two is the same in both shaders.  It does not mean that we cannot optimize, it just means they have to be optimized in the exact same way.  Or is there a guarantee somewhere that they must be the same regard of which options are given to the toolchain?

**Comment by s-perron** [comment]
Whether or not there is a problem in the amplifier depends on my tool chain question.  Because the simplifier will always do the same thing given the same input, it may not be a problem.  If the expectation is that we cannot do anything because the optimized and unoptimized give the exact same results, then we do have to do something.

**Comment by s-perron** [comment]
Thanks for that.  I double checked, and the expressions in the `*opt.spv` files are the same.

spirv-cross uses `_271` because its values is used twice in colour_opt.vert.  That is the only way to not have to recompute the expression.

**Comment by greg-lunarg** [comment]
@s-perron I am going to abandon my concern about constant folding (in simplification or ccp) and **invariant**. 

In general, I have come to the conclusion that we shouldn't worry that an **invariant** computation may be different between an optimized and non-optimized version of the same program. I think there is an implicit assumption in the definition of **invariant** that the two different programs are subjected to the same compilation regimen.

Thinking more about what **invariant** is really about, I really can't come up a test case that I think reflects anything that might come up in the real world that would cause a problem.

Sorry for the distraction.

**Comment by s-perron** [comment]
@greg-lunarg No problem.  It is worth discussing these things to make sure we are doing the right thing.  I still think of myself as a compiler writer, and there are many graphics specific concepts that I am still unfamiliar with.  Thanks for bring it up.
