### ISSUE TITLE
Re-enable InstanceId for ray tracing shaders

### ISSUE THREAD

**Issue by dgkoch** [KhronosGroup/SPIRV-Tools#2046]
#2036 disabled InstanceId for Vulkan.
This causes issues in glslang tests: https://github.com/KhronosGroup/glslang/issues/1576

It appears we made a mistake in the Vulkan and SPIR-V specs for NV_ray_tracing and documented the builtin for gl_InstanceId as InstanceIndex (as the rest of the vulkan shaders use) instead of adding InstanceId for the relevant shader stages. We are sorting out the spec issues, but at this point it's looking like we stick with InstanceId for closest-hit, any-hit, and intersection shaders

**Comment by dgkoch** [comment]
cc @dneto0

**Comment by dneto0** [comment]
Sending to @alan-baker who probably has more bandwidth than I do today.
