### ISSUE TITLE
member XXX at offset XXX is not aligned to 0 (when having an empty struct)

### ISSUE THREAD

**Issue by apayen** [KhronosGroup/SPIRV-Tools#2073]
Hello,

When converting HLSL with some empty structs (for various reasons like preprocessing) used as members' type in uniform block, validation fails saying that member's offset is not aligned to 0 (because struct alignment and size are both 0, and checking alignment of 0 with always return false).

From what I see in spirv spec, a struct without members is legit
> OpTypeStruct
> Declare a new structure type: an aggregate of **zero** or more potentially heterogeneous members.

This can be fixed by initializing `uint32_t baseAlignment = 1;` instead of 0 in `uint32_t getBaseAlignment(...)`.

Is there any case where a catching an alignment of 0 is actually intended or is it safe to set baseAlignment initial value to 1 ?

**Comment by alan-baker** [comment]
I'm not sure I understand your input. I've tried the following and it validates against the Vulkan environment:
```
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %main "main"
OpExecutionMode %main LocalSize 1 1 1
OpDecorate %struct Block
OpMemberDecorate %struct 0 Offset 0
OpDecorate %var DescriptorSet 0
OpDecorate %var Binding 0
%void = OpTypeVoid
%empty = OpTypeStruct
%struct = OpTypeStruct %empty
%ptr_struct_ubo = OpTypePointer Uniform %struct
%var = OpVariable %ptr_struct_ubo Uniform
%voidfn = OpTypeFunction %void
%main = OpFunction %void None %voidfn
%entry = OpLabel
OpReturn
OpFunctionEnd
```

Do you have a shader you could share?

**Comment by apayen** [comment]
You're on a special case where the offset of the member is 0 and it is explicitely whitelisted (see below).
If you change the decorated offset, you should be able to reproduce.

```
// Returns true if |offset| satsifies an alignment to |alignment|.  In the case
// of |alignment| of zero, the |offset| must also be zero.
bool IsAlignedTo(uint32_t offset, uint32_t alignment) {
  if (alignment == 0) return offset == 0;
  return 0 == (offset % alignment);
}
```

**Comment by alan-baker** [comment]
Thanks, I have a reproducer now.
