### ISSUE TITLE
continuous-integration/appveyor/pr check is flakey

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/SPIRV-Tools#2079]
This check is failing occasionally  due to a timeout in spirv-tools-test_val_limits.

An example failed run, https://ci.appveyor.com/project/Khronoswebmaster/spirv-tools/builds/20411836

**Comment by dj2** [comment]
@s-perron started looking into this last week and identified the issue as a linear walk that the test executes ... a lot.

**Comment by s-perron** [comment]
This is the loop that takes most of the time: https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/val/validate_cfg.cpp#L554.

This loops looks like it will be repeating a lot of work.  If a BB is contained in `n` nested constructs, then it predecessors will be checked `n` time.  It only needs to be checked for the inner-most containing construct.
