### ISSUE TITLE
Validate Column Count for OpTypeMatrix

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/SPIRV-Tools#2080]
From SPIR-V spec, section 3.32.6 on OpTypeMatrix:
> Column Count is the number of columns in the new matrix type. It must be at least 2.

This is currently not checked by the validator from what I can tell.

**Comment by dj2** [comment]
@alan-baker

**Comment by alan-baker** [comment]
We only currently check that the column is a vector. Additional rules:

2.16.1:
>Matrix types can only be parameterized with floating-point types.

>Matrix types can only be parameterized as having only 2, 3, or 4 columns.

**Comment by zoddicus** [comment]
When adding tests for my implementation of this validation, I discovered that these are already checked in ValidateMatrixNumCols and ValidateMatrixColumnType as part of the DataRulesPass.

There currently isn't any tests for them, so I will add them in.
