### ISSUE TITLE
Support VK_EXT_transform_feedback

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#2084]
See also #2011 

I think this requires a new validator option for use when VK_EXT_transform_feedback is in effect. There is no corresponding SPIR-V extension to signal the ability to use the capabilities TransformFeedback or GeometryStreams.

**Comment by alan-baker** [comment]
#2088 will add support. Our opinion is if the capability is listed by the Vulkan spec and has no corresponding SPIR-V extension, we should whitelist it as an optional Vulkan capability. It is up to the API to check whether the Vulkan support is valid.
