### ISSUE TITLE
Reduction pass idea: merge blocks

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2120]
Suppose we have blocks A and B, such that:

- B is not a merge block
- B does not contain OpPhi instructions
- A unconditionally branches to B
- A is the sole predecessor of B

Then we should consider the opportunity to merge A and B.

There is likely a pass in the optimizer to do this already.  For the reducer, though, we want the ability to do it on a block-pair by block-pair basis (rather than doing it in all the places that it is possible).

**Comment by alan-baker** [comment]
The reference pass is block_merge_pass.cpp.
