### ISSUE TITLE
SPIRV_WERROR option usage is not intuitive

### ISSUE THREAD

**Issue by acidYeah** [KhronosGroup/SPIRV-Tools#2121]
SPIRV_WERROR turned ON adds -Werror flag as expected, but turning it OFF does nothing.
When turning this option OFF I would expect to turn the errors on warnings off, not "not turn the errors on", which is a problem if I'm using -Werror with parent project by default.

Is this intended?

**Comment by s-perron** [comment]
Yes this is intended.  If you want you can add -Wno-error yourself before entering the subdirectory.  I don't know how you cmake files are set up, but you can do something like what [amber](https://github.com/google/amber/blob/master/third_party/CMakeLists.txt) did for glslang.
