### ISSUE TITLE
Optimizer tests should be able to specify the environment easily

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#2139]
Optimizer tests assume SPIR-V 1.1 universal right now. We should be able to specify the environment to use.

**Comment by s-perron** [comment]
This is now possible. See https://github.com/KhronosGroup/SPIRV-Tools/blob/43b8886490eb6af81fc61e0ff071c51a922af864/test/opt/aggressive_dead_code_elim_test.cpp#L6651
