### ISSUE TITLE
Code massage for the test fixture class

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#22]
The name of `TextToBinaryTest[Base]` is outdated; we actually have roundtrip test methods inside it. I'd like to change it to `RoundTripTest[Base]`. And also, rename the methods inside it to something like `{Encode|Decode}...{Succeeded|Failed}...`.

Opinions?

**Comment by dneto0** [comment]
I like the CompiledInstructions name.  That's very clear.
I don't like the "Encode" because, especially in a round trip sense, it's not clear what the originating format is, text or binary.
I'd rather not make this change.

**Comment by antiagainst** [comment]
I don't care about the naming that much; I just want to make sure they are consistent (like changing the `Encode` to `Compiled`). But since there are objections, I'll not do it.
