### ISSUE TITLE
loop-unswitch generates code that leads to multiple back edges

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2201]
[0008.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2685179/0008.zip)

"command" in the attachment gives the command necessary to repro the bug.

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
Loop unswitching is unswitching the conditional branch that creates the back-edge.  In the version of the loop, where the bachedge is not taken, there is no back-edge.  This is what causes the validator to complain.

The solution I will go with will be to now unswitch a condition with a back-edge.  At this time we do not now if loop unswitching is used.  We do not include it in the optimization sets provided, nor is it used in glslang's set.  When there are opportunities and no breaks from the loop, the loop with either be a single iteration loop, or an infinite loop.  There is no performance advantage to performing loop unswitching in either of those cases.  If there is a break, maintaining structured control flow will be tricky.  Unless we see a clear advantage to handling these case, I would go with the safer simpler solution.
