### ISSUE TITLE
eliminate-local-multi-store leads to code for which the validator claims an OpPhi's incoming block count does not match predecessors

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2202]
[0016.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2685185/0016.zip)

"command" in the attachment gives the command necessary to repro the bug.

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
Block %18 ends with a switch that jumps to block %21 in two different cases.  This causes the ssa rewriter to add two entries in the phinode for block %21.  The ssa rewriter should make sure the OpPhi instruction does not have duplicates when it is generated.
