### ISSUE TITLE
eliminate-common-uniform leads to code for which the validator claims that OpPhi instructions are in the wrong place

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2204]
[0061.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2685193/0061.zip)

"command" in the attachment gives the command necessary to repro the bug.

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by greg-lunarg** [comment]
eliminate-common-uniform is not currently in common use as it previously caused problems for some drivers. This of course does not excuse the problem, but it does make it less urgent.

**Comment by s-perron** [comment]
@greg-lunarg Yes, many were opened, but not all of them are high priority.  We can pick decide which ones we feel will effect real users the most.  Most of the loop optimization would be that way.

Personally, for ones like this, where I feel it can be easily fixed, I will just go ahead an do it quickly.
