### ISSUE TITLE
ssa-rewrite, eliminate-dead-branchs and merge-return lead to code which the validator rejects

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2207]
[0131.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2687121/0131.zip)

"command" in the attachment gives the command necessary to repro the bug.

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
Merge return is picking the wrong place to branch to, and it is bypassing the merge of it inner-most loop.
