### ISSUE TITLE
loop-unswitchify generates code which the validator rejects (a block being the merge header for two constructs)

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2208]
[0205.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2687129/0205.zip)

"command" in the attachment gives the command necessary to repro the bug.

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
Duplicate of #2203
