### ISSUE TITLE
convert-local-access-chains and scalar-replacement lead to code the validator rejects

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2212]
[2463.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2687192/2463.zip)

"command" in the attachment gives the command necessary to repro the bug.

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
Duplicate of #2209.
