### ISSUE TITLE
eliminate-dead-branches leads to code that the validator rejects

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2213]
[1696.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2687205/1696.zip)

"command" in the attachment gives the command necessary to repro the bug.

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
The input is invalid to begin with.  There are two nested selection constructs, and there is a branch from the inner construct to the merge of the outer construct.

@alan-baker Can you confirm that this is invalid?

@afd How was this spir-v generated?

**Comment by afd** [comment]
I started with a big .frag shader generated by glsl-fuzz, which I then reduced using glsl-reduce, using an interestingness function that would compile the .frag to .spv using glslangValidator and then apply spirv-opt and spirv-val.

I then further reduced the .spv file associated with the final .frag file using spirv-reduce.

In [this archive](https://github.com/KhronosGroup/SPIRV-Tools/files/2696603/files.zip), shader_1696_reduced_final.frag is the final reduced .frag file produced by glsl-reduce, and shader_1696_reduced_final.frag.{asm,spv} is the {assembly,binary} I get when I apply glslangValidator -V to it.

_reduced_final.{asm,spv} are the final outputs from spirv-reduce, and this is what I filed in the bug report. 
 They look the same, in terms of CFG, as before running spirv-reduce, so I don't think spirv-reduce is introducing invalidity here.

So the question is whether shader_1696_reduced_final.frag.{asm,spv} is valid.

I am using Glslang Version: 7.10.2933.

**Comment by alan-baker** [comment]
![cfg](https://user-images.githubusercontent.com/33432579/50251101-c3771700-03b0-11e9-9f72-08f649e8d141.png)

This is the cfg from shader_1696_reduced_final.frag.spv. The branch from `22` to `9` looks invalid.

**Comment by alan-baker** [comment]
```
void main()
{
 switch(_GLF_SWITCH(0))
  {
   case 0:
   if((gl_FragCoord.y < 0.0))
    {
     break;
    }
  }
}
```

Shader source code. The break from the case is not being code gen'd by glslang correctly to satisfy structured control flow. Admittedly, it is a complicated case to handle.

**Comment by alan-baker** [comment]
Moved this bug to the validator so we can try to catch it.

**Comment by alan-baker** [comment]
Probably not for this specific case, but maybe for one related. I've not looked yet.

**Comment by alan-baker** [comment]
Filed https://github.com/KhronosGroup/glslang/issues/1635 for glslang.
