### ISSUE TITLE
loop-unswitch leads to code that the validator rejects

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2214]
Could be related to #2201, but the validator gives a different error.
[0825.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2687216/0825.zip)

"command" in the attachment gives the command necessary to repro the bug.

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
Duplicate of #2203
