### ISSUE TITLE
ssa-rewrite and loop-unswitch leads to code the validator rejects

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2215]
May be related to #2214 and/or #2208, but the validator error different.

[2334.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2687233/2334.zip)

"command" in the attachment gives the command necessary to repro the bug.

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
Compact-ids invalidates the constant manager.  However, it is not possible to reset the constant manager.  This causes ccp to fail.

**Comment by s-perron** [comment]
Duplicate of #￼2245
