### ISSUE TITLE
spirv-opt aborts with no output

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2219]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--relax-struct-store 

leads to spirv-opt aborting with no output.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[0000.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689705/0000.zip)

**Comment by s-perron** [comment]
The -Oconfig option was only intended to parse optimization options.  I don't know what we documented.  @dnovillo This is your feature.  Do you have strong opinions which way we go?
