### ISSUE TITLE
assertion failure: spirv-opt: Assertion `type' failed.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2221]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--reduce-load-size --compact-ids --scalar-replacement 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/type_manager.h:_: size_t spvtools::opt::analysis::HashTypePointer::operator()(const spvtools::opt::analysis::Type*) const: Assertion `type' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[0042.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689720/0042.zip)

**Comment by s-perron** [comment]
My best guess is that compact ids is not invalidating all of the analyses that it should.

**Comment by s-perron** [comment]
Duplicate of #2220
