### ISSUE TITLE
assertion failure: spirv-opt: "Definition is not registered."

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2222]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--eliminate-local-multi-store --loop-unswitch 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/def_use_manager.cpp:_: void spvtools::opt::analysis::DefUseManager::AnalyzeInstUse(spvtools::opt::Instruction*): Assertion `def && "Definition is not registered."' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[0064.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689723/0064.zip)

**Comment by s-perron** [comment]
Duplicate of #2203
