### ISSUE TITLE
assertion failure: spirv-opt: "'after' is not a registered def."

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2223]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--merge-blocks --ssa-rewrite --loop-unswitch 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/ir_context.cpp:_: bool spvtools::opt::IRContext::ReplaceAllUsesWith(uint__t, uint__t): Assertion `get_def_use_mgr()->GetDef(after) && "'after' is not a registered def."' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[0111.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689727/0111.zip)

**Comment by s-perron** [comment]
Duplicate of #2203

**Comment by s-perron** [comment]
Duplicate of #2203
