### ISSUE TITLE
assertion failure: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2224]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--inline-entry-points-exhaustive --loop-unswitch 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[0144.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689738/0144.zip)

**Comment by s-perron** [comment]
Duplicate of #2203
