### ISSUE TITLE
assertion failure: "Definition is not registered." failed from WhileEachUser.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2225]
May be a duplicate of #2222, but the assertions trigger from different places (WhileEachUser vs. AnalyzerInstUse).

Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--eliminate-local-multi-store --loop-unswitch --simplify-instructions 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/def_use_manager.cpp:_: bool spvtools::opt::analysis::DefUseManager::WhileEachUser(const spvtools::opt::Instruction*, const std::function<bool(spvtools::opt::Instruction*)>&) const: Assertion `def && (!def->HasResultId() || def == GetDef(def->result_id())) && "Definition is not registered."' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[0146.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689755/0146.zip)

**Comment by s-perron** [comment]
Duplicate of #2203
