### ISSUE TITLE
assertion failure: spirv-opt: "Definition is not registered." from WhileEachUse

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2226]
May be a duplicate of #2222 and/or #2225, but the assertion triggers from a different place (WhileEachUse, vs. WhileEachUser or AnalyzeInstUse)

Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--eliminate-local-multi-store --loop-unswitch --redundancy-elimination 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/def_use_manager.cpp:_: bool spvtools::opt::analysis::DefUseManager::WhileEachUse(const spvtools::opt::Instruction*, const std::function<bool(spvtools::opt::Instruction*, unsigned int)>&) const: Assertion `def && (!def->HasResultId() || def == GetDef(def->result_id())) && "Definition is not registered."' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[3295.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689756/3295.zip)

**Comment by s-perron** [comment]
Duplicate of #2203
