### ISSUE TITLE
assertion failure: spirv-opt: Assertion `sbi != func->end()' failed.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2227]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--loop-unswitch --merge-blocks 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/block_merge_pass.cpp:_: bool spvtools::opt::BlockMergePass::MergeBlocks(spvtools::opt::Function*): Assertion `sbi != func->end()' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[0332.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689776/0332.zip)

**Comment by s-perron** [comment]
Duplicate of #2203

**Comment by s-perron** [comment]
Duplicate of #2203
