### ISSUE TITLE
assertion failure: spirv-opt: "We cannot have a base pointer come from this load".

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2228]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--loop-peeling --if-conversion 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/instruction.cpp:_: spvtools::opt::Instruction* spvtools::opt::Instruction::GetBaseAddress() const: Assertion `base_inst->IsValidBasePointer() && "We cannot have a base pointer come from this load"' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[0484.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689788/0484.zip)

**Comment by s-perron** [comment]
loop peeling creates a variable pointer.  It creates an OpPhi on pointer values.

**Comment by s-perron** [comment]
Duplicate of #2230
