### ISSUE TITLE
assertion failure: spirv-opt: Assertion `c->AsBoolConstant() || c->AsNullConstant()' failed.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2229]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--simplify-instructions --compact-ids --ccp 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/ccp_pass.cpp:_: spvtools::opt::SSAPropagator::PropStatus spvtools::opt::CCPPass::VisitBranch(spvtools::opt::Instruction*, spvtools::opt::BasicBlock**) const: Assertion `c->AsBoolConstant() || c->AsNullConstant()' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[0627.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689792/0627.zip)

**Comment by s-perron** [comment]
Looks like it is the same as #2220.
