### ISSUE TITLE
assertion failure: spirv-opt: "This loop is not in LCSSA form".

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2231]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--ssa-rewrite --loop-unswitch 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/loop_unswitch_pass.cpp:_: void spvtools::opt::{anonymous}::LoopUnswitch::PerformUnswitch(): Assertion `loop_->IsLCSSA() && "This loop is not in LCSSA form"' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[1124.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689802/1124.zip)

**Comment by s-perron** [comment]
Duplicate of #2203
