### ISSUE TITLE
assertion failure: spirv-opt: Assertion `cc != nullptr' failed.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2232]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--compact-ids --eliminate-common-uniform --eliminate-dead-code-aggressive --eliminate-dead-branches --merge-return --compact-ids --simplify-instructions 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/const_folding_rules.cpp:_: spvtools::opt::{anonymous}::FoldExtractWithConstants()::<lambda(spvtools::opt::IRContext*, spvtools::opt::Instruction*, const std::vector<const spvtools::opt::analysis::Constant*>&)>: Assertion `cc != nullptr' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[1317.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689806/1317.zip)

**Comment by s-perron** [comment]
Duplicate of #2220.
