### ISSUE TITLE
assertion failure: spirv-opt: "Unsettled value".

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2234]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--eliminate-local-multi-store --eliminate-common-uniform --ccp 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/propagator.cpp:_: spvtools::opt::SSAPropagator::Run(spvtools::opt::Function*)::<lambda(spvtools::opt::Instruction*)>: Assertion `(!HasStatus(inst) || Status(inst) != SSAPropagator::kNotInteresting) && "Unsettled value"' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[1974.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689816/1974.zip)

**Comment by s-perron** [comment]
Duplicate of #2246.
