### ISSUE TITLE
assertion failure: spirv-opt: "FoldScalars() only accepts ScalarConst or NullConst type of " "constant"'.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2235]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--compact-ids --eliminate-dead-branches --merge-return --eliminate-dead-const --compact-ids --simplify-instructions 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/fold.cpp:_: uint__t spvtools::opt::InstructionFolder::FoldScalars(SpvOp, const std::vector<const spvtools::opt::analysis::Constant*>&) const: Assertion `false && "FoldScalars() only accepts ScalarConst or NullConst type of " "constant"' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[3391.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689821/3391.zip)

**Comment by s-perron** [comment]
Duplicate of #2220
