### ISSUE TITLE
assertion failure: spirv-opt: "operand index out of bound".

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2236]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--loop-unswitch --eliminate-common-uniform 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/instruction.h:_: const spvtools::opt::Operand& spvtools::opt::Instruction::GetOperand(uint__t) const: Assertion `index < operands_.size() && "operand index out of bound"' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[3433.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689828/3433.zip)

**Comment by s-perron** [comment]
Duplicate of #2203
