### ISSUE TITLE
assertion failure: spirv-opt: `def != nullptr'.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2238]
The message is similar to that of #2232, but the positions of the assertions seem totally different.

Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--fold-spec-const-op-composite --compact-ids --eliminate-dead-functions --eliminate-dead-branches --merge-return 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/constants.cpp:_: spvtools::opt::Instruction* spvtools::opt::analysis::ConstantManager::GetDefiningInstruction(const spvtools::opt::analysis::Constant*, uint__t, spvtools::opt::Module::inst_iterator*): Assertion `def != nullptr' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[7790.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689848/7790.zip)

**Comment by s-perron** [comment]
Duplicate of #2220
