### ISSUE TITLE
assertion failure: spirv-opt: Assertion `result_type->AsBool()' failed.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2239]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--compact-ids --eliminate-dead-const --scalar-replacement --simplify-instructions --compact-ids --ccp 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/const_folding_rules.cpp:_: spvtools::opt::{anonymous}::FoldFOrdLessThan()::<lambda(const spvtools::opt::analysis::Type*, const spvtools::opt::analysis::Constant*, const spvtools::opt::analysis::Constant*, spvtools::opt::analysis::ConstantManager*)>: Assertion `result_type->AsBool()' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[7962.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689852/7962.zip)

**Comment by s-perron** [comment]
Duplicate of #2220
