### ISSUE TITLE
assertion failure: spirv-opt: Assertion `defining_blocks.size()' failed.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2240]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--eliminate-dead-branches --loop-unswitch 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/loop_utils.cpp:_: const std::vector<unsigned int>& spvtools::opt::{anonymous}::LCSSARewriter::GetDefiningBlocks(uint__t): Assertion `defining_blocks.size()' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[8346.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689854/8346.zip)

**Comment by s-perron** [comment]
Duplicate of #2203
