### ISSUE TITLE
assertion failure: spirv-opt: "Bool constant should be declared with one operand"

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2241]
Running ./command in the attachment should reproduce the problem.

Brief summary: running spirv-opt (debug build) with arguments:

--compact-ids --vector-dce --eliminate-dead-code-aggressive --compact-ids --ccp 

leads to the following error (numbers have been replaced with _ to avoid duplicates):

spirv-opt: source/opt/constants.cpp:_: std::unique_ptr<spvtools::opt::analysis::Constant> spvtools::opt::analysis::ConstantManager::CreateConstant(const spvtools::opt::analysis::Type*, const std::vector<unsigned int>&) const: Assertion `literal_words_or_ids.size() == _ && "Bool constant should be declared with one operand"' failed.

SPIRV-Tools v2018.7-dev v2018.6-94-geaa351a5

Found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

[9984.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2689859/9984.zip)

**Comment by s-perron** [comment]
Duplicate of #2220.
