### ISSUE TITLE
[SPIRV-Val][OpenCL] Wrong diagnostics of OpLabel layout in function definition/declaration.

### ISSUE THREAD

**Issue by bader** [KhronosGroup/SPIRV-Tools#228]
I got following error message for the attached [SPIR-V file](https://github.com/KhronosGroup/SPIRV-Tools/files/307610/test-OpLabel.zip):

  error: 25: A function must begin with a label

The disassembled module part looks like this:

         %12 = OpFunction %6 None %11
         %13 = OpFunctionParameter %8
         %14 = OpFunctionParameter %10
         %15 = OpLabel

According to specification function definition layout is:
- Function definition, using OpFunction.
- Function parameter declarations, using OpFunctionParameter.
- Block
- Block
- …
- Function end, using OpFunctionEnd.

Block must start with OpLabel instruction.

It looks like SPIR-V validation tools doesn't expect OpFunctionParameter to follow OpFunction instruction.

Function declaration layout check has the same issue.

**Comment by umar456** [comment]
The binary is incorrect because of the OpUndef located here:
```
         %11 = OpTypeFunction %6 %8 %10
=>     %23 = OpUndef %9
          %5 = OpVariable %4 UniformConstant
         %12 = OpFunction %6 None %11
         %13 = OpFunctionParameter %8
         %14 = OpFunctionParameter %10
         %15 = OpLabel
```
But the diagnostic message is incorrect.
