### ISSUE TITLE
CI-shaderc-smoketest failing due to new dependency on spirv-cross

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/SPIRV-Tools#2291]
Example of the failure: https://source.cloud.google.com/results/invocations/e397caa0-9ecf-4ef3-a5d6-48660adf0ce1/targets

I believe this failure is occuring due this commit in shaderc: https://github.com/google/shaderc/commit/a0a4695765d8641576c3e34294145c345b50dbdc

**Comment by dneto0** [comment]
Should be addressed by https://github.com/google/shaderc/issues/542

**Comment by dneto0** [comment]
https://github.com/google/shaderc/issues/542 was merged, and the smoketests are now passing (on the bots i'm watching)
