### ISSUE TITLE
Parsing of -Oconfig is leaking

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#2297]
==106826==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x916170 in operator new[](unsigned long) (/third_party/spirv-tools/tools/spirv-opt+0x916170)
    #1 0x91d94a in (anonymous namespace)::ParseOconfigFlag(char const*, char const*, spvtools::Optimizer*, char const**, char const**, spvtools::ValidatorOptions*, spvtools::OptimizerOptions*) /third_party/spirv-tools/tools/opt/opt.cpp:470:27
    #2 0x91bcb9 in (anonymous namespace)::ParseFlags(int, char const**, spvtools::Optimizer*, char const**, char const**, spvtools::ValidatorOptions*, spvtools::OptimizerOptions*) /third_party/spirv-tools/tools/opt/opt.cpp:569:13
    #3 0x91a7fe in main /third_party/spirv-tools/tools/opt/opt.cpp:669:22
    #4 0x7f27bd2a62b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

**Comment by s-perron** [comment]
I've already got at fix for this in https://github.com/KhronosGroup/SPIRV-Tools/pull/2301.
