### ISSUE TITLE
Refactor reducer

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2319]
The reducer currently has a number of different passes that share (unchanged) functionality for controlling the reduction process, and provide their own (more or less completely different) functionality for finding reduction opportunities.

The functionality for finding doesn't really belong with the functionality for controlling the reduction process.

It would be better to structure this so that we have a number of reduction opportunity finder classes, each of which captures different finding behaviour, and a single reduction pass class that has a reference to a particular finder.

**Comment by paulthomson** [comment]
Fixed in #2321
