### ISSUE TITLE
val: OpCompositeExtract and OpCompositeInsert: require at least one index

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#2360]
Recent decision by SPIR WG.  Khronos internal issue 392.

This also extends to their use within OpSpecConstantOp

**Comment by dneto0** [comment]
He @alan-baker this might be a good starter bug.

**Comment by kuhar** [comment]
There's an existing test that expects code with no indices given to OpCompositeExtract to work:
In `SPIRV-Tools/source/val/validate_composites.cpp`
```
// Valid: No Indexes were passed to OpCompositeExtract, and the Result Type is
// the same as the Base Composite type.
TEST_F(ValidateComposites, CompositeExtractNoIndexesGood) {
```
Should this test be updated, should this check run only on newer version of spir-v? Not sure how to handle the potential breakage here.
@alan-baker

**Comment by alan-baker** [comment]
That test is invalid. You can delete it.
