### ISSUE TITLE
Forward declared id usages are not being properly accounted for in validator

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/SPIRV-Tools#2372]
In the validator if there is a forward declared usage of an id, like the continue-target for an OpLoopMerge, the current code does not correct account for it. This is because usage is calculated at the time the call site is being processed, so the forward declaration hasn't been registered yet. So its usage vector cannot be updated.

Updating the usage vector needs to either be moved to a later pass or have a queue of forward declarations.

**Comment by alan-baker** [comment]
I think my preference would be to defer the calculation of uses until after resolving forward references. I don't think anything should rely on them until then.

**Comment by alan-baker** [comment]
Closed via #2378
