### ISSUE TITLE
For --webgpu-mode, convert memory model to VulkanKHR Logical if possible

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/SPIRV-Tools#2393]
For WebGPU VulkanKHR is the only valid memory model, with Logical addressing. When converting SPIR-V to be WebGPU complient with the --webgpu-mode flag/passes, there should be a pass that attempts to convert the existing memory model to the correct one if possible. If this translation is not possible then the entire transformation should fail.

**Comment by zoddicus** [comment]
@alan-baker, @dneto0 said that you were familar with converting to/from the Vulkan memory model.

**Comment by alan-baker** [comment]
I wrote the UpgradeMemoryModel pass (--upgrade-memory-model) to do this. It should not be able to fail.

**Comment by alan-baker** [comment]
There is no down-conversion pass though.
