### ISSUE TITLE
Please make --preserve-numeric-ids default

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/SPIRV-Tools#2403]
We ran into a really bizarre bug in SPIRV-Cross which took longer to track down because the disassembly -> assembly loop was not stable, IDs were not preserved when assembling and that affected code output, so I spent a lot of time chasing something which was not what I expected, and if --preserve-numeric-ids was default, that would have made the bug obvious.

https://github.com/KhronosGroup/SPIRV-Cross/issues/858

Please consider changing the defaults so the disasm -> asm loop is more stable.

**Comment by dneto0** [comment]
I don't want to do this change.

The option is already available on the command line and via the API.  If you want to be specific about this behaviour, specify the option.

Inspecting specific IDs is the rare case.  To really make it work you'd have to do both --preserve-numeric-ids on the assembler and --raw-ids on the disassembler.

Internally, the --preserve-numeric-ids functionality is implemented as two passes over the input text.  The extra time is not warranted for the vast majority of users.

**Comment by HansKristian-Work** [comment]
Alright.
