### ISSUE TITLE
What is extensions_enum.inc ?

### ISSUE THREAD

**Issue by Crisspl** [KhronosGroup/SPIRV-Tools#2406]
We are using `shaderc` as dependency and `SPIRV-Tools` is shaderc's dependency. I'm trying to "merge" source of SPIRV-Tools into out project however i encountered a problem with aforementioned `extensions_enum.inc` file. What is it? I can't find it anywhere. I assumed it has to be generated during build, but I can't even find anything about this in SPIRV-Tools' build scripts. Can you help me out somehow, please?

**Comment by s-perron** [comment]
The file is mentioned [here](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/CMakeLists.txt#L46), and is used [here](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/extensions.h#L27).  It is generated from the grammar file in spriv-headers, and it contains a list of all of the extensions found in the grammar appropriately named to fit the coding style.  Hope that helps.

**Comment by Crisspl** [comment]
Yeah, I found out it's generated by python script in util directory. However I've abandoned the idea and we'll be using SPIRV-Tools as external dependency (and not putting it directly into our build system). 
Thanks for help, I'm closing.
