### ISSUE TITLE
v2019.2 tag/release missing

### ISSUE THREAD

**Issue by tjaalton** [KhronosGroup/SPIRV-Tools#2432]
git log shows it's finalized, and other projects depend on it but it's not tagged nor released

**Comment by tjaalton** [comment]
The thing is that as a distro packager I've no idea there's a new release unless there's a tag that the automated tools can find. And now the new vulkan-validationlayers release fails to build because spirv-tools/glslang need to be updated. I'd rather not use git snapshots if possible...

**Comment by tjaalton** [comment]
hello?

**Comment by jeremy-lunarg** [comment]
I think @tjaalton is asking for a _github_ release/tag that corresponds to the sha in the known_good for Vulkan-ValidationLayers (v1.1.101). This is more convenient for maintainers than chasing shas in known_good files. Currently, you have to chase down two levels of indirection to get the correct dependencies (V-VL's glslang revision -> glslang's spirv-tools revision). Anything developers can do to simplify the release process will encourage more package maintainers to release this software on more linux distributions.

**Comment by s-perron** [comment]
Sorry I missed this.  I must have forgot to push the tag.  I won't be able to get to it until April 1st.

**Comment by s-perron** [comment]
I had a typo when creating the tag.  I forgot the "v":

```
commit 61dfd8492b6e324f684863ecbd79c299a06e6517 (tag: 2019.2)
Author: Steven Perron <stevenperron@google.com>
Date:   Wed Feb 20 11:04:41 2019 -0500

    Finalize SPIRV-Tools 2019.2
```
