### ISSUE TITLE
spvBinaryToText might leave pText uninitialized

### ISSUE THREAD

**Issue by archimedus** [KhronosGroup/SPIRV-Tools#2435]
```
spv_result_t spvBinaryToText(const spv_const_context context,
                             const uint32_t* code, const size_t wordCount,
                             const uint32_t options, spv_text* pText,
                             spv_diagnostic* pDiagnostic) {
...
  // Now disassemble!
  Disassembler disassembler(grammar, options, name_mapper);
  if (auto error = spvBinaryParse(&hijack_context, &disassembler, code,
                                  wordCount, DisassembleHeader,
                                  DisassembleInstruction, pDiagnostic)) {
// **pText left unitialized**
    return error;
  }

  return disassembler.SaveTextResult(pText);
}
```

Failing code is in the attachment: 
[failing_code.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2950039/failing_code.txt)

if statement `return error` is skipped a reasonable message is reported by ` disassembler.SaveTextResult(pText)`: `Value is being defined a second time`
[failing_info.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2950041/failing_info.txt)

**Comment by dj2** [comment]
If the disassemble fails, then we don't fill in the pText, but we return an error message. Calling SaveTextResult doesn't seem right if we were not able to generate a disassembly.

I'm not sure what you're looking for here? Do you expect us to not return error and instead try to SaveTextResult on pText even if disassembly fails?

**Comment by dj2** [comment]
@dneto0

**Comment by archimedus** [comment]
Fixed on our side.
