### ISSUE TITLE
Add check for Image arg to OpImageFetch

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#244]
The Image arg to OpImageFetch must be of type OpTypeImage. Currently OpSampledImage is not causing an error. glslang was previously generating OpSampledImage value but is now adding an OpImage operator.

**Comment by umar456** [comment]
The validator is still being actively developed and does not perform validation on the types of the operands. I am currently work on implementing this feature. I will update this issue as we make more progress.

**Comment by greg-lunarg** [comment]
Would it be possible to post some kind of general status on the spirv-tools
github page? What is working? What is not? What is being worked on actively?

Greg Fischer

Project Manager and Senior Engineer

LunarG, Inc. - 3D Driver Innovations

greg@lunarg.com <alan@lunarg.com>

**Comment by dneto0** [comment]
We could have a Validator-README.md in the root dir to describe status, and reference it from the main README.md.  It would be good to keep it simple.

**Comment by dneto0** [comment]
I've started using the new "Projects" feature in GitHub.  It's a nice and simple kanban board that ties into GitHub issues and uses "notes" for generic tasks not (yet) tied to issues.

This is the "Validator" project:
https://github.com/KhronosGroup/SPIRV-Tools/projects/1

I'm in the middle of populating it with the TODO and WIP list.  Once that's set up I'll write up the intended procedures.

**Comment by antiagainst** [comment]
@atgoo: I think we now have validation checks for `OpImageFetch`: https://github.com/KhronosGroup/SPIRV-Tools/blob/8ba68fa9b94da071e879e3064adf8aaaea1a7051/source/validate_image.cpp#L878-L950
