### ISSUE TITLE
spirv-opt (with various flags) generates code that spirv-val rejects: "Loop header is targeted by 0 back-edge blocks but the standard requires exactly one"

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2452]
[Files to reproduce the problem](https://github.com/KhronosGroup/SPIRV-Tools/files/2968697/to_file.zip)

glsl_reduced.frag is a minimized GLSL shader.  When compiled to SPIR-V with glslangValidator we get glsl_reduced.spv.  This has been further reduced using spirv-reduce to spiv_reduced.spv.

Doing:

spirv-opt --redundancy-elimination --copy-propagate-arrays --merge-blocks --ccp 
--simplify-instructions --convert-local-access-chains --eliminate-dead-code-aggr
essive --eliminate-local-single-block --if-conversion --convert-local-access-cha
ins --eliminate-dead-branches --merge-return --scalar-replacement=100 --eliminat
e-local-multi-store spirv_reduced.spv -o temp.spv

spirv-val temp.spv

should trigger the problem.

I did not try to reduce the spirv-opt flags, in case (as with #2450) there may be an issue both with the optimizer generating invalid code and the validator not picking this up soon enough.

**Comment by alan-baker** [comment]
Appears to be dead branch elimination.
