### ISSUE TITLE
spirv-opt generates code that spirv-val rejects: ID ... defined in block ... does not dominate its us e in block ...

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2453]
[Files to reproduce problem](https://github.com/KhronosGroup/SPIRV-Tools/files/2968969/to_file2.zip)

glsl_reduced.frag is a minimized GLSL shader.  When compiled to SPIR-V with glslangValidator we get glsl_reduced.spv.  This has been further reduced using spirv-reduce to spiv_reduced.spv.

Doing:

spirv-opt spirv_reduced.spv --inline-entry-points-exhaustive --private-to-local 
--ccp --merge-blocks --eliminate-dead-branches --eliminate-dead-branches --combi
ne-access-chains --reduce-load-size --redundancy-elimination --convert-local-acc
ess-chains --convert-local-access-chains --eliminate-dead-inserts --private-to-l
ocal --reduce-load-size --ccp --eliminate-dead-branches --merge-return --elimina
te-dead-inserts --eliminate-local-multi-store --inline-entry-points-exhaustive -
-eliminate-dead-branches --eliminate-dead-code-aggressive --eliminate-local-sing
le-store --eliminate-local-multi-store --reduce-load-size --inline-entry-points-
exhaustive --copy-propagate-arrays --if-conversion --simplify-instructions --ccp
 --eliminate-local-multi-store -o temp.spv
spirv-val temp.spv

should trigger the problem:

error: line 71: ID 144[%144] defined in block 142[%142] does not dominate its us
e in block 152[%152]
  %152 = OpLabel

I did not try to reduce the spirv-opt flags, in case (as with #2450) there may be an issue both with the optimizer generating invalid code and the validator not picking this up soon enough.

Found using [GraphicsFuzz](http://github.com/google/graphicsfuzz)

**Comment by alan-baker** [comment]
Looks like a missing OpPhi in %139

**Comment by alan-baker** [comment]
Combined with #2462 the first validation error occurs after merge return.

**Comment by alan-baker** [comment]
Merge return has a bad assumption about when phi nodes should be added.

**Comment by alan-baker** [comment]
I think this error only occurs with breaks and continues.

**Comment by alan-baker** [comment]
Small reproducer:
```
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %func "func"
OpExecutionMode %func LocalSize 1 1 1
%void = OpTypeVoid
%void_fn = OpTypeFunction %void
%bool = OpTypeBool
%true = OpConstantTrue %bool
%func = OpFunction %void None %void_fn
%1 = OpLabel
OpBranch %2
%2 = OpLabel
OpLoopMerge %8 %7 None
OpBranch %3
%3 = OpLabel
OpSelectionMerge %5 None
OpBranchConditional %true %4 %5
%4 = OpLabel
OpReturn
%5 = OpLabel
%def = OpLogicalNot %bool %true
OpBranchConditional %true %6 %7
%6 = OpLabel
OpBranch %8
%7 = OpLabel
OpBranchConditional %true %2 %8
%8 = OpLabel
OpBranch %9
%9 = OpLabel
%use = OpLogicalNot %bool %def
OpReturn
OpFunctionEnd
```

Prior to merge return, %5 dominates %6, %7, %8 and %9. After merge return, %4 branches to %8 and %5 no longer dominates %8 or %9.
