### ISSUE TITLE
spirv-opt generates code that spirv-val rejects: Case construct that targets ... has invalid branch to block ... (not another case construct, corresponding merge, outer loop merge or outer loop continue)

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2456]
[Files to reproduce problem](https://github.com/KhronosGroup/SPIRV-Tools/files/2968972/to_file5.zip)

glsl_reduced.frag is a minimized GLSL shader.  When compiled to SPIR-V with glslangValidator we get glsl_reduced.spv.  This has been further reduced using spirv-reduce to spiv_reduced.spv.

Doing:

spirv-opt spirv_reduced.spv --combine-access-chains --redundancy-elimination --combine-access-chains --combine-access-chains --reduce-load-size --eliminate-dead-branches --merge-return --eliminate-dead-inserts --eliminate-local-single-store --eliminate-local-single-block --eliminate-dead-code-aggressive --eliminate-dead-inserts --scalar-replacement=100 --eliminate-dead-branches --merge-return --eliminate-dead-inserts --redundancy-elimination --eliminate-dead-inserts --eliminate-dead-inserts --copy-propagate-arrays --eliminate-local-single-block --if-conversion --eliminate-dead-code-aggressive -o temp.spv

spirv-val temp.spv

should trigger the problem:

error: line 26: Case construct that targets 39[%39] has invalid branch to block 44[%44] (not another case construct, corresponding merge, outer loop merge or outer loop continue)
  %39 = OpLabel

I did not try to reduce the spirv-opt flags, in case (as with #2450) there may be an issue both with the optimizer generating invalid code and the validator not picking this up soon enough.

Found using [GraphicsFuzz](http://github.com/google/graphicsfuzz)

**Comment by alan-baker** [comment]
Problem manifests after the first dead code elimination.

**Comment by alan-baker** [comment]
After an initial inspection it seems there may be both an optimizer and a validator bug at play here. The optimizer is producing a reachable OpUnreachable, but it seems like the validator should not error with the particular error it does produce.

**Comment by alan-baker** [comment]
The validator says any block terminated by OpUnreachable is unreachable and the case validation uses that predicate during switch validation which is why it errors out in an odd manner. Probably would be good to have a real unreachable validation check.
