### ISSUE TITLE
reduce: segfault caused by StructuredLoopToSelectionReductionOpportunity querying dominance information for instructions that are not within blocks

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2457]
[Files to reproduce the problem](https://github.com/KhronosGroup/SPIRV-Tools/files/2968976/to_file_to_spirv_reduce.zip)

Running:

spirv-reduce to_reduce.spv ./interesting.py

leads to a spirv-reduce segfault.

The interestingness test depends on a spirv-opt/spirv-val bug, which is present in SPIRV-Tools revision 5186ffedb37eca08ab97a9811078c7b6a59c70f0

Found using [GraphicsFuzz](http://github.com/google/graphicsfuzz).  I love how [fuzzers and reducers fuzz themselves](https://medium.com/@afd_icl/fuzzing-fuzzers-reducing-reducers-and-shrinking-shrinkers-ac4b128c9efa).

**Comment by paulthomson** [comment]
`StructuredLoopToSelectionReductionOpportunity::FixNonDominatedIdUses` considers every instruction in the function being modified and tries to fix dominance by checking the dominance of all uses. Unfortunately, some of these "uses" can be OpDecorate instructions that are outside of blocks, which causes a segfault.
