### ISSUE TITLE
spirv-opt assertion "GetBaseAddress should only be called on instructions that take a pointer or image"

### ISSUE THREAD

**Issue by fjhenigman** [KhronosGroup/SPIRV-Tools#2458]
spirv-opt --skip-validation -O -o out bug.spv

source/opt/instruction.cpp:163: spvtools::opt::Instruction* spvtools::opt::Instruction::GetBaseAddress() const: Assertion `(IsLoad() || opcode() == SpvOpStore || opcode() == SpvOpAccessChain || opcode() == SpvOpPtrAccessChain || opcode() == SpvOpInBoundsAccessChain || opcode() == SpvOpCopyObject || opcode() == SpvOpImageTexelPointer) && "GetBaseAddress should only be called on instructions that take a " "pointer or image."' failed.

[bug.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2969159/bug.txt)

**Comment by alan-baker** [comment]
What's happens without --skip-validation? Is there a reason don't perform validation?

**Comment by fjhenigman** [comment]
Same thing.  Shader was previously validated, that's why --skip-validation.

**Comment by s-perron** [comment]
Looks like ADCE is calling `GetBaseAddress` when variable pointers are turned on.  I don't think that ADCE works correctly when there are variable pointers.  I'll have to look at that more carefully.
