### ISSUE TITLE
When creating initializers for WebGPU try to use first stored value

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/SPIRV-Tools#2468]
For #2387, the simplest suggestion of just adding a null initializer is being done for the cases that are missing an initializer. This will produce correct code, but not necessarily optimal code. For cases in which a constant value is stored to the variable before any usage, initializing to that value would remove an instruction from the emitted code. This may introduce significant complexity to the implemention, so has been broken out into its own issue to be implemented later.

**Comment by zoddicus** [comment]
This seems non-trivial to implement correctly, for what may not being a significant gain. I am going to put this on the back burner until we have evidence suggesting the current transformation's code needs optmization.

**Comment by Trass3r** [comment]
Can one rely on dead store elimination in the backends?

**Comment by dneto0** [comment]
> Can one rely on dead store elimination in the backends?

Yes, most driver shader compilers are very sophisticated, and they should be able to clean up the code.
