### ISSUE TITLE
StorageImageWriteWithoutFormat and OpenCL image writes

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/SPIRV-Tools#2470]
Trying to validate the following module built from OpenCL C via the [SPIRV-LLVM-Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator):

```
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 15
; Schema: 0
               OpCapability Addresses
               OpCapability Kernel
               OpCapability ImageBasic
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %5 "test"
         %14 = OpString "kernel_arg_type.test.image2d_t,"
               OpSource OpenCL_C 100000
               OpName %img "img"
               OpName %entry "entry"
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
       %void = OpTypeVoid
          %3 = OpTypeImage %void 2D 0 0 0 0 Unknown WriteOnly
          %4 = OpTypeFunction %void %3
     %v2uint = OpTypeVector %uint 2
     %v4uint = OpTypeVector %uint 4
         %10 = OpConstantNull %v2uint
         %13 = OpConstantComposite %v4uint %uint_1 %uint_1 %uint_1 %uint_1
          %5 = OpFunction %void None %4
        %img = OpFunctionParameter %3
      %entry = OpLabel
               OpImageWrite %img %10 %13
               OpReturn
               OpFunctionEnd
```

I'm getting the following:

```
error: line 23: Capability StorageImageWriteWithoutFormat is required to write to storage image
  OpImageWrite %img %10 %13
```

Looking at the SPIR-V spec, it seems `StorageImageWriteWithoutFormat` implicitly declares `Shader`. Which is correct, the validator or the spec?

**Comment by alan-baker** [comment]
The grammar matches the spec so I feel the spec needs a tweak to accomodate kernels (likely not requiring StorageImageWriteWithoutFormat).

**Comment by dneto0** [comment]
Right.  

OpenCL 2.2's environment spec says that OpTypeImage must use Format of Unknown. https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_Env.html 

So it looks like this rule in SPIR-V OpImageWrite must be pushed out to the Vulkan and OpenGL specs:

> The Image Format must not be Unknown, unless the StorageImageWriteWithoutFormat Capability was declared.

I recommend we weaken the validator now and file a SPIR-V spec issue.

**Comment by dneto0** [comment]
I filed spec issue https://gitlab.khronos.org/spirv/SPIR-V/issues/451

**Comment by kpet** [comment]
@dneto0 Thanks!
