### ISSUE TITLE
Update documentation on how to build with sanitizers

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2482]
The README says that SPIRV_USE_SANITIZER=<sanitizer> enables sanitizers.  However, I found that SPIRV_USE_SANITIZER=address was not enough to build with asan - it led to link errors.

This worked, however:

-DCMAKE_CXX_FLAGS=-fsanitize=address -DCMAKE_C_FLAGS=-fsanitize=address

Unless this turns out to be a problem with my setup, the README should be updated or SPIRV_USE_SANITIZER fixed.

**Comment by dj2** [comment]
Which target did the build fail on? I _think_ it should work without having to add -fsanitize yourself, but it seems like something went wrong.

**Comment by afd** [comment]
It failed on spirv-cfg.  Here is an excerpt from the build log.  You can see that e.g. spirv-opt build successfully:

Scanning dependencies of target spirv-tools-shared-pkg-config
[  0%] Built target spirv-tools-shared-pkg-config
Scanning dependencies of target spirv-tools-pkg-config
[  0%] Built target spirv-tools-pkg-config
Scanning dependencies of target re2
[  0%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/bitstate.cc.o
[  1%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/compile.cc.o
[  1%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/dfa.cc.o
[  1%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/filtered_re2.cc.o
[  1%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/mimics_pcre.cc.o
[  1%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/nfa.cc.o
[  1%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/onepass.cc.o
[  2%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/parse.cc.o
[  2%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/perl_groups.cc.o
[  2%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/prefilter.cc.o
[  2%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/prefilter_tree.cc.o
[  2%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/prog.cc.o
[  2%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/re2.cc.o
[  3%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/regexp.cc.o
[  3%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/set.cc.o
[  3%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/simplify.cc.o
[  3%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/stringpiece.cc.o
[  3%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/tostring.cc.o
[  3%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/unicode_casefold.cc.o
[  4%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/re2/unicode_groups.cc.o
[  4%] Building CXX object external/effcee/third_party/re2/CMakeFiles/re2.dir/util/rune.cc.o
...
[ 19%] Building CXX object source/CMakeFiles/SPIRV-Tools-shared.dir/val/instruction.cpp.o
[ 19%] Building CXX object source/CMakeFiles/SPIRV-Tools-shared.dir/val/validation_state.cpp.o
[ 19%] Building CXX object source/CMakeFiles/SPIRV-Tools-shared.dir/util/timer.cpp.o
[ 19%] Linking CXX shared library libSPIRV-Tools-shared.so
[ 19%] Built target SPIRV-Tools-shared
Scanning dependencies of target SPIRV-Tools
[ 19%] Building CXX object source/CMakeFiles/SPIRV-Tools.dir/util/bit_vector.cpp.o
[ 19%] Building CXX object source/CMakeFiles/SPIRV-Tools.dir/util/parse_number.cpp.o
[ 19%] Building CXX object source/CMakeFiles/SPIRV-Tools.dir/util/string_utils.cpp.o
...
[ 45%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/vector_dce.cpp.o
[ 45%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/workaround1209.cpp.o
[ 45%] Linking CXX static library libSPIRV-Tools-opt.a
[ 45%] Built target SPIRV-Tools-opt
Scanning dependencies of target SPIRV-Tools-reduce
[ 45%] Building CXX object source/reduce/CMakeFiles/SPIRV-Tools-reduce.dir/change_operand_reduction_opportunity.cpp.o
[ 50%] Built target SPIRV-Tools-link
Scanning dependencies of target spirv-cfg
[ 51%] Building CXX object tools/CMakeFiles/spirv-cfg.dir/cfg/cfg.cpp.o
[ 51%] Building CXX object tools/CMakeFiles/spirv-cfg.dir/cfg/bin_to_dot.cpp.o
[ 51%] Linking CXX executable spirv-cfg
CMakeFiles/spirv-cfg.dir/cfg/cfg.cpp.o: In function `main':
/data/afd-SPIRV-Tools/tools/cfg/cfg.cpp:49: undefined reference to `__asan_option_detect_stack_use_after_return'
/data/afd-SPIRV-Tools/tools/cfg/cfg.cpp:49: undefined reference to `__asan_stack_malloc_4'
/data/afd-SPIRV-Tools/tools/cfg/cfg.cpp:54: undefined reference to `__asan_report_load8'
...
