### ISSUE TITLE
master-tot isn't building

### ISSUE THREAD

**Issue by allanmac** [KhronosGroup/SPIRV-Tools#2517]
The [master-tot](https://github.com/KhronosGroup/SPIRV-Tools/releases/tag/master-tot) ~branch~ tag isn't up to date.

Master ToT:
```
spirv-dis --version
SPIRV-Tools v2018.5-dev a3e3869540b7c2d2f01c846fc76453be55d1ac34
Target: SPIR-V 1.3
```
Vulkan 1.1.101.0 SDK:
```
...\vulkansdk\1.1.101.0\bin\spirv-dis --version
SPIRV-Tools v2019.2 v2019.1-82-g5994ae2a
Target: SPIR-V 1.3
```

**Comment by dj2** [comment]
That branch should probably be deleted. Use master instead. @dneto0

**Comment by allanmac** [comment]
> That branch should probably be deleted. Use master instead. @dneto0

Typo by me.  It's a tag.  

Master ToT is useful because it provides prebuilt releases.

**Comment by svenvh** [comment]
The last master-tot build was on a3e3869, which is a few commits before 6e550f41 ("Disable Travis bots, and Appveyor Release bots.", 2018-07-10).

@ehsannas , would it be possible to publish the build artifacts in a similar fashion as Travis did?

**Comment by ehsannas** [comment]
You can now download prebuilt binaries for Windows, Linux, and macOS. See ['Downloads' section in the README](https://github.com/KhronosGroup/SPIRV-Tools#downloads).
