### ISSUE TITLE
Spirv-opt generates code which loads whole OpTypeRuntimeArray

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/SPIRV-Tools#2520]
This comes from CTS tests (https://github.com/KhronosGroup/VK-GL-CTS), with following command line: 
`deqp-vk.exe --deqp-optimize-spirv=disable --deqp-optimization-recipe=1 -n dEQP-VK.ssbo.layout.random.unsized_arrays.0`

This runs the GLSL-based test, where shader is compiled using glslang and than optimized using SPIRV-Tools. 

The code genarated by spirv-opt is not valid, as it contains OpLoad which loads whole runtime array, of unbounded size. 

The SPIR-V specification says: 

> OpLoad
> 
> Load through a pointer.
> 
> Result Type is the type of the loaded object. It must be a type with fixed size; i.e., **it cannot be, nor include, any OpTypeRuntimeArray types**.

Consider following GLSL source:  

```
layout(std430, row_major, binding = 4) buffer BlockE
{
	highp mat3 k;
	bvec2 l[3];
	lowp vec3 m;
	bool n;
	mediump mat3 o[];
} blockE;
...
allOk = allOk &amp;&amp; compare_mat3(blockE.o[0], mat3(1.0, 2.0, 4.0, -5.0, 3.0, 1.0, -7.0, 9.0, -2.0));
``` 

All accesses to blockE members are compiled by glslang as loading from pointers to the members: 

```
%363 = OpAccessChain %362 %353 %188
%364 = OpLoad %35 %363
...
%383 = OpAccessChain %382 %353 %371 %178
%384 = OpLoad %42 %383
...
400 = OpAccessChain %382 %353 %371 %188
%401 = OpLoad %42 %400
```

spirv-opt translates this code to single OpLoad on entire structure:

```
%350 = OpTypeRuntimeArray %42
%351 = OpTypeStruct %349 %35 %35 %177 %350
%352 = OpTypePointer Uniform %351
%353 = OpVariable %352 Uniform
%3427 = OpLoad %351 %353
```

The problem is `%351` contains `%350` - which is of OpTypeRuntimeArray type.

**Comment by s-perron** [comment]
My guess is that this is a problem with the common-uniform-elimination pass.  That is a pass that @greg-lunarg maintains.  Besides this, we know it causes problems (#946).  Greg, can you take a look?

In the meantime, I would recommend using  `--deqp-optimization-recipe=7`.  This includes the latest optimizations, and removes common-uniform-elimination.

**Comment by greg-lunarg** [comment]
See my comments for #2521

**Comment by scyganINTEL** [comment]
Given the comment in #2521, I am going to propose removal of 'common-uniform-elimination' from CTS.

**Comment by s-perron** [comment]
@greg-lunarg Are you working on this?

**Comment by s-perron** [comment]
@greg-lunarg Any update?

**Comment by greg-lunarg** [comment]
I will try to get this done in the next day or so. Thanks!
