### ISSUE TITLE
HLSL legalization for isomorphic function parameter

### ISSUE THREAD

**Issue by jaebaek** [KhronosGroup/SPIRV-Tools#2535]
It would be great if HLSL legalization handled function parameter passing where the argument is actually isomorphic to the parameter but their types are not the same.

For the following HLSL code,

```
struct R {
  int a;
  void incr() { ++a; }
};

void decr(inout R b) {
  b.a--;
}

RWStructuredBuffer<R> rwsb;

void main() {
  rwsb[0].incr();
  decr(rwsb[0]);
}
```

DXC generates the following SPIR-V code for calling `rwsb[0].incr();` and `decr(rwsb[0]);`
```
               OpMemberDecorate %R 0 Offset 0
...
          %R = OpTypeStruct %int
        %R_0 = OpTypeStruct %int
%_ptr_Function_R_0 = OpTypePointer Function %R_0
%_ptr_Uniform_R = OpTypePointer Uniform %R
       %rwsb = OpVariable %_ptr_Uniform_type_RWStructuredBuffer_R Uniform
...
 %temp_var_R = OpVariable %_ptr_Function_R_0 Function
%param_var_b = OpVariable %_ptr_Function_R_0 Function
         %26 = OpAccessChain %_ptr_Uniform_R %rwsb %int_0 %uint_0
         %27 = OpLoad %R %26
         %28 = OpCompositeExtract %int %27 0
         %29 = OpCompositeConstruct %R_0 %28
               OpStore %temp_var_R %29
         %30 = OpFunctionCall %void %R_incr %temp_var_R
         %32 = OpLoad %R_0 %temp_var_R
         %33 = OpCompositeExtract %int %32 0
         %34 = OpCompositeConstruct %R %33
               OpStore %26 %34
         %35 = OpAccessChain %_ptr_Uniform_R %rwsb %int_0 %uint_0
         %36 = OpLoad %R %35
         %37 = OpCompositeExtract %int %36 0
         %38 = OpCompositeConstruct %R_0 %37
               OpStore %param_var_b %38
         %39 = OpFunctionCall %void %decr %param_var_b
         %41 = OpLoad %R_0 %param_var_b
         %42 = OpCompositeExtract %int %41 0
         %43 = OpCompositeConstruct %R %42
               OpStore %35 %43
```

After fixing #2430, the reason why we cannot directly pass
- `%26 = OpAccessChain %_ptr_Uniform_R %rwsb %int_0 %uint_0` to `%R_incr`
- `%35 = OpAccessChain %_ptr_Uniform_R %rwsb %int_0 %uint_0` to `%decr`
because `%R` and `%R_0` are different types.

It would be nice if HLSL legalization checked isomorphism between the parameter type and the argument type and handled it.

We need two steps for this:

- [ ] spirv-val allows a function argument that is different from the parameter type but they are isomorphic when `--relax-logical-pointer` option is enabled.
- [x] spirv-opt HLSL legalization handles it.

[test.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3108590/test.txt) is the full SPIR-V code for the HLSL code.

**Comment by greg-lunarg** [comment]
Why piggy-back the spirv-val behavior on --relax-logical-pointer? Would it be better to create a new option, something like --allow-isomorphic-types?

**Comment by s-perron** [comment]
Thanks for the suggestion Greg.  We were thinking of using `relax-logical-pointer` because it still falls under the use of pointers.  We are allowing the mismatch of what pointer is expected and what is actually give as long as the types are isomorphic and the decorations of the actual type are a superset of the expected type.

However, we do not plan on allowing a mismatch of non pointer types.

**Comment by s-perron** [comment]
@greg-lunarg If you have a particular reason to separate the two let us know.  We are not tied to a specific implementation.  I can see how the name of the option is not very informative.

**Comment by s-perron** [comment]
For now I will work on extending the fix up storage class pass to also fix up the type.  This is more work because the change in type can propagate through a lot more instructions.

**Comment by jaebaek** [comment]
I want to share three examples that need the legalization.
See attachments (*.hlsl.txt contain hlsl code and the corresponding *.spv.txt contain SPIR-V code compiled by each of them)

[cs.groupshared.function-param.out.hlsl.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3128619/cs.groupshared.function-param.out.hlsl.txt)
[cs.groupshared.function-param.out.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3128620/cs.groupshared.function-param.out.spv.txt)
[cs.groupshared.struct-function.hlsl.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3128621/cs.groupshared.struct-function.hlsl.txt)
[cs.groupshared.struct-function.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3128622/cs.groupshared.struct-function.spv.txt)
[fn.param.isomorphism.hlsl.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3128623/fn.param.isomorphism.hlsl.txt)
[fn.param.isomorphism.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3128624/fn.param.isomorphism.spv.txt)
