### ISSUE TITLE
example won't run

### ISSUE THREAD

**Issue by clouds56** [KhronosGroup/SPIRV-Tools#2538]
showing the error:
```
error: No OpEntryPoint instruction was found. This is only allowed if the Linkage capability is being used.
```

according to the [specific](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_universal_validation_rules)

> There is at least one OpEntryPoint instruction, unless the Linkage capability is being used.

I think we could get the example update

**Comment by dj2** [comment]
Which example are you trying to run and how are you running it?

**Comment by clouds56** [comment]
this one, https://github.com/KhronosGroup/SPIRV-Tools/blob/master/examples/cpp-interface/main.cpp
```
cc -o test main.cpp -std=c++11 -lSPIRV-Tools -lSPIRV-Tools-link -lSPIRV-Tools-opt -lc++
./test
```
