### ISSUE TITLE
Revisit whitelist extesions

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#2553]
SPIR-V 1.4 pulled SPV_KHR_shader_float_controls and SPV_KHR_no_integer_wrap_decorations into core. If these were not supported by passes previously, then those passes should also bail based on the added capabilities.

Additionally, it is probably worth doing a once over of whitelisted extensions.

**Comment by s-perron** [comment]
None of the passes with an allows list will fail because of these capabilities, even if they did not explicitly allow those extensions.
