### ISSUE TITLE
Allow spirv-fuzz to generate a dead break from the back-edge block of a loop

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2577]
At present SPIR-V fuzz does not consider generating a dead break from a loop's continue construct to the loop's merge block, as this is usually illegal.  But it is legal if the block being broken from is the loop's back edge block.  It would be good to extend the tool to allow for this case.

**Comment by paulthomson** [comment]
@andreperezmaselco This could be an interesting issue

**Comment by andreperezmaselco** [comment]
Interesting @paulthomson.
I'll try that after the inline transformation.
