### ISSUE TITLE
Segmentation fault when applying spirv-opt to a shader that performs and out-of-bounds access

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2609]
I expect this is closely related to #2608 but am filing it in addition as the symptoms are different.

[This archive](https://github.com/KhronosGroup/SPIRV-Tools/files/3201632/files.zip) contains the files required to reproduce the problem.

To reproduce, do:

spirv-opt -O small.spv -o temp.spv

I get a segmentation fault in `spvtools::opt::Instruction::result_id()`.

The .frag file exhibits and out-of-bounds access: a is an int[1], and a[i] attempts to index v at 1.

As in #2608, I am unsure what the semantics of out-of-bounds accesses are in SPIR-V, but I note that an OpAccessChain, rather than an OpInBoundsAccessChain, is used; I would assume that the existence of OpInBoundsAccessChain means that OpAccessChain is supposed to account for the out-of-bounds case.

Found via [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by dnovillo** [comment]
@s-perron I can take a look at this one.

**Comment by dnovillo** [comment]
Working on this today (finally).
