### ISSUE TITLE
SPIR-V optimizer breaks multiple ANGLE tests

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/SPIRV-Tools#2612]
See this change enabling SPIR-V optimization in ANGLE (currently using SPIRV-Tools commit 47741f05043ad880f1964e0c2a8b6733232feaab):

https://chromium-review.googlesource.com/c/angle/angle/+/1616963

Notice the various failures on different platforms. Some of these failures are due to invalid SPIR-V generated (see e.g. `dEQP.GLES3/functional_shaders_switch_conditional_fall_through_2_static_vertex` failing [here](https://chromium-swarm.appspot.com/task?id=44f3e9d908a3c610)), some are just failures due to SPIR-V change in functionality.

I debugged one such case, `CopyTexImageTest.RGBAToL/ES2_Vulkan` end2end test failing on Android and see this:

Original shader (in `src/libANGLE/renderer/vulkan/shaders/src/ImageCopy.frag`) after preprocessing is the following:

```
#version 450 core

#extension GL_EXT_samplerless_texture_functions : require

layout(set = 0, binding = 0)uniform texture2D src;
layout(location = 0)out vec4 dest;

layout(push_constant)uniform PushConstants {

    ivec2 srcOffset;
    ivec2 destOffset;
    int srcMip;
    int srcLayer;

    bool flipY;

    bool premultiplyAlpha;
    bool unmultiplyAlpha;

    bool destHasLuminance;
    bool destIsAlpha;

    int destDefaultChannelsMask;
} params;

void main()
{
    ivec2 destSubImageCoords = ivec2(gl_FragCoord . xy)- params . destOffset;

    ivec2 srcSubImageCoords = destSubImageCoords;

    if(params . flipY)
        srcSubImageCoords . y = - srcSubImageCoords . y;

    vec4 srcValue = texelFetch(src, params . srcOffset + srcSubImageCoords, params . srcMip);

    if(params . premultiplyAlpha)
    {
        srcValue . rgb *= srcValue . a;
    }
    else if(params . unmultiplyAlpha && srcValue . a > 0)
    {
        srcValue . rgb /= srcValue . a;
    }

    vec4 destValue = vec4(srcValue);

    if(params . destHasLuminance)
    {
        destValue . rg = destValue . ra;
    }
    else if(params . destIsAlpha)
    {
        destValue . r = destValue . a;
    }
    else
    {
        int defaultChannelsMask = params . destDefaultChannelsMask;
        if((defaultChannelsMask & 2)!= 0)
        {
            destValue . g = 0;
        }
        if((defaultChannelsMask & 4)!= 0)
        {
            destValue . b = 0;
        }
        if((defaultChannelsMask & 8)!= 0)
        {
            destValue . a = 1;
        }
    }

    dest = destValue;
}
```

Reading back the shader with renderdoc, without optimization we have:

```
SPIR-V 1.0:

Glslang Reference Front End from Khronos (Contact John Kessenich, johnkessenich@google.com) - version 0x0007
IDs up to {153}

Source is GLSL 450
 + GL_EXT_samplerless_texture_functions

Capabilities: Shader
Entry point 'main' (Fragment)
            OriginUpperLeft

struct PushConstants {
  int2 srcOffset;
  int2 destOffset;
  int srcMip;
  int srcLayer;
  uint flipY;
  uint premultiplyAlpha;
  uint unmultiplyAlpha;
  uint destHasLuminance;
  uint destIsAlpha;
  int destDefaultChannelsMask;
}; // struct PushConstants

UniformConstant DescSet=0 Bind=0 Image2D<float>* src;
Input float4* gl_FragCoord = FragCoord;
Output Location=0 float4* dest;
PushConstant PushConstants* params;

void main() {
  int* defaultChannelsMask;

  int2* srcSubImageCoords = ConvertFToS(gl_FragCoord.xy) - params.destOffset;
  if(params.flipY != 0) {
    srcSubImageCoords.y = -srcSubImageCoords.y;
  }
  float4* srcValue = ImageFetch(src, params.srcOffset + srcSubImageCoords, LOD = params.srcMip);
  if(params.premultiplyAlpha != 0) {
    srcValue = float4((srcValue.xyz * srcValue.w).xyz, srcValue.w);
  } else {
    bool _80_ = params.unmultiplyAlpha != 0;
    if(_80_) {
      bool _86_ = srcValue.w > 0.0f;
    }
    if(Phi(_80_, _86_)) {
      srcValue = float4((srcValue.xyz / float3(srcValue.w)).xyz, srcValue.w);
    }
  }
  float4* destValue = float4(srcValue.xyzw);
  if(params.destHasLuminance != 0) {
    destValue = float4(destValue.xw.xy, destValue.zw);
  } else if(params.destIsAlpha != 0) {
    destValue.x = destValue.w;
  } else {
    defaultChannelsMask = params.destDefaultChannelsMask;
    if((defaultChannelsMask & 2) != 0) {
      destValue.y = 0.0f;
    }
    if((defaultChannelsMask & 4) != 0) {
      destValue.z = 0.0f;
    }
    if((defaultChannelsMask & 8) != 0) {
      destValue.w = 1.0f;
    }
  }
  dest = destValue;
} // main
```

With optimization we have:

```
SPIR-V 1.0:

Glslang Reference Front End from Khronos (Contact John Kessenich, johnkessenich@google.com) - version 0x0007
IDs up to {177}

Source is GLSL 450
 + GL_EXT_samplerless_texture_functions

Capabilities: Shader
Entry point 'main' (Fragment)
            OriginUpperLeft

struct PushConstants {
  int2 srcOffset;
  int2 destOffset;
  int srcMip;
  int srcLayer;
  uint flipY;
  uint premultiplyAlpha;
  uint unmultiplyAlpha;
  uint destHasLuminance;
  uint destIsAlpha;
  int destDefaultChannelsMask;
}; // struct PushConstants

UniformConstant DescSet=0 Bind=0 Image2D<float>* src;
Input float4* gl_FragCoord = FragCoord;
Output Location=0 float4* dest;
PushConstant PushConstants* params;

void main() {
  int2 _26_ = ConvertFToS(gl_FragCoord.xy) - params.destOffset;
  if(params.flipY != 0) {
    int2 _155_ = _26_; _155_.y = (-_26_.y);
  }
  int2 _168_ = Phi(_26_, _155_);
  int2 _54_ = params.srcOffset + _168_;
  float4 _59_ = ImageFetch(src, _54_, LOD = params.srcMip);
  if(params.premultiplyAlpha != 0) {
    float _69_ = _59_.w;
    float3 _72_ = _59_.xyz;
    float3 _73_ = _72_ * _69_;
    float4 _75_ = float4(_73_.xyz, _59_.w);
  } else {
    bool _80_ = params.unmultiplyAlpha != 0;
    if(_80_) {
      float _84_ = _59_.w;
      bool _86_ = _84_ > 0.0f;
    }
    if(Phi(_80_, _86_)) {
      float3 _93_ = _59_.xyz;
      float3 _94_ = float3(_91_);
      float3 _95_ = _93_ / _94_;
      float4 _97_ = float4(_95_.xyz, _59_.w);
    }
    float4 _171_ = Phi(_59_, _97_);
  }
  float4 _170_ = Phi(_75_, _171_);
  if(params.destHasLuminance != 0) {
    float4 _114_ = _170_.xwzw;
  } else if(params.destIsAlpha != 0) {
    float4 _161_ = _170_; _161_.x = _170_.w;
  } else if((params.destDefaultChannelsMask & 2) != 0) {
    float4 _163_ = _170_; _163_.y = 0.0f;
  }
  float4 _172_ = Phi(_170_, _163_);
if((params.destDefaultChannelsMask & 4) != 0) {
    float4 _165_ = _172_; _165_.z = 0.0f;
  }
  float4 _173_ = Phi(_172_, _165_);
if((params.destDefaultChannelsMask & 8) != 0) {
    float4 _167_ = _173_; _167_.w = 1.0f;
  }
  float4 _176_ = Phi(_173_, _167_);
  float4 _175_ = Phi(_161_, _176_);
  dest = Phi(_114_, _175_);
} // main
```

A difference in functionality that I notice is the three `if`s inside the last `else`. The last 2 of those `if`s have been moved outside the `else` in the optimized version.

There are possibly other bugs present as well. Please let me know if you need instructions on how to setup ANGLE for testing, and I'd gladly work with you to resolve all the optimizer bugs that are affecting us.

**Comment by greg-lunarg** [comment]
FWIW, I am triaging this, trying to narrow down pass and commit. I am not seeing this with the latest stable.

**Comment by greg-lunarg** [comment]
I am also not seeing this at spirv-tools TOT.

**Comment by greg-lunarg** [comment]
I am also not seeing this at the previous stable. I must not be using the correct recipe. I will let Stephen give it a try.

**Comment by ShabbyX** [comment]
@greg-lunarg, can you try this commit? 47741f05043ad880f1964e0c2a8b6733232feaab

**Comment by greg-lunarg** [comment]
Found something:

glslangValidator.exe -DSrcIsFloat=1 -DDestIsFloat=1 -V -Od --variable-name kImageCopy_frag -o t2.frag.Od.spv t2.frag

creates invalid SPIR-V in t2.frag.Od.spv with top of tree glslang.

Note that I have turned off spirv-opt with -Od. So this seems to be a glslangValidator problem.

When spirv-opt is invoked from glslangValidator, the validation of the SPIR-V that is normally done by spirv-opt is disabled, which is likely why you were not seeing the problem sooner.

**Comment by s-perron** [comment]
It took me all day, but I am able to reproduce the error in the angle test.  It seems like the VulkanSDK causes validation layers to be overridden.  I had to do `export DISABLE_VK_LAYER_LUNARG_override=1` before running the tests to get the validation layers set up correctly.

**Comment by s-perron** [comment]
I've tracked down the problem and this is a known issue in glslang.  It does not handle breaks from switches correctly.  See https://github.com/KhronosGroup/glslang/issues/1635.

In this case the code for the vertex shader given below.  Notice the case 3 just before the default case.  That is the cause of the incorrect code from glslang.  I think it passes without optimization because it is something that has been generated for a while, and driver accept it.  However, when it is changed by spirv-opt, which will generate uncommon patterns, it is flagged as an error.

```
#version 450 core
struct ANGLEDepthRangeParams {
float near;
float far;
float diff;
float dummyPacker;
};
layout(location = 0)in vec4 _ua_position;
layout(location = 1)in vec4 _ua_coords;
layout(location = 0)out vec4 _uv_color;
layout(std140, set = 0, binding = 0)uniform ANGLEUniformBlock{
vec4 viewport;
float halfRenderAreaHeight;
float viewportYScale;
float negViewportYScale;
float padding;
ANGLEDepthRangeParams depthRange;
} ANGLEUniforms;

#ifdef ANGLE_ENABLE_LINE_SEGMENT_RASTERIZATION
layout(location = 2)out vec4 ANGLEPosition;

#endif
void main(){
(gl_Position = _ua_position);
vec4 _ucoords = _ua_coords;
vec3 _ures = vec3(0.0, 0.0, 0.0);
vec4 _utmp = _ucoords;
int _uc = 2;
switch (_uc) {
case (0):
(_ures = _ucoords.xyz);
break;
case (1):
(_ures = _ucoords.wzy);
break;
case (2):
(_uc += 2);
(_utmp = _ucoords.yzwx);
case (3):
(_ures = vec3(_utmp));
if ((_uc == 4))
{
break;
}
default:
(_ures = _utmp.zyx);
break;
}
(_uv_color = vec4(_ures, 1.0));

#ifdef ANGLE_ENABLE_LINE_SEGMENT_RASTERIZATION
(ANGLEPosition = gl_Position);

#endif
(gl_Position.z = ((gl_Position.z + gl_Position.w) * 0.5));
}
```

**Comment by s-perron** [comment]
As for the odd code post in the original comment.  I believe renderdoc is generating incorrect code from the spir-v.

The reason I think this is true is because the phi instructions do not make any sense given the CFG.  Look at this snippet of code:

```
  float4 _176_ = Phi(_173_, _167_);
  float4 _175_ = Phi(_161_, _176_);
  dest = Phi(_114_, _175_);
```

There are 3 Phi instruction that all reference each other.   If they were in the same basic block, this would be illegal in many ways.  However, the spir-v that is generated passes the validator (spirv-val).  When I take the spir-v and run it through spirv-cross,  the output is correct.  I have attached the output from spri-v-cross.

[ImageCopy.frag.00000000.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3209044/ImageCopy.frag.00000000.txt)

**Comment by ShabbyX** [comment]
@johnkslang regarding incorrect shader code generated from SPIR-V in this issue.

**Comment by s-perron** [comment]
I've discussed this with others.  In the past couple weeks, it was decided that the "break from switch" is legal.  The spir validator has been updated to accept it: 60aaafbc70e051e2c23b60edfe9251e6a4def1ad.

I am not sure about the validation layers.

**Comment by s-perron** [comment]
The validation layers are not a problem.  They call spirv-val for this type of check, so, with an updated spir-val, the validation layers will not be a problem.

The next problem to deal with is an error in dead-branch-elimination in spirv-opt.  It is folding switches when there is a branch to its merge block from a nested construct.  This leaves invalid code because the original merge block is no longer a merge block.

**Comment by s-perron** [comment]
Here is an update on where I stand.  I ran all of the tests in  `angle_deqp_gles3_tests` with my change.  The test case mentioned above passes.  However, I still see 42 failures when I run on my desktop.

I'm trying to look into those.  So far I have looked at `dEQP.GLES3/functional_shaders_functions_control_flow_return_in_loop_if_fragment` and `dEQP.GLES3/functional_shaders_arrays_constructor_bool_mat3_vertex`.  The spir-v looks correct for both of those.  I cannot pick out where the error is.

I will update as I look at other failures.

**Comment by s-perron** [comment]
It seems like all of the failures fall into three groups.  36 tests fails when the ssa rewriter is turned on.  The spir-v looks correct.  One example of this is `dEQP.GLES3/functional_shaders_functions_control_flow_return_in_loop_if_fragment`.

There are 4 tests that all use boolean matrices, and they all fail.  One example is `dEQP.GLES3/functional_shaders_arrays_constructor_bool_mat3_vertex`.

There are two that fail for me even without any optimizations turned on.  One example of this is `dEQP.GLES3/functional_ubo_random_nested_structs_arrays_instance_arrays_18`.

**Comment by s-perron** [comment]
@ShabbyX Where do we stand with this issue?  Can we close it yet?

**Comment by ShabbyX** [comment]
Indeed, the remaining failures all seem to be driver bugs. I have yet to triage the failures on Android though, so let's keep this open for a while longer. Chances are, those are driver bugs as well, but I want to be sure.

**Comment by ShabbyX** [comment]
The failing tests pass on recent Qualcomm drivers, so going to close this. Thanks for looking into these.
