### ISSUE TITLE
Does the linker currently support combining shaders into one file?

### ISSUE THREAD

**Issue by JoshKlint** [KhronosGroup/SPIRV-Tools#2632]
I am interested in combining multiple SPIR-V files from different shader stages into a single SPV file for Vulkan. One shader / one file is a nice neat paradigm. Is this currently supported by the linker tool, with everything Vulkan needs to load it successfully?

**Comment by pierremoreau** [comment]
As far as I know, there shouldn’t be anything preventing the linker from merging multiple Vulkan SPIR-V files into a single one; I have successfully used it to merge simple vertex and fragment shaders into a single file.

**Comment by JoshKlint** [comment]
Thanks, I have not tried it yet but it sounds like it will do what I want.

**Comment by JoshKlint** [comment]
It works perfectly and the loaded module works in Vulkan.

Currently, I am renaming the shader main() functions to main_vert and main_frag, and using those in my Vulkan code as the entry points for the different stages. Is there any way I can detect the loaded entry points in a shader module? It would be nice to have a convention where one single .spv file equals one shader with no special customizations or formats.

**Comment by pierremoreau** [comment]
For SPIR-V reflection, you can use https://github.com/KhronosGroup/SPIRV-Cross, or simply parse the `OpEntryPoint` instructions from the SPIR-V module.
Note that having a vertex shader entry point called “foo” and a fragment shader entry point also called “foo” is perfectly legal in SPIR-V, so you don’t need to rename them as “main_vert” and “main_frag” but can keep both as “main”.

**Comment by JoshKlint** [comment]
I tried leaving both entry point names to "main:" and it worked fine, in both the linker and when loaded in Vulkan. So I really just need to detect what stages are present in the SPIR-V file.

**Comment by pierremoreau** [comment]
So for that, either parse the SPIR-V module yourself (you only need to handle the [`OpEntryPoint`](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpEntryPoint) instructions), or use [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross) to retrieve them via their [`get_entry_points_and_stages()`](https://github.com/KhronosGroup/SPIRV-Cross/wiki/Reflection-API-user-guide#query-entry-points) method.

**Comment by JoshKlint** [comment]
I have a quick and dirty parser here:
`		auto stream = ReadFile(L"Shaders/default.spv");

		// Parse SPIR-V data
		Assert(stream->ReadInt() == 0x07230203);
		int version = stream->ReadInt();
		int genmagnum = stream->ReadInt();
		int bound = stream->ReadInt();
		int reserved = stream->ReadInt();

		// Instruction stream
		while (stream->Ended() == false)
		{
			unsigned int bytes = stream->ReadUInt();
			int wordcount = (bytes >> 8) & 0xff;
			int opcode = bytes & 0xff;
			if (opcode == 15)
			{
				int f = 3;
			}
			Print(opcode);
			Print(wordcount);
			Print("");
			stream->Seek(stream->GetPos() + wordcount * 4);
		}`

I'm having trouble making sense of the documentation. I think I just need to find the right opcode and read a couple of values to detect what stage is indicated.

**Comment by JoshKlint** [comment]
I got it. Simplest SPIR-V parser ever:
`auto stream = ReadFile(L"Shaders/default.spv");

		// Parse SPIR-V data
		Assert(stream->ReadInt() == 0x07230203);
		int version = stream->ReadInt();
		int genmagnum = stream->ReadInt();
		int bound = stream->ReadInt();
		int reserved = stream->ReadInt();

		bool stages[6] = {false,false,false,false,false,false};

		// Instruction stream
		while (stream->Ended() == false)
		{
			int pos = stream->GetPos();
			unsigned int bytes = stream->ReadUInt();
			int opcode = LOWORD(bytes);
			int wordcount = HIWORD(bytes);
			if (opcode == 15)
			{
				int executionmodel = stream->ReadInt();
				Assert(executionmodel >= 0);
				if (executionmodel < 6) stages[executionmodel] = true;
			}
			stream->Seek(pos + wordcount * 4);
		}`
