### ISSUE TITLE
Simplify code-gen?

### ISSUE THREAD

**Issue by jamesdolan** [KhronosGroup/SPIRV-Tools#2640]
Little usability request here...

For those of us that have to integrate SPIRV-Tools into different build systems (really common problem on bigger projects!), having complicated code-gen steps is a tricky and fragile thing to re-create and maintain support for.

I managed to get things working, but I had to call like 4 different python scripts with a ton of arguments without clear distinction between which ones are inputs vs outputs. And setting up the tracking of dependencies was also pretty hairy since some commands can generate multiple outputs.

Other Khronos repositories (e.g. OpenGL-Registry, SPIRV-Headers, etc) pre-generate said headers to make life easier for the common end-user case, so in an ideal world since none of these files appear to be machine-dependent they would just be committed and updated only when necessary.

But possibly at least make the code-gen a bit easier to do outside of the cmake environment (simple clear syntax for inputs vs single-output, etc, e.g. `gen_header.py -o some.inc some.json`).

**Comment by dj2** [comment]
You can get the generated SPIR-V headers from https://github.com/KhronosGroup/Spirv-headers is that what you're looking for?

**Comment by jamesdolan** [comment]
I would love if SPIRV-Headers included everything, but it doesn't.

```
build-version.inc
extension_enum.inc
enum_string_mapping.inc
DebugInfo.h
core.insts-{SpirVConfigName}.inc
glsl.std.450.insts.inc
opencl.std.insts.inc
operand.kinds-{SpirVConfigName}.inc
generators.inc
```

**Comment by dneto0** [comment]
Right, but those .inc files reflect data representations that are internal to SPIRV-Tools.
I've rev'd those multiple times in the past and actually considered yet another representation change last week.  Those python scripts are.... dense and confusing as well.

**Comment by s-perron** [comment]
We won't be doing anything about this.
