### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by ChineseSeniorYouKnow** [KhronosGroup/SPIRV-Tools#267]
希望增加visual studio 工程项目。
把一个需要到的文件都放到一个项目里，这样的话也方便了新手 嗯

**Comment by antiagainst** [comment]
Hi @ChineseSeniorYouKnow,

Thanks for the suggestion! But I believe CMake can generate Visual Studio solutions. [This blog post](https://cognitivewaves.wordpress.com/cmake-and-visual-studio/) gives a nice tutorial, and you may also want to check out the [generators](https://cognitivewaves.wordpress.com/cmake-and-visual-studio/) supported by CMake.

**Comment by ChineseSeniorYouKnow** [comment]
你看的懂中文？我知道CMake 可以生成 visual studio 项目，所以我才提议让你把需要用到的文件都放到一起，比如 SPIRV-Headers的文件。。

**Comment by antiagainst** [comment]
Sorry, I typically don't develop on Windows, so I still cannot get your idea of "putting all files together." Would appreciate if you can elaborate on it a little bit.

My tentative answer: SPIRV-Headers is a different project, I don't think put it (or its derived files) in SPIRV-Tools is a good idea.

**Comment by antiagainst** [comment]
No further requests. Closing.
