### ISSUE TITLE
spirv-fuzz: Replace constant uses with uses of differently-signed constants

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2677]
In a review of #2671 @alan-baker pointed out that the sign of an index in an access chain rarely matters, and that it might be worth fuzzing this sign.

**Comment by alan-baker** [comment]
You can do this more generally. For example:
```
%add1 = OpIAdd %uint %in %const_int1
%add2 = OpIAdd %int %in %const_int2
```
Both these additions are valid. The operands in %add1 are treated as unsigned while the operands in %add2 are treated as signed. Since the opcode determines the interpretation, you could change the sign bit for the constant type and get the same result.

**Comment by afd** [comment]
Thanks - interesting.  When does the sign of the integer data type actually matter then?

**Comment by afd** [comment]
@andreperezmaselco I think this issue would be a good one for you to pick up at some point.  I don't yet have a sense for how tricky it will be to change the sign of an id (in terms of keeping the module valid), but we could go through some examples.

**Comment by andreperezmaselco** [comment]
I'll try to understand it, @afd.
That's an interesting transformation.

**Comment by afd** [comment]
@stefanomil I feel like this is kind of subsumed by what you have been working on: we can regard ids as synonymous even if their signs don't match, and when we replace ids with synonyms we are relaxed about sign.

@Vasniktel regarding the DecisionMaker class we are thinking about, I could imagine wanting a mode where we bias ReplaceIdWithSynonym to be *more* likely to pick and id that has a compatible but non-identical type (i.e., the type differs in its sign.)

**Comment by stefanomil** [comment]
@afd Yes, and I think that this could be done implementing a fuzzer pass similar to FuzzerPassInterchangeZeroLikeConstants, that:
- finds integer constants (also vectors)
- adds the corresponding toggled constants to the module and records that they are synonyms using TransformationRecordSynonymousConstants
- looks for uses where the sign can be changed (with the help of the IsAgnosticToSignednessOfOperand function)
- replaces the ids using TransformationReplaceIdWithSynonym

**Comment by afd** [comment]
@stefanomil That sounds good - I have changed the title of the issue and assigned it to you; can you add it to your pile?

**Comment by stefanomil** [comment]
@afd Sure
