### ISSUE TITLE
Update SPIRV-Headers DEPS

### ISSUE THREAD

**Issue by jonahryandavis** [KhronosGroup/SPIRV-Tools#2680]
The following commit: [3d5fb7b](https://github.com/KhronosGroup/SPIRV-Tools/commit/3d5fb7b908cbc8e416db31391d5bd76b35348a91) refers to symbols from this commit in SPIRV-Headers: [9baa9e](https://github.com/KhronosGroup/SPIRV-Headers/commit/9baa9e099e4707e07f68da54d3b5ce381b6d9475), but the DEPS file is not up to date.
This broke CI in ANGLE, but it should have probably been caught by CI here? Which ties into [issues/2665](https://github.com/KhronosGroup/SPIRV-Tools/issues/2665)

**Comment by null77** [comment]
@dneto0 @dj2

**Comment by dneto0** [comment]
Hey @zoddicus PTAL

**Comment by zoddicus** [comment]
I will roll DEPS ahead for this manually, and work on getting the process a bit better in #2665

**Comment by null77** [comment]
Awesome, thanks a lot.
