### ISSUE TITLE
Parse --vulkan-to-webgpu and --webgpu-to-vulkan in config files.

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#2701]
Spirv-opt and DXC have an option `-Oconfig=<filename>` that parses options in the given file to determine which optimizations to add.  This parsing is done [here](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/optimizer.cpp#L266).

This could be useful for people who want to generate a web-gpu shader using DXC without having it invoke spirv-opt as a separate command.

More importantly it will be in line with other optimization set flags like `--legalize-hlsl`, `-O`, and `-Os`.

**Comment by zoddicus** [comment]
This appears to be working to me. I have tested both --vulkan-to-webgpu, and --webpgu-to-vulkan in config files.

If you have a specific usage that isn't working correctly, please re-open with an example.
