### ISSUE TITLE
Bug passing RWByteAddressBuffer as parameter

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Tools#2703]
Hi,

I have a very simple shader repro that hopefully will be easy to fix. This used to compile on a pretty old version of SPIRV-Tools but fails now that we have updated. The rest of the process has been uneventful, it's just this one shader that seems to be giving us trouble.

Basically I have a helper function that takes in a buffer that we use for indirect arguments. We can pass offsets, etc. to it. Because one can use any buffer it takes one as a parameter, however the optimizer seems to get upset by this.

I use glslang to generate the SPIR-V from hlsl, then put it through the optimizer using the legalization and performance passes. I'm attaching the unoptimized binary spv.

The hlsl looks like this:

```hlsl
RWByteAddressBuffer g_indirectBuffer;

// Buffer as parameter here fails optimization pass
void SetIndirectBuffer(RWByteAddressBuffer indirectBuffer, int offset, int count)
{
       indirectBuffer.Store(offset * 4, count);
}

[numthreads(1, 1, 1)]
void main()
{
       SetIndirectBuffer(g_indirectBuffer, 1, 2);
}
```

[TerrainLODVisibilityBuildLODOffsets.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3330903/TerrainLODVisibilityBuildLODOffsets.spv.txt)

**Comment by s-perron** [comment]
Can I get some more information on how you are running the optimizer?  I do not see an error when I run the provided spir-v through the optimizer:

```
spirv-opt t.spv -o o.spv --legalize-hlsl -O
```

**Comment by redorav** [comment]
This is the way we optimize the spir-v I supplied. I think we tried it even with only legalization and performance and it was still going wrong. We didn't try with legalization only though

```
spvtools::Optimizer optimizer(target_env);
optimizer.SetMessageConsumer(messageConsumer);

// Add this combination to fix https://github.com/KhronosGroup/SPIRV-Tools/issues/1860
optimizer.RegisterLegalizationPasses();
optimizer.RegisterPass(spvtools::CreateLoopUnrollPass(true)); // We need loop unroll but it's not part of the standard recipes
optimizer.RegisterLegalizationPasses();
optimizer.RegisterPerformancePasses();

// By using the same vector as input and output, we save time in the case there was no change
bool ok = optimizer.Run(spirvBinary.data(), spirvBinary.size(), &spirvBinary);
```

**Comment by s-perron** [comment]
Okay, I think I see the problem.  When we put `--legalize-hlsl` on the command line, it changes the options that are passed to the validator to let it know that it is receiving hlsl based code before it is legalized. (See [this](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/tools/opt/opt.cpp#L781)).

When you call `optimizer.Run(...)`, the validator is called with the default options.  In this case, it is identifying that the storage class for the function parameter is wrong.  The validator will overlook this if you tell it that it is legalizing hlsl.

**Comment by redorav** [comment]
So if I understood correctly all I need to do is add that SetBeforeHlslLegalization(true); to the optimizer on my side?

I'll try that on Monday then and let you know how it goes.

**Comment by s-perron** [comment]
More or less.  The `SetBeforeHlslLegalization` is a member function of the validation options.  You will need to create an optimizer options and validator options objects and pass those as a parameter to `optimizer.Run(...)`.  You can see how to do it in `opt.cpp`.
