### ISSUE TITLE
Scalar replacement on descriptor arrays

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#2740]
Consider the following hlsl code,

```
#define COUNT 5

Texture2D    MyTextures[COUNT] : register(t0);
Texture2D    NextTexture;

SamplerState MySampler;

float4 main(float2 TexCoord : TexCoord) : SV_Target0
{
  float4 result =
    MyTextures[0].Sample(MySampler, TexCoord) +
    MyTextures[1].Sample(MySampler, TexCoord) +
    MyTextures[2].Sample(MySampler, TexCoord) +
    MyTextures[3].Sample(MySampler, TexCoord) +
    MyTextures[4].Sample(MySampler, TexCoord) +
    NextTexture.Sample(MySampler, TexCoord);
  return result;
}
```

If you look at the output from dxc when generating [dxil](http://shader-playground.timjones.io/0dd78246a5ceed3c3b1ecc85f006bd68), you will notice that `MyTextures` takes up 5 binding t0 to t4. Then `NextTexture` is placed in t5.  The [dxbc](http://shader-playground.timjones.io/f9fbbfa4bf0de7d320bf655e4dd1dcf3) from FXC is similar.

For the [spirv](http://shader-playground.timjones.io/b1db8aa140d124148025272151b71fc5), `MyTextures` is a single array at binding 0, and `NextTexture` is at binding 1.

This can make it conceptually difficult for code that wants to work with Vulkan and DirectX.  It becomes hard to keep track of where everything is bound.

To help with this DXC will be adding an option to have texture map the same way.  However, the front-end cannot convert the array of textures into separate variables until after legalization because it may require optimizations to determine fold the index in the use to a literal.

To this end, we will add a pass that will do scalar replacement on descriptor arrays.  It will be an error it the pass is unable to the scalar replacement.

**Comment by greg-lunarg** [comment]
> It will be an error it the pass is unable to the scalar replacement.

Is this still the case? I wonder if it might be better to not have an error if there is no opportunity to do sroa. Rather, look at it in terms of an opportunistic pass which does sroa if it can but otherwise generates the more general "bindless" code.

For example, glslang will turn a runtime-sized array into a fixed size array if all of the references to the array have constant indices ie. the maximum index can be determined. But otherwise generates the runtime-sized array.

Just a suggestion, but I don't have all the background that you do.

**Comment by s-perron** [comment]
@greg-lunarg  This pass will not be enabled by default.  It will become an option to have the spir-v backend for DXC to match the dxil backend.  Issuing an error is about making the behavior match.

Thanks for the suggestion.  I did not put in all of the information I should have to explain why we are doing what we do.
