### ISSUE TITLE
Can we avoid source file name collisions?

### ISSUE THREAD

**Issue by jamesdolan** [KhronosGroup/SPIRV-Tools#2754]
Small enhancement request...

For a variety of reasons, its cleaner for me to build SpirvTools as a single lib due to all the required code-gen it requires and complex internal search pathing, but msbuild does not maintain directory structure of its intermediates directory, this results in vs2019 emitting the following warnings (and subsequent missing symbol errors)....
```
warning MSB8027: Two or more files with the name of basic_block.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are SPIRV-Tools\source\opt\basic_block.cpp, SPIRV-Tools\source\val\basic_block.cpp.
warning MSB8027: Two or more files with the name of function.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are SPIRV-Tools\source\opt\function.cpp, SPIRV-Tools\source\val\function.cpp.
warning MSB8027: Two or more files with the name of instruction.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are SPIRV-Tools\source\opt\instruction.cpp, SPIRV-Tools\source\val\instruction.cpp.
```
...IMHO it would seem cleaner anyways to not have a bunch of source files with identical names kicking around in the same project.

**Comment by dneto0** [comment]
Sorry, this is a problem with VS2019 MSBuild.  I suggest you file a bug with the Visual Studio team.
