### ISSUE TITLE
spirv-opt moves RelaxedPrecision decoration from OpIAdd to FindSMsb

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2764]
[spirvoptissue.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3432486/spirvoptissue.zip)

The attached zip contains this little fragment shader:

```
#version 310 es

precision highp float;

layout(location = 0) out vec4 _GLF_color;

void main() {
  highp int a = 16777216;
  _GLF_color = vec4(24 == (0 + findMSB(a)) ? 1.0 : 0.0, 0.0, 0.0, 1.0);
}
```

glslang treats the result of "0 + findMSB(a)" as having relaxed precision, decorating `%18` in example.asm with RelaxedPrecision.

```
               OpDecorate %18 RelaxedPrecision
                       ...
         %18 = OpIAdd %6 %15 %17
```

This is OK, because `findMSB` has lowp on its return type (which makes sense because the most significant bit of an integer cannot be a large number), and 0 does not have a precision, so lowp is the lowest common denominator.

Running spirv-opt -O on the generated SPIR-V gives example.opt.asm, in which the "0 +" has been removed.

The problem is that the RelaxedPrecision decoration has now been changed to refer to `%17`, which is the call to findMSB:

```
               OpDecorate %17 RelaxedPrecision
                       ...
         %17 = OpExtInst %6 %1 FindSMsb %9
```

According to the SPIR-V specification, this leads not just to the result of FindSMsb, but also its argument, `%9`, being treated as having relaxed precision.

On some implementations this leads to `%9` being truncated to a smaller number of bits, changing what is rendered.  (In this test, `%9` contains 16777216, which has 24 as its MSB, but if it is truncated to e.g. 16 bits it has 0 as its MSB.)

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz)

**Comment by gnl21** [comment]
There's some possible confusion about whether `Find?MSB` is allowed to be RelaxedPrecision here, but the issue still manifests if we replace the GLSL code with:
```
layout (std140) uniform B {
   highp float bar;
   highp float baz;
} b;

...

  mediump float foo = b.bar - b.baz;
  _GLF_color = vec4(24.0 == (0.0 + foo) ? 1.0 : 0.0, 0.0, 0.0, 1.0);
```
This gives us, initially
```
               OpDecorate %30 RelaxedPrecision
               ...
         %30 = OpFAdd %float %float_0 %29
```
which the optimiser turns into:
```
               OpDecorate %23 RelaxedPrecision
               ...
         %23 = OpFSub %float %19 %22
```
The relaxed precision decoration here means that consumers can use a 16 bit subtract, which is incorrect for the 32-bit inputs (multiple rounding, possible overflow to infinity, etc). I think of this as another manifestation of what Alastair is reporting, but hopefully it is slightly clearer what a 16-bit subtract is than a 16-bit FindMSB.
