### ISSUE TITLE
Descriptor scalar replacement not working for loops in presence of unroll

### ISSUE THREAD

**Issue by ehsannas** [KhronosGroup/SPIRV-Tools#2803]
I have following HLSL (adapted from the shader that was posted here: https://github.com/microsoft/DirectXShaderCompiler/issues/2412)
```hlsl
// dxc -T ps_6_0 file.hlsl -E psMain -spirv  -fspv-flatten-resource-arrays
struct PS_INPUT {
	float4 Pos		: SV_Position;
};
struct PS_OUTPUT {
	float4	Color	: SV_Target0;
};

SamplerState		S;
Texture2D<float>	T[4];

PS_OUTPUT psMain(const PS_INPUT In)
{
	PS_OUTPUT	Out;
	Out.Color = float4(1,0,0,1);

        [unroll]
	for (uint i=0; i<4; i++) {
		Out.Color.y += T[i].SampleLevel(S, In.Pos.xy, 0).x;
	}

	return Out;
}
```

Compiling this to SPIR-V using DXC (without optimizations) results in the attached binary (before_opt.spv). This binary includes
```
OpLoopMerge %for_merge %for_continue Unroll
```

[before_opt.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3517345/before_opt.spv.txt)

Then running:
```
spirv-opt.exe before_opt.spv -o after_opt.spv --descriptor-scalar-replacement
```
I get:
```
error: line 0: Variable cannot be replaced: invalid index
  %55 = OpAccessChain %_ptr_UniformConstant_type_2d_image %T %53
```

Isn't the `Unroll` flag in `OpLoopMerge` enough to indicate that the loop should be unrolled?

**Comment by s-perron** [comment]
You have to run loop unrolling.  Try it whole set of optimizations that DXC does for legalization.

**Comment by ehsannas** [comment]
Oh yeah that did it.
