### ISSUE TITLE
Add passes to replace uses of AMD extensions

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#2814]
Some extensions have become obsolete because they have equivalent functionality in new versions of spir-v.  For portability developers may want to change their spir-v module to remove the extensions.

For this issue we specifically want a pass to replaces uses of three extensions:
  - VK_AMD_shader_ballot
  - VK_AMD_gcn_shader
  - VK_AMD_shader_trinary_minmax

**Comment by s-perron** [comment]
There are still two issues that need to be addressed for the three extension.  We cannot replace `TimeAMD` instructions because the Vulkan extension that enables SPV_KHR_shader_clock has not been released yet.

Also, the extension that allows `OpGroup*` instructions to work on 16-bit integers has not been release, as far as I know.

**Comment by dnovillo** [comment]
I'll take a look at adding `TimeAMD` and `OpGroup*` next.
