### ISSUE TITLE
Structured control flow checks should be optional.

### ISSUE THREAD

**Issue by bader** [KhronosGroup/SPIRV-Tools#285]
My understanding is that SPIR-V v1.0 specification doesn't force control flow to be structured. OpenCL C support things like 'goto' and OpenCL C -> SPIR-V compiler from here produces SPIR-V files with unstructured control flow. These SPIR-V files do not pass structured control flow checks.
Can we make them optional for SPIR-V files produced from OpenCL C?

I attached CL source and SPIR-V file demonstrating the issue.

[sample_test.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/390361/sample_test.zip)

**Comment by dneto0** [comment]
The sample.spv shader uses OpCapability Shader.  That's what's turning on the checks.  When I remove that instruction then the module passes the validator.
