### ISSUE TITLE
spirv-fuzz: Add OpCompositeInsert instructions to create synonyms.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2859]
Similar to the fuzzer pass that adds extracts or vector shuffles, this pass should add OpCompositeInsert instructions to the module.

Each insert yields several synonym facts: every component of the result is synonymous with the components of the original id, except for the inserted component which is synonymous with the given operand.

**Comment by antnkarp** [comment]
I can implement this

**Comment by afd** [comment]
It would be good to study the fuzzer pass that constructs composites and the fuzzer pass that shuffles vectors before working on this.
