### ISSUE TITLE
Segfault in CopyPropagateArrays

### ISSUE THREAD

**Issue by ehsannas** [KhronosGroup/SPIRV-Tools#2869]
HLSL shader originally posted in https://github.com/microsoft/DirectXShaderCompiler/issues/2423. May be related to legalization.

```
struct MyConstantBuffer {
    float4 myParam1[8];
};

cbuffer myCBuffer : register(b0) {
  MyConstantBuffer myConstantBuffer;
}

struct MyConstantBufferWrapper {
    MyConstantBuffer constants;

    float4 GetParam1(uint index) { return constants.myParam1[index]; }
};

MyConstantBufferWrapper CreateWrapper() {
    MyConstantBufferWrapper wrapper;
    wrapper.constants = myConstantBuffer;
    return wrapper;
};

struct VS_OUTPUT {
    float4  m_ScreenPos  : VS_OUT_POSITION;
};

struct MyStruct {
    uint myIndex;
};

static MyConstantBufferWrapper myWrapper = CreateWrapper();

float4 main(VS_OUTPUT In) : SV_Target {
    MyStruct myStruct = (MyStruct)0;

    // Causes the issue:
    float4 myParam = myWrapper.GetParam1(myStruct.myIndex);

    // Works fine:
    //float4 myParam = myConstantBuffer.myParam1[myStruct.myIndex];

    return myParam;
}
```

What I see is that `AsIntConstant()` returns nullptr:
https://github.com/KhronosGroup/SPIRV-Tools/blob/9325619353feea49cd25a1611f5da414a5251382/source/opt/copy_prop_arrays.cpp#L516

The attached test.spv.txt is the result of `-spirv -fcgl -O0` from DXC.
[test.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3617307/test.spv.txt)

If I run `spirv-opt.exe test.spv.txt -o test.optimized.spv`, however, I get the following error rather than the segfault (not sure why):
```
error: line 101: OpFunctionCall Argument <id> '21[%myWrapper]'s type does not match Function <id> '52[%_ptr_Function_MyConstantBufferWrapper]'s parameter type.
  %47 = OpFunctionCall %v4float %MyConstantBufferWrapper_GetParam1 %myWrapper %param_var_index
```

**Comment by s-perron** [comment]
When you run spirv-opt on the command line, the validator will be run.  It will not pass any options to the validator, because you did not give it any.  If you add `--legalize-hlsl` to the command line, it will reproduce the segfault.

**Comment by s-perron** [comment]
The issue is that the constant in the access chain is defined by an `OpConstantNull` instruction.
