### ISSUE TITLE
spirv-opt: Inliner regression: Need to add OpKill wrapping to inlining

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#2875]
PR #2842 causes a regression with inlining: functions containing OpKill will no longer inline. Existing applications containing OpKill will likely degrade in performance and size and may no longer legalize properly due to this change. OpKill is a fairly prevalent operation, appearing a couple dozen times in the one application I surveyed.

I understand that a new pass has been added that, when added to an optimization recipe before inlining causes the inliner to essentially produce previous results. But I am very concerned with making such significant, regressive, silent, non-backward-compatible changes to any tool.

I also understand the desire to keep passes as simple as possible. But I question a design that decomposes an existing pass into two new passes, neither of which is useful on their own, and only make sense when run together. It doesn't seem to me any user would want to wrap OpKills in a function except that the inliner requires it to run as it previously did. And it doesn't seem that any user would reasonably want to run an inliner that doesn't inline functions that contain OpKill, and so will always run OpKill wrapping first.

If the above line of thinking is valid, it argues that OpKill wrapping should be added to the inliner and the separate wrapping pass should be eliminated.

**Comment by greg-lunarg** [comment]
The issue with legalization mentioned above would only happen if someone is doing their own legalization recipe. One might argue whether they should even do that, but even if not, the regressions in performance and size are still a concern.

**Comment by greg-lunarg** [comment]
@s-perron Sorry to "blindside" you with this, but as I was writing this (at your request) the regressive nature of this change started to become more apparent and I thought it was necessary to give users a heads up.

I also appreciate the general philosophy of creating simple passes, but there is also the philosophy of making tools easy and intuitive to use. I just don't think users want to or should need to know about OpKill and the problems the inliner has with it.

**Comment by s-perron** [comment]
If you look at how OpKill was added to the [legalization passes](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/optimizer.cpp#L112), you will notice it is not done immediately before inlining.  That was a very conscience decision.

When you replace the OpKill instruction, it will add an OpUnreachable in the basic block.  The OpUnreachable will have the same problem.  Try validating this code:

```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %1 "main"
               OpExecutionMode %1 OriginUpperLeft
       %void = OpTypeVoid
       %bool = OpTypeBool
       %true = OpConstantTrue %bool
          %5 = OpTypeFunction %void
%_ptr_Function_bool = OpTypePointer Function %bool
          %7 = OpUndef %bool
          %1 = OpFunction %void None %5
          %8 = OpLabel
          %9 = OpVariable %_ptr_Function_bool Function
         %10 = OpLoad %bool %9
         %11 = OpFunctionCall %void %12
               OpStore %9 %10
               OpReturn
               OpFunctionEnd
         %12 = OpFunction %void None %5
         %13 = OpLabel
               OpBranch %14
         %14 = OpLabel
               OpLoopMerge %15 %16 None
               OpBranch %17
         %17 = OpLabel
               OpBranchConditional %7 %15 %16
         %16 = OpLabel
               OpSelectionMerge %18 None
```

To get around this, we have to run `merge-return`.  That will fix this up.  This does raise the issue of should we be inlining functions containing OpUnreachable?  I had forgotten this part.  Sorry I did not mention it earlier.

If you want to merge wrap-opkill into inlining, you will need to do the same with merge return.  Also because merge-return relies on dead-branch-elimination being run first, that would have to be included as well.  Notice how we now have once absolutely huge pass.  Testing becomes harder.

The other thing to notice is that wrap-opkill and merge-return only need to be run once.  If we were to implement a heuristic based inlining algorithm with multiple passes of inlining then we would be doing more work.

If things are properly documented, I believe it is far to ask people who are putting their own recipes together to understand the interaction between the passes.  Many of our passes like `dead-insert-elim` work better after loads and stores have been removed, but we don't incorporate `ssa-rewrite` into the pass. Instead we expect our user to understand the passes.  I believe we can expect the same from user in this case.

**Comment by s-perron** [comment]
Greg.  Thanks for bringing up your concerns.  It is good to ensure that these types of questions are dealt with to make sure we get user the best possible experience.

**Comment by greg-lunarg** [comment]
@s-perron Is there some code missing from your example above?

**Comment by s-perron** [comment]
Yes, there was.  I updated it.

**Comment by greg-lunarg** [comment]
> To get around this, we have to run merge-return. That will fix this up. 

I am not understanding how merge-return gets rid of OpUnreachable as it is generated by --wrap-opkill. I am also not seeing it happen.

Here is the code I am working with. It is a slight variant on the original code:

#version 330

uniform B { float f; };

void kill()
{
    if (f < 0.0)
        discard;
}

void main()
{
    for(int i=0; i < 3; kill())
        ++i;
}

Running --wrap-opkill --eliminate-dead-branches --merge-return --inline-entry-points-exhaustive --eliminate-dead-functions, I end up with invalid code.

Am I not understanding?

**Comment by s-perron** [comment]
You are right.  Merge return is not replacing the OpUnreachable, so we still have a problem.  I should be testing more thoroughly.

**Comment by s-perron** [comment]
I'm misusing OpUnreachable in OpKill.  I was thinking of it too much in terms of the gcc builtin `__builtin_unreachable`.  OpUnreachable says that the entire block is unreachable. I think I need to change WrapOpKill to add a dummy return instead of an OpUnreachable.

Does that sound correct?

**Comment by greg-lunarg** [comment]
A return would work. That would then create a need for merge-return.

Another option that would not require merge-return but would take a little more work: create a branch to the merge block of the structured control flow the OpKill is in. If you are not in a structured control flow, the entire function can be replaced with an OpKill.

**Comment by s-perron** [comment]
The branch to the merge of the structure would work, but we would have to update or create OpPhi instruction in the merge node.  It is similar work as in merge return, but would be simpler.  It is still would still have some difficulties.

Now I rememeber why I switched from an OpReturn to OpUnreachable.  My first design was suppose to use OpReturn/OpReturnValue, but it failed when the return type of the function cannot be used in and OpConstantNull.  Can we do an OpUndef on any type?  These situation come up during legalization.

**Comment by greg-lunarg** [comment]
Looks like OpUndef takes any type.

Greg Fischer

Project Manager and Senior Engineer

LunarG, Inc. - 3D Driver Innovations

greg@lunarg.com <alan@lunarg.com>

**Comment by greg-lunarg** [comment]
@s-perron I don't think a return is going to help us either :(

A return in a continue construct is just as invalid (and possibly "more" invalid) than an OpKill or an OpUnreachable.

**Comment by greg-lunarg** [comment]
I am going to try to argue that an OpKill is valid in a continue construct based on the current spec. Therefore no wrapping of OpKill is required.

I think this argument is different than the one you attempted in https://gitlab.khronos.org/spirv/SPIR-V/issues/459.

First, lets consider the following SPIR-V, generated from my example above, optimized through inlining without OpKill wrapping. I choose this one to start because the OpKill does not cause a discontinuity in the loop, so I find this one easier to talk about:

```
       %main = OpFunction %void None %3
          %5 = OpLabel
          %i = OpVariable %_ptr_Function_int Function
               OpStore %i %int_0
               OpBranch %25
         %25 = OpLabel
               OpLoopMerge %27 %28 None
               OpBranch %29
         %29 = OpLabel
         %30 = OpLoad %int %i
         %32 = OpSLessThan %bool %30 %int_3
               OpBranchConditional %32 %26 %27
         %26 = OpLabel
         %33 = OpLoad %int %i
         %35 = OpIAdd %int %33 %int_1
               OpStore %i %35
               OpBranch %28
         %28 = OpLabel
         %37 = OpAccessChain %_ptr_Uniform_float %_ %int_0
         %38 = OpLoad %float %37
         %39 = OpFOrdLessThan %bool %38 %float_0
               OpSelectionMerge %40 None
               OpBranchConditional %39 %41 %40
         %41 = OpLabel
               OpKill
         %40 = OpLabel
               OpBranch %42
         %42 = OpLabel
               OpBranch %25
         %27 = OpLabel
               OpReturn
               OpFunctionEnd
```

The spec says the back edge block must post-dominate the continue target.

The spec defines A post-dominates B by saying all paths from A to a function-return instruction go through B.

The heart of my argument is this: an OpKill instruction is *not* a function return instruction. A return instruction executes a return from the current instruction. This terminates execution of a shader invocation.

Yeah, its a stretch.

Otherwise, we are going to have to wrap them and add real branches to somewhere.

Frankly, if subroutine calls that contain an OpKill are allowed in a continue construct, why not just an OpKill?

I have some thoughts about what to do when inlining OpKill creates unreachable code. I will send those shortly.

**Comment by s-perron** [comment]
If you can convince the committee to change their minds, I will gladly remove the pass.  For now, I will fix the bug by using OpReturn* in place of OpUnreachable in the code that WrapOpkill generates.

**Comment by s-perron** [comment]
I'll close because I fixed the bug that you found.  If the working group changes their minds, you can open a new issue.

**Comment by greg-lunarg** [comment]
Just going to record some final thoughts for when priorities allow us to take this up again...

- Given that the opkill-wrap pass, as it is constituted at the moment, requires followup with merge-return which in turn requires a preceding dead-branch-elim, I agree it is problematic to add opkill-wrap into inlining, so that might be enough to close this issue.

- It is not clear to me that the WG needs to be consulted. One way to view this situation is to say that OpKill is not a function return, so it is legal in continue constructs, so it is the validator that is incorrect. Of course, then this becomes a validator issue.

- Another possible approach: In some ways, OpKill wrapping is a de-facto way to get at the solution that JohnK was proposing: to change the meaning of OpKill so it is closer to GLSL discard, which is just an operation and not a control flow construct. Essentially, you could view this as the optimizer making this change on its own. So maybe that is an indication that creating a "new" OpKill might be a good thing for the WG to do.

- Unfortunately, the current solution comes at a cost. OpKill wrapping will inject more early returns  into functions, requiring more merge-returns which inject more trivial one-trip loops into the user program, which will inhibit existing loop unrolling which will inhibit existing legalization.

- In addition, the creation of the de-optimizing OpKill wrap pass along with the inliner's dependence on it increases the complexity of the optimizer interface and increases the opportunity for mistakes and missed optimization opportunities.

- So we are reducing performance and increasing tool complexity because we feel we can't allow an OpKill in a continue construct. It seems to me it would be better to fix this in the spec than in the tools.
