### ISSUE TITLE
SPIRV-Tools.lib fails to build under MSVC

### ISSUE THREAD

**Issue by hypernewbie** [KhronosGroup/SPIRV-Tools#289]
Cmd.exe failed on Windows MSVC:

2>------ Rebuild All started: Project: SPIRV-Tools, Configuration: Release x64 ------
2>  Building Custom Rule X:/code/github/SPIRV-Tools-master/source/CMakeLists.txt
2>  CMake does not need to re-run because X:\code\github\SPIRV-Tools-master\build\source\CMakeFiles\generate.stamp is up-to-date.
2>  Generate info tables for OpenCL extended instructions and operands v1.0.
2>  Traceback (most recent call last):
2>    File "X:/code/github/SPIRV-Tools-master/utils/generate_grammar_tables.py", line 426, in <module>
2>      main()
2>    File "X:/code/github/SPIRV-Tools-master/utils/generate_grammar_tables.py", line 393, in main
2>      with open(args.spirv_core_grammar) as json_file:
2>  FileNotFoundError: [Errno 2] No such file or directory: '/spirv/1.0/spirv.core.grammar.json'

**Comment by hypernewbie** [comment]
I managed to hack around this by replacing /spirv/ with proper relative path in generate_grammar_tables.py

**Comment by Qining** [comment]
I guess this is because the spirv-header project is not checkout in your `SPIRV-Tools-master/external` directory.

**Comment by Qining** [comment]
SPIRV-tools depends on two external projects, and they should be checked out in the following way (also configured in .appveyor.yml):
```
(assume current directory is in the root directory of SPIR-V tools)
git clone https://github.com/KhronosGroup/SPIRV-Headers.git external/spirv-headers
git clone https://github.com/google/googletest.git external/googletest
```

**Comment by hypernewbie** [comment]
oh, I think I might have configured cmake before checking them out, so cmake created project files with empty directories. I did check them out, but I didn't rebuild cmake.
