### ISSUE TITLE
Validator incorrectly reports issue with pointer variable types

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Tools#2892]
I'm getting a validator error in ValidateFunctionCall where it says that "Pointer operand %# must be a memory object declaration". However as near as I can tell the declarations are correct. In particular, the argument is of type SpvOpAccessChain which should be allowed in logical addressing mode.

Seems related to https://github.com/KhronosGroup/SPIRV-Tools/issues/2106

**Comment by alan-baker** [comment]
Without variable pointers, only samplers and images (things in UniformConstant storage class) can be passed through an OpAccessChain. All other accesses must be memory object declarations.

**Comment by jodavis42** [comment]
So after re-reading the spec more carefully, am I correct in understanding that a pointer type to OpFunctionCall cannot be the result of an OpAccessChain?

So is something like:
```
%124 = OpAccessChain %_ptr_Function_SubStruct %self_4 %int_0
%125 = OpFunctionCall %void %DefaultConstructor %124
```
illegal? Is this variable first required to be stored into an OpVariable? Something like:
```
%param  OpVariable %_ptr_Function_SubStruct Function
%124 = OpAccessChain %_ptr_Function_SubStruct %self_4 %int_0
OpStore %param %124
%125 = OpFunctionCall %void %DefaultConstructor %param
```

**Comment by alan-baker** [comment]
It cannot be the result of an OpAccessChain unless that access chain resolves to an image or sampler.

The other alternative to your code snippet is to load the value and pass it directly to the function instead of passing the pointer.

**Comment by jodavis42** [comment]
Unfortunately, in this case the param to the function is an inout so it needs to be a pointer.

I'll close this then, but I wanted to ask for my own knowledge if you knew why this was a requirement? It seems odd to me that a pointer from an OpVariable would be treated differently then a pointer from an OpAccessChain when they're the same storage class.
