### ISSUE TITLE
Friendly disassembler can generate an empty Id name

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#290]
For example:

```
OpName %42 ""
```
will disassemble into:
```
OpName % ""
```
But a plain % is not a valid Id term in SPIR-V assembly.

**Comment by Qining** [comment]
Is it possible to have such an issue when we don't have OpName instruction with empty name string?

**Comment by dneto0** [comment]
@Qining: it was only possible with the OpName instruction, since in other cases either we use a "sanitized" friendly name, or we just use the raw ID number.
