### ISSUE TITLE
spirv-fuzz: allow replacing a boolean constant argument to OpPhi with a binary by inserting a binary into the OpPhi's relevant parent block.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2902]
As a fix for #2897, spirv-fuzz simply does not replace a boolean constant used in an OpPhi with a binary operator instruction, to avoid erroneously adding an instruction before OpPhi.

This could be handled by adding an instruction to the parent block associated with the OpPhi argument.

**Comment by afd** [comment]
@andreperezmaselco Can we add this one to your pile of things to work through?

**Comment by andreperezmaselco** [comment]
Sure.
I'll work on it.
