### ISSUE TITLE
#2790, #2842 OpKill changes causing size regressions

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#2912]
PRs #2790 and #2842 were done to fix a problem: stop inlining an OpKill into a loop's continue construct.

Unfortunately, these changes are now causing size regressions for real shaders that do not call functions with OpKill from a continue construct.

Case in point: the attached SPIR-V shader previously optimized to 940 bytes, now optimizes to 1148, an increase in file size of 20% and nearly 100% increase in function size.

I understand that @s-perron attempted to only "fix" problematic shaders but wasn't able to. Unfortunately, a solution was devised that caused **all** shaders with OpKill to regress in optimized size.

I propose a possible solution: create an analysis which determines if a shader contains a call to a function containing an OpKill from a continue construct. If it does, WrapOpKill and Inlining behave as they do now. If it does not, WrapOpKill returns without wrapping anything and Inlining performs without worrying about OpKill.

The analysis would be run at the beginning of both WrapOpKill and Inlining passes. There might even be a way to preserve the analysis from WrapOpKill to Inlining.

While, admittedly, the increase in size will be less dramatic for larger shaders, the case that this fix is guarding against is so rare, any penalty incurred by non-problematic shaders is difficult to justify.

**Comment by greg-lunarg** [comment]
Attn: @danginsburg

**Comment by greg-lunarg** [comment]
Here is the HLSL source for the shader:

[glsh.frag.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3649247/glsh.frag.txt)

**Comment by greg-lunarg** [comment]
@s-perron Can you please review the proposal above?

**Comment by s-perron** [comment]
We could do something like that.  That gives me another idea.  We could write an analysis that determines which functions are call from within a continue construct.  This seems like it would be a simple analysis.  Then that could be used in wrap-opkill and inlining.

In wrap-opkill, we apply the transformation only if a function is called from a continue construct.  In most cases, this will mean that wrap-opkill does not do anything.  Most of the work will be in updating the tests.

In inlinine, we say that if a function is called from a continue construct and it contains an opkill, we do not inline.  It could be the function will not be inlined in every place it could.  If it is call from multiple places, but only one is in a continue construct, then we will never inline it.  However, in the most common cases, everything will be inlined.

I would be okay with either idea.  Whatever you think is best.

**Comment by greg-lunarg** [comment]
Yes, Your idea sounds very good.

Do you have time to do this in the near future? I am working on OpDebugPrintf support which I am a little behind delivering on.
