### ISSUE TITLE
InstBuffAddrCheckPass should not use null physical storage buffer pointers

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#2929]
https://github.com/KhronosGroup/SPIRV-Registry/pull/51 updated the EXT version of the extensions and https://github.com/KhronosGroup/SPIRV-Registry/pull/50 updated the KHR version. Physical storage buffer pointers cannot be used with OpConstantNull (or OpPtrEqual, OpPtrNotEqual or OpPtrDiff).

The pass should instead convert the pointer before generating the OpPhi and use a 64-bit integer or uvec2 0 value.

@greg-lunarg, I am disabling validation in one of the tests until this is resolved.

**Comment by greg-lunarg** [comment]
Dang! Forgot about that case :(

Will convert a uint64 zero to the pointer type.
