### ISSUE TITLE
ValidateExecutionScope is incorrect for OpReadClockKHR

### ISSUE THREAD

**Issue by alegal-arm** [KhronosGroup/SPIRV-Tools#2952]
spirv-val subjects OpReadClockKHR to generic Vulkan rules regarding execution scope, i.e. 
Scope for execution must be limited to:
◦ Workgroup
◦ Subgroup

However the spec actually says that 
Scope for OpReadClockKHR must be limited to:
◦ Subgroup ...
◦ Device ...

**Comment by alegal-arm** [comment]
@AaronHaganAMD @alan-baker can you have a look?

**Comment by alan-baker** [comment]
The currently published spec says:
> All invocations within the Execution read from the same source clock. Execution must be a valid execution scope.

And Vulkan limits execution scopes to workgroup and subgroup.

**Comment by alegal-arm** [comment]
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/pdf/vkspec.pdf v 1.1.124
p. 1574
```
Scope for OpReadClockKHR must be limited to:
◦ Subgroup
▪ if shaderSubgroupClock is not enabled, the Subgroup scope must not be used.
◦ Device
▪ if shaderDeviceClock is not enabled, the Device scope must not be used
```

**Comment by alan-baker** [comment]
The Vulkan spec is inconsistent then IMO and needs fixed. In the SPIR-V extension we intentionally made it an execution scope to fall in with what already existed.

**Comment by alan-baker** [comment]
I will disable scope validation until this gets resolved

**Comment by alan-baker** [comment]
Vulkan internal issue 1854

**Comment by alegal-arm** [comment]
Just to give the full picture. glslang actually generates Device scope for OpReadClockKHR

https://github.com/KhronosGroup/glslang/issues/1923
