### ISSUE TITLE
Add description for wrap-opkill

### ISSUE THREAD

**Issue by Keryen** [KhronosGroup/SPIRV-Tools#2965]
Dear all,

I have seen the spriv-opt options and I saw that the option -O apply several flags, but i do not know if it apply them in the order they appear at the information in "spirv-opt --help":

	        wrap-opkill
		eliminate-dead-branches
		merge-return
		inline-entry-points-exhaustive
		eliminate-dead-code-aggressive
		private-to-local
		eliminate-local-single-block
		eliminate-local-single-store
		eliminate-dead-code-aggressive
		scalar-replacement=100
		convert-local-access-chains
		eliminate-local-single-block
		eliminate-local-single-store
		eliminate-dead-code-aggressive
		ssa-rewrite
		eliminate-dead-code-aggressive
		ccp
		eliminate-dead-code-aggressive
		redundancy-elimination
		combine-access-chains
		simplify-instructions
		vector-dce
		eliminate-dead-inserts
		eliminate-dead-branches
		simplify-instructions
		if-conversion
		copy-propagate-arrays
		reduce-load-size
		eliminate-dead-code-aggressive
		merge-blocks
		redundancy-elimination
		eliminate-dead-branches
		merge-blocks
		simplify-instructions

Could someone confirm me this doubt?

Also, it mention the option --wrap-opkill, but it does not appear at help information, but I saw it at the options directoy for spirv-opt: 
/spirv-tools/build/source/opt/CMakeFiles/SPIRV-Tools-opt.dir/wrap_opkill.cpp.o

Can I apply that flag individually like "spirv-opt --wrap-opkill input.spv -o output.spv" ??

**Comment by greg-lunarg** [comment]
You can find the different optimization recipes in optimizer.cpp. But yes, it appears this is the recipe for -O and yes, they are run in this order. They are listed in RegisterPerformancePasses().

Yes, it seems the --wrap-opkill is not in the --help. I think this was inadvertant, but I will let the author make the final call there.

And yes, --wrap-opkill can be applied as you have applied it if you wish.

**Comment by s-perron** [comment]
I'll add the help info for warp opkill.  It was suppose to be there.  Thanks for your questions, and pointing out the problems.
