### ISSUE TITLE
spirv-fuzz assertion failure in FuzzerPassObfuscateConstants

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2973]
[This test](https://github.com/KhronosGroup/SPIRV-Tools/files/3735483/newtest.txt), to be added to fuzzer_replayer_test.cpp, exposes the issue.

**Comment by afd** [comment]
@Vasniktel perhaps you could pick this one up?  It would involve adding the shader attached to the issue to the shaders that are used in fuzzer_replayer_test, and running those tests to see whether an assertion failure still triggers.

If it doesn't, fine - we add the test and close the issue.

If an assertion failure does trigger, we investigate.

(Looks like when making the issue I did not give details of the failure.)

**Comment by Vasniktel** [comment]
Sure, I'll take a look.

**Comment by Vasniktel** [comment]
I didn't find an assertion failure but I did find a validation issue. This is the message:
```
error: line 817: Header block 1138[%1138] is contained in the loop construct headed by 1132[%1132], but its merge block 1146[%1146] is not
  %1138 = OpLabel
```
There seems to be a problem with the loop here:
```spirv
%1132 = OpLabel
       %1969 = OpPhi %6 %35 %1128 %2576 %1146
       %1137 = OpINotEqual %51 %1969 %39
               OpLoopMerge %1133 %1146 None
               OpBranchConditional %1137 %1138 %1133
       %1138 = OpLabel
       %1140 = OpAccessChain %8 %58 %1969
       %1141 = OpLoad %7 %1140
       %1552 = OpCompositeExtract %6 %1141 0
       %1553 = OpCompositeExtract %6 %1141 1
       %1554 = OpCompositeExtract %6 %1141 2
       %1145 = OpIEqual %51 %1552 %178
               OpSelectionMerge %1146 None
               OpBranchConditional %1145 %1147 %1146
       %1147 = OpLabel
               OpBranch %1133
       %1146 = OpLabel
       %1152 = OpSGreaterThan %51 %178 %1552
       %2576 = OpSelect %6 %1152 %1554 %1553
               OpBranch %1132
       %1133 = OpLabel
       %1976 = OpPhi %6 %1895 %1132 %178 %1147
       %1971 = OpPhi %51 %371 %1132 %374 %1147
               OpSelectionMerge %1162 None
               OpBranchConditional %1971 %1129 %1162
```

**Comment by Vasniktel** [comment]
It seems like the block `%1146` is both the continue target for the `%1132` loop and the merge block for `%1138` `OpSelectionMerge`. I don't think this should cause the problem though. Also, we might still add this test to the file but mark it as disabled.

**Comment by Vasniktel** [comment]
According to https://github.com/KhronosGroup/SPIRV-Tools/issues/3260 this shader is invalid.

**Comment by afd** [comment]
Ah, right - in that case I suggest we close this issue.  Some months ago such shaders were not correctly picked up as invalid - the validator got fixed to pick them up and we had to change quite a few test shaders in response.
