### ISSUE TITLE
upgrading memory model (spirv-opt)

### ISSUE THREAD

**Issue by Carandiru0** [KhronosGroup/SPIRV-Tools#2992]
I'm having a consistent problem enabling "upgrade memory model" on Vulkan glsl geometry shaders only. I can enable this switch for all my other shaders and it succeeds just fine when using spirv-opt

I first compile all my Vulkan GLSL shaders with:
`"$(VULKAN_SDK)\bin\glslangValidator.exe" -V110 --target-env vulkan1.1 "%(FullPath)" -o "%(FullPath)\..\Binary\%(Filename)%(Extension).bin"`

then there is a batch file that runs at the end of the build that runs spirv-opt:
(attached file)
[BATCH_optimize.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3775274/BATCH_optimize.txt)

Maybe someone will find this batch useful, at the moment it works with the issue if the spirv-opt process fails with the memory model option on, by running spirv-opt again with the same options excluding the memory model upgrade option.

Is there a known issue with geometry shaders and the Vulkan memory model?
spirv-opt specifically fails on only geometry shaders for me.

Thanks!

**Comment by dneto0** [comment]
Is it general to all geometry shaders?  Can you submit an example we can test with?

**Comment by Carandiru0** [comment]
sure I can submit an example, I don't know if it is all geometry shaders as I have only tried the ones I have written.  I have posted the geometry shader on pastebin at:
[https://pastebin.com/VRLiky81](https://pastebin.com/VRLiky81)

compiled with:
"$(VULKAN_SDK)\bin\glslangValidator.exe" -V110 --target-env vulkan1.1 "%(FullPath)" -o "%(FullPath)\..\Binary\%(Filename)%(Extension).bin"
