### ISSUE TITLE
Warnings from JPMS JVM

### ISSUE THREAD

**Issue by Graou74** [KhronosGroup/SPIRV-Tools#2993]
Hello,
Just a little post to report a warning that for the moment does not affect the smooth running of the program but may change in the future.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by graphics.scenery.spirvcrossj.Loader (file:/Users/  ...  jar) to field java.lang.ClassLoader.sys_paths
WARNING: Please consider reporting this to the maintainers of graphics.scenery.spirvcrossj.Loader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
The operating system is Mac Osx.
The JVM is from OpenJDK 11.
The SPIR-V java library is spirvcrossj version 0.6.0-1.1.106.0 loaded from Gradle.

I also noticed that when the library is included in a distribution jar file, its loading fails.
For some reason that I did not deepen, the temporary local directory intended to accommodate the copy of the lib file to be loaded remains empty.
I work around the problem by implementing code that forces the loading of the library.

**Comment by dneto0** [comment]
This is not the right repository for this issue.
It seems this issue should be filed against https://github.com/scenerygraphics/spirvcrossj
