### ISSUE TITLE
Enable iOS platform

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/SPIRV-Tools#2994]
CMake 3.15 added [first-class support for iOS builds](https://cmake.org/cmake/help/v3.15/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos).
Xcode projects targeting iOS can be generated by specifying `-DCMAKE_SYSTEM_NAME=iOS` in the command line, but CMake fails with the following error:

```
CMake Error at ThirdParty/SPIRV-Tools/CMakeLists.txt:56 (message):
  Your platform 'iOS' is not supported!
```

There should be no major problems adding iOS support as I can already successfully build the project for iOS by specifying custom CMake toolchain. As a matter of fact, just treating iOS similar to Darwin makes the project build OK.

**Comment by dneto0** [comment]
> As a matter of fact, just treating iOS similar to Darwin makes the project build OK.

Ah, that's useful info.

**Comment by DiligentGraphics** [comment]
Works great now, thanks!
