### ISSUE TITLE
Improve RegisterSizePasses?

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#3004]
I propose a new recipe for RegisterSizePasses:

Optimizer& Optimizer::RegisterSizePasses() {
  return RegisterPass(CreateWrapOpKillPass())
      .RegisterPass(CreateDeadBranchElimPass())
      .RegisterPass(CreateMergeReturnPass())
      .RegisterPass(CreateInlineExhaustivePass())
      .RegisterPass(CreateEliminateDeadFunctionsPass())
      .RegisterPass(CreatePrivateToLocalPass())
      .RegisterPass(CreateFixStorageClassPass())
      .RegisterPass(CreateScalarReplacementPass(0))
      .RegisterPass(CreateLocalMultiStoreElimPass())
      .RegisterPass(CreateCCPPass())
      .RegisterPass(CreateLoopUnrollPass(true))
      .RegisterPass(CreateDeadBranchElimPass())
      .RegisterPass(CreateSimplificationPass())
      .RegisterPass(CreateScalarReplacementPass(0))
      .RegisterPass(CreateLocalSingleStoreElimPass())
      .RegisterPass(CreateIfConversionPass())
      .RegisterPass(CreateSimplificationPass())
      .RegisterPass(CreateAggressiveDCEPass())
      .RegisterPass(CreateDeadBranchElimPass())
      .RegisterPass(CreateBlockMergePass())
      .RegisterPass(CreateLocalAccessChainConvertPass())
      .RegisterPass(CreateLocalSingleBlockLoadStoreElimPass())
      .RegisterPass(CreateAggressiveDCEPass())
      .RegisterPass(CreateCopyPropagateArraysPass())
      .RegisterPass(CreateVectorDCEPass())
      .RegisterPass(CreateDeadInsertElimPass())
      .RegisterPass(CreateEliminateDeadMembersPass())
      .RegisterPass(CreateLocalSingleStoreElimPass())
      .RegisterPass(CreateBlockMergePass())
      .RegisterPass(CreateLocalMultiStoreElimPass())
      .RegisterPass(CreateRedundancyEliminationPass())
      .RegisterPass(CreateSimplificationPass())
      .RegisterPass(CreateAggressiveDCEPass())
      .RegisterPass(CreateCFGCleanupPass());
}

Background:

A month or so back, a user noted on Slack that dxc for SPIR-V was not doing a sufficient job of optimizing a shader. The SPIR-V optimization was leaving some unused samples which was requiring them to bind unneeded textures. The dxc optimization for DX byte code was able to get rid of all unused texture sample instructions. I offered to look into the situation.

In order to get the sufficient results, I essentially needed to run the "legalization" recipe and run two iterations of the "size" recipe. I then created a new "size" recipe based on this process. I essentially concatenated these recipes and, starting at the beginning of the recipe, removed all passes that had no effect on the size of the final code.

I did a little more tinkering to fix any regressions on a set of real-life shaders I have collected over the years. The results are above.

Other considerations:

Essentially, this is a recipe based on a couple fairly well-thought out optimization recipes, a simplistic concatenation/elimination process and empirical results. I really have not completely intellectually thought through the resulting recipe or looked a lot at why the current passes and order are required.

For example, I am a little surprised that the first invocation of "dead member elimination" has an effect on following passes.

I have done regression testing of this new recipe on a couple hundred different real-life shaders I have collected over the years. I am generally seeing a 10% reduction in size over the previous recipe.

I have tried tacking an additional round of passes to the end of it but did not see much additional benefit. 

Ultimately, we might want to come up with some type of dynamic algorithm that iterates until some sort of steady state or diminishing returns is hit. But for the moment I know that this algorithm seems to work better than the one we have.

One departure from the previous "size" recipe is that this recipe does unrolling. In fact, it uses the entire "legalization" recipe as its base. This was done partly because the original shader that precipitated this study required unrolling to get the desired code elimination. I think it sort of makes sense that the "size" recipe contains "legalization" as a by-product since "legalization" is designed to be a minimal amount of optimization to achieve a goal (legal Vulkan code from HLSL). It seems intuitive that any larger scope goal such as size reduction would include the legalization recipe as a subset.

It doesn't look like dxc is using RegisterSizePasses. glslangValidator is not using it. There does not seem to be any regression tests for it, so I am a little uncertain as to what the exact criteria is to change it. Google and LunarG have been doing some extra regression testing of spirv-opt when they publish a new "stable" branch. I am assuming that that process will be a sufficient regression test for this option.

The spirv-opt --help does warn that the recipe for -Os can change.

**Comment by s-perron** [comment]
We are okay with you changing it.  You can open a PR, and I can look at it closer.  I just have 1 comment for now.

CreateFixStorageClassPass: this is really only needed is legalization.  I comes out of a specific code pattern that DXC generates where actual parameter do not match the type of the formal parameters.

**Comment by greg-lunarg** [comment]
Addressed with #3059
