### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.discard-continue-return

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3031]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[discard-continue-return.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833315/discard-continue-return.zip)

**Comment by s-perron** [comment]
This is invalid spir-v that is not getting caught by the validator.  The relevant portion of the spir-v is given below.

Notice that `%34` is the continue for the loop, and the merge for the inner selection construct.  The spec says "when a construct contains another header block, it also contains that header’s corresponding merge block if that merge block is reachable in the CFG."  So `%34` is in the selection construct with header `%35`.  However, this means that the branch from `%34` to `%32` exits the selection construct, but that is not a valid exit from the construct.

```
%32 = OpLabel
OpLoopMerge %33 %34 None
OpBranch %35
%35 = OpLabel
%36 = OpAccessChain %14 %3 %13
%37 = OpLoad %9 %36
%38 = OpFOrdLessThan %16 %37 %15
OpSelectionMerge %39 None
OpBranchConditional %38 %40 %39
%40 = OpLabel
%41 = OpAccessChain %23 %6 %21 %22
%42 = OpLoad %9 %41
%43 = OpFOrdGreaterThan %16 %17 %42
OpSelectionMerge %34 None
OpBranchConditional %43 %44 %34
%44 = OpLabel
OpKill
%34 = OpLabel
OpBranchConditional %24 %32 %33
%39 = OpLabel
OpBranch %33
%33 = OpLabel
```

**Comment by paulthomson** [comment]
@alan-baker shared the WIP fix for this. The fix appears to be detecting a certain type of invalid SPIR-V:

Blocks:

```
loop header
  |
  selection header
  |  |
  | block               ^ (back-edge)
  |  |                  |
  selection merge / loop continue construct (continue target and back-edge block)
  |
loop merge
```

(The selection merge is required to be contained within the loop construct, yet the continue construct is NOT part of the loop construct, so this is invalid...or at least a contradiction!)

But I was actually thinking about a different issue that I *thought* this test also highlighted: a nested continue construct. E.g.


Blocks:

```
loop header
  |
  selection header     ^ (back-edge)
  | |                  |
  | loop continue construct (continue target and back-edge block)
  |
  selection merge
  |
loop merge
```

Is this valid? @s-perron described the back-edge as being the invalid exit from the selection construct, hence why I thought about this issue. And indeed, I was picturing the back-edge in the above example as being an invalid exit. But actually, the loop construct is not part of the selection construct (otherwise it would be part of the loop construct, which is not the case). And branching to the continue target is a valid exit from a selection construct. So I guess this example is valid?

**Comment by s-perron** [comment]
I'll let Alan given a more detailed response.  The first example should be find.  The continue is not in the selection.  The second example seem fine as is because even if you draw it that way, the continue would still be technically outside of the selection construct.

However, if you add a second section around the selection construct in the first example, so that the continue target is the merge of the inner selection, then we start having problems.

**Comment by alan-baker** [comment]
@paulthomson in your second example, the branch to the continue target is an exit from selection (like a conditional continue statement). So the continue is not part of the selection. The selection is part of the loop and the loop contains the selection merge.

**Comment by paulthomson** [comment]
@alan-baker Thanks that makes sense. (I corrected a typo, so my previous description of the second example hopefully makes more sense.)

Just to confirm: what about the first example? Is it valid?

**Comment by alan-baker** [comment]
The first example is invalid because the continue construct is not part of the loop construct and the selection is straddling them.

**Comment by paulthomson** [comment]
Great thanks. That makes sense. @s-perron I wasn't quite sure what you meant about my first example, but do you agree that my first example is invalid? This causes quite a lot of SPIR-V output by spirv-opt to be invalid (in our tests). If we all agree, then it is great news that the validator will soon catch this. And bad news that we will have to remove/modify a lot of GraphicsFuzz dEQP tests!

**Comment by s-perron** [comment]
The example in https://github.com/KhronosGroup/SPIRV-Tools/issues/3031#issue-521201430 is invalid.

From the sketches in https://github.com/KhronosGroup/SPIRV-Tools/issues/3031#issuecomment-557705630, I believe both of those should be valid.

**Comment by paulthomson** [comment]
According to @alan-baker the first sketch in https://github.com/KhronosGroup/SPIRV-Tools/issues/3031#issuecomment-557705630 is actually **invalid**. I think I get it now.

**Comment by paulthomson** [comment]
(Edited my earlier comment to label the examples as sketch 1 and sketch 2). I believe the WIP validator patch by @alan-baker also flags a file similar to sketch 1 as invalid.

**Comment by paulthomson** [comment]
Discussed offline.

* attached file in the first comment: invalid
* sketch 1: invalid
* sketch 2: valid

**Comment by paulthomson** [comment]
Attach another file that I think should be invalid, but I think is missed by the WIP validator patch. 

[invalid_ct.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3887995/invalid_ct.zip)


```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 18
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
               OpSource ESSL 310
               OpName %4 "main"
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
         %11 = OpTypeBool
         %12 = OpConstantFalse %11
          %4 = OpFunction %2 None %3

          %5 = OpLabel
               OpBranch %6

          %6 = OpLabel
               OpLoopMerge %8 %15 None
               OpBranchConditional %12 %13 %8

            %13 = OpLabel
                  OpLoopMerge %15 %16 None
                  OpBranchConditional %12 %14 %15

                  %14 = OpLabel
                        OpBranch %16

                  %16 = OpLabel
                        OpBranch %13

            %15 = OpLabel
                  OpBranch %6

          %8 = OpLabel
               OpReturn
               OpFunctionEnd

```
