### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.discard-in-loop-in-function

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3032]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[discard-in-loop-in-function.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833318/discard-in-loop-in-function.zip)

**Comment by s-perron** [comment]
Duplicate of #3031.
