### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.discard-in-loop

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3033]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[discard-in-loop.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833323/discard-in-loop.zip)

**Comment by s-perron** [comment]
Duplicate of #3031.
