### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.do-while-with-always-true-if

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3034]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[do-while-with-always-true-if.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833328/do-while-with-always-true-if.zip)

**Comment by s-perron** [comment]
Duplicate of #3030.
