### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.return-before-writing-wrong-color

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3035]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[return-before-writing-wrong-color.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833331/return-before-writing-wrong-color.zip)

**Comment by s-perron** [comment]
Duplicate of #3030.
