### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.return-float-from-while-loop

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3036]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[return-float-from-while-loop.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833334/return-float-from-while-loop.zip)

**Comment by s-perron** [comment]
Duplicate of #3031.
