### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.undefined-integer-in-function

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3039]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[undefined-integer-in-function.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833350/undefined-integer-in-function.zip)

**Comment by s-perron** [comment]
I cannot reproduce.  @paulthomson Can you double check if this is failing for you?

**Comment by paulthomson** [comment]
Oops sorry. You need to do:

```
spirv-opt -O --validate-after-all -o temp.spv *.spv
```

**Comment by s-perron** [comment]
This is a duplicate of #3031.
