### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.uninitialized-var-decrement-and-add

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3040]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[uninitialized-var-decrement-and-add.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833351/uninitialized-var-decrement-and-add.zip)

**Comment by s-perron** [comment]
@greg-lunarg This is segfaulting in code that you wrote.  Can you take a look?

**Comment by s-perron** [comment]
The problem is that there is an implicit type conversion for integers:

```
          %5 = OpISub %uint %25 %int_1
          %6 = OpIAdd %uint %uint_178493 %5
```

The `OpISub` interprets `int_1` as an unsigned integer.  When the instruction folder tries to combine `%uint_178493` and `%int_1`, it complain that the types do not match.  However, for integer types this is not a problem.
