### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.unreachable-discard-statement

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3042]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[unreachable-discard-statement.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833353/unreachable-discard-statement.zip)

**Comment by s-perron** [comment]
Duplicate of #3038
