### ISSUE TITLE
unnecessary copy when using matrices

### ISSUE THREAD

**Issue by ehsannas** [KhronosGroup/SPIRV-Tools#3067]
The high-level shader for this issue was reported on https://github.com/microsoft/DirectXShaderCompiler/issues/2598.

The issue comes down to a matrix variable that seems unnecessary to have. It is initialized by copying the matrix from another variable and only used once. (hence the original matrix variable could have been used). The user is reporting a 17x slowdown (the duration in RenderDoc for the draw using this shader is ~1300μs with the copy and ~75μs without the copy).

The HLSL shader is:
```hlsl
struct PSInput
{
    float4 color : COLOR;
};

cbuffer bob
{
    float4x3 matrices[3];  
};

struct compute_params
{
    uint index;
    float4x3 input_matrices[3];  
};

inline float3 compute_result(float4x3 input_matrices[3], uint index)
{
    return input_matrices[index][0];
}

float4 main(PSInput input) : SV_TARGET
{
    float4 result = input.color;
    
    compute_params p;
    for (uint i = 0; i < 3; i++) {
        p.input_matrices[i] = matrices[i];
    }
    p.index = 0;
    
    result.xyz += compute_result(p.input_matrices, p.index);
    return result;
}

```

Here is the compilation result to SPIR-V:
http://shader-playground.timjones.io/6159d5ca53c9ddbfcaab4199fac479ec

specifically note:
```spir-v
         %29 = OpVariable %_ptr_Function__arr_mat4v3float_uint_3_0 Function
         %30 = OpVariable %_ptr_Function__arr_mat4v3float_uint_3_0 Function
         %41 = OpLoad %_arr_mat4v3float_uint_3_0 %29
               OpStore %30 %41

       ; uses %30 for the remainder of the shader (could have used %29 instead)
```

@s-perron can you share your thoughts on this?
Thanks

**Comment by s-perron** [comment]
Are they willing to add the unroll directive to the loop?  After that we would have to look into what scalar replacement does.  If we cannot add the unroll directive, then anything that can be done will be very difficult.

We would also need some more information on what id done in the real `compute_result` function.  Are real matrix operations done?  Can all values used to index the matrix constant?  Other uses effect how complex the analysis needs to be in order to do the copy propagation.

**Comment by Vincent-P** [comment]
Hi, I started the issue in the DXC repository.
Adding `[unroll]` before the loop doesn't change anything.
Furthermore, does the real `compute_result` really matters as even with this simple function there is an unecessary copy?

**Comment by s-perron** [comment]
I agree that adding `[unroll]` will not solve the problem on its own, but, if the source cannot be changed in this way there there is no way of doing it.

As for the real `compute_result`, it is possible for me to do something to get this simple case.  However, that is not guarantee that will be able to get the more complicated real case.  Before I do anything I want to try to understand the real problem, so you don't have to come back with 5 different examples.  Anything you can tell us will be useful.

**Comment by Vincent-P** [comment]
The real case is also kind of simple, it just reads from the matrices using a variable as index.

```
struct compute_params
{
    float4x3 input_matrices[3];  
    ...
};

inline float3 compute_result(compute_params p)
{
    uint index = 0;
    ... code computing an index ...
    uint something = ... value computed from p.input_matrices[index] ...;
   ...
}
```
