### ISSUE TITLE
Validate Vulkan rules for Workgroup scope/storage class in stages

### ISSUE THREAD

**Issue by dgkoch** [KhronosGroup/SPIRV-Tools#3069]
New rules being added by an internal [MR](https://gitlab.khronos.org/vulkan/vulkan/merge_requests/3484)

Scope for execution:
```
  *** The *Workgroup* scope must: only be used in the
ifdef::VK_NV_mesh_shader[]
      task, mesh,
endif::VK_NV_mesh_shader[]
      tessellation control, and compute execution models.
```

Scope for memory: 
```
   *** The *WorkGroup* scope must: only be used in the
ifdef::VK_NV_mesh_shader[]
      task, mesh, and
endif::VK_NV_mesh_shader[]
      compute execution model(s).
```

For storage classes:
```
  *** The *Workgroup* storage class must: only be used in the
ifdef::VK_NV_mesh_shader[]
      task, mesh, and
endif::VK_NV_mesh_shader[]
      compute execution model(s).
```

Note the quirk of the Workgroup execution scope only that is allowed in the TCS, primarily because this is what glslang uses and we don't have anything better without an extension to add patch scope.

**Comment by alan-baker** [comment]
This should be done by adding execution model limitations in ValidateMemoryScope and ValidateExecutionScope if the scope is Workgroup and its a Vulkan environment. Likewise, add an execution model limitation in ValidateVariable for Workgroup storage class if in the Vulkan environment.

**Comment by sfricke-samsung** [comment]
these translate now to

- VUID-StandaloneSpirv-None-04637 (waiting on internal issue 2497 as related code path)
- VUID-StandaloneSpirv-None-04639 (added https://github.com/KhronosGroup/SPIRV-Tools/pull/4106)
- VUID-StandaloneSpirv-None-04645 (planning to do already)
