### ISSUE TITLE
Lots of SPIRV Validation failure in tfjs-webgpu are shown with #3068

### ISSUE THREAD

**Issue by qjia7** [KhronosGroup/SPIRV-Tools#3085]
Lots of SPIRV Validation failure are shown as below with patch https://github.com/KhronosGroup/SPIRV-Tools/pull/3068:
```
SPIRV Validation failure:
error: line 78: Header block 139[%139] is contained in the loop construct headed by 138[%138], but it's merge block 155[%155] is not
  %139 = OpLabel
```
Steps to reproduce:
1. set CHROME_BIN='path/to/google chrome canary'
2. git clone https://github.com/tensorflow/tfjs
3. cd tfjs/tfjs-backend-webgpu
4. yarn
5. yarn test --no-single-run
6. In the opened browser, click 'Debug' -> right click-> Inspect -> Console

Note: Must use 'Google Chrome Canary' since we need webgpu support.

**Comment by qjia7** [comment]
cc @annxingyuan

**Comment by dj2** [comment]
That's a new, valid validation that has been added. There are a few possibilities of what's going wrong, and a bit more information would help us track down the issue.

1- Which Chrome canary are you testing with?
2- Can you dump the problematic shader source to the console and paste it here? We can then run it through glslang and the optimizer to make sure there isn't a case we've missed?

**Comment by kainino0x** [comment]
Yup, if we have the GLSL shader source then we can easily look into why this changed.

It's possible that the version of glslang we're using in tf.js is too old and just doesn't output the correct spir-v (it's very old). @annxingyuan was looking at getting glslang updated - if we're lucky, maybe that will just fix it.

**Comment by qjia7** [comment]
Just verified that this issue disappears after upgrading the glslang version with Ann's fix https://github.com/tensorflow/tfjs/pull/2474. Close this one. Thanks.

**Comment by kainino0x** [comment]
Awesome!
