### ISSUE TITLE
spirv-fuzz: have outliner use some auxiliary transformations to handle more complex control flow

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3095]
Following dicussion on #3078, the outlining transformation has been made more restrictive with respect to the control flow that it handles.

[These tests](https://github.com/KhronosGroup/SPIRV-Tools/files/3944974/disabled_tests.txt) were removed.  The outliner should be enhanced so that it can use other transformations - such as block splitting and merging - to be capable of applying outlining in the contexts captured by the tests what were removed.

**Comment by afd** [comment]
@stefanomil Can you take a look at this one?  Please reply and I can assign it.  We'll discuss it with you in some detail.

**Comment by stefanomil** [comment]
Yes

**Comment by afd** [comment]
Comments following our discussion about this:

In the fuzzer pass:
- If the entry block starts with OpVariable, split the entry block after the final OpVariable and make the new block be the entry block.
- If the entry block is a loop header, check whether there is already a loop pre-header - i.e., a single predecessor not in the loop that branches unconditionally to the loop header.  If so, use this.  If not, apply a (new) transformation to add a pre-header to the loop and make the entry block be the pre-header.
- If the exit block is a merge block, split the merge block and make the exit block be the second block in the pair.

When populating "candidate exit blocks", skip any blocks that are continue targets.
