### ISSUE TITLE
What does the "index" field mean in a spv_position_t for a diagnostic on binary parse and validation?

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#31]
The binary parser uses "index" to indicate word offset into the binary.
The validator pull request uses "index" as the instruction count.  
https://github.com/KhronosGroup/SPIRV-Tools/pull/27 

It's not 100% clear which is better, and the definition of spv_position_t is silent on this point.

Need to decide what is the right interpretation, and stick to it.

**Comment by dj2** [comment]
Duping this into #1810 as it has more discussion on this point.
