### ISSUE TITLE
DebugFunction has a function as its operand which results in spirv-val "not defined ID" error

### ISSUE THREAD

**Issue by jaebaek** [KhronosGroup/SPIRV-Tools#3102]
DebugFunction must be located before a function definition based on the layout rule in the debug info spec:

"All other debugging instructions should be located between section 9
(All type declarations (OpTypeXXX instructions), all constant instructions, and
all global variable declarations …​) and section 10 (All function declaration)
per the core SPIR-V specification."

However, DebugFunction has a function id as one of its operands which results in "not defined ID" error when we run spirv-val

```
; Function information
%main_info = OpExtInst %void %DbgExt DebugFunction %main_name %main_type_info %dbg_src 6 1 %comp_unit %main_linkage_name FlagIsPublic 7 %main

       %main = OpFunction %void None %16
```

outputs

```
error: line 54: ID 2[%main] has not been defined
  %44 = OpExtInst %void %1 DebugFunction %14 %42 %35 6 1 %36 %15 FlagIsProtected|FlagIsPrivate 7 %main
```

**Comment by alan-baker** [comment]
You could just have the DebugFunction occur after the OpFunctionEnd and it would satisfy the use/def rules. If the debug extension specifically allows new forward references, then the validator should be relaxed.

**Comment by alan-baker** [comment]
I guess the spec intended to allow forward references based on the that text.

**Comment by jaebaek** [comment]
Yeah, I guess we must allow forward references to `OpFunction` from `DebugFunction`.
