### ISSUE TITLE
Why VS 2016? -.-

### ISSUE THREAD

**Issue by asylum2010** [KhronosGroup/SPIRV-Tools#311]
Pal...I know you will close this issue, but for God's sake. I'm spending HOURS trying to make this thing compile with VS2010, currently stuck with an internal compiler error related to your "negatable_left_shift" template magic, C interface with C++11 internal implementation...seriously...fuck you!

**Comment by dneto0** [comment]
I hear you.  I'm sorry that code is causing you trouble.

In fact that negatable_left_shift template magic is already a workaround to various frustrating compiler differences. We support Darwin, Linux x86-64, Windows, MinGW-for-windows (32 and 64 bits), and 7 different Android ABIs.

Unfortunately we don't support VS2010.

I'll leave this issue open in case someone can propose a good fix that still meets our portability constraints.

As for the last point, C interface with C++ internals, I refer you to the following blog post and follow-on  Cppcon talk:
http://blog.sduto.it/2014/05/a-c-error-handling-style-that-plays.html
http://www.slideshare.net/StefanusDuToit/cpp-con-2014-hourglass-interfaces-for-c-apis and also 

Thank you for your interest in this project!

**Comment by asylum2010** [comment]
I ended up calling the assembler executable with ShellExecuteEx(). Duh...
Anyway here is a possible solution for this negatable left shift (compiles, but not tested tho):

```
  template <int_type N>
  struct negatable_left_shift {
    static uint_type val(uint_type val) {
      if (N < 0) {
        uint_type newN = (uint_type)(-N);
        return static_cast<uint_type>(val >> newN);
      }

      uint_type newN = (uint_type)N;
      return static_cast<uint_type>(val << newN);
    }
  };
```

**Comment by dj2** [comment]
I'm going to close this as wont fix. It's been 2 years since it was opened, newer compilers are out, 2010 is very old at this point.
