### ISSUE TITLE
Build regression in GN from recent commit

### ISSUE THREAD

**Issue by null77** [KhronosGroup/SPIRV-Tools#3120]
Example failing builds:

https://chromium-review.googlesource.com/c/angle/angle/+/1978600
https://chromium-review.googlesource.com/c/chromium/src/+/1978604

Error message:

```

ERROR at //third_party/spirv-tools/src/BUILD.gn:177:7: Undefined identifier
      debug_insts_file,
      ^---------------
See //third_party/spirv-tools/src/BUILD.gn:260:1: whence it was called.
spvtools_language_header("debuginfo") {
^--------------------------------------
See //third_party/glslang/src/BUILD.gn:196:5: which caused the file to be included.
    "${spirv_tools_dir}:spvtools_opt",
    ^--------------------------------
```

Regression range:

https://chromium.googlesource.com/external/github.com/KhronosGroup/SPIRV-Tools.git/+log/e70b009b0f1e..64f36ea5296e

Suspecting 64f36ea5296ec023f65f75d7 "Support OpenCL.DebugInfo.100 extended instruction set (#3080)" by dneto@google.com since that's the only one that changed the GN.

@dneto0 can you investigate?

**Comment by zoddicus** [comment]
This is blocking rolling DEPS in Dawn.
