### ISSUE TITLE
Grammatical error in an error message

### ISSUE THREAD

**Issue by bioglaze** [KhronosGroup/SPIRV-Tools#3121]
This line contains `it's` instead of `its`:

    error: line 333: Header block 768[%768] is contained in the loop construct headed by 761[%761], but it's merge block 775[%775] is not

I found the file in here:
https://github.com/KhronosGroup/SPIRV-Tools/blob/b334829a91d6bcbbf6e101ca54adccb113a24fa9/source/val/validate_cfg.cpp

**Comment by ben-clayton** [comment]
Appears fixed: https://github.com/KhronosGroup/SPIRV-Tools/commit/fad92f1e7e5b90df69fcf9be70fd006e1c540dc1
