### ISSUE TITLE
Linux compile error in hex_float.h

### ISSUE THREAD

**Issue by mrzerg** [KhronosGroup/SPIRV-Tools#313]
Hi,

I'm compiling SPIRV-Tools on linux, and run into a compiling error:

`In file included from ../../../../../../../../../bil/khronos/source/SPIRV-tools/source/disassemble.cpp:44:0:
../../../../../../../../../bil/khronos/source/SPIRV-tools/source/util/hex_float.h: In instantiation of 'typename other_T::uint_type spvutils::HexFloat<T, Traits>::getRoundedNormalizedSignificand(spvutils::round_direction, bool*) [with other_T = spvutils::HexFloat<spvutils::FloatProxy<spvutils::Float16>, spvutils::HexFloatTraits<spvutils::FloatProxy<spvutils::Float16> > >; T = spvutils::FloatProxy<float>; Traits = spvutils::HexFloatTraits<spvutils::FloatProxy<float> >; typename other_T::uint_type = short unsigned int]':
../../../../../../../../../bil/khronos/source/SPIRV-tools/source/util/hex_float.h:591:40:   required from 'void spvutils::HexFloat<T, Traits>::castTo(other_T&, spvutils::round_direction) [with other_T = spvutils::HexFloat<spvutils::FloatProxy<spvutils::Float16>, spvutils::HexFloatTraits<spvutils::FloatProxy<spvutils::Float16> > >; T = spvutils::FloatProxy<float>; Traits = spvutils::HexFloatTraits<spvutils::FloatProxy<float> >]'
../../../../../../../../../bil/khronos/source/SPIRV-tools/source/util/hex_float.h:826:51:   required from here
../../../../../../../../../bil/khronos/source/SPIRV-tools/source/util/hex_float.h:501:63: internal compiler error: in dependent_type_p, at cp/pt.c:19523
             : negatable_left_shift<num_throwaway_bits>::val(1u);
                                                               ^`

The following modification can get it to work:
![linuxcompile](https://cloud.githubusercontent.com/assets/17901031/17511375/2858c78a-5e55-11e6-8760-451a9a7dddb5.png)

please take a look, thank you!

**Comment by dneto0** [comment]
Also, it's customary to propose a patch via pull request.

**Comment by AWoloszyn** [comment]
Unfortunately the patch you proposed will not work for MSVC for the reasons stated in the comment above the templates. The purpose of these templates is to allow a shift using either a positive or negative operand.
Although GCC silently accepts it, the C++ spec specifically states that this is undefined behavior 
```
5.8 Shift operators §1

The behavior is undefined if the right operand is negative, or greater than or
equal to the length in bits of the promoted left operand.
```

**Comment by mrzerg** [comment]
Hi dneto0, AWoloszyn,
I'm using gcc-4.8.2, glibc-2.17, with c++0x enabled(-std=c++0x). And I'm targeting x86_64.
Sorry I didn't provided a formal patch because I'm not very familiar with these code, I just tried to get it work for me. Would you provide some idea that I can work with? Or maybe fix them if you feel comfortable :)

**Comment by dneto0** [comment]
2fb502b1d@mrzerg The project requires a C++11 compiler.

**Comment by mrzerg** [comment]
Seems it's a bug of gcc-4.8.2, they didn't get std::enable_if to work right. I tried gcc-5.3.1 and things are fine. thanks for your explanation @dneto0, @AWoloszyn , I'm closing this issue.
