### ISSUE TITLE
spirv-fuzz: Interchange zero-like constants

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3132]
OpConstantNull is in at least some cases equivalent to zero.  An interesting transformation would be to change zeros to null, or vice versa.

**Comment by paulthomson** [comment]
@stefanomil Please reply and I will officially assign this to you :-)

**Comment by stefanomil** [comment]
Sure, thanks!

**Comment by afd** [comment]
@stefanomil We are done with this one, correct?  (I guess we didn't include "Fixes ..." in the final PR related to it.)

**Comment by stefanomil** [comment]
Yes
