### ISSUE TITLE
spirv-opt generating OpSwitch without Default operand

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#3145]
I am seeing spirv-opt generate an OpSwitch without a Default operand. This seems to be in violation of the latest SPIR-V spec (1.5 R3).

@alan-baker Can you please confirm that this is an invalid OpSwitch?

I am not quite sure what pass is doing this yet, but wanted to make sure it was indeed invalid before pursuing further.

I am seeing this happen when the Default is the OpSwitch's merge block.

**Comment by alan-baker** [comment]
Yes that is invalid. Ok for the default to be the merge, but the it must be present.

**Comment by greg-lunarg** [comment]
Nevermind. Misread the instruction. The form I was seeing had an (unused) selector of %uint_0 and *only* a default label, no other Targets. I misread it as a having a single zero target with no Default. Sorry for the interrupt.
