### ISSUE TITLE
spirv-fuzz: Account for unreachable loop merge blocks when making functions livesafe

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3162]
Making a function livesafe involves adding a branch from a loop's back-edge block to the loop's merge if the number of loop iterations exceeds some limit.  If the loop's merge block was unreachable, the new edge could be a problem, e.g. because the previously unreachable block might now be dominated, and might not be in the right position in the module for this.

A possible solution to this is to branch to a new block and have that new block return.

**Comment by afd** [comment]
@andreperezmaselco Can we also add this one to your list?

**Comment by andreperezmaselco** [comment]
Sure.

**Comment by afd** [comment]
@andreperezmaselco Change in how we should approach this: rather than solving the problem, bail out when we find the problem exists.

- When trying to add loop limiters, check whether the loop header dominates the loop merge.  If it does not, return false - i.e. bail out.

- Add a test that checks for this case.
