### ISSUE TITLE
spirv-fuzz: Add fact to id uses to make it clear they could be fuzzed.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3177]
Sometimes, for convenience, the fuzzer needs to produce some value, e.g. the parameter of a called function, but often it does not matter what this value is.  There should be a way to mark the fact that this value is irrelevant, so that future fuzzer passes could transform it into something more interesting.

**Comment by paulthomson** [comment]
We decided to add a fresh id that is a copy of an existing id. The fresh id is marked as "IdIsIrrelevant".

**Comment by afd** [comment]
@Vasniktel can you reply so that I can assign this to you?

**Comment by Vasniktel** [comment]
Reply
