### ISSUE TITLE
spirv-fuzz: Transformation to add access chain initially restricted to use literal indices

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3179]
For simplicity, the original version of the transformation to add access chain instructions to a module will be restricted to using access chain indices that use in-bounds literals.  In the future it would be nice to generalise this so that non-struct indices can be dynamic and clamped to be in-bounds.

**Comment by paulthomson** [comment]
If you pick an id to use as the index that is not already arbitrary, you should add a fresh id (that is a copy of the id) that is marked as arbitrary.

**Comment by afd** [comment]
@stefanomil Are you happy to take this?  Please reply and I can assign you.

**Comment by paulthomson** [comment]
@stefanomil

**Comment by stefanomil** [comment]
@afd yes, I can take this
