### ISSUE TITLE
spirv-fuzz: Strict assertions for testing

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3185]
When checking the precondition of a transformation, there are cases where the transformation is potentially valid but does not apply, and cases where the transformation is completely bogus and should not have been created in the first place.

For the second case, when writing transformation unit tests we would like to be able to have negative tests that check that such transformations are not applicable.

But when actually running the fuzzer, we would like an assertion to fail when a completely invalid transformation is created.

Some thought is required to figure out how best to allow both cases.

**Comment by afd** [comment]
Death tests provide a solution for this.

**Comment by paulthomson** [comment]
There are still TODOs that reference this issue.
