### ISSUE TITLE
spirv-fuzz: add branch weights to OpBranchConditional

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3208]
In SPIR-V, the `OpBranchConditional` instruction is a conditional branch that branches to the true label or the false label depending on a boolean condition.

E.g. below, `OpBranchConditional` will jump to either %12 or %13 depending on the boolean value %11 (which is actually always false).

```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 15
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
               OpSource ESSL 310
               OpName %4 "main"
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeInt 32 1
          %7 = OpConstant %6 0
         %10 = OpTypeBool
         %11 = OpConstantFalse %10

          %4 = OpFunction %2 None %3

          %5 = OpLabel
               OpSelectionMerge %9 None
               OpSwitch %7 %9 0 %8

             %8 = OpLabel
                  OpSelectionMerge %13 None
                  OpBranchConditional %11 %12 %13

                %12 = OpLabel
                      OpBranch %13

            %13 = OpLabel
                  OpBranch %9

          %9 = OpLabel
               OpReturn
               OpFunctionEnd

```

`OpBranchConditional` can optionally include branch weights; I recommend checking the latest PDF of the SPIR-V spec at the [SPIR-V registry](https://www.khronos.org/registry/spir-v/).

Add a transformation, `TransformationAdjustBranchWeights`, that is made up of an instruction descriptor and a list of IDs. When applied, the transformation will replace the branch weights of the instruction with the list of IDs. The instruction descriptor will point to an `OpBranchConditional` instruction and every ID should be an unsigned int (and check the spec for other restrictions).

Add a fuzzer pass, `FuzzerPassAdjustBranchWeights`, that goes through the module and randomly decides whether to create and apply this transformation to each relevant instruction.

This fuzzer pass should come at the end (as opposed to being applied repeatedly), as it does not make sense to change branch weights again and again (as we only output the final SPIR-V module after applying all fuzzer passes). 

Refer to [Guide to writing a spirv-fuzz fuzzer pass
](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/docs/spirv-fuzz.md).

**Comment by afd** [comment]
Fixed via #3336.
