### ISSUE TITLE
spirv-fuzz: Segmentation fault and assertion failure

### ISSUE THREAD

**Issue by andreperezmaselco** [KhronosGroup/SPIRV-Tools#3213]
Doing some tests on the spirv-fuzz, more specifically, on the commit hash `66a682b6a8f973ba79b0e250221d53a4fbd11f4c`, by making it run several times in a bash loop.
Using `--seed=4352` and `--seed=4764`, the following errors were logged in the terminal, respectively:

`Segmentation fault (core dumped)`
                                                                                                    
```
spirv-fuzz: ./spirv-tools/source/fuzz/fact_manager.cpp:547: void spvtools::fuzz::FactManager::DataSynonymAnd
IdEquationFacts::AddEquationFactRecursive(const spvtools::fuzz::protobufs::DataDescriptor&, SpvOp, const std::vector<const spvtools::fuzz::p
rotobufs::DataDescriptor*>&, spvtools::opt::IRContext*): Assertion `synonymous_.Find(&lhs_dd) == &lhs_dd' failed.                            
Aborted (core dumped)
```

I guess it has something to do with the `FuzzerPassAddEquationInstructions` fuzzer.
Doing the same test, but removing the `FuzzerPassAddEquationInstructions` fuzzer from the file fuzzer.cpp there were no more errors.

The shader used on the test was the following:
```
#version 310 es
precision highp float;

layout(location = 0) out vec4 color;

void main()
{
  color = vec4(1.0, 0.0, 0.0, 1.0);
}
```

**Comment by Vasniktel** [comment]
I'm getting the same error on [this branch](https://github.com/Vasniktel/SPIRV-Tools/tree/permute_parameters_transformation) with seed `3131`

**Comment by afd** [comment]
@andreperezmaselco Thanks for reporting this.  Can you please add the hash of a commit to master on which this repros, to make it easier to reproduce as master moves on?

**Comment by Vasniktel** [comment]
I can get this error on 2a20e6e with seed `888577`.

**Comment by Vasniktel** [comment]
@afd, this looks wrong but I've just reproduced this issue on 6428ad05 with seed `362154` and [this shader](https://gist.github.com/Vasniktel/c5ecc0f0527be9b78f630389cb931e9c#file-original_shader-frag).
