### ISSUE TITLE
spirv-fuzz: Assertion fault in TransformationOutlineFunction

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3217]
To reproduce:
- clone [this branch](https://github.com/Vasniktel/SPIRV-Tools/tree/permute_parameters_transformation)
- compile
- `spirv-fuzz shader.spv -o fuzzed.spv --donors=donors.txt --seed=989`

You will get 
```
def_use_manager.cpp:153: bool spvtools::opt::analysis::DefUseManager::WhileEachUse(const spvtools::opt::Instruction*, const std::function<bool(spvtools::opt::Instruction*, unsigned int)>&) const: Assertion `def && (!def->HasResultId() || def == GetDef(def->result_id())) && "Definition is not registered."' failed.
```
Assertion fails here https://github.com/KhronosGroup/SPIRV-Tools/blob/da4cd214850296225484d3c2575c0e7eec83d607/source/fuzz/transformation_outline_function.cpp#L400

The reason is that `function_parameter` is not registered.

**Comment by afd** [comment]
Thanks for this!  It's possible that this could be happening due to your new transformation not invalidating analyses - see comment in my review of #3212.  Can you see whether adding that invalidation makes the problem go away?

**Comment by Vasniktel** [comment]
Yes, it seems that I did forget to update analyses. I can't reproduce this issue any longer.
