### ISSUE TITLE
spirv-fuzz: Assertion failure in TransformationCompositeConstruct

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3219]
To reproduce:
- use 2a20e6e commit
- use [this shader](https://gist.github.com/Vasniktel/c5ecc0f0527be9b78f630389cb931e9c#file-original_shader-frag)
- with seed `510278`

You will get an assertion failure
```
source/fuzz/fact_manager.cpp:712: void spvtools::fuzz::FactManager::DataSynonymAndIdEquationFacts::AddDataSynonymFactRecursive(const spvtools::fuzz::protobufs::DataDescriptor&, const spvtools::fuzz::protobufs::DataDescriptor&, spvtools::opt::IRContext*): Assertion `DataDescriptorsAreWellFormedAndComparable(context, dd1, dd2)' failed.
```
on this line
https://github.com/KhronosGroup/SPIRV-Tools/blob/da4cd214850296225484d3c2575c0e7eec83d607/source/fuzz/transformation_composite_construct.cpp#L150

**Comment by afd** [comment]
@Vasniktel I cannot repro this because I cannot check out the commit you mention, perhaps because you deleted the associated branch.

Are you able to repro this on master and give me a relevant commit there?

**Comment by Vasniktel** [comment]
Sorry, my mistake. I can reproduce it on dd3d9169 with seed `253253`.

**Comment by afd** [comment]
@Vasniktel I haven't seen this crop up when doing recent fuzzing runs; I reckon the problem has been fixed in the meantime. 
 I made loads of fixes to the fuzzer towards the end of March.

Would you be happy to close it?

**Comment by Vasniktel** [comment]
The problem has been fixed.
