### ISSUE TITLE
spir-v opt: Seeing an assert and invalid output with a one sized array.

### ISSUE THREAD

**Issue by asuonpaa** [KhronosGroup/SPIRV-Tools#3226]
Running spirv-opt for a shader that contains a struct with an array of size one I'm running into two problems. One is an assert:

```
spirv-opt: ../source/opt/copy_prop_arrays.cpp:699: void spvtools::opt::CopyPropagateArrays::UpdateUses(spvtools::opt::Instruction*, spvtools::opt::Instruction*): Assertion `false && "Don't know how to rewrite instruction"' failed.
```

and the other one is an optimized shader that fails to validate:

```
error: line 66: The <id> passed to OpAccessChain to index into a structure must be an OpConstant.
  %76 = OpLoad %int %75
```

I've attached the GLSL shader and the resulting SPIR-V shader I got from glslangValidator. I'm generating the unoptimized shader by doing

`glslangValidator -V one-sized-array-in-struct.frag`

and then running spirv-opt like this

`spirv-opt frag.spv -Os --validate-after-all -o tmp.spv`

The GLSL shader has comments how to switch from the assert to the invalid code issue. There are also commented out code that circumvents both problems.

[shaders.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/4329501/shaders.zip)

**Comment by s-perron** [comment]
Works with the latest debug build.
