### ISSUE TITLE
Dependencies should be updated

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3227]
It seems that pull request #3215 has forgotten to update `SPIRV-Headers` dependency. 
Right now, compilation fails saying that https://github.com/KhronosGroup/SPIRV-Tools/blob/1fe9bcc10824c1fa35bd9b697188340132d39213/source/opt/inst_debug_printf_pass.cpp#L19 file can't be found.

**Comment by Vasniktel** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/pull/3215#issuecomment-596701026
I see. I should've read the comments first ;)

**Comment by null77** [comment]
Also seeing a break in the ANGLE and Chromium SPIRV-Tools auto-rollers:

https://chromium-review.googlesource.com/c/chromium/src/+/2102136
https://chromium-review.googlesource.com/c/angle/angle/+/2102177

Would be great to merge this in if that's the right fix.
