### ISSUE TITLE
spirv-fuzz: Segmentation fault in FuzzerPassAddLocalVariables.

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3243]
This can be reproduced on 25ede1ce with [this compute shader](https://github.com/google/clspv/blob/master/test/InlineEntryPoints/inline_everything.cl), seed `488607` and empty donor file. 

`clspv` generates an `OpSpecConstant` instruction and uses it to specify the size for the `OpTypeArray` instruction. The problem is that `ConstantManager::GetConstantFromInst` returns `nullptr` for `OpSpecConstant` here https://github.com/KhronosGroup/SPIRV-Tools/blob/60104cd97446877dad8ed1010a635218937a2f18/source/opt/constants.cpp#L304-L320
which is later used without any assertions in 
https://github.com/KhronosGroup/SPIRV-Tools/blob/60104cd97446877dad8ed1010a635218937a2f18/source/fuzz/fuzzer_util.cpp#L321-L325

**Comment by afd** [comment]
@Vasniktel Similar to the other issue I commented on: I haven't seen this crop up when doing recent fuzzing runs; I reckon the problem has been fixed in the meantime.

Would you be happy to close it?

**Comment by Vasniktel** [comment]
The problem has been fixed.
