### ISSUE TITLE
Optimizer's Array type: inconsistent  ExtraHashWords and IsSameImpl

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#3248]
See https://github.com/KhronosGroup/SPIRV-Tools/blob/1346dd5de119d603686e260daf08f36958909a23/source/opt/types.cpp#L428

The Array::IsSameImpl method is sensitive to decorations, but Array::ExtraHashWords is not.
Either the comment is wrong or the methods are wrong.

**Comment by s-perron** [comment]
The code is correct.  The decorations are added in the generic `Type::GetHashWords`:

https://github.com/KhronosGroup/SPIRV-Tools/blob/75e53b9f685830ac42242cf0c46cc9af523bd0df/source/opt/types.cpp#L192

I agree the comment is misleading.
