### ISSUE TITLE
spirv-opt: Add passes for removing/adding glslang style gl_PerVertex decorations

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/SPIRV-Tools#3258]
When generating SPIR-V glslang currently adds in PointSize, CullDistance, ClipDistance decorations, even if they are not used. This causes validation failures when trying to convert to WebGPU SPIR-V. When going Vulkan->WebGPU we will need to remove these decorations, and when going WebGPU->Vulkan we need to add them in, since many tools expect them.

**Comment by zoddicus** [comment]
From my conversation with dento0:

> Those 3 decorations are very much standard.  They are the last 3 fields from gl_PerVertex in GLSL, and always appear in the same positions with the same types.
> So if you see a struct with Position in first member, then make sure the next 3 are PointSize, CullDistance, ClipDistance with the right types.
> Should be straightforwar.
> The idea of gl_PerVertex was that extensions would keep on appending to that structure.  It didn't turn out that way, as the ecosystem was not disciplined.

**Comment by zoddicus** [comment]
For further context here are the GLSL shader and the generated SPIRV:
GLSL DUMP START

        #version 450
        #extension GL_KHR_memory_scope_semantics : require

        #pragma use_vulkan_memory_model
        layout (set = 0, binding = 1) uniform fragmentUniformBuffer {
            vec4 color;
        };
        layout(location = 0) out vec4 fragColor;
        void main() {
            fragColor = color;
        }
GLSL DUMP END
SPIRV ASSEMBLY DUMP START
; SPIR-V
; Version: 1.3
; Generator: Google Shaderc over Glslang; 8
; Bound: 19
; Schema: 0
               OpCapability Shader
               OpCapability VulkanMemoryModel
               OpExtension "SPV_KHR_vulkan_memory_model"
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical Vulkan
               OpEntryPoint Fragment %main "main" %fragColor
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 450
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpSourceExtension "GL_KHR_memory_scope_semantics"
               OpName %main "main"
               OpName %fragColor "fragColor"
               OpName %fragmentUniformBuffer "fragmentUniformBuffer"
               OpMemberName %fragmentUniformBuffer 0 "color"
               OpName %_ ""
               OpDecorate %fragColor Location 0
               OpMemberDecorate %fragmentUniformBuffer 0 Offset 0
               OpDecorate %fragmentUniformBuffer Block
               OpDecorate %_ DescriptorSet 0
               OpDecorate %_ Binding 1
       %void = OpTypeVoid
          %7 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
         %11 = OpConstantNull %v4float
  %fragColor = OpVariable %_ptr_Output_v4float Output %11
%fragmentUniformBuffer = OpTypeStruct %v4float
%_ptr_Uniform_fragmentUniformBuffer = OpTypePointer Uniform %fragmentUniformBuffer
          %_ = OpVariable %_ptr_Uniform_fragmentUniformBuffer Uniform
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
%_ptr_Uniform_v4float = OpTypePointer Uniform %v4float
       %main = OpFunction %void None %7
         %16 = OpLabel
         %17 = OpAccessChain %_ptr_Uniform_v4float %_ %int_0
         %18 = OpLoad %v4float %17
               OpStore %fragColor %18
               OpReturn
               OpFunctionEnd

SPIRV ASSEMBLY DUMP END

**Comment by zoddicus** [comment]
GLSL DUMP START
```
        #version 450
        #extension GL_KHR_memory_scope_semantics : require

        #pragma use_vulkan_memory_model
        layout (set = 0, binding = 0) uniform vertexUniformBuffer {
            mat2 transform;
        };
        void main() {
            const vec2 pos[3] = vec2[3](vec2(-1.f, 1.f), vec2(1.f, 1.f), vec2(-1.f, -1.f));
            gl_Position = vec4(transform * pos[gl_VertexIndex], 0.f, 1.f);
        }
```
GLSL DUMP END
SPIRV ASSEMBLY DUMP START
```
; SPIR-V
; Version: 1.3
; Generator: Google Shaderc over Glslang; 8
; Bound: 49
; Schema: 0
               OpCapability Shader
               OpCapability VulkanMemoryModel
               OpExtension "SPV_KHR_vulkan_memory_model"
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical Vulkan
               OpEntryPoint Vertex %main "main" %_ %gl_VertexIndex
               OpSource GLSL 450
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpSourceExtension "GL_KHR_memory_scope_semantics"
               OpName %main "main"
               OpName %gl_PerVertex "gl_PerVertex"
               OpMemberName %gl_PerVertex 0 "gl_Position"
               OpMemberName %gl_PerVertex 1 "gl_PointSize"
               OpMemberName %gl_PerVertex 2 "gl_ClipDistance"
               OpMemberName %gl_PerVertex 3 "gl_CullDistance"
               OpName %_ ""
               OpName %vertexUniformBuffer "vertexUniformBuffer"
               OpMemberName %vertexUniformBuffer 0 "transform"
               OpName %__0 ""
               OpName %gl_VertexIndex "gl_VertexIndex"
               OpName %indexable "indexable"
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
               OpDecorate %gl_PerVertex Block
               OpMemberDecorate %vertexUniformBuffer 0 ColMajor
               OpMemberDecorate %vertexUniformBuffer 0 Offset 0
               OpMemberDecorate %vertexUniformBuffer 0 MatrixStride 16
               OpDecorate %vertexUniformBuffer Block
               OpDecorate %__0 DescriptorSet 0
               OpDecorate %__0 Binding 0
               OpDecorate %gl_VertexIndex BuiltIn VertexIndex
       %void = OpTypeVoid
         %10 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
%_arr_float_uint_1 = OpTypeArray %float %uint_1
%gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
         %17 = OpConstantNull %gl_PerVertex
          %_ = OpVariable %_ptr_Output_gl_PerVertex Output %17
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
    %v2float = OpTypeVector %float 2
%mat2v2float = OpTypeMatrix %v2float 2
%vertexUniformBuffer = OpTypeStruct %mat2v2float
%_ptr_Uniform_vertexUniformBuffer = OpTypePointer Uniform %vertexUniformBuffer
        %__0 = OpVariable %_ptr_Uniform_vertexUniformBuffer Uniform
%_ptr_Uniform_mat2v2float = OpTypePointer Uniform %mat2v2float
     %uint_3 = OpConstant %uint 3
%_arr_v2float_uint_3 = OpTypeArray %v2float %uint_3
   %float_n1 = OpConstant %float -1
    %float_1 = OpConstant %float 1
         %28 = OpConstantComposite %v2float %float_n1 %float_1
         %29 = OpConstantComposite %v2float %float_1 %float_1
         %30 = OpConstantComposite %v2float %float_n1 %float_n1
         %31 = OpConstantComposite %_arr_v2float_uint_3 %28 %29 %30
%_ptr_Input_int = OpTypePointer Input %int
%gl_VertexIndex = OpVariable %_ptr_Input_int Input
%_ptr_Function__arr_v2float_uint_3 = OpTypePointer Function %_arr_v2float_uint_3
%_ptr_Function_v2float = OpTypePointer Function %v2float
    %float_0 = OpConstant %float 0
%_ptr_Output_v4float = OpTypePointer Output %v4float
         %37 = OpConstantNull %_arr_v2float_uint_3
       %main = OpFunction %void None %10
         %38 = OpLabel
  %indexable = OpVariable %_ptr_Function__arr_v2float_uint_3 Function %37
         %39 = OpAccessChain %_ptr_Uniform_mat2v2float %__0 %int_0
         %40 = OpLoad %mat2v2float %39
         %41 = OpLoad %int %gl_VertexIndex
               OpStore %indexable %31
         %42 = OpAccessChain %_ptr_Function_v2float %indexable %41
         %43 = OpLoad %v2float %42
         %44 = OpMatrixTimesVector %v2float %40 %43
         %45 = OpCompositeExtract %float %44 0
         %46 = OpCompositeExtract %float %44 1
         %47 = OpCompositeConstruct %v4float %45 %46 %float_0 %float_1
         %48 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %48 %47
               OpReturn
               OpFunctionEnd
```
SPIRV ASSEMBLY DUMP END

**Comment by zoddicus** [comment]
So we are looking for groups of decorations like this:
```
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
```
and removing PointSize, ClipDistance and CullDistance

**Comment by Trass3r** [comment]
> This causes validation failures when trying to convert to WebGPU SPIR-V.

`spirv-opt --vulkan-to-webgpu --validate-after-all` didn't print anything.
And the validator just complained about the memory model:
```sh
$ spirv-val --target-env webgpu0 vert.spv
error: line 3: Memory model must be VulkanKHR for WebGPU environment.
  OpMemoryModel Logical GLSL450
```
Then I added `--upgrade-memory-model` (why isn't this enabled by `--vulkan-to-webgpu`?).
```
error: line 31: OpDecorate decoration 'BufferBlock' is not valid for the WebGPU execution environment.
  OpDecorate %Input2 BufferBlock
```
Ok so `glslangValidator -Os -V110` doesn't do what I thought it does, adding `--target-env vulkan1.1` finally leads to:
```llvm
error: line 77: WebGPU does not allow BuiltIn PointSize
  %gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
```
But why does `spirv-val` seemingly stop after 1 finding?

The following indeed finally produces a valid webgpu spirv file (although it still won't work in Chrome cause of https://github.com/KhronosGroup/SPIRV-Cross/issues/1568):
```glsl
out gl_PerVertex {
  vec4 gl_Position;
};
```

**Comment by dneto0** [comment]
The validation of SPV_ENV_WEBGPU0 has fallen behind discussions at W3C.  This is expected as W3C continues to develop that standard.

Indeed, WebGPU doesn't support PointSize, CullDistance or ClipDistance, each of which is added automatically by Glslang as part of the standard gl_PerVertex interface block.

When developing Tint and Dawn, the lack of PointSize support has proven to be a problem. In a flow targeting Vulkan when the topology is POINT_LIST, Vulkan requires the shader to assign to PointSize.
See https://bugs.chromium.org/p/tint/issues/detail?id=321 
WebGPU flows will write a value of 1.0.

Today I've posted a modification to Tint's SPIR-V reader to _ignore_ assignments to PointSize when those values are constant 1.0, and to have reads result in 1.0 unconditionally.  This is as a compatibility shim.
See https://dawn-review.googlesource.com/c/tint/+/35861/3

**Comment by dneto0** [comment]
It might be the case that we don't write spirv-opt passes for performing these transformations.

Our team is already doing the work in the Tint SPIR-V reader.  That essentially has a tighter development loop with the W3C discussions.
