### ISSUE TITLE
spirv-val: Header block is contained in the loop construct but its merge block is not

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/SPIRV-Tools#3260]
Many of my shaders that were previously passing spirv-val (last tested at Vulkan SDK 1.1.121.0) now fail with Vulkan SDK 1.2.131.2.  The specific error is:

c:\vulkansdk\1.2.131.2\Bin\spirv-val shader_0085.spv
error: line 956: Header block 12163[%12163] is contained in the loop construct headed by 6548[%6548], but its merge block 17470[%17470] is not
  %12163 = OpLabel

An example spir-v file is attached.  I was talking to @greg-lunarg about this.  The question is whether this is legitimately a bad shader or a spirv-val bug, and then second where in the spirv-opt chain this might get introduced.  

Filing here first to triage the issue, also in case someone else already has hunted this down and knows offhand what the problem is.

[shader_0085.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/4404204/shader_0085.zip)

**Comment by greg-lunarg** [comment]
Looking at it...

**Comment by greg-lunarg** [comment]
The loop and enclosed selection construct appear to be valid. The selection is a simple conditional break. Suspect spirv-val problem.

**Comment by greg-lunarg** [comment]
Can a spirv-val expert take over here?

**Comment by dj2** [comment]
@alan-baker

**Comment by alan-baker** [comment]
This is a real problem we fixed a while back (see #3068). Along with that validation change, I fixed a couple spots in spirv-opt that might produce it. The biggest culprit was that block merging would often merge a selection merge with the loop continue target.

**Comment by greg-lunarg** [comment]
@alan-baker Are you thinking this is no longer a problem? I think I am seeing the problem above with the latest spirv-tools. Are you not seeing the problem anymore?

**Comment by alan-baker** [comment]
@greg-lunarg where are you seeing problems? I expect the validator to issue the message on invalid CFGs, but if the optimizer is producing it then please file a bug and I'll get it fixed up.

**Comment by danginsburg** [comment]
I think what @alan-baker is saying is that this shader does actually violate the SPIR-V spec and that I need to rebuild my shaders.  It is the case that I do not have the fix(es) in #3068 .  My glslang/spirv-tools was sync'd on 10/16/2019 to commit b03e4fc4e072c997b19e4425a0a8fc3c5b280685 

So probably that's why my shaders have this bug.

**Comment by greg-lunarg** [comment]
@alan-baker Sorry. I didn't realize / had forgotten that continue blocks cannot also be selection merge blocks.

Based on that, @danginsburg will indeed to regen his shaders.

**Comment by danginsburg** [comment]
Thanks for the investigation.  I'll update my tools and reopen if it's still an issue.

**Comment by greg-lunarg** [comment]
@alan-baker Just curious: where does the spec state that it is invalid for a (selection) merge block to be the continue block of the enclosing loop?

Is it this passage?:

> when a construct contains another header block, it also contains that header’s corresponding merge block if that merge block is reachable in the CFG

If so, this is pretty subtle, at least to me. Should we have some additional language that states that the merge cannot be the continue of an enclosing loop?

Similarly,I find the text of the spirv-val error message to be subtle at best, and was the reason for my initial confusion. Should we change the message similarly?

**Comment by alan-baker** [comment]
That's the right rule. That rule is a generalization to enforce proper nesting. I'm not sure how I'd state the side effect about continue targets that isn't just covered by this rule. If you do have a proposal to improve the language please open an issue in the SPIR-V Khronos repo.

**Comment by greg-lunarg** [comment]
@alan-baker What do you think of this?:

Change

> the merge block declared by a header block cannot be a merge block declared by any other header block

to

> the merge and continue blocks declared by a header block cannot be a merge and continue block declared by any other header block

**Comment by alan-baker** [comment]
I'm not sure that's true for single block loops. A single block loop is just a continue construct and another construct at the same nesting could declare it as the merge I think.

**Comment by greg-lunarg** [comment]
Surprising that sometimes a continue can be someone else's merge, and sometimes it can't.

Do you remember the reason for #3068 ? Was it a driver compiler that didn't like that construct?

**Comment by alan-baker** [comment]
The issue it fixes details it reasonably well, but, basically, it was preventing a proper nesting analysis in the structured cfg analysis.

**Comment by greg-lunarg** [comment]
Sorry. Missed that issue when I scanned the PR.

I remember this now. It all hinges on the fact that a continue is not part of its loop. Very unintuitive to me, and it surprises me everytime I re-read it, but I don't think I want to get into changing that.

Thanks for indulging me.

**Comment by greg-lunarg** [comment]
@alan-baker Is there an advantage that you are aware of to defining a loop to not include its continue construct?

**Comment by alan-baker** [comment]
The loop includes the continue construct, but the loop construct does not. I think this is reasonable since there would be too many special cases in the structured cfg rules dealing with escapes from the loop construct that are non-standard.
