### ISSUE TITLE
[opt] remove redundant texture lookups

### ISSUE THREAD

**Issue by Trass3r** [KhronosGroup/SPIRV-Tools#3288]
http://shader-playground.timjones.io/dd879d7b5649510e6e674e319c646d7f

```
#version 330
uniform sampler2D tex0;
in vec4 color;
in vec4 texCoord0;
void main()
{
    gl_FragColor.rgb = textureProj(tex0, texCoord0).rgb * color.rgb;
    gl_FragColor.a = textureProj(tex0, texCoord0).a * color.a;
}
```
(The code is like that cause it's generated from snippets.)

**Comment by s-perron** [comment]
@Trass3r Can you check if the PR will fix the cases you are interested in?  Spirv-opt tries to keep our redundancy elimination algorithm simple, so we don't keep track of which memory location in between two loads.  So if a load is not read-only, then we will not common them.

I've added some extra conditions to be able to get the cases you have above, but it is specific to sampled images.

**Comment by Trass3r** [comment]
Thanks!
