### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by Keryen** [KhronosGroup/SPIRV-Tools#3310]
When using Ninja, it gives me the following error:

enrique@enrique-VirtualBox:~/Escritorio/spirv-tools/build$ cmake -G Ninja ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Debug
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring Effcee to build tests.
-- Configuring Effcee to build samples.
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- effcee: effcee-fuzz won't be built.  Can't find FuzzedDataProvider.h
-- Found Google Mock, building tests.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/enrique/Escritorio/spirv-tools/build
enrique@enrique-VirtualBox:~/Escritorio/spirv-tools/build$ ninja
[67/621] Building CXX object source/op...RV-Tools-opt.dir/loop_dependence.cpp.o
FAILED: source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_dependence.cpp.o 
/usr/bin/c++  -DSPIRV_CHECK_CONTEXT -DSPIRV_COLOR_TERMINAL -DSPIRV_LINUX -DSPIRV_TIMER_ENABLED -I../ -I../include -I../external/spirv-headers/include -I. -g -fPIC   -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Werror -std=c++11 -fno-exceptions -fno-rtti -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -std=gnu++11 -MD -MT source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_dependence.cpp.o -MF source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_dependence.cpp.o.d -o source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_dependence.cpp.o -c ../source/opt/loop_dependence.cpp
In file included from ../source/opt/instruction.h:30:0,
                 from ../source/opt/loop_dependence.h:29,
                 from ../source/opt/loop_dependence.cpp:15:
../source/opt/reflect.h: In function ‘bool spvtools::opt::IsTypeInst(SpvOp)’:
../source/opt/reflect.h:49:20: error: ‘SpvOpTypeAccelerationStructureKHR’ was not declared in this scope
          opcode == SpvOpTypeAccelerationStructureKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../source/opt/reflect.h:49:20: note: suggested alternative: ‘SpvOpTypeAccelerationStructureNV’
          opcode == SpvOpTypeAccelerationStructureKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    SpvOpTypeAccelerationStructureNV
../source/opt/reflect.h:50:20: error: ‘SpvOpTypeRayQueryProvisionalKHR’ was not declared in this scope
          opcode == SpvOpTypeRayQueryProvisionalKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[68/621] Building CXX object source/op...-opt.dir/loop_dependence_helpers.cpp.o
FAILED: source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_dependence_helpers.cpp.o 
/usr/bin/c++  -DSPIRV_CHECK_CONTEXT -DSPIRV_COLOR_TERMINAL -DSPIRV_LINUX -DSPIRV_TIMER_ENABLED -I../ -I../include -I../external/spirv-headers/include -I. -g -fPIC   -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Werror -std=c++11 -fno-exceptions -fno-rtti -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -std=gnu++11 -MD -MT source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_dependence_helpers.cpp.o -MF source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_dependence_helpers.cpp.o.d -o source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_dependence_helpers.cpp.o -c ../source/opt/loop_dependence_helpers.cpp
In file included from ../source/opt/instruction.h:30:0,
                 from ../source/opt/loop_dependence.h:29,
                 from ../source/opt/loop_dependence_helpers.cpp:15:
../source/opt/reflect.h: In function ‘bool spvtools::opt::IsTypeInst(SpvOp)’:
../source/opt/reflect.h:49:20: error: ‘SpvOpTypeAccelerationStructureKHR’ was not declared in this scope
          opcode == SpvOpTypeAccelerationStructureKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../source/opt/reflect.h:49:20: note: suggested alternative: ‘SpvOpTypeAccelerationStructureNV’
          opcode == SpvOpTypeAccelerationStructureKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    SpvOpTypeAccelerationStructureNV
../source/opt/reflect.h:50:20: error: ‘SpvOpTypeRayQueryProvisionalKHR’ was not declared in this scope
          opcode == SpvOpTypeRayQueryProvisionalKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[72/621] Building CXX object source/op...RV-Tools-opt.dir/loop_descriptor.cpp.o
FAILED: source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_descriptor.cpp.o 
/usr/bin/c++  -DSPIRV_CHECK_CONTEXT -DSPIRV_COLOR_TERMINAL -DSPIRV_LINUX -DSPIRV_TIMER_ENABLED -I../ -I../include -I../external/spirv-headers/include -I. -g -fPIC   -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Werror -std=c++11 -fno-exceptions -fno-rtti -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -std=gnu++11 -MD -MT source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_descriptor.cpp.o -MF source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_descriptor.cpp.o.d -o source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_descriptor.cpp.o -c ../source/opt/loop_descriptor.cpp
In file included from ../source/opt/instruction.h:30:0,
                 from ../source/opt/basic_block.h:29,
                 from ../source/opt/loop_descriptor.h:27,
                 from ../source/opt/loop_descriptor.cpp:15:
../source/opt/reflect.h: In function ‘bool spvtools::opt::IsTypeInst(SpvOp)’:
../source/opt/reflect.h:49:20: error: ‘SpvOpTypeAccelerationStructureKHR’ was not declared in this scope
          opcode == SpvOpTypeAccelerationStructureKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../source/opt/reflect.h:49:20: note: suggested alternative: ‘SpvOpTypeAccelerationStructureNV’
          opcode == SpvOpTypeAccelerationStructureKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    SpvOpTypeAccelerationStructureNV
../source/opt/reflect.h:50:20: error: ‘SpvOpTypeRayQueryProvisionalKHR’ was not declared in this scope
          opcode == SpvOpTypeRayQueryProvisionalKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[73/621] Building CXX object source/op...SPIRV-Tools-opt.dir/loop_fission.cpp.o
FAILED: source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_fission.cpp.o 
/usr/bin/c++  -DSPIRV_CHECK_CONTEXT -DSPIRV_COLOR_TERMINAL -DSPIRV_LINUX -DSPIRV_TIMER_ENABLED -I../ -I../include -I../external/spirv-headers/include -I. -g -fPIC   -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Werror -std=c++11 -fno-exceptions -fno-rtti -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -std=gnu++11 -MD -MT source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_fission.cpp.o -MF source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_fission.cpp.o.d -o source/opt/CMakeFiles/SPIRV-Tools-opt.dir/loop_fission.cpp.o -c ../source/opt/loop_fission.cpp
In file included from ../source/opt/instruction.h:30:0,
                 from ../source/opt/basic_block.h:29,
                 from ../source/opt/cfg.h:24,
                 from ../source/opt/loop_fission.h:24,
                 from ../source/opt/loop_fission.cpp:15:
../source/opt/reflect.h: In function ‘bool spvtools::opt::IsTypeInst(SpvOp)’:
../source/opt/reflect.h:49:20: error: ‘SpvOpTypeAccelerationStructureKHR’ was not declared in this scope
          opcode == SpvOpTypeAccelerationStructureKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../source/opt/reflect.h:49:20: note: suggested alternative: ‘SpvOpTypeAccelerationStructureNV’
          opcode == SpvOpTypeAccelerationStructureKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    SpvOpTypeAccelerationStructureNV
../source/opt/reflect.h:50:20: error: ‘SpvOpTypeRayQueryProvisionalKHR’ was not declared in this scope
          opcode == SpvOpTypeRayQueryProvisionalKHR ||
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[74/621] Building CXX object source/CM...iles/SPIRV-Tools.dir/name_mapper.cpp.o
ninja: build stopped: subcommand failed.

**Comment by alan-baker** [comment]
Have you updated SPIRV-Headers? That is the likely cause.

**Comment by Keryen** [comment]
I have just pulled the changes of SPIRV-TOOLS and rebuild it, I have not done anything more.

**Comment by Keryen** [comment]
Any solution? I need to use the SPIRV-TOOLS to continue my final degree project.

**Comment by Keryen** [comment]
Error solved! Thanks!
