### ISSUE TITLE
Could IsReadOnlyVariable() be generalized to apply to pointer instructions?

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3324]
I would like to be able to check whether an instruction of pointer type should be considered read-only.

`Instruction::IsReadOnlyVariable()` seems to do what I want, except that it is designed to work on OpVariable instructions.  However, looking at the code it seems like it should be suitable for application to any instruction whose result type is OpTypePointer.  Some of the checks would not be relevant for non-variables, e.g. checking for `SpvDecorationNonWritable`, but it looks like it would be harmless to do such checks for pointers that are not from `SpvOpVariable`.

@s-perron can you think of any reasons why this wouldn't work?  If not then I'll do a PR.

**Comment by s-perron** [comment]
I do not see a problem with that.
