### ISSUE TITLE
spirv-opt --ssa-rewrite error

### ISSUE THREAD

**Issue by Keryen** [KhronosGroup/SPIRV-Tools#3344]
When i apply the command `spirv-opt --ssa-rewrite` in the code below, I receive this error message:

>     enrique@enrique-VirtualBox:~/Escritorio/OpenCL-SPIRV_Optimizer/Generated/SPV_Lists/kernels/longest_1895$ spirv-opt --ssa-rewrite longest_0105.spv -o longest_0105_0.spv
>     spirv-opt: ../source/opt/instruction.h:583: const spvtools::opt::Operand& spvtools::opt::Instruction::GetOperand(uint32_t) const: Assertion `index < operands_.size() && "operand index out of bound"' failed.

Disassembled code of longest_0105.spv (spirv-dis):
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 32
; Schema: 0
               OpCapability Addresses
               OpCapability Kernel
               OpCapability Int64
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %8 "A"
         %31 = OpString "kernel_arg_type.A.int*,float*,int,"
               OpSource OpenCL_C 200000
               OpName %a "a"
               OpName %b "b"
               OpName %c "c"
               OpName %entry "entry"
               OpName %for_end92 "for.end92"
               OpName %cleanup114 "cleanup114"
               OpName %call "call"
               OpName %add18 "add18"
               OpName %cmp71 "cmp71"
               OpName %xor "xor"
               OpDecorate %b FuncParamAttr NoCapture
       %uint = OpTypeInt 32 0
      %ulong = OpTypeInt 64 0
     %uint_2 = OpConstant %uint 2
   %uint_272 = OpConstant %uint 272
%uint_269484031 = OpConstant %uint 269484031
       %void = OpTypeVoid
%_ptr_CrossWorkgroup_uint = OpTypePointer CrossWorkgroup %uint
      %float = OpTypeFloat 32
%_ptr_CrossWorkgroup_float = OpTypePointer CrossWorkgroup %float
          %7 = OpTypeFunction %void %_ptr_CrossWorkgroup_uint %_ptr_CrossWorkgroup_float %uint
       %bool = OpTypeBool
    %float_0 = OpConstant %float 0
    %float_1 = OpConstant %float 1
         %22 = OpConstantNull %_ptr_CrossWorkgroup_uint
          %8 = OpFunction %void None %7
          %a = OpFunctionParameter %_ptr_CrossWorkgroup_uint
          %b = OpFunctionParameter %_ptr_CrossWorkgroup_float
          %c = OpFunctionParameter %uint
      %entry = OpLabel
       %call = OpExtInst %float %1 exp10 %float_0
               OpStore %b %call Aligned 4
               OpControlBarrier %uint_2 %uint_2 %uint_272
         %19 = OpLoad %float %b Aligned 4
      %add18 = OpFAdd %float %19 %float_1
               OpStore %b %add18 Aligned 4
               OpControlBarrier %uint_2 %uint_2 %uint_272
               OpControlBarrier %uint_2 %uint_2 %uint_272
         %24 = OpConvertPtrToU %ulong %a
         %25 = OpConvertPtrToU %ulong %22
      %cmp71 = OpIEqual %bool %24 %25
               OpBranchConditional %cmp71 %for_end92 %cleanup114
  %for_end92 = OpLabel
               OpControlBarrier %uint_2 %uint_2 %uint_272
         %28 = OpLoad %uint %22 Aligned 536870912
        %xor = OpBitwiseXor %uint %28 %uint_269484031
               OpStore %22 %xor Aligned 536870912
               OpBranch %cleanup114
 %cleanup114 = OpLabel
               OpReturn
               OpFunctionEnd

**Comment by greg-lunarg** [comment]
@dnovillo This is your code, right?

**Comment by dnovillo** [comment]
I'll take a look.

**Comment by jaebaek** [comment]
Sent a PR in #3362
