### ISSUE TITLE
spirv-fuzz: FuzzerPassDonateModules doesn't support StorageBuffer storage class

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3347]
`clspv` compiler for the OpenCL programming language can produce SPIR-V that contains `OpTypePointer` instructions with `StorageBuffer` storage class. (e.g. there is a PR #3238 that contains SPIR-V of this kind). `FuzzerPassDonateModules` does not support these cases: https://github.com/KhronosGroup/SPIRV-Tools/blob/bd0a2da946c3fb4c641acc4a0d53ee67653e200a/source/fuzz/fuzzer_pass_donate_modules.cpp#L114-L135

**Comment by afd** [comment]
@Vasniktel It would make sense to change SpvStorageClassStorageBuffer to SpvStorageClassPrivate.  Can you do a PR for that?
