### ISSUE TITLE
spirv-fuzz: Replace OpCopyObject with the pair OpStore and OpLoad instructions

### ISSUE THREAD

**Issue by andreperezmaselco** [KhronosGroup/SPIRV-Tools#3351]
If we have `%8 = OpCopyObject %type %7`, we could create a new variable with type `pointer to %type`, store `%7` to the new variable and load the new variable to `%8`. The following is an example.
```
OpStore %fresh_variable_id %7
%8 = OpLoad %type %fresh_variable_id
```
This transformation protobuf would consist of `copy_object_result_id`, `fresh_variable_id`, `variable_storage_class`, `variable_initializer_id`.

The transformation is only applicable if the pointer type already exists. The pointer type cannot be a pointer to a pointer.

The fuzzer pass would look for OpCopyObject instructions and create and apply a transformation to add the required pointer type, if needed using `FindOrCreatePointerType`.

The transformation should add a synonym fact to the fact manager.

This will be similar to `TransformationPushIdThroughVariable`.

**Comment by afd** [comment]
@antkarp can we assign this to you?  (We'll help prioritize the order.)

**Comment by antnkarp** [comment]
Ok, that's great :)

**Comment by paulthomson** [comment]
A bigger example:

```
%1 = OpTypeInt 32 0
%2 = OpTypePointer Function %1
%3 = OpConstant %1 42
…
%5 = OpIAdd %1 %3 %3 ; %5 = 42 + 42
%4 = OpCopyObject %1 %5 ; Copy the value 84 into %4.

→
%100 = OpVariable %2 Function ; new variable to store into
...
%5 = OpIAdd %1 %3 %3 ; %5 = 42 + 42
     OpStore %100 %5 ; Store the value 84 into variable %100
%4 = OpLoad %1 %100 ; Load the value 84 from %100.



```
