### ISSUE TITLE
spirv-fuzz: Replace OpCopyMemory with the pair OpLoad and OpStore instructions 

### ISSUE THREAD

**Issue by andreperezmaselco** [KhronosGroup/SPIRV-Tools#3352]
If we have `OpCopyMemory %target %source`, we could load `%source` to `%source_value` and store `%source_value` to `%target`. The following is an example.
```
%source_value = OpLoad %type %source
OpStore %target %source_value
```
This transformation would receive a fresh id and an instruction descriptor.
The fuzzer pass would look for `OpCopyMemory` instructions and, randomly, apply the transformation.

**Comment by afd** [comment]
@antkarp can we assign this to you? (We'll help prioritize the order.)

**Comment by antnkarp** [comment]
Sure, thanks
