### ISSUE TITLE
spirv-fuzz: Replace the pair OpLoad and OpStore with OpCopyMemory

### ISSUE THREAD

**Issue by andreperezmaselco** [KhronosGroup/SPIRV-Tools#3353]
If we have a pair of instructions like `%source_value = OpLoad %type %source` and `OpStore %target %source_value`, we could replace this pair with `OpCopyMemory %target %source`.

This transformation would receive `%target`, `%source` and a pair of instruction descriptors.
The fuzzer pass would look for pairs `OpLoad` and `OpStore`, like described above, and, randomly apply the transformation.

**Comment by afd** [comment]
@andreperezmaselco would be OK if we give this to @antnkarp?  I think it's a good warm-up issue.

**Comment by andreperezmaselco** [comment]
Sure, @afd.

**Comment by afd** [comment]
Great - @antnkarp can you reply so I can assign you?

**Comment by antnkarp** [comment]
Ok, thanks
