### ISSUE TITLE
spirv-fuzz: FuzzerPassDonateModules does not support OpSpecConstant

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3371]
If the module contains `OpSpecConstant` instructions, the assertion fails here: https://github.com/KhronosGroup/SPIRV-Tools/blob/3c47dac28208eb5b1ae7909ba3cda0a1df88ba4b/source/fuzz/fuzzer_pass_donate_modules.cpp#L542-L545

Example of such a module can be found in #3238.

**Comment by afd** [comment]
Interesting!

We should donate OpSpecConstantTrue, OpSpecConstantFalse, OpSpecConstant and OpSpecConstantComposite by converting them to OpConstantTrue, OpConstantFalse, OpConstant and OpConstantComposite, respectively, using the default values from the specialization constants.

For OpSpecConstantOp I suggest that we instead use FindOrCreateZero to ensure there is a constant of the right type in the module, and use the id of that constant in place of the OpSpecConstantOp.

@Vasniktel would you like to work on this?

**Comment by Vasniktel** [comment]
Sure :)
