### ISSUE TITLE
spirv-fuzz: Add unused components to image instructions

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/SPIRV-Tools#3375]
We had a bug report that ended up being triggered by an image instruction having unused components in the coordinate. The SPIR-V spec for image instructions has language like:

> Coordinate must be a scalar or vector of floating-point type or integer type. It contains (u[, v] … [, array layer]) as needed by the definition of Sampled Image. Unless the Kernel capability is being used, it must be floating point. **It may be a vector larger than needed, but all unused components will appear after all used components.**

Adding unused components seems ideally suited for the fuzzer.

**Comment by afd** [comment]
Thanks @jeffbolznv - this is really useful!

**Comment by afd** [comment]
If we had, for example:

```
%a = %vec2 ...
%b = SomeImageInstruction %a
```

we could turn this into:

```
%a = %vec2 ...
%c = OpCompositeConstruct %vec3 %a %some_other_id
%b = SomeImageInstruction %c
```
