### ISSUE TITLE
spirv-opt --ccp error

### ISSUE THREAD

**Issue by Keryen** [KhronosGroup/SPIRV-Tools#3376]
When i apply the command `spirv-opt --ccp` in the code below, I receive this error message:

   

>  enrique@enrique-VirtualBox:~/Escritorio/OpenCL-SPIRV_Optimizer/Generated/SPV_Lists/kernels/longest_0420$ spirv-opt --ccp longest_0420.spv -o longest_0420_0.spv
>     spirv-opt: ../source/opt/optimizer.cpp:592: bool spvtools::Optimizer::Run(const uint32_t*, size_t, std::vector<unsigned int>*, spv_optimizer_options) const: Assertion `optimized_binary_with_nop.size() == original_binary_size && "Binary size unexpectedly changed despite the optimizer saying " "there was no change"' failed.

Disassembled code of longest_0420.spv (spirv-dis):

> ; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 142
; Schema: 0
               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
               OpCapability Int64
               OpCapability Int8
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %17 "L" %__spirv_BuiltInGlobalInvocationId %__spirv_BuiltInLocalInvocationId %__spirv_BuiltInWorkgroupSize
        %139 = OpString "kernel_arg_type.L.uchar*,uchar*,int,int,int,int,"
               OpSource OpenCL_C 200000
               OpName %L_k "L.k"
               OpName %__spirv_BuiltInGlobalInvocationId "__spirv_BuiltInGlobalInvocationId"
               OpName %__spirv_BuiltInLocalInvocationId "__spirv_BuiltInLocalInvocationId"
               OpName %__spirv_BuiltInWorkgroupSize "__spirv_BuiltInWorkgroupSize"
               OpName %a "a"
               OpName %b "b"
               OpName %c "c"
               OpName %d "d"
               OpName %e "e"
               OpName %f "f"
               OpName %entry "entry"
               OpName %for_cond_preheader "for.cond.preheader"
               OpName %for_body "for.body"
               OpName %for_cond46_preheader "for.cond46.preheader"
               OpName %for_cond58_preheader "for.cond58.preheader"
               OpName %for_body50 "for.body50"
               OpName %for_body62 "for.body62"
               OpName %if_then67 "if.then67"
               OpName %if_else72 "if.else72"
               OpName %if_end79 "if.end79"
               OpName %if_end84 "if.end84"
               OpName %cleanup "cleanup"
               OpName %call "call"
               OpName %conv "conv"
               OpName %call1 "call1"
               OpName %conv2 "conv2"
               OpName %call8 "call8"
               OpName %call9 "call9"
               OpName %mul "mul"
               OpName %call10 "call10"
               OpName %add "add"
               OpName %mul12 "mul12"
               OpName %add13 "add13"
               OpName %idxprom "idxprom"
               OpName %arrayidx "arrayidx"
               OpName %idxprom14 "idxprom14"
               OpName %arrayidx15 "arrayidx15"
               OpName %sub18 "sub18"
               OpName %add19 "add19"
               OpName %cmp "cmp"
               OpName %add22 "add22"
               OpName %cmp23 "cmp23"
               OpName %or_cond_not "or.cond.not"
               OpName %cmp27 "cmp27"
               OpName %or_cond161 "or.cond161"
               OpName %or_cond161_not "or.cond161.not"
               OpName %add30 "add30"
               OpName %cmp31 "cmp31"
               OpName %or_cond162 "or.cond162"
               OpName %sub "sub"
               OpName %j_3 "j.3"
               OpName %j_0170 "j.0170"
               OpName %inc86 "inc86"
               OpName %r_0169 "r.0169"
               OpName %add39 "add39"
               OpName %cmp40 "cmp40"
               OpName %cmp43 "cmp43"
               OpName %or_cond163 "or.cond163"
               OpName %mul51 "mul51"
               OpName %add52 "add52"
               OpName %add39_lobit "add39.lobit"
               OpName %mul68 "mul68"
               OpName %sub73 "sub73"
               OpName %mul75 "mul75"
               OpName %sub74 "sub74"
               OpName %call56 "call56"
               OpName %j_1166 "j.1166"
               OpName %inc "inc"
               OpName %t_0165 "t.0165"
               OpName %add53 "add53"
               OpName %idxprom54 "idxprom54"
               OpName %arrayidx55 "arrayidx55"
               OpName %cmp47 "cmp47"
               OpName %call80 "call80"
               OpName %j_2168 "j.2168"
               OpName %inc82 "inc82"
               OpName %t57_0167 "t57.0167"
               OpName %add63 "add63"
               OpName %or "or"
               OpName %tobool "tobool"
               OpName %add69 "add69"
               OpName %idxprom70 "idxprom70"
               OpName %arrayidx71 "arrayidx71"
               OpName %add76 "add76"
               OpName %idxprom77 "idxprom77"
               OpName %arrayidx78 "arrayidx78"
               OpName %u64_0 "u64.0"
               OpName %cmp59 "cmp59"
               OpName %cmp37 "cmp37"
               OpName %j_3_sink "j.3.sink"
               OpName %mul88 "mul88"
               OpName %add89 "add89"
               OpName %idxprom90 "idxprom90"
               OpName %arrayidx91 "arrayidx91"
               OpDecorate %140 Constant
        %140 = OpDecorationGroup
               OpDecorate %141 FuncParamAttr NoCapture
        %141 = OpDecorationGroup
               OpDecorate %__spirv_BuiltInWorkgroupSize BuiltIn WorkgroupSize
               OpDecorate %__spirv_BuiltInLocalInvocationId BuiltIn LocalInvocationId
               OpDecorate %__spirv_BuiltInGlobalInvocationId BuiltIn GlobalInvocationId
               OpDecorate %a FuncParamAttr NoWrite
               OpDecorate %__spirv_BuiltInWorkgroupSize LinkageAttributes "__spirv_BuiltInWorkgroupSize" Import
               OpDecorate %__spirv_BuiltInGlobalInvocationId LinkageAttributes "__spirv_BuiltInGlobalInvocationId" Import
               OpDecorate %__spirv_BuiltInLocalInvocationId LinkageAttributes "__spirv_BuiltInLocalInvocationId" Import
               OpDecorate %L_k Alignment 1
               OpGroupDecorate %140 %__spirv_BuiltInGlobalInvocationId %__spirv_BuiltInLocalInvocationId %__spirv_BuiltInWorkgroupSize
               OpGroupDecorate %141 %a %b
      %ulong = OpTypeInt 64 0
      %uchar = OpTypeInt 8 0
       %uint = OpTypeInt 32 0
  %ulong_256 = OpConstant %ulong 256
   %ulong_32 = OpConstant %ulong 32
    %ulong_0 = OpConstant %ulong 0
     %uint_2 = OpConstant %uint 2
   %uint_272 = OpConstant %uint 272
%uint_4294967280 = OpConstant %uint 4294967280
    %uint_16 = OpConstant %uint 16
    %uint_20 = OpConstant %uint 20
%uint_4294967276 = OpConstant %uint 4294967276
    %uint_31 = OpConstant %uint 31
     %uint_4 = OpConstant %uint 4
     %uint_1 = OpConstant %uint 1
     %uint_0 = OpConstant %uint 0
%_arr_uchar_ulong_256 = OpTypeArray %uchar %ulong_256
%_ptr_Workgroup__arr_uchar_ulong_256 = OpTypePointer Workgroup %_arr_uchar_ulong_256
    %v3ulong = OpTypeVector %ulong 3
%_ptr_Input_v3ulong = OpTypePointer Input %v3ulong
       %void = OpTypeVoid
%_ptr_CrossWorkgroup_uchar = OpTypePointer CrossWorkgroup %uchar
         %16 = OpTypeFunction %void %_ptr_CrossWorkgroup_uchar %_ptr_CrossWorkgroup_uchar %uint %uint %uint %uint
%_ptr_Workgroup_uchar = OpTypePointer Workgroup %uchar
       %bool = OpTypeBool
        %L_k = OpVariable %_ptr_Workgroup__arr_uchar_ulong_256 Workgroup
%__spirv_BuiltInGlobalInvocationId = OpVariable %_ptr_Input_v3ulong Input
%__spirv_BuiltInLocalInvocationId = OpVariable %_ptr_Input_v3ulong Input
%__spirv_BuiltInWorkgroupSize = OpVariable %_ptr_Input_v3ulong Input
       %true = OpConstantTrue %bool
         %17 = OpFunction %void None %16
          %a = OpFunctionParameter %_ptr_CrossWorkgroup_uchar
          %b = OpFunctionParameter %_ptr_CrossWorkgroup_uchar
          %c = OpFunctionParameter %uint
          %d = OpFunctionParameter %uint
          %e = OpFunctionParameter %uint
          %f = OpFunctionParameter %uint
      %entry = OpLabel
         %36 = OpLoad %v3ulong %__spirv_BuiltInGlobalInvocationId
       %call = OpCompositeExtract %ulong %36 0
       %conv = OpUConvert %uint %call
         %39 = OpLoad %v3ulong %__spirv_BuiltInGlobalInvocationId
      %call1 = OpCompositeExtract %ulong %39 1
      %conv2 = OpUConvert %uint %call1
         %42 = OpLoad %v3ulong %__spirv_BuiltInLocalInvocationId
      %call8 = OpCompositeExtract %ulong %42 1
         %44 = OpLoad %v3ulong %__spirv_BuiltInWorkgroupSize
      %call9 = OpCompositeExtract %ulong %44 0
        %mul = OpIMul %ulong %call9 %call8
         %47 = OpLoad %v3ulong %__spirv_BuiltInLocalInvocationId
     %call10 = OpCompositeExtract %ulong %47 0
        %add = OpIAdd %ulong %mul %call10
      %mul12 = OpIMul %uint %conv2 %c
      %add13 = OpIAdd %uint %mul12 %conv
    %idxprom = OpSConvert %ulong %add13
   %arrayidx = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_uchar %a %idxprom
         %54 = OpLoad %uchar %arrayidx Aligned 1
         %56 = OpShiftLeftLogical %ulong %add %ulong_32
  %idxprom14 = OpShiftRightArithmetic %ulong %56 %ulong_32
 %arrayidx15 = OpInBoundsPtrAccessChain %_ptr_Workgroup_uchar %L_k %ulong_0 %idxprom14
               OpStore %arrayidx15 %54 Aligned 1
               OpControlBarrier %uint_2 %uint_2 %uint_272
      %sub18 = OpBitwiseAnd %uint %conv2 %uint_4294967280
      %add19 = OpIAdd %uint %sub18 %uint_16
        %cmp = OpSLessThan %bool %conv2 %uint_20
      %add22 = OpIAdd %uint %conv2 %uint_20
      %cmp23 = OpSGreaterThanEqual %bool %add22 %f
%or_cond_not = OpLogicalOr %bool %cmp %cmp23
      %cmp27 = OpSLessThan %bool %conv %uint_20
 %or_cond161 = OpLogicalOr %bool %cmp27 %or_cond_not
%or_cond161_not = OpLogicalNotEqual %bool %or_cond161 %true
      %add30 = OpIAdd %uint %conv %uint_20
      %cmp31 = OpSLessThan %bool %add30 %e
 %or_cond162 = OpLogicalAnd %bool %cmp31 %or_cond161_not
               OpBranchConditional %or_cond162 %for_cond_preheader %cleanup
%for_cond_preheader = OpLabel
        %sub = OpBitwiseAnd %uint %conv %uint_4294967280
               OpBranch %for_body
   %for_body = OpLabel
     %j_0170 = OpPhi %uchar %54 %for_cond_preheader %j_3 %if_end84
     %r_0169 = OpPhi %uint %uint_4294967276 %for_cond_preheader %inc86 %if_end84
      %add39 = OpIAdd %uint %r_0169 %conv2
      %cmp40 = OpSGreaterThanEqual %bool %add39 %sub18
      %cmp43 = OpSLessThan %bool %add39 %add19
 %or_cond163 = OpLogicalAnd %bool %cmp40 %cmp43
               OpBranchConditional %or_cond163 %for_cond58_preheader %for_cond46_preheader
%for_cond46_preheader = OpLabel
      %mul51 = OpIMul %uint %add39 %c
      %add52 = OpIAdd %uint %mul51 %conv
               OpBranch %for_body50
%for_cond58_preheader = OpLabel
%add39_lobit = OpShiftRightLogical %uint %add39 %uint_31
      %mul68 = OpIMul %uint %add39 %c
      %sub73 = OpISub %uint %add39 %sub18
      %mul75 = OpShiftLeftLogical %uint %sub73 %uint_4
      %sub74 = OpISub %uint %mul75 %sub
               OpBranch %for_body62
 %for_body50 = OpLabel
     %j_1166 = OpPhi %uchar %j_0170 %for_cond46_preheader %call56 %for_body50
     %t_0165 = OpPhi %uint %uint_4294967276 %for_cond46_preheader %inc %for_body50
      %add53 = OpIAdd %uint %add52 %t_0165
  %idxprom54 = OpSConvert %ulong %add53
 %arrayidx55 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_uchar %a %idxprom54
        %106 = OpLoad %uchar %arrayidx55 Aligned 1
     %call56 = OpExtInst %uchar %1 u_max %106 %j_1166
        %inc = OpIAdd %uint %t_0165 %uint_1
      %cmp47 = OpSLessThan %bool %t_0165 %uint_20
               OpBranchConditional %cmp47 %for_body50 %if_end84
 %for_body62 = OpLabel
     %j_2168 = OpPhi %uchar %j_0170 %for_cond58_preheader %call80 %if_end79
   %t57_0167 = OpPhi %uint %uint_4294967276 %for_cond58_preheader %inc82 %if_end79
      %add63 = OpIAdd %uint %t57_0167 %conv
         %or = OpBitwiseOr %uint %add63 %add39_lobit
     %tobool = OpIEqual %bool %or %uint_0
               OpBranchConditional %tobool %if_else72 %if_then67
  %if_then67 = OpLabel
      %add69 = OpIAdd %uint %add63 %mul68
  %idxprom70 = OpSConvert %ulong %add69
 %arrayidx71 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_uchar %a %idxprom70
        %122 = OpLoad %uchar %arrayidx71 Aligned 1
               OpBranch %if_end79
  %if_else72 = OpLabel
      %add76 = OpIAdd %uint %sub74 %add63
  %idxprom77 = OpSConvert %ulong %add76
 %arrayidx78 = OpInBoundsPtrAccessChain %_ptr_Workgroup_uchar %L_k %ulong_0 %idxprom77
        %126 = OpLoad %uchar %arrayidx78 Aligned 1
               OpBranch %if_end79
   %if_end79 = OpLabel
      %u64_0 = OpPhi %uchar %122 %if_then67 %126 %if_else72
     %call80 = OpExtInst %uchar %1 u_max %u64_0 %j_2168
      %inc82 = OpIAdd %uint %t57_0167 %uint_1
      %cmp59 = OpSLessThan %bool %t57_0167 %uint_20
               OpBranchConditional %cmp59 %for_body62 %if_end84
   %if_end84 = OpLabel
        %j_3 = OpPhi %uchar %call80 %if_end79 %call56 %for_body50
      %inc86 = OpIAdd %uint %r_0169 %uint_1
      %cmp37 = OpSLessThan %bool %r_0169 %uint_20
               OpBranchConditional %cmp37 %for_body %cleanup
    %cleanup = OpLabel
   %j_3_sink = OpPhi %uchar %54 %entry %j_3 %if_end84
      %mul88 = OpIMul %uint %conv2 %d
      %add89 = OpIAdd %uint %mul88 %conv
  %idxprom90 = OpSConvert %ulong %add89
 %arrayidx91 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_uchar %b %idxprom90
               OpStore %arrayidx91 %j_3_sink Aligned 1
               OpReturn
               OpFunctionEnd

**Comment by s-perron** [comment]
This has been fixed.
