### ISSUE TITLE
OpenCL.DebugInfo.100 information preservation in spirv-opt legalization passes

### ISSUE THREAD

**Issue by jaebaek** [KhronosGroup/SPIRV-Tools#3386]
This is an umbrella bug for OpenCL.DebugInfo.100 information preservation in spirv-opt legalization passes. #3367 and #3366 are parts of the debug information preservation.

- [x] wrap-opkill
- [x] eliminate-dead-branches
- [x] merge-return
- [x] inline-entry-points-exhaustive
- [x] eliminate-dead-functions
- [x] private-to-local
- [x] fix-storage-class
- [x] eliminate-local-single-block
- [x] eliminate-local-single-store
- [x] eliminate-dead-code-aggressive
- [x] scalar-replacement=0
- [x] ssa-rewrite
- [x] ccp
- [x] loop-unroll
- [x] simplify-instructions
- [x] copy-propagate-arrays
- [x] vector-dce
- [x] eliminate-dead-inserts
- [x] reduce-load-size

**Comment by jaebaek** [comment]
- `DebugInfoManager` is an analysis for OpenCL.DebugInfo.100 instructions, which was submitted by #3305 

- function inlining: #3328 #3349

- dead-function-elimination: #3251

- wrap-opkill: #3331

**Comment by jaebaek** [comment]
Related spirv-val PRs: #3133 #3104 #3374

We have to add the validation for more OpenCL.DebugInfo.100 instructions: #3369

**Comment by jaebaek** [comment]
ssa-rewrite is WIP: #3356

**Comment by greg-lunarg** [comment]
I will start with eliminate-local-single-block and eliminate-local-single-block.

**Comment by jaebaek** [comment]
I just sent a PR for merge return pass: #3389

**Comment by jaebaek** [comment]
I created this kanban to easily check the progress: https://github.com/KhronosGroup/SPIRV-Tools/projects/6

**Comment by jaebaek** [comment]
For the fix-storage-class pass, we do not have to update the code for the debug information because it does not have any impact on the debug information.

**Comment by jaebaek** [comment]
The debug info preservation in the spirv-opt legalization passes is done \o/
