### ISSUE TITLE
spirv-fuzz: fuzzer_replayer failure

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3395]
To reproduce:
Clone 636f449e, comment out these lines
https://github.com/KhronosGroup/SPIRV-Tools/blob/636f449e1529a10d259eb7dc37d97192cf2820f8/source/fuzz/fuzzer.cpp#L253-L255
and run `FuzzerReplayerTest.Miscellaneous6`. The issue occurs on seed 69.
What's known so far.
The test fails because replayer is unable to reproduce some transformations. Diffs for the transformation sequence and decompiled code are below.
```diff
--- fuzzer.json 2020-06-03 11:37:05.149236422 +0300
+++ replayer.json       2020-06-03 11:37:05.153236518 +0300
@@ -815,43 +815,6 @@
   {
    "replaceIdWithSynonym": {
     "idUseDescriptor": {
-     "idOfInterest": 318,
-     "enclosingInstruction": {
-      "baseInstructionResultId": 324,
-      "targetInstructionOpcode": 81
-     }
-    },
-    "synonymousId": 335
-   }
-  },
-  {
-   "replaceIdWithSynonym": {
-    "idUseDescriptor": {
-     "idOfInterest": 318,
-     "enclosingInstruction": {
-      "baseInstructionResultId": 340,
-      "targetInstructionOpcode": 80
-     },
-     "inOperandIndex": 1
-    },
-    "synonymousId": 338
-   }
-  },
-  {
-   "replaceIdWithSynonym": {
-    "idUseDescriptor": {
-     "idOfInterest": 335,
-     "enclosingInstruction": {
-      "baseInstructionResultId": 324,
-      "targetInstructionOpcode": 81
-     }
-    },
-    "synonymousId": 318
-   }
-  },
-  {
-   "replaceIdWithSynonym": {
-    "idUseDescriptor": {
      "idOfInterest": 335,
      "enclosingInstruction": {
       "baseInstructionResultId": 360,
```
```diff
--- fuzzer.dis  2020-06-03 11:37:05.157236614 +0300
+++ replayer.dis        2020-06-03 11:37:05.157236614 +0300
@@ -315,7 +315,7 @@
 %570 = OpLogicalNot %319 %372
 %425 = OpAccessChain %114 %418
 %571 = OpLogicalNot %319 %564
-%340 = OpCompositeConstruct %76 %357 %338
+%340 = OpCompositeConstruct %76 %357 %318
 %572 = OpLogicalNot %319 %501
 %410 = OpLogicalNot %319 %377
 %370 = OpCompositeConstruct %94 %454 %360
```

As you can see, three transformations are missing from the replayer sequence. The first one is missing because `IsApplicable` method returns `false` in replayer here
https://github.com/KhronosGroup/SPIRV-Tools/blob/636f449e1529a10d259eb7dc37d97192cf2820f8/source/fuzz/transformation_replace_id_with_synonym.cpp#L47-L51

It seems that `Exists` method returns `false` here.
https://github.com/KhronosGroup/SPIRV-Tools/blob/636f449e1529a10d259eb7dc37d97192cf2820f8/source/fuzz/fact_manager.cpp#L1195-L1201

However, if you are to print a sequence of facts that gets added into the `FactManager` in both fuzzer and replayer, you'll see that those sequences are completely identical.

**Comment by paulthomson** [comment]
This could be to do with the fact manager giving up adding synonyms. Maybe it could be to do with iteration over unordered containers. I would suggest printing out ALL facts at each step and comparing the fuzz vs replay.
