### ISSUE TITLE
spirv-opt: iterator_template has wrong return type

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3397]
`IntrusiveList::iterator_template` serves as a base class for some iterators in the library (e.g. `InstructionList::iterator`). It also defines pre-increment and pre-decrement operators. The problem lies in the return type of those operators. If one uses `operator++` on `InstructionList::iterator`, he will get a reference to `IntrusiveList::iterator_template`, not `InstructionList::iterator`. This means that some methods defined in the `InstructionList::iterator` won't be accessible to the user. A solution could be to use a curiously recurring template pattern in pretty much the same way it's used in `IntrusiveList` class.

Example code:
```cpp
opt::InstructionList::iterator iter = fuzzerutil::GetIteratorForInstruction(...);
auto it = ++iter;
it.InsertBefore(...); // compiler error: IntrusiveList::iterator_template has no InsertBefore method
```

A workaround, suggested by @paulthomson, is to use the old value of the iterator, which has the desired type. This wouldn't work for post-increment if we had them, though.
```cpp
opt::InstructionList::iterator iter = fuzzerutil::GetIteratorForInstruction(...);
++iter;
iter.InsertBefore(...);
```

**Comment by Vasniktel** [comment]
@alan-baker @s-perron, would be good to know your opinion on this one?

**Comment by s-perron** [comment]
I can't remember what I was thinking when I wrote that code.

It fix this, we can override operator++ in the iterator class:

```
    iterator& operator++() {
      utils::IntrusiveList<Instruction>::iterator::operator++();
      return *this;
    }
```

**Comment by Vasniktel** [comment]
I wonder whether CRTP would be a better solution here. We'll have to change some APIs in the library in both cases but with CRTP we won't have to change it every time we add a method to the `iterator_template`. CRTP might not be as good with error messages, though, so I guess it's a tradeoff. What do you think, @s-perron?

**Comment by s-perron** [comment]
Sure CRTP would be better.

**Comment by Vasniktel** [comment]
Ok, I'll make a PR then.

**Comment by Vasniktel** [comment]
Well, I was unable to implement CRTP there. The simplified explanation is that if we do so, we won't be able to use `MoveBefore` method in the `InstructionList::iterator`. So I went ahead and implemented @s-perron's idea instead.
