### ISSUE TITLE
"Invalid capability operand: 61" when optimizing shader with subgroup operations

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/SPIRV-Tools#3407]
Encountered in ANGLE. To reproduce, take [this CL][1] or wait for it to land (this CL enables SPIR-V optimization on internal ANGLE shaders). Then do:

```
$ cd src/libANGLE/renderer/vulkan
$ vim shaders/src/OverlayCull.comp.json
# Remove "-Od" from list of arguments in the json file
$ python gen_vk_internal_shaders.py OverlayCull
```

Observe the following:

```
shaders/gen/OverlayCull.comp.00000000.inc: OverlayCull.comp|Is8x4|SupportsBallot
error: input:0:0:2: Invalid capability operand: 61

shaders/gen/OverlayCull.comp.00000001.inc: OverlayCull.comp|Is8x8|SupportsBallot
error: input:0:0:2: Invalid capability operand: 61

shaders/gen/OverlayCull.comp.00000002.inc: OverlayCull.comp|Is8x4|SupportsArithmetic
error: input:0:0:2: Invalid capability operand: 61

shaders/gen/OverlayCull.comp.00000003.inc: OverlayCull.comp|Is8x8|SupportsArithmetic
error: input:0:0:2: Invalid capability operand: 61

shaders/gen/OverlayCull.comp.00000004.inc: OverlayCull.comp|Is8x4|SupportsNone
shaders/gen/OverlayCull.comp.00000005.inc: OverlayCull.comp|Is8x8|SupportsNone
```

The first 4 cases use subgroup operations and are built with `--target-env vulkan1.1` (which enables SPIR-V 1.3). FYI capability 61 is `GroupNonUniform`.

In `gen_vk_internal_shaders.py`, you can add `print ' '.join(glslang_args)` right after `glslang-args` is fully built. Nevertheless, here is exactly how glslang is invoked for the 4 failing cases:

```
../../../../tools/glslang/glslang_validator -DIs8x4=1 -DSupportsBallot=1 -V -Os --variable-name kOverlayCull_comp_00000000 --target-env vulkan1.1 -o shaders/gen/OverlayCull.comp.00000000.inc shaders/src/OverlayCull.comp
../../../../tools/glslang/glslang_validator -DIs8x8=1 -DSupportsBallot=1 -V -Os --variable-name kOverlayCull_comp_00000001 --target-env vulkan1.1 -o shaders/gen/OverlayCull.comp.00000001.inc shaders/src/OverlayCull.comp
../../../../tools/glslang/glslang_validator -DIs8x4=1 -DSupportsArithmetic=1 -V -Os --variable-name kOverlayCull_comp_00000002 --target-env vulkan1.1 -o shaders/gen/OverlayCull.comp.00000002.inc shaders/src/OverlayCull.comp
../../../../tools/glslang/glslang_validator -DIs8x8=1 -DSupportsArithmetic=1 -V -Os --variable-name kOverlayCull_comp_00000003 --target-env vulkan1.1 -o shaders/gen/OverlayCull.comp.00000003.inc shaders/src/OverlayCull.comp
```

[1]: https://chromium-review.googlesource.com/c/angle/angle/+/1616963

**Comment by alan-baker** [comment]
Uses my local (relatively up-to-update) glslang I ran:
```
glslangValidator -DIs8x4=1 -DSupportsBallot=1 -V -Os  --target-env vulkan1.1 -o tmp.spv shaders/src/OverlayCull.comp
```

This produced no errors. The resulting binary parses and validates under Vulkan 1.1. If I remove the optimization option and run the optimizer independently it also succeeds. Based on the error you have, I would guess something is up with the headers being used, but I'm not familiar with ANGLE's build.

**Comment by ShabbyX** [comment]
ANGLE is using top-of-tree glslang, SPIR-V headers and SPIR-V tools. I'm afraid I'm not familiar with how these tie together to tell what could be wrong.

**Comment by ShabbyX** [comment]
I remembered we use a build of glslang we upload to cloud occasionally, and this issue was because the build was too old. Updating the glslang binary fixed the issue.
