### ISSUE TITLE
Invalid SPIR-V generated after optimization

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/SPIRV-Tools#3408]
Encountered in ANGLE. [This CL][1] enables SPIR-V optimization of internal shaders. This causes regressions due to a validation error, see for example:

    https://ci.chromium.org/p/chromium/builders/try/linux_angle_deqp_rel_ng/14218
    https://ci.chromium.org/p/chromium/builders/try/linux-swangle-try-tot-angle-x64/1492

The validation error is:

```
[ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x102ab373f050, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Header block 278[%278] is contained in the loop construct headed by 202[%202], but its merge block 279[%279] is not
  %278 = OpLabel
```

Trying one of the failures:

```
$ ./angle_end2end_tests --gtest_filter=VertexAttributeTest.HalfFloatBuffer/ES2_Vulkan_SwiftShader
```

I can see the error generated from [this shader (ConvertVertex variant 0x1)][2], though that's probably not the only shader affected by this.

[1]: https://chromium-review.googlesource.com/c/angle/angle/+/1616963/8
[2]: https://chromium-review.googlesource.com/c/angle/angle/+/1616963/8/src/libANGLE/renderer/vulkan/shaders/gen/ConvertVertex.comp.00000001.inc

**Comment by alan-baker** [comment]
There was a known bug in the optimizer that was causing this bug. It was fixed in #3068. Can you confirm your shaders were re-generated after that fix?

**Comment by ShabbyX** [comment]
This error happens using top-of-tree SPIR-V tools.

**Comment by alan-baker** [comment]
Were the shaders generated from glsl source or were they pre-existing binaries?

**Comment by ShabbyX** [comment]
I remembered we use a build of glslang we upload to cloud occasionally, and this issue was because the build was too old. Updating the glslang binary fixed the issue.
