### ISSUE TITLE
spirv-fuzz: Refactor find type functions

### ISSUE THREAD

**Issue by andreperezmaselco** [KhronosGroup/SPIRV-Tools#3428]
Some `FuzzerPass` functions find or create a type. For example, `FindOrCreateVectorType` checks if the vector type exist and if needed create it. Although, it would be interesting to move the finding part to a `fuzzerutil` function such that it could be called in the transformation classes. The `FindOrCreatePointerType` already uses such logic by calling the `MaybeGetPointerType`.

**Comment by afd** [comment]
@andreperezmaselco and @Vasniktel is this issue still relevant?  I know that a lot of work was done on the MaybeGet and FindOrCreate functions lately, and I've lost track as to whether more work is required.

**Comment by Vasniktel** [comment]
I believe most of the `FindOrCreate` functions from `fuzzer_pass` have a counterpart `MaybeGet*` function in `fuzzer_util`, so  I think we can close this issue.

**Comment by andreperezmaselco** [comment]
Yes, I also think we can close this issue.
