### ISSUE TITLE
optimizer: allow OpUndef in section 9 (types, constants, variables)

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#343]
This is a change in 1.0 Rev 7 and 1.1 Rev 3
https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#_changes_from_version_1_00_revision_6

Optimizer needs to be updated.
(Similar to #339)

**Comment by antiagainst** [comment]
Done via https://github.com/KhronosGroup/SPIRV-Tools/pull/345.
