### ISSUE TITLE
Add an option to strip all debug info

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/SPIRV-Tools#3430]
`glslangValidator` uses the `SpvOptions::generateDebugInfo` to add more debug info if asked (through `-g`.

This is a request to add an option to `stripDebugInfo` (so `glslangValidator` could add a command-line argument for it). In short, this option should drop `OpName` and `OpMemberName` (and whatever other debug info I don't know about).

The reason for this request is to be able to reduce the binary size of compiled shaders when debug info doesn't really need to be shipped to users.

**Comment by alan-baker** [comment]
This exists in the form of `--strip-debug` in spirv-opt. It will strip those debug instructions. This could be done by glslang the same way it handles legalization.

**Comment by ShabbyX** [comment]
Thanks, that worked. Going to talk with JohnK about it.
