### ISSUE TITLE
SPIRV-opt Produces Output That FXC Compiles Incorrectly

### ISSUE THREAD

**Issue by bjjones** [KhronosGroup/SPIRV-Tools#3445]
With the introduction of https://github.com/KhronosGroup/SPIRV-Tools/commit/e7afeb060e1637ca964c62517c3e6c225704b7eb, SPIRV-opt may produce this uncommon pattern in HLSL:

```
switch (0u)
{
    default:
    {
        if (/* ... */)
        {
            _801 = /* assign a value */;
            break;
        }
        _801 = /* assign another value */;
        break;
    }
}
```

FXC seems to have some issue with correctly compiling this code, which is causing incorrect rendering in our workflow (WebGPU). Ideally, this issue would be fixed by FXC, given that it is FXC that is incorrect. However, it is not easy to get bugs fixed in FXC (closed source) - so I'm wondering if a workaround is possible on the SPIRV-opt side.

This issue has been touched on already in https://github.com/KhronosGroup/SPIRV-Tools/issues/3244, however was not entirely resolved.

A simple example of SPIRV-opt output compiled by FXC can be seen [here](http://shader-playground.timjones.io/3f6ba17487fe0419bd718abd5c564885).

It seems that anything within the `default` case is disregarded by FXC. I found a simple fix was instead putting code under `case 0u:` and leaving `default` empty. (disclosure: I know little about compiler optimizations and have no idea if this could translate to a valid fix).

**Comment by s-perron** [comment]
This is a bug in FXC for sure.  If I change the HLSL to use an undefined variable for the switch, correct code is generated.  We could probably work around this by add a case for 0 as you suggested, and generating a separate dummy default case.

This is ugly, but it can be done.

**Comment by s-perron** [comment]
It shouldn't mess with optimizations.  Once a compiler does not care about the structured control flow rules that exist in spir-v, the switch should be folded.

**Comment by bjjones** [comment]
I've thought a bit more about the issue and I'm now thinking a more robust fix would be to identify and workaround this pattern when converting to HLSL in SPIRV-Cross. I've filed an issue at https://github.com/KhronosGroup/SPIRV-Cross/issues/1402 - and I think it would make this change in SPIRV-opt unnecessary.

**Comment by s-perron** [comment]
I agree that might be better.  I had thought of it too, and I saw that pattern could be generated in many other ways as well.  The spirv-cross solution would be more robust.

**Comment by bjjones** [comment]
A fix has been merged in https://github.com/KhronosGroup/SPIRV-Cross/pull/1404. Closing this.

Thanks for the responsiveness @s-perron.
