### ISSUE TITLE
spirv-fuzz: Side effects in InstructionFromMessage

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3446]
`InstructionFromMessage` updates module's id bound. Consider removing this functionality.

**Comment by afd** [comment]
I'm going to close this as the updating of the module's id bound is deliberate and is documented in the comment for the function.  This is used by TransformationAddFunction: the instructions for the function are messages in the transformation's protobuf, and as we add the corresponding instructions to the module we want the id bound to increase.
