### ISSUE TITLE
spirv-opt: moves expensive constant expressions to inside loops

### ISSUE THREAD

**Issue by pixelflinger** [KhronosGroup/SPIRV-Tools#3460]
In some cases, _spirv-opt_ moves expensive operations to inside loops, even though these expressions were outside of the loop to begin with. Such expensive operations include `1/x`, `textureSize()`,` dFdx()`/`dFdy()`.

The attached shader (please remove the .txt extension) shows the problem with all operations above:

```
./glslangValidator --target-env opengl test0.frag -o test0.spv
./spirv-opt -O test0.spv -o test0.opt.spv
./spirv-cross --es test0.opt.spv
```

The resulting code contain this:
```
    for (float _58 = 0.0; _58 < count; ) {
        _59 += ((1.0 / float(textureSize(tex, 0).x)) * dFdx(vertex.x));
        _58 += 1.0;
        continue;
    }
```

Not only `(1.0 / float(textureSize(tex, 0).x)) * dFdx(vertex.x)` is constant, but it wasn't even inside the loop to begin with.

[test0.frag.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/4828246/test0.frag.txt)

**Comment by s-perron** [comment]
This is not a problem in spirv-opt.  spirv-cross is the tool that is moving the code inside the loop.  Here is the spir-v after optimization:

```
       %main = OpFunction %void None %3
          %5 = OpLabel
         %14 = OpLoad %11 %tex
         %17 = OpImage %10 %14
         **%19 = OpImageQuerySizeLod %v2int %17 %int_0**
         %22 = OpCompositeExtract %int %19 0
         %23 = OpConvertSToF %float %22
         %24 = OpFDiv %float %float_1 %23
         %32 = OpAccessChain %_ptr_Input_float %vertex %uint_0
         %33 = OpLoad %float %32
         **%34 = OpDPdx %float %33**
               OpBranch %36
         %36 = OpLabel
         %59 = OpPhi %float %float_0 %5 %51 %37
         %58 = OpPhi %float %float_0 %5 %53 %37
         %44 = OpLoad %float %count
         %46 = OpFOrdLessThan %bool %58 %44
               OpLoopMerge %38 %37 None
               OpBranchConditional %46 %37 %38
         %37 = OpLabel
         %49 = OpFMul %float %24 %34
         %51 = OpFAdd %float %59 %49
         %53 = OpFAdd %float %58 %float_1
               OpBranch %36
         %38 = OpLabel
         %57 = OpCompositeConstruct %v4float %59 %59 %59 %59
               OpStore %fragColor %57
               OpReturn
               OpFunctionEnd

```

**Comment by pixelflinger** [comment]
Ah... I assumed spirv-cross wouldn't do any transformation like that.  Thank you for looking into it quickly, I will re-file this with spirv-cross.

**Comment by pixelflinger** [comment]
mh... but wait, if you skip the `spirv-opt` step above, the problem doesn't happen!

**Comment by s-perron** [comment]
> mh... but wait, if you skip the spirv-opt step above, the problem doesn't happen!

Yes, before spirv-opt, the value is stored to a variable:

```
         %34 = OpDPdx %float %33 ; not in loop
               OpStore %d %34
...  
         %48 = OpLoad %float %d  ; in loop
         %49 = OpFMul %float %47 %48

```

spirv-cross will respect this explicit store and load because it does not have to create a new variable.

After optimization, the local variable has been removed, and the ssa value (%34) is used directly:

```
         %34 = OpDPdx %float %33 ; not in loop
...
         %49 = OpFMul %float %24 %34 ; in loop
```

Spir-v cross will propagate the OpDPdx as long as %34 is used exactly once.
