### ISSUE TITLE
spirv-fuzz: Add support for more comparizon operators to TransformationInvertComparisonOperator

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3495]
We could possibly add support for floating-point comparison operators (see https://github.com/KhronosGroup/SPIRV-Tools/pull/3475#issuecomment-654375460).

**Comment by afd** [comment]
@antnkarp This would be a good one for you to take in due course; can you reply so that I can assign you?

**Comment by antnkarp** [comment]
Yes, thanks

**Comment by afd** [comment]
Closed via #3551.
