### ISSUE TITLE
SPIR-V not valid: Passing uniform constants as function parameters

### ISSUE THREAD

**Issue by Carandiru0** [KhronosGroup/SPIRV-Tools#3496]
Looks like glslangvalidator just had this bug fixed, please refer to the issue:
https://github.com/KhronosGroup/glslang/issues/2264

This bug however inherited by spirv-opt still remains only in spirv-opt
Compiling the code in the above-referenced issue is working with glslangvalidator now, then a further pass with spirv-opt is currently failing for me. Giving the error I have mentioned, now only in spirv-opt.

My commandline:
start /B !spirv-opt! --target-env=vulkan1.2 --upgrade-memory-model -O !vIn! -o !vOut!

Using the Vulkan SDK 1.2.141.2

Thanks!

**Comment by alan-baker** [comment]
This works fine if I use an updated glslang to generate the SPIR-V sent to spirv-opt. spirv-opt validates the module before optimizing so using the invalid binary correctly generates the same validation error. Do you have valid SPIR-V that spirv-opt is making invalid?

**Comment by Carandiru0** [comment]
Yes, the valid spir-v that is compiled from glslangvalidator is then "optimized" afterwards with spirv-opt.
spirv-opt then fails due to it complaining about the: same spirv-v that was valid with glslangvalidator. I will see if I can upload a shader source example with the batch file I'm using as a reference for you.

**Comment by Carandiru0** [comment]
compiled with glslangvalidator, resulting spirv valid :
`$(VULKAN_SDK)\bin\glslangValidator.exe" -V120 --target-env vulkan1.2`

*then*

compiling with spirv-opt, fail spirv not valid 👎 
`!spirv-opt! --target-env=vulkan1.2`

error message:
`error : line 111: Interfaces passed to OpEntryPoint must be of type OpTypeVariable. Found OpFunctionParameter.
1>  %sdfTexture = OpFunctionParameter %_ptr_UniformConstant_8'

`#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_KHR_shader_subgroup_quad: enable

#define subgroup_quad_enabled
#define fragment_shader

#include "screendimensions.glsl"
#include "common.glsl"

layout(binding = 1) uniform sampler2DArray sdfTexture;

layout(location = 0) in vec4 fragColor;
layout(location = 1) in vec2 fragUv;
layout(location = 0) out vec4 outColor;

#define shade r
#define dist g

#define PIXEL_SIZE 5.0f

vec2 textureSDF(in restrict sampler2DArray sdfTexture, in const vec2 uv, in float pixel_size)
{
	vec3 uvw;
	uvw.xy = uv;
	
	// *first
	uvw.z = 0.0f;
	vec2 last_sdf = textureLod(sdfTexture, uvw, 0).rg;	
	last_sdf.shade = last_sdf.shade * last_sdf.dist;
	
	// *layers
	for (uvw.z = 1.0f ; uvw.z < 8.0f ; ++uvw.z )
	{
		uvw.xy = (InvScreenResDimensions * pixel_size) * floor(uv.xy / (InvScreenResDimensions * pixel_size));
		--pixel_size;

		vec2 sdf = textureLod(sdfTexture, uvw, 0).rg;	// .r shade , .g distance
		sdf.shade = mix(last_sdf.shade, sdf.shade, sdf.dist);

		// for the next layer //
		last_sdf.dist = last_sdf.dist + sdf.dist * (1.0f - last_sdf.dist);
	
		last_sdf.shade = mix(last_sdf.shade, sdf.shade, last_sdf.dist);		
	}
	return(last_sdf);
}

void main() {    
	const vec2 shaded = textureSDF(sdfTexture, fragUv, PIXEL_SIZE);
	outColor.rgb = fragColor.rgb * 2.0f * shaded.shade * fragColor.a;
}`

**Comment by alan-baker** [comment]
I cannot reproduce this error. I did have to change `InvScreenResDimensions` to a constant since I don't have the includes, but I doubt that's the difference. glslang and spirv-opt are both producing valid SPIR-V. Have you tried the latest versions of the tools? Which versions did you use to get this error?

**Comment by Carandiru0** [comment]
really ? I'm using the Vulkan SDK 1.2.141.2 which is the latest available on vulkan.lunarg.com
Do you have a newer version of the sdk installed, if so can you attach spirv-opt.exe in a zip file -- I can test it out that way.
Thanks for your help again!

**Comment by alan-baker** [comment]
I'm building from the latest source. So that glslang bugfix will likely be integrated into the next SDK. You can either build your own version for now or wait for a new SDK.

**Comment by Carandiru0** [comment]
Thanks, this issue has been resolved.
