### ISSUE TITLE
spirv-fuzz: a transformation that replaces an "irrelevant" id with some other id of the required type

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3503]

**Comment by afd** [comment]
@stefanomil Would you be happy to take this one?

I think we want:

- A transformation that takes an IdUseDescriptor for an existing id use, and an id
- It checks that the given id has the right type to be used in place of the id use described by the IdUseDescriptor
- It checks that the id use being replaced has the IdIsIrrelevant fact
- It does the replacement

The associated fuzzer pass should look for all uses of irrelevant ids and - for each one that it decides to replace - randomly choose something else in scope that has the right type.

Look at FuzzerPassReplaceIdWithSynonym for some inspiration.

@paulthomson for info.

**Comment by stefanomil** [comment]
@afd Yes, I can take this
