### ISSUE TITLE
spirv-fuzz: TransformationMoveBlockDown invalidates the module

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3529]
Consider the following file.
[shader.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/4919001/shader1.txt)

It contains a perfectly valid SPIR-V (i.e. the following test succeeds).
```cpp
TEST(A, a) {
  std::string shader; // code from the file

  const auto env = SPV_ENV_UNIVERSAL_1_3;
  const auto consumer = nullptr;
  const auto context = BuildModule(env, consumer, shader, kFuzzAssembleOption);
  ASSERT_TRUE(IsValid(env, context.get()));
}
```

However, if we try to move a basic block with id `370` one block down, the transformation will be applied correctly (i.e. `TransformationMoveBlockDown::IsApplicable` returns `true`) but the `spirv-val` will fail with with a somewhat ambiguous message:
```
error: line 121: Case construct that targets 310[%310] has invalid branch to block 414[%414] (not another case construct, corresponding merge, outer loop merge or outer loop continue)
  %310 = OpLabel
```

Commit id is 7afbc0c8.

**Comment by afd** [comment]
@alan-baker Would you be able to take a look at the following files?

[bad.asm.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/4919798/bad.asm.txt)
[good.asm.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/4919799/good.asm.txt)

They differ only in the syntactic positions of blocks 370 and 402, and there is no dominance relationship between these blocks so I don't think that swapping them should change whether the module is considered valid - but "bad" is considered invalid while "good" is considered valid.

Might this be a validator bug?

**Comment by alan-baker** [comment]
It does look like a validator bug. The reachability information is incorrect. Because of that, it is miscalculating the contents of the case construct.
