### ISSUE TITLE
spirv-fuzz: Relax type checking in TransformationRecordSynonymousConstants when dealing with integers

### ISSUE THREAD

**Issue by stefanomil** [KhronosGroup/SPIRV-Tools#3536]
Signed and unsigned integers will have different type ids. It would make sense, though, to consider them equivalent in TransformationRecordSynonymousConstants.

Related to PR #3537

**Comment by stefanomil** [comment]
This should be the behaviour:
- a signed integer of some value can be considered equivalent to an unsigned integer of the same value
- if these integers are in some composite constants, these constants should not be considered equivalent

**Comment by afd** [comment]
What about vectors?  I think we should consider integer vectors that have equivalent components as being equivalent even if they have different sign.

**Comment by stefanomil** [comment]
Also for matrices?

I have seen that you can give any type of integers to an integer vector, regardless of the type of the vector.
However, you can't interchange two vectors of different types (e.g. vector of signed integers with vector of unsigned integers).

So we should probably consider vectors that have equivalent components as being equivalent even if the components have different sign, however the types of the vectors must match exactly.

Do you agree or are there any situations in which it would be useful to consider vectors of different signs synonyms (e.g. some operations where they can be interchanged)?

**Comment by stefanomil** [comment]
Looking in the spec, I have seen that most arithmetic and bitwise logic operations operate both on integer scalars and vectors and don't care about their signedness, so I agree that it actually does make sense to consider two integer vector constants equivalent if their components are equivalent, regardless of whether their type is equivalent (and update the checks in the ReplaceIdWithSynonyms IsApplicable method to ensure that swapping the ids is only allowed for some operations if the types don't match exactly).
