### ISSUE TITLE
spirv-fuzz: Transformation to convert OpSelect to conditional branch (and vice versa?)

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3544]

**Comment by afd** [comment]
@stefanomil I think this would be a good one for you to look at in due course.

Turning OpSelect into a conditional branch should be relatively straightforward.

The "vice versa" part might be a lot harder but is potentially very interesting.

**Comment by stefanomil** [comment]
@afd Thanks, I'll look into it!
