### ISSUE TITLE
spirv-opt assertion failure related to OpCopyObject

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3547]
[tofile.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/4932781/tofile.zip)

spirv-opt with -O fails with:

```
spirv-opt: ../source/opt/def_use_manager.cpp:61: void spvtools::opt::analysis::DefUseManager::AnalyzeInstUse(spvtools::opt::Instruction*): Assertion `def && "Definition is not registered."' failed.
```

The SPIR-V applies OpCopyObject to an id with void type, which is a dumb thing to do but valid according to the current spec.

Issue found using spirv-fuzz.

**Comment by Vasniktel** [comment]
I think this has been fixed (can't reproduce it locally).

**Comment by s-perron** [comment]
Yes, I remember making a few changes to make this work.
