### ISSUE TITLE
spirv-opt crashes in constants.h

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3553]
Found by spirv-fuzz. Affects SwiftShader.

To reproduce, do:

```
spirv-opt -O small.spv -o temp.spv
```

I get this crash:

```
spvtools::opt::analysis::Constant::type() const
/home/runner/work/gfbuild-swiftshader/gfbuild-swiftshader/SwiftShader/b_Debug/../third_party/SPIRV-Tools/source/opt/constants.h:130
```

[tofile.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/4936525/tofile.zip) contains the .spv and corresponding .asm files needed to repro the bug - `large` is before reduction with spirv-reduce; `small` is after.  The .amber file is a runnable test that exposed the crash in SwiftShader.

**Comment by Vasniktel** [comment]
This might be related to #3634.

**Comment by Vasniktel** [comment]
I think this has been fixed.
