### ISSUE TITLE
Build failing due to wrong SPIRV-Headers DEPS revision

### ISSUE THREAD

**Issue by timvpGoogle** [KhronosGroup/SPIRV-Tools#3574]
ANGLE is hitting a build error trying to build SPIRV-Tools related to the wrong revision of SPIRV-Headers being specified in the DEPS file.

```
../../third_party/spirv-tools/src/source/opt/code_sink.cpp:217:12: error: use of undeclared identifier 'SpvOpAtomicFAddEXT'; did you mean 'SpvOpAtomicIAdd'?
      case SpvOpAtomicFAddEXT:
```

https://github.com/KhronosGroup/SPIRV-Tools/blob/f3cec93665ec6097dbc56dafbb8b46595842eded/DEPS#L9

The symbol `SpvOpAtomicFAddEXT` was added after this revision (I haven't looked which revision, but 979924c8bc839e4cb1b69d03d48398551f369ce7 looks good).

**Comment by null77** [comment]
@dj2 can someone in your team take a look ? We're getting failures rolling into Chromium here:

https://chromium-review.googlesource.com/c/chromium/src/+/2320029

And ANGLE here:

https://chromium-review.googlesource.com/c/angle/angle/+/2311732

Not sure if it's the same failure mode.

**Comment by dj2** [comment]
I believe Ryan is already looking into this.

**Comment by zoddicus** [comment]
This is going to require a multi-DEPS roll into Chromium, since Chromium doesn't auto-roll spirv-headers. Once my fix lands in spirv-tools, I will generate the manual roll needed for Chromium.

**Comment by null77** [comment]
@zoddicus SPIRV-Headers are pulled in via a transitive dependency on SPIRV-Tools's headers version in your DEPS file. So once you have the right headers version in your DEPS we can restart the rollers and they should work just fine.

**Comment by zoddicus** [comment]
oh, did not know that. Thanks for the heads up
