### ISSUE TITLE
auto-(dis)assemble from various tools using spirv-dis/as

### ISSUE THREAD

**Issue by steve-lunarg** [KhronosGroup/SPIRV-Tools#359]
As this isn't exactly an "issue", please feel free to delete if it's a breach of protocol.  I wasn't sure where else to put it, and I thought these might be handy for some people using SPIRV-Tools.
#### To allow the "less" pager (under *nix, BSD, and possibly cygwin) to transparently invoke spirv-dis on SPIRV binary files:

Place a script like this somewhere handy, and make it executable (chmod +x):

```
#!/bin/bash

case "$1" in
    *.spv) spirv-dis --raw-id "$1" 2>/dev/null;;
    *) exit 1;;
esac

exit $?
```

Then point the LESSOPEN variable to it, like so:

```
export LESSOPEN='|~/bin/lesspipe.sh "%s"'
```

Assuming spirv-dis is in your search path, you can now directly "less -R my_module.spv" on a binary and see it in a handy human readable form.  The -R is to preserve ANSI colors; you can add --no-color to the script if you don't like that.
#### To use spirv-dis and spirv-as to automatically (dis)assemble a SPIR-V binary file when loading or saving from emacs:

Place these lines into your .emacs file.  Then loading a binary will show the human readable asm in asm-mode in the editor buffer.  You can edit it within the constraints of validity, and when you re-save the file it will be assembled back to a SPIR-V binary.  Again you'll need the tools in your search path.  Handy for making hand tweaks to binary modules.

```
;; Handle auto-(dis)assemble of SPV binaries on save/load
(add-to-list 'jka-compr-compression-info-list
             '["\\.spv"
               "Assembling SPIRV" "spirv-as" ("-o" "-")
               "Disassembling SPIRV" "spirv-dis" ("--no-color" "--raw-id")
               t nil "\003\002\043\007"])

(add-to-list 'auto-mode-alist '("\\.spv\\'" . asm-mode))
```

**Comment by dneto0** [comment]
These are good ideas!

I made https://github.com/KhronosGroup/SPIRV-Tools/pull/364 to capture the less feature.  Please take a look.  It adds a spirv-lesspipe program that gets installed appropriately. 
The only funny bit is the people might have different preferences for default flags.  E.g. I didn't keep the --raw-id flag in the script, and others might not regularly use -R.   But it's a reasonable default.
Please take a look and provide a +1 on that MR if you like it.

As for the Emacs trick.  Is there a norm for sharing  emacs script file like that?  We could modify SPIRV-Tools to install a file in something like <prefix>/etc/emacs.  I'm a vim guy so I don't know.  Feel free to make a pull request to add the file and install target.  Or a PR to just update the README with instructions like you've got above.

**Comment by steve-lunarg** [comment]
Looks good - comments left in the PR.

Agreed about the flags.  I suppose it could be handled with an optional env variable that'd set them if given, but I don't know how much effort it's worth.

About the emacs blurb: to install it in a system location, it can be put into /etc/emacs/site-start.d/, at least on Debian flavored distributions.  I'm rather fuzzier about redhat derivations.  However, there is a bit more fiddling about required: the file must be named beginning with two digits, such as 50spirv-tools.el, and be given as follows.  Per your suggestion I'll put together a PR with it + copyright message, though it might take me a few days to get to it.

```
;; Handle auto-(dis)assemble of SPV binaries on load/save
;; This requires spirv-as and spirv-dis be in $PATH.

(require 'jka-compr)

(add-to-list 'jka-compr-compression-info-list
             '["\\.spv\\'"
               "Assembling SPIRV" "spirv-as" ("-o" "-")
               "Disassembling SPIRV" "spirv-dis" ("--no-color" "--raw-id")
               t nil "\003\002\043\007"])

(add-to-list 'auto-mode-alist '("\\.spv\\'" . asm-mode))

(jka-compr-update)

```

**Comment by dneto0** [comment]
Keeping this open in case anybody wants to add vim support.  :-)

**Comment by kbenzie** [comment]
@dneto0 I was not aware of this issue, I made [vim-spirv](https://github.com/kbenzie/vim-spirv) a couple of months ago. Its implemented as a vim plugin so I'm not 100% sure it belongs in this project, although I'm open to that. Might be better off with a link in the documentation.

**Comment by dneto0** [comment]
@kbenzie vim-spirv looks cool.   It's quite a bit more substantial than the emacs support.  I think vim-spirv should not be in this project.  But it would be good to point to it from the same part of this project's README that describes the emacs support: https://github.com/KhronosGroup/SPIRV-Tools#utility-filters 
I encourage you to submit a PR to update this project's README.

You should also submit a PR to update the SPIR-V resources page https://github.com/KhronosGroup/Khronosdotorg/blob/master/api/spir/resources.md

Hm. That doesn't mention the emacs filter either.  It should, and I encourage your change adds references to both.
