### ISSUE TITLE
spirv-fuzz: Duplicate region using selection construct

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3614]
Given a region R, this transformation will essentially turn R into:

```
if (...) {
  R;
} else {
  duplicate_of_R;
}
```

or alternatively to:

```
switch(...) {
case ...:
   R;
   break;
default:
   duplicate_of_R;
   break;
```

In both cases the value of the boolean guard or integer switch selector does not matter given that the branches are semantically equivalent.

The code after the duplicated region will need to use an OpPhi to capture ids generated by R and used after R.

**Comment by afd** [comment]
@paulthomson for info.

**Comment by paulthomson** [comment]
@antnkarp I think this might be a good one for you to take.

**Comment by antnkarp** [comment]
Great, I can implement this.
