### ISSUE TITLE
spirv-fuzz: Introduce a loop to create a synonym of an integer constant

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3616]
**Motivation for transformation:*
- Increase the extent to which loops are used in the SPIR-V module
- Provide the possibility to replace constant uses with the results of computations coming from loops
- The new loops can be transformed further by other fuzzer passes to make them more interesting.

Suppose that C is an integer constant (possibly a vector).

Decide on:
- A number of loop iterations, N
- A step count vector S
- An initial value vector I such that C = I - N*S

Introduce a loop that does:

```
temp = I // A constant containing value I
for (int new_counter = 0; new_counter < N; new_counter++) {
  temp = temp - S;
}
```

The number of loop iterations should be fairly small, to avoid very long-running loops.
The step count can vary between components of the vector, but overall should be small enough that we don't have overflow problems.
We should be careful about the extent to which we nest these - that could be taken care of in the fuzzer pass, not the transformation, though.

Then add a synonym between C and the final value of temp.

**Comment by afd** [comment]
@paulthomson for info.

**Comment by stefanomil** [comment]
@afd @paulthomson Should N and S already be present in the module for the transformation to be applicable? Maybe the fuzzer pass could take care of adding them, if needed.

Should the transformation also be given an instruction specifying where to insert this loop?

I could take this.

**Comment by afd** [comment]
Yes, the fuzzer pass should add N and S in advance, and the transformation should only be applicable if they are present - i.e. the transformation should take literal values for them and should find suitable constants.

Some info should indeed be provided to explain where to insert the loop.

There are a few choices as to how this could be done - let's discuss in person.

**Comment by afd** [comment]
@stefanomil What's the status of this - is there an open PR for it or is it done already?

**Comment by stefanomil** [comment]
@afd I have not opened the PR yet. I still need to implement the fuzzer pass and I think I will open the PR today or tomorrow morning
