### ISSUE TITLE
spirv-opt: Loop unroller doesn't support OpConstantNull

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3634]
[shader.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/5010247/shader.txt)

If you try to execute `spirv-opt <attached file> -o out.spv --loop-unroll` on the attached file, the tool will crash. The reason is that `LoopUnroller` optimization pass doesn't support `OpConstantNull` instructions. 

Note that the attached file demonstrates the case when the initial value of the counter

 is an `OpConstantNull`. The same bug can be observed if we try to use `OpConstantNull` to limit the number of iterations or as a step of an iteration (ids `%7`, %13`, %21` in the attached file).

The code that causes these crashes is as follows.
https://github.com/KhronosGroup/SPIRV-Tools/blob/b78f4b1518e0052491f4e7e01ace4ee915cb5de2/source/opt/loop_descriptor.cpp#L687-L688
https://github.com/KhronosGroup/SPIRV-Tools/blob/b78f4b1518e0052491f4e7e01ace4ee915cb5de2/source/opt/loop_descriptor.cpp#L712-L713
https://github.com/KhronosGroup/SPIRV-Tools/blob/b78f4b1518e0052491f4e7e01ace4ee915cb5de2/source/opt/loop_descriptor.cpp#L194-L195

Can be reproduced on b78f4b15.

**Comment by Vasniktel** [comment]
@s-perron @alan-baker ping

**Comment by s-perron** [comment]
Yes, this is a common error.  The null constant is not an "IntConstant", so it needs special handling.  We have since added functions in the constant class to be used.  These code patterns should be:

```
type = upper_bound->type()->AsInteger();
if (type) {
  if (type->IsSigned()) *value = upper_bound->GetSignExtendedValue();
  else *value = upper_bound->GetZeroExtendedValue();
}
```

This will work for integers up to 64-bit, signed and unsigned, and work with OpConstantNull.

**Comment by Vasniktel** [comment]
@s-perron, added a PR.
