### ISSUE TITLE
spirv-opt: CCP pass might create a new constant and return SuccessWithoutChange

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3636]
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
               OpSource ESSL 320
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeInt 32 1
          %7 = OpConstant %6 2
         %13 = OpConstant %6 4
         %21 = OpConstant %6 1
         %10 = OpTypeBool
         %17 = OpTypePointer Function %6
          %4 = OpFunction %2 None %3
         %11 = OpLabel
               OpBranch %5
          %5 = OpLabel
         %23 = OpPhi %6 %7 %11 %20 %15
          %9 = OpSLessThan %10 %23 %13
               OpLoopMerge %8 %15 None
               OpBranchConditional %9 %15 %8
         %15 = OpLabel
         %20 = OpIAdd %6 %23 %21
               OpBranch %5
          %8 = OpLabel
               OpReturn
               OpFunctionEnd
```

The attached shader contains a SPIR-V that causes an assertion failure at https://github.com/KhronosGroup/SPIRV-Tools/blob/b78f4b1518e0052491f4e7e01ace4ee915cb5de2/source/opt/optimizer.cpp#L590-L592

if the tool is executed with the following command `spirv-opt <attached binary> -o out.spv --ccp` (can be reproduced on b78f4b15).

The reason is that a new `OpConstantTrue` is created here https://github.com/KhronosGroup/SPIRV-Tools/blob/b78f4b1518e0052491f4e7e01ace4ee915cb5de2/source/opt/ccp_pass.cpp#L138-L140
when a CCP pass tries to fold an instruction with id `%9` for the first time. The second time the pass tries to simulate the execution of that instruction, it finds out that the instruction actually has a varying value, so the pass returns `SuccessWithoutChange` even though a new constant was created previously.

**Comment by Vasniktel** [comment]
@alan-baker @s-perron ping

**Comment by s-perron** [comment]
I see how that would happen.  I don't know the implementation for that pass well enough to know what to do about it.  @dnovillo Do you have any ideas on how to fix this up?  I think you are the one who implemented it.

**Comment by dnovillo** [comment]
I will take a look.

**Comment by dnovillo** [comment]
So, here I think CCP should actually said "yes, I've modified the source".  It introduces the constants `%int_3` and `%true` during simulation.  The fact that it later finds it impossible to replace either constant is independent.  It is still generating code that ends up being dead.  So, it's no different than if it did an actual replacement in the IR.

We still want to run DCE after this to get rid of the newly created constants.

Thoughts?

**Comment by s-perron** [comment]
I'm fine with that.  It does mean that some analyses will be invalidated needlessly, but that is not a big deal as long at it is not the inst-to-block map and the def-use chains.

**Comment by dnovillo** [comment]
Neither should be affected.  When constants are needlessly created, they will just show up as new (and unused) `OpConstant` declarations.
