### ISSUE TITLE
spirv-opt: OpAccessChain without indices is not supported

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3643]
The following SPIR-V passes `spirv-val`'s checks
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
               OpSource ESSL 310
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeBool
          %7 = OpTypePointer Function %6
          %4 = OpFunction %2 None %3
          %5 = OpLabel
         %10 = OpVariable %7 Function
         %11 = OpAccessChain %7 %10
               OpReturn
               OpFunctionEnd
```

In this code, the `Base` operand of the `OpAccessChain` is not a pointer to a composite. Also, indices operands are missing. The same issue arises with `OpInBoundsAccessChain`.

**Comment by Vasniktel** [comment]
@alan-baker @s-perron ping

**Comment by s-perron** [comment]
@alan-baker Where did the spec come done on the legality of this?  I remember we had discussions about it because some optimizations assume at least one index.  However, I forget the result.

**Comment by alan-baker** [comment]
It was left as valid because there are a reasonable number of code generators that generate this case.

**Comment by Vasniktel** [comment]
spirv-opt doesn't support this case, though. This SPIR-V
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
               OpSource ESSL 310
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeBool
          %7 = OpTypePointer Function %6
          %4 = OpFunction %2 None %3
          %5 = OpLabel
         %10 = OpVariable %7 Function
         %11 = OpAccessChain %7 %10
         %12 = OpLoad %6 %11
               OpReturn
               OpFunctionEnd
```
produces an error
> error: line 16: Expected at least one index to OpCompositeExtract, zero found
  %12 = OpCompositeExtract %bool %13
>
> error: line 0: Validation failed after pass convert-local-access-chains

when executed with the following command `spirv-opt <attached file> -o out.spv --validate-after-all --convert-local-access-chains`. This can be reproduced on 28f32ca5.

Compiled shader is in the [attached file ](https://github.com/KhronosGroup/SPIRV-Tools/files/5028997/data.zip).

**Comment by paulthomson** [comment]
In an internal discussion, it was suggested that the pointer operand must point to a composite (as implied by the spec). Thus, this can be regarded as a spirv-val bug.

And 0 indices is fine, so this can be classed as a spirv-opt bug.
