### ISSUE TITLE
spirv-fuzz: TransformationAccessChain produces OpAccessChain without indices

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3644]
`TransformationAccessChain` can produce a code from the #3643.

**Comment by Vasniktel** [comment]
@stefanomil I can assign you to this one if you want :)

**Comment by stefanomil** [comment]
Yes, thank you!

**Comment by Vasniktel** [comment]
The issue here is in a fuzzer pass
https://github.com/KhronosGroup/SPIRV-Tools/blob/b78f4b1518e0052491f4e7e01ace4ee915cb5de2/source/fuzz/fuzzer_pass_add_access_chains.cpp#L106-L108
In this snippet, we might break out of the loop without ever adding any indices.

The transformation class will probably require some adjustment as well: we will need to check that the base type of an `OpAccessChain` is a composite.

No rush on this one though. I think it would be better to wait for the reply from the `spirv-val` team on #3643. It might turn out that the bug is actually in the `spirv-opt` and the spec needs clarification.

**Comment by Vasniktel** [comment]
Turns out this is not a bug.
