### ISSUE TITLE
spirv-fuzz: Fuzzed shader invalidation due missing Float64 capability

### ISSUE THREAD

**Issue by andreperezmaselco** [KhronosGroup/SPIRV-Tools#3669]
`spirv-val` invalidated a fuzzed shader because a 64-bit float type was declared but the `Float64` capability was missing.
```
error: line 67: Using a 64-bit floating point type requires the Float64 capability.
  %double = OpTypeFloat 64
```
Debugging `spirv-fuzz`, I found that `TransformationAddTypeFloat` adds 16-bit and 64-bit float types without adding the corresponding `Float16` and `Float64` capabilities.

**Comment by paulthomson** [comment]
`TransformationAddTypeFloat` and `TransformationAddTypeInt` did not check whether the required capabilities were present when adding 16-bit, 64-bit, and 8-bit types.

#3670 adds the required checks to the transformations.

#3685 fixes FuzzerPassAddEquationInstructions to avoid applying the transformations with types that are not allowed.
