### ISSUE TITLE
spirv-val: OpUndef can be applied to OpTypeVoid

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3716]
According to spirv-val, the following code is valid:
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
        %575 = OpUndef %2
          %4 = OpFunction %2 None %3
          %5 = OpLabel
               OpReturn
               OpFunctionEnd
```
However:

`OpUndef` spec:

```
Make an intermediate object whose value is undefined.
Result Type is the type of object to make.
```
What is `intermediate object`:

```
Intermediate Object or Intermediate Value or Intermediate Result: An object created by an operation 
(not memory allocated by OpVariable) and dying on its last consumption.
```

What is `object`:

```
Object: An instantiation of a non-void type, either as the Result <id> of an operation, or created
through OpVariable.
```

The object is of a non-void type, so `OpUndef` shall not have `OpTypeVoid` as a type.

**Comment by Vasniktel** [comment]
The bug was found originally [here](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3427#note_600111)

**Comment by Vasniktel** [comment]
@s-perron @alan-baker ping

**Comment by Vasniktel** [comment]
This is a valid use case for an `OpUndef`, as was discussed in #3720. This means, however, that the spec might need some clarification regarding the use of `intermediate object` term in the `OpUndef` opcode spec.

**Comment by s-perron** [comment]
@dneto0 @alan-baker This is an interesting question: Is an undef on the void type allowed?  I'll be generating them with my change to inlining.  If not, there is no way to inline a void function when the result is used.  If we are going to change the spec, I would prefer that we disallow any use of the result of calling a void function.

**Comment by werman** [comment]
Is there any issue created for SPIV spec?

I'd like to know the resolution of this inconsistency to understand whether there is a need to fix Mesa (https://gitlab.freedesktop.org/mesa/mesa/-/issues/3427).

**Comment by alan-baker** [comment]
I think this will depend on how Khronos internal issue 585 works out.

**Comment by cmarcelo** [comment]
The Khronos internal issue was resolved, the result is already implemented (and merged) in validator https://github.com/KhronosGroup/SPIRV-Tools/pull/4036. Should we close this issue?
