### ISSUE TITLE
spirv-fuzz: Make the spirv-fuzz inliner more aggressive

### ISSUE THREAD

**Issue by andreperezmaselco** [KhronosGroup/SPIRV-Tools#3735]
Currently, the `TransformationInlineFunction` does not inline functions containing `OpKill` / `OpUnreachable` instructions. This is to guard against making the module invalid when the caller is inside a continue construct. However, it could allow functions that use `OpKill` / `OpUnreachable` to be inlined if the function call is not part of a continue construct.

**Comment by afd** [comment]
Duplicate of #3717
