### ISSUE TITLE
spirv-fuzz: Invalid variant shader

### ISSUE THREAD

**Issue by andreperezmaselco** [KhronosGroup/SPIRV-Tools#3761]
A variant shader was invalidated due an issue in `FuzzerPassAddOpPhiSynonyms`.
Debugging `spirv-fuzz`, I found that, in `FuzzerPassAddOpPhiSynonyms::GetIdEquivalenceClasses` at line 165, `pair` represents an `OpFunction` instruction with float return type. But this instruction can not be synonymous with anything. In this case the synonym to be considered is an `OpFunctionCall` instruction that calls `pair.first`.

```
error: line 113: Invalid use of function result id 10[%fx_f1_].
  %262 = OpPhi %float %fx_f1_ %56
```

**Comment by afd** [comment]
Thanks @andreperezmaselco!  Do you mean a transformation to add an OpPhi synonym actually gets applied and leads to an invalid module?  Would you be able to give a concrete example (ideally as a failing test)?

@stefanomil would you be able to look into this?

**Comment by stefanomil** [comment]
@afd Yes

**Comment by stefanomil** [comment]
@afd The problem, as @andreperezmaselco said, is that ``FuzzerPassAddOpPhiSynonyms::GetIdEquivalenceClasses`` considered also OpFunction instructions as valid ids from which to get ids.

I think that also OpUndef instructions would cause problems. Are there any other opcodes that have particular requirements or cause undefined behaviour (the result type is already restricted to be one of Bool, Integer, Float, Vector, Matrix, Array, Struct, or Pointer if the VariablePointers capability is enabled).
