### ISSUE TITLE
Feature request: ELF section header

### ISSUE THREAD

**Issue by seanbaxter** [KhronosGroup/SPIRV-Tools#3765]
Is there a section header defined for allowing spirv-dis, spirv-val etc to find .spv modules embedded in ELF binaries? CUDA compilers put PTX modules into .nvFatBinSegment to allow cubojdump to locate it within executables. A similar thing would make the SPIRV tooling nicer.

**Comment by s-perron** [comment]
That is not an issue for spirv-tools. The binary format is defined by the SPIR-V spec, and that is what we work with.
