### ISSUE TITLE
spirv-fuzz: Apply transformation for blocks with pointers (and other types) when adding OpPhi is unnecessary.

### ISSUE THREAD

**Issue by antnkarp** [KhronosGroup/SPIRV-Tools#3787]
Adding OpPhi for instructions with pointer types requires CapabilityVariablePointers in a shader. Currently the transformation adds OpPhi instructions to all instructions from original region which are available at the end of the region. If the shader does not have a CapabilityVariablePointers, this limits the applicability of the transformation. Consider not adding OpPhi instructions corresponding to pointers which are not used after the region, so that the transformation is still applicable to regions contaning them.

**Comment by afd** [comment]
The same applies when the result type is OpTypeSampledImage (and any other types that are not allowed as OpPhi arguments).
