### ISSUE TITLE
Optimizer::Run crashes on invalid SPIR-V input

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/SPIRV-Tools#3801]
See glslang issue https://github.com/KhronosGroup/glslang/issues/2385.  The primary issue is glslang not validating the HLSL and hence emitting unsupported code.  Secondarily, SPIRV-Tools might want to protect against the crash.  I'd thought the validator was run first, and if so, maybe there is something the validator is not catching.

**Comment by johnkslang** [comment]
Oh, you'd want to test that with a non-fixed glslang.  The (current one) at 759ae5 should work for reproduction.

**Comment by dj2** [comment]
In the `glslang/SpvTools.cpp` there are several `spvOptOptions.set_run_validator(false); // The validator may run as a separate step later on` which is disabling the use of the validator in the optimizer.

Without the validator being run the optimizer will make assumptions that the provided spir-v is valid.

**Comment by johnkslang** [comment]
Yes, that's fine with me. If it's okay for you, you can close.

**Comment by dj2** [comment]
Closing as invalid.
