### ISSUE TITLE
spirv-fuzz: Should TransformationAddImageSampleUnusedComponents use an irrelevant id for the unused components?

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3808]
TransformationAddImageSampleUnusedComponents adds unused components to an image sample instruction.  These components can presumably have arbitrary values, so we should use a zero with the id is irrelevant fact.  I'm not sure we do that at present.

@andreperezmaselco for info.

**Comment by andreperezmaselco** [comment]
You're right. We do not do this at present.
May I fix it?
