### ISSUE TITLE
Compiler error on macOS with XCode 12.0

### ISSUE THREAD

**Issue by richard-lunarg** [KhronosGroup/SPIRV-Tools#3825]
Apple recently released a new version of XCode and command line tools. When using XCode 12, the build fails in /source/cfa.h at line 130.

Just removing the 'const' qualifier for the 'auto b' declaration allows the whole project to build again.

i.e.
for (auto b : work_list) {

Here is the actual compiler error if an alternate work-around/fix is prefered:

*** ERROR ***
stderr contains:
In file included from /Users/lunarg/Dev/macos-sdk-build/Glslang/External/spirv-tools/source/val/validate_cfg.cpp:28:
/Users/lunarg/Dev/macos-sdk-build/Glslang/External/spirv-tools/source/cfa.h:130:19: error: loop variable 'b' of type 'const spvtools::CFA<spvtools::val::BasicBlock>::block_info' creates a copy from type 'const spvtools::CFA<spvtools::val::BasicBlock>::block_info' [-Werror,-Wrange-loop-analysis]
  for (const auto b : work_list) {
                  ^
/Users/lunarg/Dev/macos-sdk-build/Glslang/External/spirv-tools/source/cfa.h:161:11: note: in instantiation of member function 'spvtools::CFA<spvtools::val::BasicBlock>::FindInWorkList' requested here
      if (FindInWorkList(work_list, child->id())) {
          ^
/Users/lunarg/Dev/macos-sdk-build/Glslang/External/spirv-tools/source/val/validate_cfg.cpp:952:24: note: in instantiation of member function 'spvtools::CFA<spvtools::val::BasicBlock>::DepthFirstTraversal' requested here
      CFA<BasicBlock>::DepthFirstTraversal(
                       ^
/Users/lunarg/Dev/macos-sdk-build/Glslang/External/spirv-tools/source/cfa.h:130:8: note: use reference type 'const spvtools::CFA<spvtools::val::BasicBlock>::block_info &' to prevent copying
  for (const auto b : work_list) {
       ^~~~~~~~~~~~~~
                  &
1 error generated.

**Comment by greg-lunarg** [comment]
> When using XCode 11

Do you mean XCode 12?

**Comment by richard-lunarg** [comment]
>Do you mean XCode 12?

Yes, thanks. I updated the original text to avoid future confusion.

**Comment by richard-lunarg** [comment]
Fixed with PR #3836
