### ISSUE TITLE
Intent to relicense SPIRV-Tools under Apache 2 license

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#383]
To better align with other Khronos Group-sponsored software tools and the Vulkan spec, the SPIR Working Group expressed a desire to relicense the SPIRV-Tools suite under the Apache 2 license.

Let's use this issue to track consent for this change from all contributing authors.
(Often a corporation can own the copyright of a contributor's work.)

Consent is already received for contributions from:
* Google Inc.:  dneto0, antiagainst, dekimir, awoloszyn, qining, chrisforbes, phaulos, null77
* The Khronos Group Inc.: umar456.

Need to round up consent from:
@kbenzie 
@a2flo 
@1ace 
@McNopper 
@benvanik 
@pierremoreau 
@drWulf

**Comment by McNopper** [comment]
You have also my consent.

**Comment by a2flo** [comment]
You have my consent to relicensing SPIRV-Tools under the Apache 2 license.

**Comment by dneto0** [comment]
I received consent by email from @benvanik 
Thanks!

**Comment by kbenzie** [comment]
I consent.

**Comment by drWulf** [comment]
I consent as well.

**Comment by 1ace** [comment]
You also have my consent 👍

**Comment by dneto0** [comment]
Only one remaining: @pierremoreau do you consent?

**Comment by pierremoreau** [comment]
Sorry, I was lagging behind Github notifications… You have my consent as well.

**Comment by dneto0** [comment]
Thanks all!  Actually that took less time than expected.  :-)
