### ISSUE TITLE
spirv-opt ssa-rewrite produces code that fails the validator

### ISSUE THREAD

**Issue by khyperia** [KhronosGroup/SPIRV-Tools#3873]
Minimized repro case:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos SPIR-V Tools Assembler; 0
; Bound: 14
; Schema: 0
               OpCapability Shader
               OpCapability VariablePointers
               OpExtension "SPV_KHR_variable_pointers"
               OpMemoryModel Logical Simple
               OpEntryPoint Fragment %1 "main" %2 %3
               OpExecutionMode %1 OriginUpperLeft
      %float = OpTypeFloat 32
       %void = OpTypeVoid
          %6 = OpTypeFunction %void
%_ptr_Input_float = OpTypePointer Input %float
%_ptr_Output_float = OpTypePointer Output %float
%_ptr_Function__ptr_Input_float = OpTypePointer Function %_ptr_Input_float
          %2 = OpVariable %_ptr_Input_float Input
          %3 = OpVariable %_ptr_Output_float Output
          %1 = OpFunction %void None %6
         %10 = OpLabel
         %11 = OpVariable %_ptr_Function__ptr_Input_float Function
               OpStore %11 %2
         %12 = OpLoad %_ptr_Input_float %11
         %13 = OpLoad %float %12
               OpStore %3 %13
               OpReturn
               OpFunctionEnd
```

which succeeds spirv-val.

command: `spirv-as --target-env spv1.0 thing.txt -o thing.spv && spirv-val thing.spv && spirv-opt --ssa-rewrite thing.spv -o thing_opt.spv && spirv-val thing_opt.spv`

the resulting module:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos SPIR-V Tools Assembler; 0
; Bound: 12
; Schema: 0
               OpCapability Shader
               OpCapability VariablePointers
               OpExtension "SPV_KHR_variable_pointers"
               OpMemoryModel Logical Simple
               OpEntryPoint Fragment %1 "main" %2 %3
               OpExecutionMode %1 OriginUpperLeft
      %float = OpTypeFloat 32
       %void = OpTypeVoid
          %6 = OpTypeFunction %void
%_ptr_Input_float = OpTypePointer Input %float
%_ptr_Output_float = OpTypePointer Output %float
%_ptr_Function__ptr_Input_float = OpTypePointer Function %_ptr_Input_float
          %2 = OpVariable %_ptr_Input_float Input
          %3 = OpVariable %_ptr_Output_float Output
          %1 = OpFunction %void None %6
         %10 = OpLabel
         %11 = OpVariable %_ptr_Function__ptr_Input_float Function
               OpStore %11 %2
               OpStore %3 %2
               OpReturn
               OpFunctionEnd
```

which fails spirv-val with

```
error: line 19: OpStore Pointer <id> '3[%3]'s type does not match Object <id> '2[%2]'s type.
  OpStore %3 %2
```

---

From a high-level glance, it seems like handling of pointers-to-pointers is the culprit? Or the sequence of load-load. No idea though.

**Comment by khyperia** [comment]
I tried to dig in to this, but I'm a little confused.

So, this line calls GetPtr.

https://github.com/KhronosGroup/SPIRV-Tools/blob/d91afd8de27a064f938a196fdea2ace234971faa/source/opt/ssa_rewrite_pass.cpp#L323

When inst = `%13 = OpLoad %float %12`, this _should_ return `%12` in `var_id` or something, I'm not 100% sure. Instead, it returns `var_id = %2`!

This is because this line "dereferences it" once, going from the `%13` instruction to `%12`:

https://github.com/KhronosGroup/SPIRV-Tools/blob/d91afd8de27a064f938a196fdea2ace234971faa/source/opt/mem_pass.cpp#L131

then this line "dereferences it" _again_, going from `%12` to `%2`:

https://github.com/KhronosGroup/SPIRV-Tools/blob/d91afd8de27a064f938a196fdea2ace234971faa/source/opt/mem_pass.cpp#L108

Adding a `ptrInst->opcode() != SpvOpLoad` condition into this statement completely fixes the problem and produces valid spir-v output (albeit with an extra OpVariable and useless single OpStore...), but because I have no idea what `GetPtr` is supposed to be doing or what it's supposed to return, I'm guessing this is an incorrect fix.

https://github.com/KhronosGroup/SPIRV-Tools/blob/d91afd8de27a064f938a196fdea2ace234971faa/source/opt/mem_pass.cpp#L106-L107

**Comment by Jasper-Bekkers** [comment]
@dnovillo you did the original implementation, maybe you can provide us with some clues how to fix this?

**Comment by dnovillo** [comment]
Sure.  I'll take a look.

**Comment by dnovillo** [comment]
Apologies for the delays.   I'll try to get to this next week.

**Comment by dnovillo** [comment]
@alan-baker could you take a look at this?  The SSA rewriter is essentially assigning an input float into an output float, which is tripping the validator.  I'm not convinced this is a validation failure, but you'll know better:

```
[ ... ]
%_ptr_Input_float = OpTypePointer Input %float
%_ptr_Output_float = OpTypePointer Output %float
[ ...]
          %2 = OpVariable %_ptr_Input_float Input
          %3 = OpVariable %_ptr_Output_float Output
[ ...]
               OpStore %3 %2
               OpReturn
```

Thanks.

**Comment by khyperia** [comment]
Oh, sorry, to be clear, this is a bug in spirv-opt, not the validator. `ssa-rewrite` *should* produce code that looks something like this:

```
%tmp = OpLoad %2
OpStore %3 %tmp
```

I meant "fails the validator" as a proxy for "generates invalid code", should have been more explicit about that.

**Comment by dnovillo** [comment]
> Oh, sorry, to be clear, this is a bug in spirv-opt, not the validator. `ssa-rewrite` _should_ produce code that looks something like this:
> 
> ```
> %tmp = OpLoad %2
> OpStore %3 %tmp
> ```
> 
> I meant "fails the validator" as a proxy for "generates invalid code", should have been more explicit about that.

Thanks.  Huh, so the `Output` and `Input` qualifiers matter.  I wonder why the type system is marking them compatible.  @alan-baker, is this a matter of making these two types incompatible?

**Comment by dnovillo** [comment]
I finally got back to this.  The problem here is during the analysis of `OpLoad` instructions.  When analyzing `%13 = OpLoad %float %12`, the reaching definition for `%12` is ultimately `%2` (via `*%11`).  The analysis was (wrongly) adding the equivalence `%13 == %2`, when in reality it should be `%13 == *%2`.

I'm about to post the PR, which ultimately converts the code in this bug into:

```
[ ... ]
          %1 = OpFunction %void None %6
         %10 = OpLabel
         %11 = OpVariable %_ptr_Function__ptr_Input_float Function
               OpStore %11 %2
         %13 = OpLoad %float %2
               OpStore %3 %13
               OpReturn
               OpFunctionEnd
```
