### ISSUE TITLE
Make Function::AddBasicBlock set the parent of the block

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3912]
Currently AddBasicBlock does not set the parent of the given block to be the function to which it is being added.

Overlooking this has been the source of a few bugs in spriv-fuzz.

@s-perron and @alan-baker can you think of any reason why we shouldn't change AddBasicBlock so that it always sets the parent?  If not then I will make the change.

**Comment by alan-baker** [comment]
That does seem like an oversight. Go ahead and make the change.
