### ISSUE TITLE
spirv-fuzz: Bug in TransformationPropagateInstructionUp

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#3924]
`prev.asm` is valid, while `current.asm` is not.  The difference is that TransformationPropagateInstructionUp has been applied.

[tofile.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/5390696/tofile.zip)

@Vasniktel for info.

**Comment by Vasniktel** [comment]
Strangely, I can't reproduce this on dd534e87. I wrote the following test:
```cpp
TEST(TransformationPropagateInstructionUpTest, A) {
  std::string shader = "<contents of the prev.asm>"; 

  const auto env = SPV_ENV_UNIVERSAL_1_5;
  const auto consumer = nullptr;
  const auto context = BuildModule(env, consumer, shader, kFuzzAssembleOption);
  ASSERT_TRUE(IsValid(env, context.get()));

  spvtools::ValidatorOptions validator_options;
  TransformationContext transformation_context(
      MakeUnique<FactManager>(context.get()), validator_options);

  TransformationPropagateInstructionUp transformation(
      10, {{{422, 425}, {42, 424}}});
  ASSERT_TRUE(transformation.IsApplicable(context.get(), transformation_context));
  transformation.Apply(context.get(), &transformation_context);
  ASSERT_TRUE(IsValid(env, context.get()));

  std::string after_transformation = "<contents of the current.asm>"; 

  ASSERT_TRUE(IsEqual(env, after_transformation, context.get()));
}
```

It fails with the following diff:
```diff
@@ -95,8 +95,9 @@
                OpBranch %422
         %422 = OpLabel
+        %425 = OpSLessThan %17 %9 %16
                OpLoopMerge %423 %422 None
                OpBranchConditional %420 %10 %422
          %10 = OpLabel
-         %18 = OpPhi %17 %424 %42
+         %18 = OpPhi %17 %425 %422 %424 %42
         %302 = OpPhi %6 %9 %422 %55 %42
                OpLoopMerge %12 %42 None
```
which is exactly what the transformation should have produced in your case.

This bug might depend on some previous transformations applied to the module. It might also be a bug in the spirv-opt. Namely, it seems that this line
https://github.com/KhronosGroup/SPIRV-Tools/blob/dd534e877e725c9bb6f751c427442456a05384e4/source/fuzz/transformation_propagate_instruction_up.cpp#L136
 doesn't return all predecessors of the block we propagate an instruction from - `%10`.

**Comment by afd** [comment]
Thanks for checking - I will see whether I can debug it locally.  I have been fixing some other things and it may be some bad interaction with my "fixes".
