### ISSUE TITLE
Failed to build on SLES (Linux)

### ISSUE THREAD

**Issue by skosnits** [KhronosGroup/SPIRV-Tools#395]
We need this tools build support on Linux for automatic check generated SPIRV files with latest SPIRV-GEN tool.

Environment:
OS - SUSE Linux Enterprise Server 11 (x86_64)
CMAKE- 3.0
GCC - 4.7

Build log:
cmake -D CMAKE_BUILD_TYPE=Release .
cmake --build . --config Release
...
16:34:02 -- The C compiler identification is GNU 4.7.2
16:34:02 -- The CXX compiler identification is GNU 4.7.2
16:34:02 -- Check for working C compiler: /usr/bin/gcc-4.7
16:34:02 -- Check for working C compiler: /usr/bin/gcc-4.7 -- works
16:34:02 -- Detecting C compiler ABI info
16:34:02 -- Detecting C compiler ABI info - done
16:34:02 -- Check for working CXX compiler: /usr/bin/g++-4.7
16:34:02 -- Check for working CXX compiler: /usr/bin/g++-4.7 -- works
16:34:02 -- Detecting CXX compiler ABI info
16:34:02 -- Detecting CXX compiler ABI info - done
16:34:03 -- Found PythonInterp: ***/lin.x64/python-2.7.9/bin/python (found version "2.7.9") 
16:34:03 -- Did not find googletest, tests will not be built.To enable tests place googletest in '<spirv-dir>/external/googletest'.
16:34:03 -- Configuring done
16:34:03 -- Generating done
16:34:03 -- Build files have been written to: /localdisk/workspace/build_161
16:34:03 [  2%] Update build-version.inc in the SPIRV-Tools build directory (if necessary).
16:34:03 [  4%] Generate info tables for OpenCL extended instructions and operands v1.0.
16:34:03 [  6%] Generate info tables for GLSL extended instructions and operands v1.0.
16:34:03 [  8%] Generate info tables for SPIR-V v1.0 core instructions and operands.
16:34:03 [ 10%] Generate info tables for SPIR-V v1.1 core instructions and operands.
16:34:03 Scanning dependencies of target SPIRV-Tools
16:34:03 [ 12%] Building CXX object source/CMakeFiles/SPIRV-Tools.dir/assembly_grammar.cpp.o
16:34:04 [ 14%] Building CXX object source/CMakeFiles/SPIRV-Tools.dir/binary.cpp.o
16:34:06 [ 16%] Building CXX object source/CMakeFiles/SPIRV-Tools.dir/diagnostic.cpp.o
16:34:07 [ 18%] Building CXX object source/CMakeFiles/SPIRV-Tools.dir/disassemble.cpp.o
16:34:08 In file included from /localdisk/workspace/build_161/source/disassemble.cpp:47:0:
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h: In instantiation of ‘std::ostream& spvutils::operator<<(std::ostream&, const spvutils::HexFloat<T, Traits>&) [with T = spvutils::FloatProxy<spvutils::Float16>; Traits = spvutils::HexFloatTraits<spvutils::FloatProxy<spvutils::Float16> >; std::ostream = std::basic_ostream<char>]’:
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:1082:44:   required from here
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:679:43: error: no type named ‘uint_type’ in ‘using HF = class spvutils::HexFloat<T, Traits>’
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:680:41: error: no type named ‘int_type’ in ‘using HF = class spvutils::HexFloat<T, Traits>’
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:698:44: error: in argument to unary !
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h: In instantiation of ‘std::ostream& spvutils::operator<<(std::ostream&, const spvutils::HexFloat<T, Traits>&) [with T = spvutils::FloatProxy<float>; Traits = spvutils::HexFloatTraits<spvutils::FloatProxy<float> >; std::ostream = std::basic_ostream<char>]’:
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:1073:7:   required from ‘std::ostream& spvutils::operator<<(std::ostream&, const spvutils::FloatProxy<T>&) [with T = float; std::ostream = std::basic_ostream<char>]’
16:34:08 /localdisk/workspace/build_161/source/disassemble.cpp:258:58:   required from here
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:679:43: error: no type named ‘uint_type’ in ‘using HF = class spvutils::HexFloat<T, Traits>’
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:680:41: error: no type named ‘int_type’ in ‘using HF = class spvutils::HexFloat<T, Traits>’
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:698:44: error: in argument to unary !
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h: In instantiation of ‘std::ostream& spvutils::operator<<(std::ostream&, const spvutils::HexFloat<T, Traits>&) [with T = spvutils::FloatProxy<double>; Traits = spvutils::HexFloatTraits<spvutils::FloatProxy<double> >; std::ostream = std::basic_ostream<char>]’:
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:1073:7:   required from ‘std::ostream& spvutils::operator<<(std::ostream&, const spvutils::FloatProxy<T>&) [with T = double; std::ostream = std::basic_ostream<char>]’
16:34:08 /localdisk/workspace/build_161/source/disassemble.cpp:277:57:   required from here
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:679:43: error: no type named ‘uint_type’ in ‘using HF = class spvutils::HexFloat<T, Traits>’
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:680:41: error: no type named ‘int_type’ in ‘using HF = class spvutils::HexFloat<T, Traits>’
16:34:08 /localdisk/workspace/build_161/source/util/hex_float.h:698:44: error: in argument to unary !
16:34:08 gmake[2]: *** [source/CMakeFiles/SPIRV-Tools.dir/disassemble.cpp.o] Error 1
16:34:08 gmake[1]: *** [source/CMakeFiles/SPIRV-Tools.dir/all] Error 2
16:34:08 gmake: *** [all] Error 2

**Comment by dneto0** [comment]
You're using GCC 4.7 while we've been using GCC 4.8.2, Clang something (on Apple), VS 2013 and VS 2015.
Is it possible to use a newer compiler?

**Comment by skosnits** [comment]
I think yes, thanks for the quick response.
