### ISSUE TITLE
Problem with use of `std::stringstream`

### ISSUE THREAD

**Issue by Jake-Shadle** [KhronosGroup/SPIRV-Tools#3992]
name_mapper.cpp has this [to_string function](https://github.com/KhronosGroup/SPIRV-Tools/blob/abe2eff36f3cefa15eec98d9f08e12e05493966e/source/name_mapper.cpp#L34-L40) which was add in 0bdcc23f7e851c309327e7330a80651e058050c2 and hasn't been touched since then.

The reason I'm bring this up because I get this exception with using it.

![image](https://user-images.githubusercontent.com/2316028/97044653-af843980-1574-11eb-92a8-a37e9548f667.png)

And if I change it, no exception, validation runs as it should.

```diff
std::string to_string(uint32_t id) {
-  // Use stringstream, since some versions of Android compilers lack
-  // std::to_string.
-  std::stringstream os;
-  os << id;
-  return os.str();
+  return std::to_string(id);
}
```

I assume that something is wrong with my [build setup](https://github.com/EmbarkStudios/rust-gpu/pull/117/files#diff-05e3739f05dc5e1a063c878010e8ad178aff3dc51680e93db13a108b4b3433c3) but nothing is jumping out as a likely culprit, so I'm wondering if replacing name_mapper's to_string with std::to_string would be fine now, supposedly it's C++11, and it's been 4 years, so maybe whatever Android compiler(s) are being referenced in the comment have been supplanted by now?

**Comment by s-perron** [comment]
I don't know why this is failing, but we specifically did not want to use `std::to_string`. See the comment that your suggestion removes.

I also don't understand why you are getting an exception. With a way of reproducing, I don't think there is much we can do.

@dneto0 Is this something you want to update, or should we just close it?

**Comment by Jake-Shadle** [comment]
Oh forgot this bug existed, I just patched it in our own fork to avoid this crash and it's been fine.
