### ISSUE TITLE
2020.5 build fails due to missing commit a1d38174b1f7d2651c718ae661886d606cb50a32

### ISSUE THREAD

**Issue by cbxbiker61** [KhronosGroup/SPIRV-Tools#3999]
Commit a1d38174b1f7d2651c718ae661886d606cb50a32 is required to build 2020.05.

**Comment by alan-baker** [comment]
Does it build with the SPIRV-Headers mentioned in the DEPS file?

**Comment by cbxbiker61** [comment]
Ah, yes.  I just added to ./utils/git-sync-deps to my build script rather than pulling directly from git.  That fixed the problem.  Thanks.
