### ISSUE TITLE
Unused function not being optimized out by spirv-opt

### ISSUE THREAD

**Issue by sugoi1** [KhronosGroup/SPIRV-Tools#4003]
The behavior we're seeing is that when the only call site of a function gets removed, the function itself doesn't necessarily get removed from the SPIR-V code, which can cause some unexpected opcodes to stay in the final optimized SPIR-V code.

Here's an example:
[unoptimized_spirv_with_used_function.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/5461206/unoptimized_spirv_with_used_function.txt)
[optimized_spirv_with_unused_function.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/5461229/optimized_spirv_with_unused_function.txt)

In this example, the function at %35 goes from used to unused, but isn't removed.

**Comment by srisser** [comment]
This is present in 82b378d67 and produces the same optimized code that the original comment mentions.

**Comment by alan-baker** [comment]
Are you running `-O`? If not, what optimization formula are you using?
