### ISSUE TITLE
When doing -legalize-hlsl, debug information is removed.

### ISSUE THREAD

**Issue by cmaughan** [KhronosGroup/SPIRV-Tools#4012]
I'm running -legalize-hlsl on a spirv file, with that as the only argument.  The output has had 'OpLine' removed, which makes it hard to link back to source in my tool.
Is this a bug?  If not, is there a way to get legalized hlsl and maintain these lines?

**Comment by s-perron** [comment]
In my tests, I see the OpLine instructions are not removed unless the `--strip-debug` option is also added. Reopen with more details if I am wrong.
