### ISSUE TITLE
spirv-val: shared/workgroup memory not allowed in tessellation control stage

### ISSUE THREAD

**Issue by LukasBanana** [KhronosGroup/SPIRV-Tools#4017]
According to the SPIR-V specification, workgroup memory (`shared` in GLSL) is only allowed in the compute shader stage (as well as the new mesh and task shader stages). However, DXC generates this to communicate patch constant data in a tessellation control shader as intermediate storage. The SPIRV-Tools validation does not catch this error and causes a triangle soup on NVIDIA hardware and a crash in the Vulkan implementation on AMD hardware. I will also file a bug report for this issue in the DXC repository.

**Comment by sfricke-samsung** [comment]
The Vulkan spec has `VUID-StandaloneSpirv-None-04639` and I think https://github.com/KhronosGroup/SPIRV-Tools/pull/4106 covers this
