### ISSUE TITLE
spirv-val: OpCapability Int64ImageEXT invalid capability

### ISSUE THREAD

**Issue by onatto** [KhronosGroup/SPIRV-Tools#4020]
Trying to generate `OpCapability Int64ImageEXT` results in `Invalid capability operand: 5016` error with both `spirv-dis` and `spirv-val` nightly builds.
`SPIRV-Tools v2020.6 v2020.5-100-ga61d07a7`

**Comment by alan-baker** [comment]
Did you update SPIRV-Headers?

**Comment by onatto** [comment]
Thanks, I hadn't updated the headers, that fixed building from source.
Sorry, should've checked with `which` first, it was just the binaries shipping in Vulkan SDK taking precedence over nightly builds exported to `/usr/bin`. :facepalm:
