### ISSUE TITLE
Extend assembly syntax to allow for ID preservation through disassembly and re-assembly

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#404]
The assembler treats ID as symbolic and assigns ID numbers sequentially-by-mention starting with 1.  So passing a binary module through the disassembler, then assembler will automatically renumber IDs.  This is might be considered bad when you use spirv-dis and spirv-as as filters for editing .spv files, since the _binary_ file contents are not preserved by a no-op edit.

We could extend the assembly language syntax so that you explicitly tag numbers to ID definitions, e.g.

```
%int:12 = OpTypeInt 32 1    ; assembler assigns ID value 12 to %int
%v2int:14 = OpTypeVector %int 2  ; assign ID value 14 to %v2int
```

Disassembling with these annotations would be opt-in.

For simplicity of bookkeeping in the assembler, if the feature is on then it would be required for all IDs.  (If we didn't force this, then an auto-assigned value might be later occupied by a forcibly-assigned value.  And I don't want to make ID assignment two-pass.)

I don't think this is high priority.

**Comment by dneto0** [comment]
Tweak:  Sometimes IDs are mentioned before they are defined (assigned to).  E.g. Decorations are forward references.  So change the rule so that the first mention of an ID has the colon-number syntax.
And maybe allow later mentions to have the colon-number syntax, provided that the numbers are always consistent.

**Comment by steve-lunarg** [comment]
(Quick comment from the sidelines - sorry if I'm missing something obvious).

As long as it's generally opt-in (which makes sense), could the opt-in happen on the assemble side, and not need a syntax extension?  E.g, a --raw-id option for spirv-as could use the incoming IDs, and error out on a symbolic such as %int to avoid the two pass problem.  Use --raw-id in both steps, and a dis->as cycle would preserve the IDs for the round trip.  It basically says, "trust me, the IDs are cool."  

Well, actually you'd have a choice: if you care about ID preservation, use --raw-id on both sides.  If prefer ease of reading/editing and are OK with automatic ID assignment, omit it on both sides.  The only thing you can't do is have your cake and eat it too.

**Comment by dneto0** [comment]
That's clever.   But would you actually like editing a file with only raw IDs?  It was a step up to add some amount of friendly name generation.

Then again, maybe raw ids for the assembler is just generally useful, e.g. for generating test cases for a remapper?

A small friction: the current assembler's API interface doesn't accommodate options.  We can work around that in an extensible way (e.g. like Shaderc's use of an opaque options object https://github.com/google/shaderc/blob/master/libshaderc/include/shaderc/shaderc.h#L118)

**Comment by steve-lunarg** [comment]
About editing (or generally any round trip through text): I was thinking that it wouldn't be too burdensome to require a choice between either the friendly path (symbolic IDs, and you don't get to care about their numeric values), or the preservation path (numeric IDs, and you don't get to have symbolic names).  It's not as flexible as allowing symbolic IDs that also preserve the numeric values, but... oh well :).  It doesn't preclude having that ability in the future.

**Comment by s-perron** [comment]
I don't think we will ever get to this. I'm trying to get the number of open issue down, so I will close it. Using the `preserve-numeric-ids` is good for me. If I only ever look at the friendly names, I do not mind if the hidden id for say `%int` changes.
