### ISSUE TITLE
RobustBufferAccess Pass generating invalid clamping

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/SPIRV-Tools#4056]
It looks like the RBA is trying to assign the result of a SClamp to an unsigned int.
Specifically:
         %28 = OpLoad %uint %VertexIndex
         %30 = OpAccessChain %_ptr_Function_v3float %26 %28

gets turned into this:
         %28 = OpLoad %uint %VertexIndex
         %40 = OpExtInst %uint %39 SClamp %28 %int_0 %int_5
         %30 = OpAccessChain %_ptr_Function_v3float %26 %40

Full shaders:
[before_rba.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/5661650/before_rba.txt)
[after_rba.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/5661652/after_rba.txt)

**Comment by dneto0** [comment]
This is valid. In SPIR-V the signedness of an integer value doesn't have any effect except at shader interface boundaries. 
For cases like here, only the bit pattern is significant, and the consuming instruction interprets the value as either signed or unsigned.
