### ISSUE TITLE
spirv-opt: Please add cmd line flag to retain uniform names

### ISSUE THREAD

**Issue by Boscop** [KhronosGroup/SPIRV-Tools#4081]
Please add a cmd line flag to `spirv-opt` to retain uniform names when optimizing.

Motivation:
I'm compiling Rust shaders to SPIR-V and loading them with OpenGL using a [library](https://github.com/glium/glium) that only allows setting uniform values by name (not by `location`, and there is no way to even specify an explicit `location` for uniforms in a Rust shader).
When I don't use `spirv-opt`, the shaders work fine.
But `spirv-opt` strips the uniform names, so then I cannot set the uniform values by name, which means I currently cannot make use of `spirv-opt` (since the resulting spv is not useful without being able to set uniform values).
But I'd really like to use `spirv-opt`, because the Rust to SPIR-V compiler does almost no optimizations.
Can you please add such a cmd line flag to `spirv-opt` to keep the uniform names in the SPIR-V binary?

**Comment by s-perron** [comment]
If you still care about this, please reopen with more information. I'm not sure what you mean by "uniform name". Spirv-opt should not be removing the OpName for variables in the uniform storage class (or any other) unless you run the strip debug info pass. If that is what you mean, then do not run the strip-debug pass.

If you mean something else, I will need clarification.
