### ISSUE TITLE
spirv-link strips GL_EXT_scalar_block_layout info

### ISSUE THREAD

**Issue by Rainer-1** [KhronosGroup/SPIRV-Tools#4082]
Compiling a shader with a uniform with scalar layout, and then using spirv-opt on that shader works as planned. Using spirv-link to link that optimized module with other optimized modules also works. However, using spirv-opt again on the resulting combined module results in an error that seems to suggest that the GL_EXT_scalar_block_layout info was lost in spirv-link.

In the shader, the uniform block was declared as follows:
```
layout(binding = 0, scalar) uniform addrsUniform {
    uint64_t addrs[];
};
```

This is the error:
`    error: line 186: Structure id 21 decorated as Block for variable in uniform storage class must follow relaxed uniform buffer layout rules: member 0 contains an array with stride 8 not satisfying alignment to 16 %addrsUniform = OpTypeStruct %_arr_ulong_uint_100`

**Comment by alan-baker** [comment]
Scalar block layout information is not encoded in the module. To correctly validate it, the `--scalar-block-layout` option must be used. This is likely a case of missing that option in one of the runs or not being able to specify it to the linker.

**Comment by Rainer-1** [comment]
Solved: The problem in compiling to spirv was not passing --scalar-block-layout to sprirv-opt. The warning in the runtime validation layers went away after setting VkPhysicalDeviceVulkan12Features::uniformBufferStandardLayout (based on VK_KHR_uniform_buffer_standard_layout) to VK_TRUE.
