### ISSUE TITLE
spirv-link fails on ray tracing modules

### ISSUE THREAD

**Issue by seanbaxter** [KhronosGroup/SPIRV-Tools#4083]
$ spirv-link raytrace.rchit.spv raytrace.rgen.spv -o linked.spv
error: 140: Invalid opcode: 330
error: 0: Failed to build a module out of 0.

[shaders.tar.gz](https://github.com/KhronosGroup/SPIRV-Tools/files/5757750/shaders.tar.gz)

These are the rchit and rgen shaders from this project:
https://github.com/nvpro-samples/vk_raytracing_tutorial/tree/master/ray_tracing__simple/shaders

When I compile these myself with glslc with no command line options, the resulting modules do link, but they don't work in execution. When I compile with
```
glslc --target-spv=spv1.5 --target-env=vulkan1.2
``` 
the modules fail to link.

**Comment by seanbaxter** [comment]
Oh geez. opcode 330 is OpModuleProcessed. 

So i grep the inputs:
OpModuleProcessed "Linked by SPIR-V Tools Linker"

spirv-link inserts an opcode that it itself is unable to consume.

**Comment by seanbaxter** [comment]
spirv-link also doesn't recognize OpCopyLogical.

**Comment by pierremoreau** [comment]
If one does not specify a target environment, spirv-link defaults to the `SPV_ENV_UNIVERSAL_1.0` one, which does not support `OpModuleProcessed` (added in SPIR-V 1.1) nor `OpCopyLogical` (added in SPIR-V 1.4).

Note that the `OpModuleProcessed` instruction it is complaining about is coming from your input shaders
```
               OpModuleProcessed "client vulkan100"
               OpModuleProcessed "target-env spirv1.3"
               OpModuleProcessed "target-env vulkan1.1"
               OpModuleProcessed "entry-point main"
```
and occurs when the linker first tries building the modules and the internal data structures from the specified binaries, before doing any modifications to them.

Try running `spirv-link --target-env spv1.5 -o a.spv raytrace.rchit.spv raytrace.rgen.spv`, similar to how you specified a target-spv for glslc; without the target-spv and/or target-env when calling glslc, I assume that glslc defaults to generating SPIR-V 1.0-compatible modules.

**Comment by seanbaxter** [comment]
Usability bug.

This is what I was typing:
```
$ spirv-link --target-env=vulkan1.2 -o linked.spv raytrace.rchit.spv raytrace.rgen.spv
error: 139: Invalid opcode: 330
error: 0: Failed to build a module out of 0.
```
Apparently the = after --target-env discards the argument and reverts to 1.0. It'll even take non-arguments like --blahlab=cow and not report. But this is the syntax I use with glslc, which actually specifies the = in its --help:
```
--target-env=<environment>                    Set the target client environment, and the semantics
                    of warnings and errors.  An optional suffix can specify
                    the client version.  Values are:
                        vulkan1.0       # The default
                        vulkan1.1
                        vulkan1.2
                        vulkan          # Same as vulkan1.0
                        opengl4.5
                        opengl          # Same as opengl4.5
```
I mean, it's good to know now, but it's not something I would have figured out had I not pasted what you gave me into my terminal.

**Comment by pierremoreau** [comment]
There is some mismatch between the different tools in SPIRV-Tools: spirv-as uses the notation without the equal-sign in-between (but does complain about the unknown option), while spirv-opt uses an equal-sign. And both default to SPIR-V 1.5 when nothing is specified.

I will open a merge request with some improvements for the linker, like complaining about unrecognised options and be clearer about the syntax in the usage message.

Thank you for the report.

**Comment by pierremoreau** [comment]
I opened #4084 with a couple of modifications for spirv-link. I would be interested to hear if you have any feedback about the new output of `spirv-link --help`.
