### ISSUE TITLE
validate VUID-StandaloneSpirv-OpImageQuerySizeLod-04659 

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#4102]
VUID-StandaloneSpirv-OpImageQuerySizeLod-04659
OpImageQuerySizeLod, and OpImageQueryLevels must only consume an “Image” operand whose type has its “Sampled” operand set to 1

It must be guarded by being in the Vulkan environment.

cc: @sfricke-samsung in case you're trying to do this too somewhere.

**Comment by sfricke-samsung** [comment]
Sounds good, also heads up that we just this Monday approved
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4316

so you will also want to add `OpImageQueryLod` to this

**Comment by dneto0** [comment]
Well I'm glad I tagged you!  :-)

Will add ImageQueryLod, thanks.
