### ISSUE TITLE
Validation exception for Phi-function in a loop

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-Tools#415]
spirv-val tool reports an error:

> error: 48: The following forward referenced IDs have not be defined:
13[result.0]

 on the following line:
`%result_0 = OpPhi %uint %12 %entry %result_0 %if_then %inc %if_end`

But I think the following exception from the [specification (2.16.1 SSA)](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_universal_validation_rules) is applicable in this case

> Uses in a phi-function in a loop may consume definitions in the loop that don’t dominate the use

...and therefore validator should not report an error. Please fix it.
The problem can be reproduced with attached [files](https://github.com/KhronosGroup/SPIRV-Tools/files/471981/tmp.zip)

**Comment by dneto0** [comment]
Confirmed.  In the disassembly below, %result_0 is defined in block %while_cond, which dominates block %if_end.

![tmp](https://cloud.githubusercontent.com/assets/13054574/18514616/47548cba-7a60-11e6-86e7-876a07a32528.png)


```
      %entry = OpLabel
               OpBranch %while_cond

 %while_cond = OpLabel
   %result_0 = OpPhi %uint %12 %entry %result_0 %if_then %inc %if_end
 %num_addr_0 = OpPhi %uint %num %entry %dec %if_then %dec %if_end
     %tobool = OpINotEqual %bool %num_addr_0 %18
               OpBranchConditional %tobool %while_body %while_end

 %while_body = OpLabel
        %dec = OpIAdd %uint %num_addr_0 %21
    %tobool1 = OpINotEqual %bool %dec %18
               OpBranchConditional %tobool1 %if_then %if_end

    %if_then = OpLabel
               OpBranch %while_cond

     %if_end = OpLabel
        %inc = OpIAdd %uint %result_0 %12
               OpBranch %while_cond

  %while_end = OpLabel
               OpReturnValue %result_0
               OpFunctionEnd

```

**Comment by dneto0** [comment]
I reduced it further to this case.  The reported error is: "error: 13: The following forward referenced IDs have not be defined:  7"

```
               OpCapability Addresses
               OpCapability Kernel
               OpMemoryModel Physical32 OpenCL
       %uint = OpTypeInt 32 0
          %2 = OpConstantNull %uint
          %3 = OpTypeFunction %uint
          %4 = OpFunction %uint None %3
          %5 = OpLabel
               OpBranch %6
          %6 = OpLabel
          %7 = OpPhi %uint %2 %5 %7 %6
               OpBranch %6
               OpFunctionEnd
```

**Comment by umar456** [comment]
I think I know what the problem is. I will have a PR out shortly

**Comment by dneto0** [comment]
@umar456 I already have a fix.  :-)
