### ISSUE TITLE
spirv-fuzz: Vulkan environment is not supported

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#4155]
Tint fuzzer uses Vulkan SPIR-V environment. However, some transformations don't support it. Here is a list of errors from the tint fuzzer:

>CopyMemory with two memory access operands requires SPIR-V 1.4 or later
>  OpCopyMemory %985 %param_18 Volatile|Nontemporal Volatile
>
>OpEntryPoint interfaces must be OpVariables with Storage Class of Input(1) or Output(3). Found Storage Class 6 for Entry Point id 4.
>  %1468 = OpVariable %_ptr_Private_int Private %int_0
>
>Expected scalar or vector type as Result Type: Select
>  %805 = OpSelect %BST %248 %1615 %1617
>
>Invalid loop control operand: 256 has invalid mask component 256

**Comment by Vasniktel** [comment]
@afd for info.

**Comment by afd** [comment]
@Vasniktel Thanks for this. Is the issue that the tint fuzzer uses:

spv_target_env::SPV_ENV_VULKAN_1_1

as its target environment?

**Comment by Vasniktel** [comment]
Yes.
