### ISSUE TITLE
utils/roll_deps.sh says to run: `git cl upload --send-mail`

### ISSUE THREAD

**Issue by timvpGoogle** [KhronosGroup/SPIRV-Tools#4186]
The script to update DEPS `git cl upload --send-mail` finishes with the following:

```
Run:
  git cl upload --send-mail
Successfully rebased and updated refs/heads/rollDeps.
```

However, running the command `git cl upload --send-mail` always fails:
```
$ git cl upload --send-mail
Credentials for the following hosts are required:
  github-review.com
  github.com
These are read from /home/<username>/.gitcookies (or legacy /home/<username>/.netrc)
You can (re)generate your credentials by visiting https://github-review.com/new-password
```

Attempting to go to https://github-review.com/new-password gives a 404, since that site doesn't exist.

Either the script should be updated to not tell users to run `git cl upload --send-mail` or support for `git cl upload` should be added.

**Comment by zoddicus** [comment]
Rolls for DEPS should be handled like a normal PR on GitHub for uploading.

'git cl upload' is a tool from Chromium's depot_tools and is used for simplifying uploading patches to repos that use Gerrit for code review.
The reference to 'git cl upload --send-mail' is actually coming from the underlying tool, roll-dep, that is being invoked, not the script itself.
We are kinda using the roll-dep tool in an off label manner, so I think it would be unlikely that upstream would accept a patch to remove this message.

I should probably add a message or documentation about this to the roll_deps.sh script.
