### ISSUE TITLE
spirv-opt: Crash with debugPrintfEXT()

### ISSUE THREAD

**Issue by FrancoisBeaune** [KhronosGroup/SPIRV-Tools#4219]
Hi,

This seems to crash `spirv-opt.exe` (64-bit version) from Vulkan 1.2.170.0:

`test.rchit`:
```
#version 460
#extension GL_EXT_debug_printf : require

layout(set = 0, binding = 0) uniform sampler3D samplers[];

void foo()
{
    const vec4 c = texture(samplers[0], vec3(0.0f));
    debugPrintfEXT("%f", c.r);
}

void main()
{
    foo();
}
```

Build instructions:

1. Compile:
   
   ```
   glslangValidator.exe --target-env vulkan1.2 test.rchit -o test.spv
   ```

2. Optimize:
   
   ```
   spirv-opt -O test.spv -o test-opt.spv
   echo %errorlevel%
   ```
   
   The last `echo %errorlevel%` statement outputs -1073741819 (0xC0000005).

**Comment by greg-lunarg** [comment]
I will investigate.

**Comment by FrancoisBeaune** [comment]
Any update?

**Comment by greg-lunarg** [comment]
Sorry. Fell off my stack. Will look.

**Comment by FrancoisBeaune** [comment]
Thanks Greg!

In fact, another one that's even more problematic for us, and a constant pain for the whole team, is this one: https://github.com/KhronosGroup/SPIRV-Tools/issues/4241

**Comment by greg-lunarg** [comment]
More specifically, crashing in EliminateFunction().

**Comment by greg-lunarg** [comment]
Suspecting an issue with the algorithms iterating over the function instructions interacting with the deletion of those instructions. Should have the problem identified momentarily.

**Comment by greg-lunarg** [comment]
The first implementation of WhileEachInst() for BasicBlock is stashing away the next instruction, which becomes a bad pointer when that instruction is a nonsemantic using the current instruction and is deleted along with the current instruction.

**Comment by greg-lunarg** [comment]
It seems these iteration methods can tolerate killing of the current instruction, but not the instruction following the current instruction. My approach will be to defer killing of any non-semantic instructions until after the analysis is complete.
