### ISSUE TITLE
vscode extension: formatter adds a trailing new line on every invocation

### ISSUE THREAD

**Issue by dylanede** [KhronosGroup/SPIRV-Tools#4222]
I have VSCode set up to format a file upon save, so this means that every time I save an edited *.spvasm assembly file a new line is added to the end of the file, even if there are several there already. This is on Windows, so I'm using `\r\n` line endings, in case that's relevant.

**Comment by ben-clayton** [comment]
I believe this was fixed with https://github.com/KhronosGroup/SPIRV-Tools/pull/4246
