### ISSUE TITLE
spirv-fuzz: TranformationPermuteFunctionVariables crashes when the function has no variables

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#4257]
`FuzzerContext::RandomIndex` requires that the vector argument has at least one element.

As a solution, we can check for whether the function has more than 2 variables and apply the transformation only if it does. Additionally, it might be better to limit the number of iterations in the following loop so that we don't end up swapping the same variables (e.g. consider the case when the function has only 2 variables - we'd want to apply at most 1 transformation).

https://github.com/KhronosGroup/SPIRV-Tools/blob/f82f5af5e212373230b8df4dedbd8e1c950e1cc1/source/fuzz/fuzzer_pass_permute_function_variables.cpp#L53-L66

@afd, @Mostafa-ashraf19 ping.

**Comment by Mostafa-ashraf19** [comment]
Yes @Vasniktel, you are right. I will refactor it according to your suggestion, What do you think @afd?

**Comment by Mostafa-ashraf19** [comment]
Sorry for the late reply @Vasniktel. Ok, I will do that.

**Comment by Mostafa-ashraf19** [comment]
@Vasniktel, Regarding the limit number of iterations, are you want to follow this [old](https://github.com/KhronosGroup/SPIRV-Tools/pull/4213#discussion_r619609065) approach? or you think of another one? 

```cpp
    uint32_t iterations_limit = 0;
    do {
      uint32_t instruction_1_index = GetFuzzerContext()->RandomIndex(variables);
      uint32_t instruction_2_index = GetFuzzerContext()->RandomIndex(variables);

      if (instruction_1_index != instruction_2_index) {
        ApplyTransformation(TransformationSwapFunctionVariables(
            variables[instruction_1_index]->result_id(),
            variables[instruction_2_index]->result_id()));
      }

    } while (GetFuzzerContext()->ChoosePercentage(
                 GetFuzzerContext()
                     ->GetChanceOfSwappingAnotherPairOfFunctionVariables()) &&
             iterations_limit++ <
                 25); 
```
I think we can use something like a flag to make a limit for iterations. (e.g. break of make `iterations_limit = 1` in case of function has only 2 variables) also, consider other cases. 

@afd  ping.

**Comment by Vasniktel** [comment]
I think it might be better to have a limit that depends on the number of variables in the function. For example, something like
```cpp
for (size_t i = 0; i < variables.size() / 2 + 1; ++i) {
  // <the current swapping code goes here>
  if (!GetFuzzerContext()->ChoosePercentage(
                 GetFuzzerContext()
                     ->GetChanceOfSwappingAnotherPairOfFunctionVariables())) {
    break;
  }
}
```

@afd what do you think?

**Comment by Mostafa-ashraf19** [comment]
> I think it might be better to have a limit that depends on the number of variables in the function. For example, something like
> 
> ```c++
> for (size_t i = 0; i < variables.size() / 2 + 1; ++i) {
>   // <the current swapping code goes here>
>   if (!GetFuzzerContext()->ChoosePercentage(
>                  GetFuzzerContext()
>                      ->GetChanceOfSwappingAnotherPairOfFunctionVariables())) {
>     break;
>   }
> }
> ```
> 
> @afd what do you think?

what is the objective of sample below after making a limited fixed size!
```cpp
      if (!GetFuzzerContext()->ChoosePercentage(
                     GetFuzzerContext()
                         ->GetChanceOfSwappingAnotherPairOfFunctionVariables())) {
        break;
      }
```
I think we can get rid of this. or you want to keep it as a guard! what do you think @afd, @Vasniktel?
