### ISSUE TITLE
spirv-fuzz: Update analyses in TransformationSwapFunctionVariables

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#4259]
When we swap 2 variables, we invalidate DefUseManager. The latter contains a map from a result id to an `opt::Instruction` object. We should update it in the transformation accordingly.

@Mostafa-ashraf19, you can use `opt::DefUseManager::AnalyzeInstDefUse` to do that.
@afd for info.

**Comment by Vasniktel** [comment]
@afd I wonder if `TransformationSwapFunctions` suffers from a similar bug.

**Comment by sliu-UIUC** [comment]
> @sliu-UIUC Can you look at whether TransformationSwapFunctions also suffers from this issue?
> 
> @Mostafa-ashraf19 and @sliu-UIUC - the ideal thing to do here is to augment your test that applies a transformation to do something like this:
> 
> * Get the DefUse manager from ir_context before applying the transformation
> * Apply the transformation
> * Assert something about the def use manager after the transformation
> 
> For example, if variables with ids 10 and 20 are being swapped (@Mostafa-ashraf19), or functions with ids 10 and 20 (@sliu-UIUC), we'd do something like:
> 
> ```
> auto def_use_manager = ir_context->get_def_use_mgr();
> auto first_instruction = def_use_manager->GetDef(10);
> auto second_instruction = def_use_manager->GetDef(20);
> // Apply the transformation
> ASSERT_EQ(first_instruction, def_use_manager->GetDef(10));
> ASSERT_EQ(second_instruction, def_use_manager->GetDef(20));
> ```
> 
> You might (should) find that these tests fail at present. The Apply method of each transformation should be updated to fix that.

I will look into it. I expect there is no issue from transformation_swap_two_functions because I initially have a script with only 1 function in it and it didn't crash, but it would be nice to check on it just to be sure.

**Comment by Mostafa-ashraf19** [comment]
Sorry for the late reply @Vasniktel. Ok, I will do that.

> When we swap 2 variables, we invalidate DefUseManager. The latter contains a map from a result id to an `opt::Instruction` object. We should update it in the transformation accordingly.
> 
> @Mostafa-ashraf19, you can use `opt::DefUseManager::AnalyzeInstDefUse` to do that.
> @afd for info.

sorry for the late. I will do that.

**Comment by Mostafa-ashraf19** [comment]
> Interesting!
> 
> @Mostafa-ashraf19 are you OK to attend to this? If you're not familiar with def-use analysis I suggest you do some brief reading online. The required code change should be simple.

sure @afd, sorry for the late. I will do that.

**Comment by Vasniktel** [comment]
@Mostafa-ashraf19 @sliu-UIUC One thing to note, though, is that storing `DefUseManager` in a local variable before applying the transformation is probably not a good idea since some transformations invalidate that analysis completely. And when that happens, the pointer to the `DefUseManager` becomes deallocated. Thus, you'll end up with a dangling pointer and a segmentation fault.

**Comment by afd** [comment]
@Vasniktel I agree in general. But the transformations in question don’t invalidate it, so in this case it provides a good way to check that they update the analysis appropriately. Do you agree?

**Comment by Vasniktel** [comment]
Yes. Since we don't invalidate the analysis here, it's indeed ok to use the approach with the local variable.

**Comment by sliu-UIUC** [comment]
@afd @Vasniktel Hi guys. I think that I don't have the bug Vasyl mentioned in issue #4257. In the fuzzer pass for applying the transformation I didn't call `randomIndex` for my functions. Instead, I added function_ids available in the module into a function iterator and perform swapping with the given functions. If there is no function there will be no transformation performed, and if there is only 1 transformation,  the 2d forloop: 
```C++
  for (size_t i = 0; i < function_ids.size(); ++i) {
    for (size_t j = i + 1; j < function_ids.size(); ++j) {
```
will make sure that there will be no transformation performed also. Even though there is, the assertion will fail as the two parameters would have the same function id. I have tested it using an assembly script with only one function `main`, and it builds and passed all test. So I think `transformation_swap_function` doesn't suffer from the bug in #4257. 

As for issue #4259, I am not sure whether swapping functions has anything to do with `DefUseManager`, as it seems to deal with issues in the instruction space. Is there a function level equivalent class that I might use to perform a similar def-use analysis?

**Comment by afd** [comment]
@Vasniktel This PR adds the tests I was assuming would fail given your concerns:

https://github.com/KhronosGroup/SPIRV-Tools/pull/4266

However, they pass locally for me.

Did you have something similar in mind or something else?

**Comment by Vasniktel** [comment]
@sliu-UIUC What I was concerned with regarding swapping 2 functions is the following. In `TransformationSwapFunctionVariables` we swap the contents of 2 `opt::Instruction` pointers. The problem with this approach is that if some analysis references the pointer, it will now continue to reference the same address in memory but containing a totally different instruction. Thus, we need to invalidate analyses to make sure that our changes to the contents of the pointers were noticed.

With `TransformationSwapFunctions` situation is a bit different, though. We don't swap contents of 2 `opt::Function` pointers. Instead, we swap 2 elements of the `std::vector<std::unique_ptr<opt::Function>>` (`func1_it.Get()` returns an iterator to such a vector). With this approach, the contents of the `opt::Function` pointers remain unchanged inside `unique_ptr`'s, only their positions in the vector change. Thus, if some analysis references the` opt::Function` pointer or anything it contains, it will still continue to reference the same thing.

Additionally, there is `std::vector<std::unique_ptr<opt::Instruction>>` in the `opt::BasicBlock`. Thus, we can use the same approach of swapping variables in `TransformationSwapFunctionVariables` without the need to invalidate analyses (if I recall correctly, someone proposed to use it in the beginning and then we switched to the current approach).

@afd @sliu-UIUC @Mostafa-ashraf19 what do you think about all this?

**Comment by afd** [comment]
Thanks @Vasniktel !  @sliu-UIUC there is indeed no problem with your transformation. I have updated #4266 with a test that demonstrates there is no problem: no harm for this extra thorough test to be merged.

**Comment by sliu-UIUC** [comment]
> @sliu-UIUC What I was concerned with regarding swapping 2 functions is the following. In `TransformationSwapFunctionVariables` we swap the contents of 2 `opt::Instruction` pointers. The problem with this approach is that if some analysis references the pointer, it will now continue to reference the same address in memory but containing a totally different instruction. Thus, we need to invalidate analyses to make sure that our changes to the contents of the pointers were noticed.
> 
> With `TransformationSwapFunctions` situation is a bit different, though. We don't swap contents of 2 `opt::Function` pointers. Instead, we swap 2 elements of the `std::vector<std::unique_ptr<opt::Function>>` (`func1_it.Get()` returns an iterator to such a vector). With this approach, the contents of the `opt::Function` pointers remain unchanged inside `unique_ptr`'s, only their positions in the vector change. Thus, if some analysis references the` opt::Function` pointer or anything it contains, it will still continue to reference the same thing.
> 
> Unfortunately, there is no `std::vector<std::unique_ptr<opt::Instruction>>` so we are forced to swap contents of the pointers instead and invalidate analyses.

That makes sense. I can see swapping pointers can be problematic indeed.
