### ISSUE TITLE
spirv-dis: Not following spec for OpSpecConstantOp Operands

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#4272]
The latest SPIR-V spec (Version 1.5, Revision 5, Unified) says the following for OpSpecConstantOp concerning its Operands:

```
Operands are the operands required by opcode, and satisfy the semantics of opcode. In addition, all Operands must
be either:
- the <id>s of other constant instructions, or
- OpUndef, when allowed by opcode, or
- for the AccessChain named opcodes, their Base is allowed to be a global (module scope) OpVariable instruction.
```

The key point to note here is that, according to this text, all _operands_ should be _Ids_. However, if the _opcode_ of OpSpecConstantOp is CompositeExtract, it appears that spirv-dis is treating the second _operand_ after the _opcode_ as a _literal_ i.e. in the disassembly, the operand is not preceded with a `%`. In other words, the disassembler seems to be interpreting the `operands` as it would for an OpCompositeExtract instruction.

This issue is not just confined to spirv-dis and could have broader implications. glslang is also generating code for OpSpecConstantOp CompositExtract in this same way and I highly suspect the spirv-as does as well. I am trying to figure out why this is happening when the spec seems to quite clearly contradict this practice.

Which requires correction: the spec or the tools?

To see this, compiler the following with glslang -V:

```
#version 450

layout(local_size_x_id = 18, local_size_z_id = 19) in;
layout(local_size_x = 32, local_size_y = 32) in;

buffer bn {
    uint a;
} bi;

void main()
{
    bi.a = gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z;
}
```

Disassembling the SPIR-V, note the operands for the OpSpecConstantOp Composite Extracts:

```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main" %bi
               OpExecutionMode %main LocalSize 32 32 1
               OpSource GLSL 450
               OpName %main "main"
               OpName %bn "bn"
               OpMemberName %bn 0 "a"
               OpName %bi "bi"
               OpMemberDecorate %bn 0 Offset 0
               OpDecorate %bn Block
               OpDecorate %bi DescriptorSet 0
               OpDecorate %bi Binding 0
               OpDecorate %12 SpecId 18
               OpDecorate %14 SpecId 19
               OpDecorate %gl_WorkGroupSize BuiltIn WorkgroupSize
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
         %bn = OpTypeStruct %uint
%_ptr_StorageBuffer_bn = OpTypePointer StorageBuffer %bn
         %bi = OpVariable %_ptr_StorageBuffer_bn StorageBuffer
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
         %12 = OpSpecConstant %uint 32
    %uint_32 = OpConstant %uint 32
         %14 = OpSpecConstant %uint 1
     %v3uint = OpTypeVector %uint 3
%gl_WorkGroupSize = OpSpecConstantComposite %v3uint %12 %uint_32 %14
     %uint_0 = OpConstant %uint 0
         %18 = OpSpecConstantOp %uint CompositeExtract %gl_WorkGroupSize 0
     %uint_1 = OpConstant %uint 1
         %20 = OpSpecConstantOp %uint CompositeExtract %gl_WorkGroupSize 1
         %21 = OpSpecConstantOp %uint IMul %18 %20
     %uint_2 = OpConstant %uint 2
         %23 = OpSpecConstantOp %uint CompositeExtract %gl_WorkGroupSize 2
         %24 = OpSpecConstantOp %uint IMul %21 %23
%_ptr_StorageBuffer_uint = OpTypePointer StorageBuffer %uint
       %main = OpFunction %void None %3
          %5 = OpLabel
         %26 = OpAccessChain %_ptr_StorageBuffer_uint %bi %int_0
               OpStore %26 %24
               OpReturn
               OpFunctionEnd
```

**Comment by greg-lunarg** [comment]
The following commit seems related to the behavior I am seeing in the tools:

https://github.com/KhronosGroup/SPIRV-Tools/commit/78c3b4377469e7120c942aca3cb7312d85bfac11

This behavior on its own seems fine, even desirable, but it does not match the SPIR-V spec. Wondering if the spec originally specified this behavior but got changed at the last minute for some reason, and the tools were never updated?

**Comment by alan-baker** [comment]
I think this is a spec bug. The first statement that the operands are the operands of the opcode makes sense. The other requirements I expect are meant to be extra limitations on ids. So I would expect something more along the lines of:
>Operands are the operands required by opcode, and satisfy the semantics of opcode. In addition, all Operands that are <id>s must be either:
- the <id>s of other constant instructions, or
- OpUndef, when allowed by opcode, or
- for the AccessChain named opcodes, their Base is allowed to be a global (module scope) OpVariable instruction.

**Comment by greg-lunarg** [comment]
Thanks for your thoughts @alan-baker. I wanted to get one other opinion before bringing this to the SPIR-V WG.

BTW, I think the idiosyncratic formatting of these comments might have bitten you. I think you wanted the above to read:

... In addition, all Operands that are _Ids_ must ...

I will create an issue for the WG.

In light of this, should I also create an issue asking for additional validation of OpSpecConstantOp? I created OpSpecConstantOp CompositeExtract where the base was a vec3, but the index was 15 (the Id of a Constant 0).

**Comment by alan-baker** [comment]
Yeah, I fixed the second formatting issue, but missed the first. I'll edit my comment to clarify this.

You can definitely file a validator bug for missing coverage. It will likely wait till we formally resolve the issue though.

**Comment by greg-lunarg** [comment]
An issue has been filed against the SPIR-V spec.
