### ISSUE TITLE
Incorrect execution when using debugPrintfEXT()

### ISSUE THREAD

**Issue by wlwooten** [KhronosGroup/SPIRV-Tools#4282]
The attached zip file contains two large, nearly identical shaders in SPIR-V form that differ very slightly.

The first shader is written as:
```
...
if (!(emittingTrianglePdf > 0.0f)) { debugPrintfEXT("pdf: %f", emittingTrianglePdf); }
...
```

And the second shader has this additional conditional:
``` 
...
if (!(emittingTrianglePdf > 0.0f)) { debugPrintfEXT("pdf: %f", emittingTrianglePdf); }
if (!(emittingTriangleArea > 0.0f)) { debugPrintfEXT("Triangle area is invalid."); }
...
```

Interestingly enough, the first shader does not operate correctly. It will print values for emittingTrianglePdf that are less than zero, even when they are not.

The second shader does operate correctly on the exact same input. Simply the addition of the 2nd conditional and debugPrintfEXT() causes the shader to not print values for emittingTrianglePdf that are less than zero. The final image output between the two shaders is the same. NOTE: If the emittingTrianglePdf value had actually been negative; the final image output would have differed significantly.

So it seems debugPrintfEXT() is broken in the presence of conditionals and adding more or fewer debugPrintfEXT() conditionals changes the broken behavior. NOTE: Another clue is that I can place the 2nd conditional pretty much anywhere within the function that has the first conditional and it will cause it to behave as expected.

I did examine the disassembled SPIR-V and did not notice anything explicitly wrong; which makes me think the issue may lie further down the pipeline when the shader is ingested and compiled for the card. However, I wanted to bring this as a heads up in case this might be related to other issues logged with debugPrintfEXT() like:

https://github.com/KhronosGroup/SPIRV-Tools/issues/4241
https://github.com/KhronosGroup/SPIRV-Tools/issues/4219

Thanks,
--Wayne

```$ C:\VulkanSDK\1.2.170.0\Bin\glslangValidator.exe -version
Glslang Version: 10:11.1.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 11.1.0
GLSL Version: 4.60 glslang Khronos. 11.1.0
SPIR-V Version 0x00010500, Revision 4
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 10
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100```

[shaders-dbg-broken.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/6510910/shaders-dbg-broken.zip)

**Comment by greg-lunarg** [comment]
Thanks for reporting this. I will take a look and see if there is a problem with the spirv-opt instrumentation for debugPrintf.

**Comment by greg-lunarg** [comment]
Please disregard request for glslang issue. It appears the SPIR-V is using scalar alignment. spirv-val.exe --target-env vulkan1.2 --scalar-block-layout test-debugPrintfEXT-broken.spv passes fine.

**Comment by wlwooten** [comment]
Thanks for the follow up!

**Comment by greg-lunarg** [comment]
I have run the debug instrumentation and the generated code looks correct to me. I suspect the problem is the driver.

You can actually run the instrumentation yourself. The (secret!) command is: spirv-opt.exe --skip-validation --inst-debug-printf -o test-debugPrintfEXT-broken.inst.spv test-debugPrintfEXT-broken.spv

If you disassemble (spirv-dis) both spv files, the diff is pretty clean.

The debug printf just turns into a a function call that does  an atomic add followed by a series of buffer writes. When inlined by the driver, there is a potential for dropped memory synchronization.

I am going to recommend this be closed, but if you find my analysis is incorrect, feel free to re-open.

@dnovillo Please close.

**Comment by greg-lunarg** [comment]
FWIW, --inst-debug-printf isn't EXACTLY what the layer does, but it is close. It is really just a debugging option for me so it uses placeholders for the descriptor set and binding for the output buffer it writes to. The layer passes the "real" set and binding when it runs.

**Comment by FrancoisBeaune** [comment]
Hi Greg,

Thanks for looking into this and for the detailed report.

We'll be forwarding this to our NVIDIA DevTechs for analysis on their side.
