### ISSUE TITLE
spirv-val doesn't work properly with OpTypeForwardPointer

### ISSUE THREAD

**Issue by echuraev** [KhronosGroup/SPIRV-Tools#429]
spirv-val get me the following error: error: 14: ID 6 has not been defined. But I think that spirv file is correct. I think that the problem is in spirv-val tool and how it works with OpTypeForwardPointer.
Files with spirv text representation, spirv binary and llvm ir are attached. I added extension "*.txt" for all of them because githug does not allow attach another types of files.
Step to reproduce: 
1. Run: spirv-val layout.spv.txt
2. Get error: error: 14: ID 6 has not been defined

llvm-ir: [layout.ll.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/486960/layout.ll.txt)
spirv text representation: [layout.spt.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/486961/layout.spt.txt)
spirv binary: [layout.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/486962/layout.spv.txt)

**Comment by umar456** [comment]
Confirmed. Fix should be out shortly.

**Comment by umar456** [comment]
Reduced the failing kernel to:

```LLVM
               OpCapability Kernel
               OpCapability Addresses
               OpMemoryModel Logical OpenCL
               OpName %intptrt "intptrt"
               OpTypeForwardPointer %intptrt UniformConstant
       %uint = OpTypeInt 32 0
    %intptrt = OpTypePointer UniformConstant %uint
```

Also exposes a bug for `OpTypeStruct`

```LLVM
               OpCapability Kernel
               OpCapability Addresses
               OpMemoryModel Logical OpenCL
               OpName %structptr "structptr"
               OpTypeForwardPointer %structptr UniformConstant
       %uint = OpTypeInt 32 0
    %structt = OpTypeStruct %uint %structptr
 %structptr  = OpTypePointer UniformConstant %structt
```
