### ISSUE TITLE
SPV_KHR_vulkan_memory_model and eliminate-dead-code-aggressive

### ISSUE THREAD

**Issue by khyperia** [KhronosGroup/SPIRV-Tools#4296]
Currently, `--eliminate-dead-code-aggressive` does not run if `OpExtension "SPV_KHR_vulkan_memory_model"` is present (required for `OpMemoryModel [...] Vulkan` before SPIR-V 1.5), as it is not [included in this list](https://github.com/KhronosGroup/SPIRV-Tools/blob/91931ffcd22ae774ed932c98c2d0319db9720d93/source/opt/aggressive_dead_code_elim_pass.cpp#L948-L1000). I wanted to ask if this was intentional or not before submitting a PR similar to https://github.com/KhronosGroup/SPIRV-Tools/pull/4047 or https://github.com/KhronosGroup/SPIRV-Tools/pull/4049 adding the string to the list - at the very least, searching for discussions around this topic on this github didn't turn up anything, so if it was intentional, it'll at least be documented here!

Thanks!

**Comment by alan-baker** [comment]
It's probably ok, but I haven't gone through the whole pass again to be sure.
