### ISSUE TITLE
spirv-fuzz: TransformationOutlineFunction doesn't capture all input ids

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#4300]
This can be reproduced on 91931ffcd22ae774ed932c98c2d0319db9720d93 with the following command:
> spirv-fuzz --replay=1.fuzzer.transformations.binary 1.fuzzer.original.spv --replay-validation -o invalid.spv

This will produce a message
> ERROR 0:0:244: ID 280[%280] defined in block 205[%205] does not dominate its use in block 423[%423]
  %423 = OpLabel

The reason is that one of the users of `%280` is outlined but the use itself (`%280`) is not. `DefUseMgr::NumUsers` will return 0 for `%280` when collecting input ids in the fuzzer pass. The reason is probably that some previous transformation doesn't invalidate all the analyses it needs. Hence, it might be related to https://github.com/KhronosGroup/SPIRV-Tools/issues/4267.

**Comment by afd** [comment]
@Vasniktel Did you intend to upload files to accompany this?

**Comment by Vasniktel** [comment]
True, thanks for spotting this. 
[shader.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/6552894/shader.zip)
