### ISSUE TITLE
spirv-opt: indexless OpAccessChain optimizing opportunity

### ISSUE THREAD

**Issue by jarisiru** [KhronosGroup/SPIRV-Tools#4307]
While investigating dEQP-VK.graphicsfuzz.spv-stable-orbit-Os-access-chain-mutate-pointer issue on swiftshader, the culprit appears to be an indexless OpAccessChain opcode which swiftshader doesn't currently know how to handle.

While that will be fixed on swiftshader side, a spirv-opt transform to turn, for example

```
        %330 = OpAccessChain %162 %163
               OpStore %330 %442
```
into:
```
               OpStore %163 %442
```

may help avoid this issue in other drivers (like older drivers that are not easy to change).

**Comment by s-perron** [comment]
This is not a bug, and will not make much difference in many real cases.  I've only seen OpAccessChain without an index generated by the fuzzer and not in any real code.  This will be low priority.  The maintainers will probably not fix this, but we will accept a change from the community if someone decides to do it.

The fix would be to add a new folding rule to source/opt/folding_rules.cpp.

**Comment by jarisiru** [comment]
I agree, it's not a bug - only a bug in swiftshader, which uses spirv-opt, and it feels like it would be elegant to fix it there. I'll see whether this gets resolved inside swiftshader or whether I'll make a pull request. In either case, I'll close this issue.
