### ISSUE TITLE
Spirv-fuzz: Support instances of OpAtomicLoad

### ISSUE THREAD

**Issue by Mostafa-ashraf19** [KhronosGroup/SPIRV-Tools#4324]
## Overview
Atomic operation it's important because it provides us waiting until other processes finish their job to avoid mutual exclusion among basic shared variables. 

I'm going to support instances `OpAtomicLoad`. According to [`OpAtomicLoad` specification](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpAtomicLoad), it's Atomically loaded through pointer using the given memory Semantics within scope under some conditions. A pointer is a pointer to memory to read under a mask and should be compatible with atomic operations.

## Implementation details

I will adapt the:

- Support opCode in `transformation_load` and its header.
 https://github.com/KhronosGroup/SPIRV-Tools/blob/4d22f58a812ea02e1ad53c9ccba12cb48f2bd0b2/source/fuzz/transformation_load.cpp#L15
 
- Add test cases into `transformation_load_test`.
 https://github.com/KhronosGroup/SPIRV-Tools/blob/4d22f58a812ea02e1ad53c9ccba12cb48f2bd0b2/test/fuzz/transformation_load_test.cpp#L15

- Apply needed requirements in `fuzzer_pass_add_loads` and its header.
https://github.com/KhronosGroup/SPIRV-Tools/blob/4d22f58a812ea02e1ad53c9ccba12cb48f2bd0b2/source/fuzz/fuzzer_pass_add_loads.cpp#L18

**Comment by afd** [comment]
Thanks @Mostafa-ashraf19.

Atomic loads are only valid from pointers with particular storage classes - see the SPIR-V spec for details. The fuzzer pass should thus only consider adding an atomic load when the storage class is right, and the precondition of the transformation should check that this is the case.

If you like, you can proceed by first doing a WIP PR that contributes test cases for the improved transformation. I could review those to check they look good, and then you could update the PR with the full functionality. But if you prefer just to implement the functionality together with the tests that's also fine.

**Comment by Mostafa-ashraf19** [comment]
> Thanks @Mostafa-ashraf19.
> 
> Atomic loads are only valid from pointers with particular storage classes - see the SPIR-V spec for details. The fuzzer pass should thus only consider adding an atomic load when the storage class is right, and the precondition of the transformation should check that this is the case.
> 
> If you like, you can proceed by first doing a WIP PR that contributes test cases for the improved transformation. I could review those to check they look good, and then you could update the PR with the full functionality. But if you prefer just to implement the functionality together with the tests that's also fine.

Thanks for the suggestion, I will make WIP PR first.
