### ISSUE TITLE
Spirv-fuzz: new various transformations and fuzzer passes for some atomic operations

### ISSUE THREAD

**Issue by Mostafa-ashraf19** [KhronosGroup/SPIRV-Tools#4338]
Add new transformations and fuzzer passes for some atomic operations like `OpAtomicIAdd`, `OpAtomicSMax`, `OpAtomicAnd`, `OpAtomicOr`, `OpAtomicXor`, and others. **The full description will update soon**, will mention each new transformation PR to this issue.

**Comment by afd** [comment]
Let's use #4419 to track this instead.
