### ISSUE TITLE
Reducing build size

### ISSUE THREAD

**Issue by mgood7123** [KhronosGroup/SPIRV-Tools#4351]
how can i reduce my build size?

as i currently require ~850 to ~930 MB to cross-compile `SPIRV-Tools` for each architecture leading to me quickly running out of build space as the total build directory is ~1GB per full build with ~400 MB without SPIRV-Tools

any ideas on how i can reduce the total space needed to build?

i am building via CMake as a sub project in originating from https://github.com/DiligentGraphics/DiligentCore/blob/20d5d7d2866e831a73437db2dec16bdc61413eb0/ThirdParty/CMakeLists.txt#L33

https://github.com/DiligentGraphics/DiligentCore IS NOT owned by me however i would like to support Vulkan shader compilation for Android

**Comment by dneto0** [comment]
I looked at that CMakeLists.txt and it's already doing the obvious things: turning off building of tests and executables.

Right now a build of SPIRV-Tools builds core things, plus
- validator
- optimizer
- fuzzer
- reducer
- linker

You may not need any of the last four things.  I don't think there are CMake options to disable building them.   But in the meantime, you could delete those outputs as soon as they are built.

The "core" functionality includes the assembler, disassembler, and binary parsing.

**Comment by mgood7123** [comment]
the main build size is from the optimizer which on my machine builds at

```
1.4G    app/.cxx/cmake/debug/x86_64/DiligentEngine/DiligentCore/ThirdParty/SPIRV-Tools/source/opt
```
