### ISSUE TITLE
OpFunctionCall type matching validation includes storage class, is that correct?

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/SPIRV-Tools#4359]
`OpTypeFunction` always defines its parameters with the `Function` storage class. When calling the function, the passed-in variable may have a different storage class. It doesn't seem right to expect the storage classes to match, as otherwise it means the variable needs to be copied to a local variable in the caller just to get the storage classes identical (which is what glslang does).

**Comment by alan-baker** [comment]
For clarification, you are asking about pointer parameters to a function correct? If so, yes the storage classes must match. An implementation likely addresses `Function` and `StorageBuffer` (as an example) very differently which would lead to incorrect code generation if you coerced the storage class.

You can either do what glslang does (make a `Function` variable in the caller), load the value in the caller (if possible) and pass as non-pointer value or make a version of the callee with the right storage class.

**Comment by ShabbyX** [comment]
@alan-baker your example makes sense. Since I wrote this, I also learned that you can specify non-`Function` storage in parameters, so this limitation really only affects sending `Private`, `Input` and `Output` variables to a function (which would require a load/store to a local variable).

It would have been nice if you could send those directly to a function, but not worth making an exception for.
