### ISSUE TITLE
Tag SPIRV-Header commit cf00fad5 as minimal requirement to build SPIRV-Tools 2021.1 and 2021.2

### ISSUE THREAD

**Issue by Oxalin** [KhronosGroup/SPIRV-Tools#4366]
Hi there. A few of us have been wasting time figuring out which SPIRV-Header commit or tag to use to be able to build SPIRV-Tools 2021.1 and 2021.2. Using HEAD may have worked at some point, but as of now, SPIRV-Tools fails to build against it and tag "1.5.4.raytracing.fixed" is useless.

Could you tag commit cf00fad5b4374c1ee10b46659d2766797769a658: it is the minimal commit to successfully build SPIRV-Tools 2021.1 and 2021.2?

For a cleaner solution, could you make sure to add tags regularly, maybe when a new SPIRV-Tools is released or just before so we will know against which tag it was successfully build?

**Comment by Oxalin** [comment]
Maybe this request would be better addressed by requesting it under SPIRV-Header?

**Comment by s-perron** [comment]
This is currently handled by the DEPS file for the latest releases.
