### ISSUE TITLE
Missing inc file in GN build after PR 4362

### ISSUE THREAD

**Issue by cnorthrop** [KhronosGroup/SPIRV-Tools#4374]
We're getting the following downstream while building ANGLE dependencies:
`ninja: error: '../../third_party/vulkan-deps/spirv-headers/src/include/spirv/unified1/extinst.nonsemantic.vulkan.debuginfo.100.grammar.json', needed by 'gen/third_party/vulkan-deps/spirv-tools/src/nonsemantic.vulkan.debuginfo.100.insts.inc', missing and no known rule to make it`

https://chromium-review.googlesource.com/c/angle/angle/+/3020508

It looks like that inc file is generated and support needs to be added for GN.

**Comment by cnorthrop** [comment]
@jaebaek Is this something you're working on?

**Comment by null77** [comment]
It would be helpful for us to be able to resolve this quickly as it's blocking moving forward the Vulkan dependencies in Chrome. Could we either get a quick fix or a revert of the CL above?

**Comment by greg-lunarg** [comment]
He merged this for me.

@jaebaek You can revert this until we figure out the ninja build problem.

@cnorthrop This PR passed CI, so CI apparently is not testing all build paths? I did update BUILD.gn. Are there other build files your build depends on?

**Comment by greg-lunarg** [comment]
The extinst.nonsemantic.vulkan.debuginfo.100.grammar.json file is currently in spirv-tools/source. It is looking in third_party/vulkan-deps/spirv-headers/src/include/spirv/unified1. I must have missed a place where this path is specified.

**Comment by greg-lunarg** [comment]
I think I see the problem. It is in the spvtools_vendor_table logic. I will attempt to create a fix.

**Comment by greg-lunarg** [comment]
@cnorthrop It looks like the above PR will pass CI. Is there a way you can proactively test that branch to see if it works for ANGLE?

**Comment by cnorthrop** [comment]
Thanks Greg, gave it a try and replied on the PR.

**Comment by greg-lunarg** [comment]
@jaebaek If the PR above passes CI and we merge it, it appears the revert of #4362 will no longer be necessary.

**Comment by jaebaek** [comment]
@greg-lunarg Thank you for fixing the issue. I quickly checked it and submitted it.
