### ISSUE TITLE
spirv-fuzz: Null dereference in AddLocalVariable

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4387]
Null dereference reported by ClusterFuzz: https://clusterfuzz.com/testcase-detail/5714345953394688

```
  | #0 0x55cb1f1e2c69 in spvtools::fuzz::fuzzerutil::AddLocalVariable(spvtools::opt::IRContext*, unsigned int, unsigned int, unsigned int, unsigned int) buildtools/third_party/libc++/trunk/include/__memory/unique_ptr.h:288:19
  | #1 0x55cb1f248814 in spvtools::fuzz::TransformationAddLocalVariable::Apply(spvtools::opt::IRContext*, spvtools::fuzz::TransformationContext*) const third_party/vulkan-deps/spirv-tools/src/source/fuzz/transformation_add_local_variable.cpp:73:39
  | #2 0x55cb1f10293c in spvtools::fuzz::FuzzerPass::ApplyTransformation(spvtools::fuzz::Transformation const&) third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass.cpp:189:18
  | #3 0x55cb1f142ae6 in spvtools::fuzz::FuzzerPassAddLocalVariables::Apply() third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer_pass_add_local_variables.cpp:70:7
  | #4 0x55cb1f0e8c7d in spvtools::fuzz::Fuzzer::Run(unsigned int) third_party/vulkan-deps/spirv-tools/src/source/fuzz/fuzzer.cpp:273:9
```

**Comment by afd** [comment]
It's very hard to tell where this is coming from.

Line 288 of unique_ptr.h is in the `get()` method:

https://source.chromium.org/chromium/chromium/src/+/main:buildtools/third_party/libc++/trunk/include/__memory/unique_ptr.h;drc=2b1ceaace24b8564465e8bb9ac9d64e442a893d8;l=288

But this should only cause a null pointer dereference if we're calling `get()` on a pointer to a unique pointer that turns out to be null.

I've been reading the code of `TransformationAddLocalVariable::Apply` and `fuzzerutil::AddLocalVariable` and it's not clear to me how this could be occuring.

@Vasniktel would you be able to have a look at the relevant code?

**Comment by Vasniktel** [comment]
Hard to say what causes it indeed. Do we have a full stack trace or parameters that were used to run the fuzzer (i.e. the seed, the shader etc)?

Stacktrace would be really useful since I don't have access to the clusterfuzz (it requires authorization).

**Comment by afd** [comment]
Closing as this is very likely due to MemorySanitizer leading to memory being exhausted and an allocation failing.
