### ISSUE TITLE
spirv-fuzz: Account for different signedness of integer operands in WrapVectorySynonym transformation and fuzzer pass

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4413]
If %a is a signed integer and %b an unsigned integer then we can have a scalar instruction like:

```
%c = OpIAdd %signed_int %a %b
```

We can even do:

```
%c = OpIAdd %unsigned_int %a %a
```

That is, get an unsigned result from adding two signed operands.

The fuzzer pass and transformation that wraps vector synonyms should respect the signedness of the scalar instruction's operands and result. At the moment it assumes homogeneous sign.

**Comment by afd** [comment]
@sliu-UIUC and @Vasniktel for info. I found this pretty interesting - I'll put up a PR which fixes it shortly.

**Comment by sliu-UIUC** [comment]
Didnt we have all components checked that they should have the same type as specified by `type_id`? If either `a` and `b` has incompatible types the transformation would be inapplicable.
