### ISSUE TITLE
spirv-opt error: OpPhi must appear within a non-entry block before all non-OpPhi instructions

### ISSUE THREAD

**Issue by bejado** [KhronosGroup/SPIRV-Tools#4452]
Optimizing for performance and then running the `--convert-relaxed-to-half` pass generates invalid SPIR-V.

I attached a [test.frag.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/6941712/test.frag.txt) program that reproduces the issue. Repro steps:

```
mv test.frag.txt test.frag

# Compile.
glslangValidator -V -o test.unoptimized.spv test.frag

# Optimize for performance.
spirv-opt -O test.unoptimized.spv -o test.optimized.spv

# Check that it's good so far.
spirv-val test.optimized.spv

# Convert relaxed to half.
spirv-opt \
    --convert-relaxed-to-half \
    --simplify-instructions \
    --redundancy-elimination \
    --eliminate-dead-code-aggressive \
    test.optimized.spv \
    -o test.half.spv

# Validate the SPIR-V.
# This outputs:
# error: line 54: OpPhi must appear within a non-entry block before all non-OpPhi instructions (except for OpLine, which can be mixed with OpPhi).
spirv-val test.half.spv
```

```
# glslangValidator --version
# Glslang Version: 10:11.5.0
# ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 11.5.0
# GLSL Version: 4.60 glslang Khronos. 11.5.0
# SPIR-V Version 0x00010500, Revision 4
# GLSL.std.450 Version 100, Revision 1
# Khronos Tool ID 8
# SPIR-V Generator Version 10
# GL_KHR_vulkan_glsl version 100
# ARB_GL_gl_spirv version 100

# spirv-opt --version
# SPIRV-Tools v2021.3-dev v1.3.0-2585-gf6b2a4b38
```

**Comment by s-perron** [comment]
@greg-lunarg Hey, this seems to be a bug in your pass.  Do you have time to look at it?

**Comment by bejado** [comment]
@s-perron I don't have permission to reopen this issue, but I'm still able to reproduce with the latest glslang and spirv-tools.

```
Glslang Version: 10:11.6.0
SPIRV-Tools v2021.4-dev v1.3.0-2772-g719c47006
```

**Comment by greg-lunarg** [comment]
I will try to recreate and will reopen if needed.

**Comment by greg-lunarg** [comment]
I am able to repro with components built in the last week:

Glslang Version: 10:11.6.0
SPIRV-Tools v2021.4-dev v2021.3-13-g013b1f3

error: line 57: OpPhi must appear within a non-entry block before all non-OpPhi instructions (except for OpLine, which can be mixed with OpPhi).
  %58 = OpPhi %v3float %68 %5 %37 %32

**Comment by greg-lunarg** [comment]
Sorry for the lack of response here. I will check it out presently.
