### ISSUE TITLE
SPIRV-headers version for 2021.2 tag?

### ISSUE THREAD

**Issue by Crisspl** [KhronosGroup/SPIRV-Tools#4477]
What's SPIRV-headers commit SHA/tag/branch to use with SPIRV-Tools 2021.2 tag? When using its current HEAD (https://github.com/KhronosGroup/SPIRV-Headers/commit/449bc986ba6f4c5e10e32828783f9daef2a77644), I'm getting 
```
'SPV_OPERAND_TYPE_OPTIONAL_PACKED_VECTOR_FORMAT': undeclared identifier (compiling source file ...\SPIRV-Tools\source\opcode.cpp)	SPIRV-Tools-static	...\SPIRV-Tools\core.insts-unified1.inc	455	
```
errors. Which results from `core.insts-unified1.inc` being generated from too new json (https://github.com/KhronosGroup/SPIRV-Headers/blob/master/include/spirv/unified1/spirv.core.grammar.json) relatively to yours `libspirv.h` (where `SPV_OPERAND_TYPE_*` enums are defined).

**Comment by XieJiSS** [comment]
@Crisspl Maybe you can try 2021.3, on my machine it compiles with the current HEAD (`ae217c17809fadb232ec94b29304b4afcd417bb4`) of spirv-headers.

**Comment by s-perron** [comment]
This is old, but we currently keep the hash of the deps in the `DEPS` file. You can check it out using `utils/git-sync-deps`
