### ISSUE TITLE
source/instruction.cpp and source/val/Instruction.cpp conflict in external build config

### ISSUE THREAD

**Issue by null77** [KhronosGroup/SPIRV-Tools#451]
On Windows, instruction and Instruction evaluate to the same filename, so the visual studio linker in my custom build outputs the warning:

1>D:\angle\build\Debug_x64\obj\spirv_tools\Instruction.obj : warning LNK4042: object specified more than once; extras ignored

This forces the latest compiled "instruction" file to be linked, which can produce link errors.

My solution is to rename one or both of the files, but I wasn't sure on the preferred naming scheme. Can someone fix this, or tell me what a good preferred name is? Would be much appreciated, I know it doesn't affect all configs, but would make my life easier.

**Comment by dneto0** [comment]
Ouch.  There's a similar warning on my OSX build, but I've never seen a functional problem.  We should fix this.

I just took a look.  source/instruction.cpp is fairly trivial.  We can get rid of it by moving its single-line function body into the header with explicit inlining.

Thanks for raising this issue.

**Comment by null77** [comment]
Thanks a lot for fixing this David!
