### ISSUE TITLE
OSS-Fuzz: assertion failure in spvtools::val::ValidationState_t::GetComponentType 

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4526]
OSS-Fuzz issue:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38625

@alan-baker for info.

**Comment by alan-baker** [comment]
@afd Is that the right linked issue?

**Comment by afd** [comment]
@alan-baker Oops, no - cut and pate error!

I have edited the description with the correct issue. Though OSS-Fuzz has now determined that the issue is fixed, so perhaps one of the recent fixes that went in addressed it. I guess we can close this (but I'll let you decide).

**Comment by alan-baker** [comment]
Fixed by #4524
