### ISSUE TITLE
spirv-opt: Add pass to remove unused input attributes, shorten input attribute arrays

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/SPIRV-Tools#4532]
It feels like the RemoveUnusedInterfaceVariablesPass may be a little aggressive given that it doesn't look at multiple stages to determine if it can remove an input/output. I assume that's why GLSLang doesn't use it as part of it's optimization pass.

However it seems like it would be safe to add a pass that removes:
1. Unused vertex input attributes.
2. Reduce the size of input attribute arrays to the size of the highest element used.

This at least would free up input attribute resource usage. Any chance in this getting added, or is it already in another pass that GLSLang isn't yet using?
Thanks

**Comment by greg-lunarg** [comment]
--eliminate-dead-code-aggressive will remove totally unused inputs for all stages.

I will also add a new optimization --eliminate-unused-input-components to eliminate unused components of input variables for all stages. This first implementation will just remove trailing unused components from input arrays.
