### ISSUE TITLE
OSS-Fuzz: Null-dereference READ in spvtools::opt::Instruction::result_id

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4539]
OSS-Fuzz issue:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38822

@s-perron for info

**Comment by s-perron** [comment]
ID overflow

**Comment by afd** [comment]
Hmm, is there anything sensible we can do to avoid this leading to crashes? Not because it matters for users, but to avoid noise created by the fuzzer.

**Comment by afd** [comment]
I'm wondering if we could use an ifdef to do something like this:

```
  inline uint32_t TakeNextId() {
    uint32_t next_id = module()->TakeNextIdBound();
    if (next_id == 0) {
      if (consumer()) {
        std::string message = "ID overflow. Try running compact-ids.";
        consumer()(SPV_MSG_ERROR, "", {0, 0, 0}, message.c_str());
      }
#ifdef SPIRV_STOP_ON_ID_OVERFLOW
      exit(0); // Avoid fuzzer false positives by gracefully exiting when an
               // id overflow occurs
#endif
    }
    return next_id;
  }
```

We could define `SPIRV_STOP_ON_ID_OVERFLOW` only for the fuzz targets. What do you think @s-perron ?

**Comment by turol** [comment]
The standard name for such a macro is `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` and it should be defined automatically. See for example AFL++ manual.

**Comment by s-perron** [comment]
>  What do you think @s-perron ?

I'm okay with that if those who care about the fuzzing are okay with that.

**Comment by s-perron** [comment]
The issue is that spirv-opt is a library.  Ideally, we should propagate the error up to the library call.  Since we do not allow C++ exceptions, there is no easy way to handle the id overflow everywhere.  It involves adding a lot of error handling code to propagate the error up.

The other thing we could do is run compact-ids as the first pass when this macro is set.  I don't know what the fuzzing team would prefer.

**Comment by afd** [comment]
I don't think we should change the way the library behaves just for the sake of fuzzing - i.e., I think running compact-ids first wouldn't be the right thing to do.

I agree that it would be very intrusive to add plumbing so that the error is propagated - that probably *is* the right thing to do, but I don't think actually doing it should be motivated by fuzzing - let's do that if at some point there's a compelling production use case.

I thus think that the macro approach would be good. @zoddicus would you be OK with that?

@turol thanks for the note on the macro. Will OSS-Fuzz define that for all fuzzer builds (i.e., not just AFL)?. And for an early exit, do you know what the options are for exiting (under this macro) in a manner that won't lead to OSS-Fuzz reporting a bug? I'm sure `exit(0)` will work, but I'd prefer `exit(1)`, to indicate that the exit was premature, if that won't lead to a bug being auto-filed.

**Comment by turol** [comment]
I have no idea what OSS-Fuzz does, I've only ever run fuzzers standalone. You'll have to ask them.

**Comment by afd** [comment]
I have opened #4652 to add a check that will avoid this problem during fuzzing. Closing this issue as it's not a bug.
