### ISSUE TITLE
Validator should complain about missing required decorations (Location, etc)

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/SPIRV-Tools#454]
See KhronosGroup/Vulkan-LoaderAndValidationLayers#1065 for details

**Comment by dneto0** [comment]
Agreed.  It should be conditioned on being in the Vulkan environment.

**Comment by asuonpaa** [comment]
The validator is also not complaining about missing ArrayStride or MatrixStride decorations when writing to an SSBO which contains arrays or matrices.

**Comment by baldurk** [comment]
Bumping the last comment with a repro, this assembly doesn't throw any validation errors (despite missing ArrayStride decoration on the runtime array):

```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %2 "main"
               OpExecutionMode %2 OriginUpperLeft

; this decoration should be required
;              OpDecorate %_runtimearr_uint ArrayStride 4

               OpMemberDecorate %_struct_4 0 Offset 0
               OpDecorate %_struct_4 BufferBlock
               OpDecorate %5 DescriptorSet 0
               OpDecorate %5 Binding 0
       %void = OpTypeVoid
          %7 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
%_runtimearr_uint = OpTypeRuntimeArray %uint
  %_struct_4 = OpTypeStruct %_runtimearr_uint
%_ptr_Uniform__struct_4 = OpTypePointer Uniform %_struct_4
          %5 = OpVariable %_ptr_Uniform__struct_4 Uniform
          %2 = OpFunction %void None %7
         %10 = OpLabel
               OpReturn
               OpFunctionEnd

$ spirv-val frag.spv
$ spirv-val --version
SPIRV-Tools v2019.2 v2019.1-82-g5994ae2a
```

**Comment by spencer-lunarg** [comment]
For the original issue of missing `Location`

- VUID-StandaloneSpirv-Location-04915
- VUID-StandaloneSpirv-Location-04916
- VUID-StandaloneSpirv-Location-04917
- VUID-StandaloneSpirv-Location-04918
- VUID-StandaloneSpirv-Location-04919

were all added and this is being validated properly

For @baldurk issue, running this shows

> error: line 13: Structure id 2 decorated as BufferBlock for variable in Uniform storage class must follow relaxed storage buffer layout rules: member 0 contains an array with stride 0, but with an element size of 4
  %_struct_2 = OpTypeStruct %_runtimearr_uint
  
  which seems to have been added in https://github.com/KhronosGroup/SPIRV-Tools/pull/3028

for @asuonpaa issue, confirmed we now catch MatrixStride as well

> error: line 16: Structure id 2 decorated as Block must be explicitly laid out with MatrixStride decorations.
  %_struct_2 = OpTypeStruct %mat2v2float %mat2v2float

So I think there is nothing left to do in this issue
