### ISSUE TITLE
OSS-Fuzz: ASSERT: return_value_ && "Did not generate the variable to hold the return value."

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4540]
OSS-Fuzz issue:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38960

@s-perron for info.

**Comment by s-perron** [comment]
A function with the return type void contains the following code:

```
%37 = OpUndef %void
OpReturnValue %37
```

A function with a return type of void is returning an undef value of type void.  I can't find anything in the spec to say this not allowed, but  it was not really intended right?

@alan-baker @afd Where did we land with the use of void types?  Is this legal?

**Comment by afd** [comment]
This is illegal (updated rules for uses of OpTypeVoid in upcoming spec release).

I have opened an issue to track whether the validator has support for this:

https://github.com/KhronosGroup/SPIRV-Tools/issues/4638

**Comment by afd** [comment]
OK, the validator does already reject the creation of OpUndef with void type. So @s-perron is the issue that the optimiser is creating such an OpUndef somewhere?

**Comment by s-perron** [comment]
You are right.  It is being generated by the optimizer.  I'll track that down an fix it.
