### ISSUE TITLE
OSS-Fuzz: memout in spirv-opt

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4545]
OSS-Fuzz issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38842

spirv-opt does indeed hang on the reproducer test case, which is a very small piece of SPIR-V.

@s-perron for info.

**Comment by s-perron** [comment]
Spirv-opt to trying to fully unroll a loop with 2,097,410 iterations.  I kindof want to leave this.  For legalization, we sometime have to unroll the loop fully at the request of the developer.  If I put a limit, just for the sake of the fuzzer, then we risk missing something we have to do.

I'll close this issue as "won't fix".
