### ISSUE TITLE
Spirv - Improve half support for GLSL

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/SPIRV-Tools#4546]
So my understanding is that long ago, HLSL mapped half to float, but the dxc compile flag and SM6.5 added --enable-16-bit-types flag to undo this mapping.  HLSL also has a type "min16Float" that must be used to be explicit about what is half and what is not.

GLSL has an equivalent in float16_t, fp16vec2/3/4.  But these types are only defined when GL_EXT_shader_explicit_arithmetic_types_float16 is present off the VK_KHR_shader_float16_int8 extension.  

On Android, the float16_t extension is only enabled on Android 10/11 on Mali devices.  I don't see this extension on older Adreno chips, or on some consoles either.  gpuinfo.org points to the extension present on Adreno and PowerVR on Android11, but it doesn't show the Vulkan bool settings on these extensions which are important.   Then combine this with Android8/9 drivers that are frozen, or that Adreno completely left half out of their Vulkan driver.   

It's especially hard to write fp16 shaders given the minefield of storage16 flags (four of them).  Nvidia doesn't support storage16.inputOutput16, and AMD doesn't support storage16.pushConstants16.  Mali supports all of these, Adreno none of the shader or storage extensions.   I don't have an Android PowerVR device.

Contrast this with MSL, where half is a part of the language.  It can be used everywhere, and has full support across inputOutput16 and other stages.  It supports passing half out of the vertex shader, which is especially important on TBDR architectures since that varying data must be stored in system memory.

So this leaves falling back to the vague mediump designator.  lowp is moot at this point, since it often is just remapped to mediump precision.  However, a precision modifier like lowp/mediump/highp isn't quite the same construct, since it isn't a type.  It can't be used in casts, which are numerous since every float must be cast to half or the compile fails.

What I would like to propose is that GL_EXT_shader_explicit_arithmetic_types_float16 : enable still supply float16_t but switch that to relaxed precision off a compile flag.  Callers would then pick one compiled shader over another to get explicit float16_t support.  The following code would then work for type definitions and casts.   Although it would be nice if spirv supported 1.0h instead of the uglier half(1.0) on all constants.

```
        #extension GL_EXT_shader_explicit_arithmetic_types_float16 : enable

	#extension GL_AMD_gpu_shader_half_float : enable
	#extension GL_AMD_gpu_shader_half_float_fetch : enable

        precision mediump int;
        precision highp float;

#if USE_HALF
        // these are well defined types
        #define half float16_t

	#define half2 f16vec2
	#define half3 f16vec3
	#define half4 f16vec4

	#define half2x2 f16mat2
	#define half3x3 f16mat3
	#define half4x4 f16mat4
#else 
       #define half float
       ....
#endif

// storage.inputOutput16 is false on Nvidia, so can't use half for any vs/fs input/output vars
#if USE_HALF_INPUT_OUTPUT
     #define half_io half
     #define half2_io half2
     ...
#else 
    #define half_io float
    #define half2_io vec2
     ...
#endif
```

This doesn't work

```
#define half mediump float
#define half2 mediump vec2

half one;                   // works -> mediump float one;
half one = half(1.0); // fails -> mediump float one = mediump float(1.0);

```

This maybe works but is ugly, and it's unclear what the passthrough tohalf calls really work.  Splits the casts off from the type definition.

```

#define half mediump float
#define half2 mediump vec2

#define tohalf(x) x
#define tohalf2(x) x

half one;                       // works -> mediump float one;
half one = tohalf(1.0); // works -> mediump float one = 1.0;

This approach fails on constructs like the following:
half3(1.0,2.0,3.0)
half4(rgbA, texColor.a)

These must be changed to the following, which is even more ugly and more unclear what the type is, since the tohalf macros are just passthrough.

tohalf(vec3(1.0,2.0,3.0))
tohalf(vec4(rgbA, texColor.a))


```

**Comment by alecazam** [comment]
Note that this affects the MSL codegen out of spriv-cross.  If we don't set float16_t support, then generated MSL transpiles to fp32 ops since %v2/3/4half is not used in any of the operation.   On the SPV side it's unclear what the device shader compiler does with getting with "Relaxed Precision" tagged on variables, but it's clear the spv ops are full fp32.  

Trying to use the ops LunarG to map Relaxed Precision from spirv-opt was a nightmare where a single use of a "Relaxed Precision" varaible caused entire expressions to use fp16 even if it was a mix of fp32 and fp16, where fp32 should have been the correct choice.

**Comment by alecazam** [comment]
Also don't forget to compile to vulkan1.1 or even with the extension defined, only OpLoad/OpConvert/Store is generated.  With 1.1 set, I actually see math and other ops.  The load/stores seemed pointless and repeated using vulkan 1.0 target.

**Comment by dneto0** [comment]
This seems like it should be filed against Glslang ?
