### ISSUE TITLE
Add a SPIRV_ENV_MAX value to spv_target_env

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4558]
The spv_target_env enum contains all the SPIR-V versions, but there's no easy way to query how many enum values there are.

When turning an arbitrary unsigned integer into an enum value we need to be able to check whether the value is in range (to avoid an undefined behaviour).

Using the current largest environment value is a fragile solution as that will change over time.

Would anyone object to us adding a special enum constant capturing the number of values, e.g. SPIRV_ENV_MAX?

**Comment by zoddicus** [comment]
Since you mentioned that OSS-Fuzz has found an UB around this, I think it is worthwhile.

**Comment by dneto0** [comment]
Seems fine to me.
I like to keep binary compatibility over time,  e.g. SPV_ENV_VULKAN_1_2,  but that wouldn't apply to sentinels like a MAX_VALUE enum.
