### ISSUE TITLE
Adding optimization passes to aid in in-file size reduction

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#457]
We would like to add the following transforms to spirv-opt:

(Exhaustive) Inlining
PromoteMemoryToRegisters (essentially store/load pair elimination)
ScalarReplacementofAggregates (essentially decomposing aggregate loads and stores into their component loads and stores)
Composite/Extract Elimination
Aggressive Dead Code Elimination (incuding empty control flow removal)
AccessChain-Load CSE

These optimizations will mainly be utilized to remove dead computations from SPIR-V shaders with the ultimate goal of minimizing the size of the resulting in-file SPIR-V. 

We expect that we will be adding these using the same command line model currently used to specify which optimization spirv-opt should be run.

**Comment by dneto0** [comment]
Sounds great.  I look forward to assisting the integration.

**Comment by antiagainst** [comment]
It seems all the items listed are done. I'll close this.
