### ISSUE TITLE
OSS-Fuzz: Null-dereference READ in spvtools::opt::EliminateDeadMembersPass::UpdateCompsiteExtract

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4642]
This reproduces when spirv-opt is executed with the `-Os` flag.

It is not id overflow-related.

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40263

@s-perron for info.

**Comment by s-perron** [comment]
Might have been fixed by https://github.com/KhronosGroup/SPIRV-Tools/pull/4819
