### ISSUE TITLE
Unhelpful error messsage

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/SPIRV-Tools#4650]
https://github.com/KhronosGroup/SPIRV-Tools/blob/d0a827a9f313954935e3d9edb0c063fd8625a22e/source/opt/instrument_pass.cpp#L977-L990

This message complains that `Mixed stage shader module not supported`, it could be nice to report what the shader stages actually are.

Edit: Additionally we're hitting this message in a raytracing PSO, so it may be time to address the todo?

**Comment by greg-lunarg** [comment]
Are you calling this pass directly or indirectly through GPU-assisted validation? In general, this pass is not intended to be used by the general public.

**Comment by greg-lunarg** [comment]
Nonetheless, such a shader module is possible and should be supported.

I do believe that neither of the high-level shader compilers (glslangValidator or dxc) will create such a module, which is why I did not support it initially.

So I would be curious how this shader module was created.

**Comment by jeremyg-lunarg** [comment]
This functionality has been moved in to Vulkan-ValidationLayers so I've opened an issue over there: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8716
