### ISSUE TITLE
Assertion failure in spvtools::val::getBaseAlignment

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4671]
OSS-Fuzz issue:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43265

@alan-baker would you be able to take a look?

**Comment by alan-baker** [comment]
I think the best thing to do here would be only check layouts in the Vulkan environment. Right now layouts are checked in universal environments, but invalid buffer are only checked in Vulkan environments. Unfortunately this affects a lot of tests so it requires some tedious updates.

There is also the related work in #4597 which may conflict slightly.
