### ISSUE TITLE
scalar-replacement pass generates invalid SPIR-V: expected AliasedPointerEXT or RestrictPointerEXT for PhysicalStorageBufferEXT pointer

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-Tools#4678]
SPIRV-Tools version: latest head (c5ee1bc7)

Input module: [in.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/7833624/in.zip)
Command run: `spirv-opt --scalar-replacement=0 --validate-after-all -o out.spv in.spv`
Output:
```
error: line 66: OpVariable 42: expected AliasedPointerEXT or RestrictPointerEXT for PhysicalStorageBufferEXT pointer.
  %42 = OpVariable %_ptr_Function__ptr_PhysicalStorageBuffer_Indices Function

error: line 0: Validation failed after pass scalar-replacement=0
```

It sounds like the pass should check the decorations on the pointee type before creating such a variable.

**Comment by s-perron** [comment]
This seems like a hole in the spec to me.  The input shader has a variable whose type is a struct that contains a pointer to the PhysicalStorageBufferExt class:

```
               OpTypeForwardPointer %_ptr_PhysicalStorageBuffer_Indices PhysicalStorageBuffer
       %Mesh = OpTypeStruct %_ptr_PhysicalStorageBuffer_Indices
%_ptr_Function_Mesh = OpTypePointer Function %Mesh                                                                                         
...
       %mesh = OpVariable %_ptr_Function_Mesh Function                                                                                                                                                                                                                                  
```

There are no decorations on the member for scalar replacement to copy.  So after scalar replacement the variable becomes:

```
         %42 = OpVariable %_ptr_Function__ptr_PhysicalStorageBuffer_Indices Function
```

This violates the spec:

```
If an OpVariable's pointee type is a pointer (or array of pointers) in PhysicalStorageBufferEXT storage class, then the variable must be decorated with exactly one of AliasedPointerEXT or RestrictPointerEXT.
```

However, I find it odd that a decoration is required when a variable with type `%_ptr_PhysicalStorageBuffer_Indicies` is declared, but it is not if you wrap it in a struct.

@alan-baker @dneto0  What are your thoughts?  I believe the input shader should be invalid as well.

**Comment by dneto0** [comment]
The in.spv module seems to be out of spec already, but the validator does not catch it.

The spec says:

> Variables holding PhysicalStorageBuffer pointers must be decorated as either AliasedPointer or RestrictPointer. Only those memory object declarations decorated with Aliased or AliasedPointer may alias each other.

No variable in the module is decorated either with AliasedPointer or RestrictPointer.

But the %mesh variable stores a pointer into PhysicalStorageBuffer, but is has no decorations.  (It has OpName, but that's different.)

    %mesh = OpVariable %_ptr_Function_Mesh Function 

%_ptr_Function_Mesh = OpTypePointer Function %Mesh

       %Mesh = OpTypeStruct %_ptr_PhysicalStorageBuffer_Indices

%_ptr_PhysicalStorageBuffer_Indices = OpTypePointer PhysicalStorageBuffer %Indices

     %v3uint = OpTypeVector %uint 3
%_runtimearr_v3uint = OpTypeRuntimeArray %v3uint
    %Indices = OpTypeStruct %_runtimearr_v3uint

**Comment by dneto0** [comment]
I noticed the generator was Shaderc over Glslang, so I made this sample GLSL compute shader:

```
#version 450

#extension GL_EXT_buffer_reference: enable
layout(buffer_reference) buffer Node;

layout(buffer_reference) buffer Node {
  int payload;
  Node next;
} buf;

layout(buffer_reference, set = 0, binding = 0) buffer Root {
  Node root;
} r;

void main() {
  Node n = r.root;
  n.payload = 1;
}
```

When compiling with glslc, I get a module where %n is decorated with AliasedPointer.

So something it looks like Glslang's output is within spec, probably.  Is something else modifying the module in the meantime?

**Comment by alan-baker** [comment]
This has been raised internally as Khronos SPIR issue 696.

**Comment by pierremoreau** [comment]
Here is the GLSL shader code used to generate the attached in.spv; it was compiled as `glslc --target-env=vulkan1.2 -o in.spv in.comp`.

```glsl
#version 460

#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require

layout (buffer_reference, scalar) readonly buffer Indices {
  uvec3 i[];
};

struct Mesh {
  Indices indices;
};

layout (set=0, binding=0, std430) readonly buffer Meshes {
  Mesh meshes[];
};

void main() {
  Mesh mesh = meshes[gl_GlobalInvocationID.x];

  uvec3 indices = mesh.indices.i[gl_LocalInvocationID.x];
}
```

> Is something else modifying the module in the meantime?

There should not be: it was just compiled using glslc, and that’s the version that was uploaded as in.spv, without any further modifications.

**Comment by pierremoreau** [comment]
Replacing
```glsl
struct Mesh {
  Indices indices;
};
```
by
```glsl
layout (buffer_reference) buffer Mesh {
  Indices indices;
};
```
fixes it, i.e. `%mesh` gets decorated by `AliasedPointer` and running spirv-opt on the output does not trigger any validation issues.

**Comment by s-perron** [comment]
This is invalid. Glslang should be adding a decoration for `%mesh` (the function scope `Mesh` variable), but it does not.  See https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#:~:text=If%20the%20type%20an%20OpVariable%20points%20to%20is%20a%20pointer%20(or%20contains%20a%20pointer)%20in%20the%20PhysicalStorageBuffer%20storage%20class%2C%20the%20OpVariable%20must%20be%20decorated%20with%20exactly%20one%20of%20AliasedPointer%20or%20RestrictPointer.

If we add the correct decoration, the test case passes.

Open up an issue against glslang to fix the code generation.

**Comment by arcady-lunarg** [comment]
This should be fixed in glslang as of https://github.com/KhronosGroup/glslang/pull/3229, but if there are still cases where glslang is not adding the necessary decorations please open an issue against glslang and we will look into it.
