### ISSUE TITLE
linker fails to compile

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/SPIRV-Tools#4684]
@pierremoreau since your last commit the linker doesn't compile here 

/home/airlied/devel/spirv-tools/source/link/linker.cpp: In lambda function:
/home/airlied/devel/spirv-tools/source/link/linker.cpp:177:55: error: conversion from ‘size_t’ {aka ‘long unsigned int’} to ‘uint32_t’ {aka ‘unsigned int’} may change value [-Werror=conversion]
  177 |       insn->ForEachId([&id_bound](uint32_t* id) { *id += id_bound; });
      |   

looks like a size mismatch, did you just build on 32-bit?

**Comment by pierremoreau** [comment]
I am building on 64-bit and did not get that warning with clang, but I can see that several CI tests failed. Does the above commit fixes it? I will set up a build with gcc and see if I can catch it there.

**Comment by pierremoreau** [comment]
The current HEAD is indeed failing with gcc, and builds fine with the fix.
