### ISSUE TITLE
spirv-val: not catching "Image Operand Offset can only be used with OpImage*Gather operations"?

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/SPIRV-Tools#4693]
Please see related glslang issue: https://github.com/KhronosGroup/glslang/issues/2877

The shader in this bug produces a Vulkan validation layer warning at runtime:
```
[VUID-StandaloneSpirv-Offset-04663] Image Operand Offset can only be used with OpImage*Gather operations"
```

However, spirv-val does not detect this issue, only when I run through full Vulkan validation to I get this error at runtime.  This seems like something that could be detected offline with spirv-val.  The shader in the referenced glslang bug reproduces the error.

**Comment by alan-baker** [comment]
See https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/val/validate_image.cpp#L454

There are checks for this. I'm not sure why you're not hitting them. Are you running offline validation with a Vulkan environment specified?

**Comment by danginsburg** [comment]
> There are checks for this. I'm not sure why you're not hitting them. Are you running offline validation with a Vulkan environment specified?

No, I wasn't.  That is why I wasn't seeing it.  Adding  --target-env vulkan1.1spv1.4 to spir-val does indeed give the error. Sorry for the noise, I had the impression for some reason that it could discern the environment from the SPIR-V when the target-env was specified for glslang, but I guess not.
