### ISSUE TITLE
spirv-diff tests failing on Windows

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#4696]
Our internal Windows CI testers are failing the spirv-diff tests added in #4611.  @ShabbyX could you take a look?  I've disabled them for now in #4695.

Attached are the failures from our bots.

[windows-failures.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/7998278/windows-failures.txt)

**Comment by s-perron** [comment]
That is strange.  All of the test passed for #4611, so I merged.  I did not notice that the windows tests did not run.  They are not on the list at all.  I should have noticed that.

**Comment by ShabbyX** [comment]
There seemed to have been a flake: https://github.com/KhronosGroup/SPIRV-Tools/pull/4611#issuecomment-1027622404

No worries though, I'll sort it out.

**Comment by ShabbyX** [comment]
Should be fixed now. Please close.
