### ISSUE TITLE
OSS-Fuzz: ASSERT: memcmp(optimized_binary_with_nop.data(), original_binary, original_binary_size)

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4722]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39696

@s-perron for info.

**Comment by s-perron** [comment]
The problem with this on is that the input spir-v is in big endian, but the output spir-v is in little endian.  This is why there is an assert that the contents of the spir-v changed, even if the optimizer did nothing.

**Comment by s-perron** [comment]
I don't believe this will affect anybody because everybody uses little endian anyway.
