### ISSUE TITLE
OSS-Fuzz: Undefined shift in spirv-as

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4724]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40219

**Comment by dneto0** [comment]
A smaller reproducer:

```%float = OpTypeFloat 16

%t = OpConstant %float
; fedcba9876543210
; 3210
0xaaaa8p0
```
Trouble occurs when there are 5 hex digits in the mantissa.

runtime error: shift exponent 4294967295 is too large for 32-bit type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior spirv-tools/source/util/hex_float.h:1003:29 in 
Executed hex-float-overshift.txt in 2 ms
