### ISSUE TITLE
OSS-Fuzz: ASSERT: a->type() == b->type()

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4725]
For some reason OSS-Fuzz has reported three separate issues for this, but they are likely all duplicagtes:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43555

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43570

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43684

We should check the associated test cases all pass before closing.

@s-perron for info.

**Comment by s-perron** [comment]
Invalid spir-v.  The float type is decorated with RelaxPrecision:

               OpDecorate %float RelaxedPrecision
