### ISSUE TITLE
OSS-Fuzz: timeouts and memouts in optimizer

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4728]
OSS-Fuzz has reported a number of timeouts and memouts. These could simply be due to weird fuzzed shaders, but ideally we should look at them in case there are infinite loops.

Rather than creating one SPIRV-Tools issue per bug, I've made this umbrella issue.

- [x] https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39010
- [x] https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39686
- [x] https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39714
- [x] https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40272
- [x] https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40839
- [x] https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41311

@s-perron for info

**Comment by s-perron** [comment]
39010: This has a loop with 1048586 that is marked as unroll.  For technical reasons, we have to unroll these loop.  We will not add a heuristic to avoid unrolling the loop.

**Comment by s-perron** [comment]
[40272](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40272): Looks like an infinite loop while doing dead branch elimination again.

**Comment by s-perron** [comment]
[40839](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40839): Has a loop with 536,870,917 iterations that needs to be unrolled.  It will take a long time to compile.

**Comment by s-perron** [comment]
[39686](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39686):  The CFG is invalid.  The merge block for a loop is post dominated by the continue target for the same loop.

The OpLoopMerge in block %313 has merge block %318 which then goes to %315, the continue target for %313.

![t39686](https://user-images.githubusercontent.com/31666470/175332258-3def4249-cd22-4392-be1d-3ff813f4b844.png)

**Comment by afd** [comment]
@s-perron I can indeed close the OSS-Fuzz issues, and I agree that it does not make sense to change how the optimizer works in production in response to these.

However, can we first discuss two alternatives?

(1) use a fuzzer ifdef so that unrolling beyond a certain bound will not be applied during fuzzing. 

(2) add an option (if it doesn't already exist) to allow a bound on unrolling to be passed to the optimiser. Do not pass a bound in production, but configure the fuzzer to pass a bound.

I would be keen on these options over merely closing the issues as they will avoid noise in the future. If we just close the issues, it might be that OSS-Fuzz simply opens more issues that arise from the same root cause. And if we just ignore all timeout / memout issues then we might end up missing other things that are genuine bugs.

What do you think? I'm happy to do a PR if you're OK with one of the above options.
