### ISSUE TITLE
spirv-val: Check for the use of output buffers in compute kernel

### ISSUE THREAD

**Issue by rayanht** [KhronosGroup/SPIRV-Tools#4759]
The following code after assembly using `spirv-as` passes `spirv-val` successfully. It isn't valid SPIRV as OpenGL compute kernels can't have output buffers

```
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %13 "main" %10 %12
OpExecutionMode %13 LocalSize 1 1 1
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%3 = OpTypeBool
%4 = OpTypeInt 32 1
%5 = OpTypeFloat 32
%6 = OpTypeInt 32 0
%7 = OpConstant %6 13
%8 = OpTypeArray %5 %7
%9 = OpTypePointer Input %5
%10 = OpVariable %9 Input
%11 = OpTypePointer Output %5
%12 = OpVariable %11 Output
%13 = OpFunction %1 Pure %2
%14 = OpLabel
OpReturn
OpFunctionEnd
```

**Comment by sfricke-samsung** [comment]
So this is [VUID-StandaloneSpirv-None-04644](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-StandaloneSpirv-None-04644) in the Vulkan spec. This is begin validated but at `ValidationState_t::RegisterStorageClassConsumer()` time.

So because no instruction in any function block is trying to use the variable it is not being triggered

**Comment by rayanht** [comment]
> VUID-StandaloneSpirv-None-04644
If the Storage Class is Output, then it must not be used in the GlCompute, RayGenerationKHR, IntersectionKHR, AnyHitKHR, ClosestHitKHR, MissKHR, or CallableKHR execution models

Given this validation rule, I'd argue that this should fail the validator even if the variable isn't actually accessed by the program. This can also cause issues for downstream consumers of spirv that rely on certain assumptions about the validator's behaviour. In the case of `spirv-cross` for example, trying to emit MSL from this spirv program will generate a function with a return type as it sees a buffer with a storage class `Output` but it is actually illegal for MSL compute kernels to have a return type.

I do understand that you are not responsible for `spirv-cross` and that this program will in practice run without errors as the variable is never accessed so I'm not too sure what's the course of action from here.

**Comment by sfricke-samsung** [comment]
So something to also think about is you could have a SPIR-V module with 2 entry points (Fragment and Compute as an example) and it could be possible there is a variable declared in as `Output` but only ever used in the Fragment entry point path, in this case the current validation would not complain as it walks the instructions that are possible

**Comment by rayanht** [comment]
In the case where you have a Compute and a Fragment the Output buffer would have to be in the list of interfaces for the Fragment's OpEntryPoint, wouldn't it? Can we somehow validate for OpVariables that aren't "bound" to any OpEntryPoint?

**Comment by rayanht** [comment]
Following up on this, it seems like the validator doesn't catch it even if it is being used:

```
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %9 "main" %6 %8
OpExecutionMode %9 LocalSize 1 1 1
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%3 = OpTypeFloat 32
%4 = OpTypeInt 32 0
%5 = OpTypePointer Input %4
%6 = OpVariable %5 Input
%7 = OpTypePointer Output %4
%8 = OpVariable %7 Output
%9 = OpFunction %1 DontInline %2
%10 = OpLabel
%11 = OpLoad %4 %6
%12 = OpIAdd %4 %11 %11
OpStore %8 %12
OpReturn
OpFunctionEnd
```

Running `spirv-as` and `spirv-val`:

```
$ ./bin/spirv-as --target-env spv1.3 -o test.spv test.spasm && bin/spirv-val test.spv
```

Exits with return code 0.

Vulkan validation layers do catch it correctly though:

```
[ERROR] validation layer (Validation):
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x7ff207030218, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: OpEntryPoint Entry Point <id> '1[%1]'s callgraph contains function <id> 1[%1], which cannot be used with the current execution model:
[VUID-StandaloneSpirv-None-04644] in Vulkan evironment, Output Storage Class must not be used in GLCompute, RayGenerationKHR, IntersectionKHR, AnyHitKHR, ClosestHitKHR, MissKHR, or CallableKHR execution models
```

**Comment by rayanht** [comment]
Seems like the update above was a false positive. It does get validated but only when `vulkan1.2` is explicitly passed as the `target-env` of the validator:

```
 ./bin/spirv-as --target-env spv1.3 -o test.spv test.spasm && bin/spirv-val --target-env vulkan1.2 test.spv
error: line 13: OpEntryPoint Entry Point <id> '1[%1]'s callgraph contains function <id> 1[%1], which cannot be used with the current execution model:
[VUID-StandaloneSpirv-None-04644] in Vulkan evironment, Output Storage Class must not be used in GLCompute, RayGenerationKHR, IntersectionKHR, AnyHitKHR, ClosestHitKHR, MissKHR, or CallableKHR execution models

  %1 = OpFunction %void DontInline %5
```
