### ISSUE TITLE
spirv-opt: Remove unneeded OpCapability

### ISSUE THREAD

**Issue by godlikepanos** [KhronosGroup/SPIRV-Tools#4778]
This is a very simple fragment shader in HLSL:
```hlsl
struct PSInput
{
	float2 color : COLOR;
};

struct Foo
{
    uint64_t u;
};

ConstantBuffer<Foo> u_foo; // Not used anywhere

float4 PSMain(PSInput input) : SV_TARGET
{
    return float4(0, 0, 0, 0);
}
```

spirv-opt does eliminate the `u_foo` just fine but it leaves the `OpCapability Int64`. If I comment out the declaration of `u_foo` myself I'll get the same SPIR-V as before without `OpCapability Int64`. 

It might be beneficial to add some functionality that removes unneeded `OpCapability`. Unless it's there and I missed it.

PS: If you want to play with the shader and see the SPIR-V use this https://shader-playground.timjones.io/c4707a75f904a7eae04110fddb78fa92

**Comment by s-perron** [comment]
No we have not implemented anything like this.  Having a pass that does not, but is not part of the predefined transformation sequences would be fine, if you want to contribute it.  I don't know when I will get around to doing it myself.

There was debate about what having a capability in the spir-v mean.  Should it be an indication of the things that can be done, freeing tools to add code to use anything those capabilities define or is it the list of capabilities used by the shader?  We opted to be conservative, and not remove or add capabilities unless the pass is specifically intended to do that.  Those passes do not become part of the size or optimization sets.

**Comment by Keenuts** [comment]
Hello!
FYI there is a new pass in SPIR-V Tools to trim those unused capabilities.
It is also integrated in DXC. What's missing is the support for the Int64 capability, that can be added (https://github.com/KhronosGroup/SPIRV-Tools/blob/main/source/opt/trim_capabilities_pass.h#L75).

I will have to focus on raytracing capabilities first, and then this one. If you want to move faster, you can send a PR to SPIRV-Tools and request me for review.

**Comment by godlikepanos** [comment]
Thank you for looking into this. There is no rush from my side. I may try to add this myself when I find some time but I'll notify you first to avoid duplicate work.
