### ISSUE TITLE
Build error regarding 'SpvBuiltInCullMaskKHR'

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/SPIRV-Tools#4791]
Building vulkan-deps from SPIRV-Tools and SPIRV-Headers is failing due to the error below:
```
error: enumeration value 'SpvBuiltInCullMaskKHR' not handled in switch [-Werror,-Wswitch]
switch (label) {
^~~~~
```
Even though the case is already included in commit 58dc37ea6af7ec09f32f7b13ff60071e3ba2bd24. It is possible that SPIRV-Tools and SPIRV-Headers are out of sync.

More info: [Here](https://bugs.chromium.org/p/angleproject/issues/detail?id=7273)
CC: @s-perron

**Comment by s-perron** [comment]
I don't know what we can do.  We have added that case to the switch.  Our CI build are passing (https://github.com/KhronosGroup/SPIRV-Tools/commits/master).  I cannot reproduce this problem anymore.

Can you check vulkan-deps to make sure it has the latest for both spirv-headers and spirv-tools?

**Comment by aabdolrashidi** [comment]
Using the latest updates today, the issue seems to have been fixed. Thanks!
