### ISSUE TITLE
Validation of a switch where the default block also occurs as a target

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4799]
@alan-baker Consider this SPIR-V, which comes from [this validator test case](https://github.com/KhronosGroup/SPIRV-Tools/blob/f74b85853c35b0dc973b92037f09db591f3e3fec/test/val/val_cfg_test.cpp#L2410):

```
               OpCapability Shader
               OpCapability Linkage
               OpMemoryModel Logical GLSL450
               OpName %1 "first"
               OpName %2 "second"
               OpName %3 "third"
          %4 = OpTypeVoid
          %5 = OpTypeInt 32 0
          %6 = OpUndef %5
          %7 = OpTypeFunction %4
          %8 = OpFunction %4 None %7
          %9 = OpLabel
               OpSelectionMerge %10 None
               OpSwitch %6 %2 0 %1 1 %2 2 %3
          %1 = OpLabel
               OpBranch %2
          %2 = OpLabel
               OpBranch %3
          %3 = OpLabel
               OpBranch %10
         %10 = OpLabel
               OpReturn
               OpFunctionEnd
```

We think this violates the rule for the order of OpSwitch targets.

The rule says (in its revised form):

> if T1 and T2 appear as labels of targets in the OpSwitch instruction, and either the case construct defined by T1 branches to T2, or the case construct defined by T1 branches to the Default case construct of the OpSwitch which in turn branches to T2, then the last target with label T1 must immediately precede the first target with label T2 in the list of OpSwitch Target operands

In this example, %2 is the default, and the targets, in order, are [%1, %2, %3]. (It's interesting that the default is also a target, but I believe that is allowed.)

The path %1->%2->%3 violates the rule, because:

- The last target with label %1 does not immediately precede the first target with label %3 (the target %2 is in the way)
- The case construct defined by %1 branches to the Default case construct (defined by %2) which in turn branches to %3.

Do you agree that this test case violates the rule?

If so, it would be easy to fix the test case - but do we think it should indeed be disallowed in its current form (i.e., are we happy with the rule)?

**Comment by alan-baker** [comment]
I don't think this is invalid. `%1` branches to `%2` and precedes it in the list (except that `%2` is also the default and can't precede that listing). `%2` branches to `%3` and immediately precedes it in the list. I don't read the rule as requiring immediate precedence for transitive branches. I can buy the rule is isn't particularly clear in the spec. I think reordering the targets would be worse.

This is the likely HLL switch statement:
```
switch (c) {
  case 0:
    // %1
  default:
  case 1:
    // %2
  case 2:
    // %3
}
```

**Comment by afd** [comment]
Thanks - have migrate this to a spec issue for discussion.
