### ISSUE TITLE
spirv-val still complains about using OpVariable initializers

### ISSUE THREAD

**Issue by aarongreig** [KhronosGroup/SPIRV-Tools#482]
The following was added in revision five of the spec:
> Initializer must be an `<id>` from a constant instruction or a global (module scope) OpVariable instruction.

But trying something like
```
%10 = OpTypeInt 32 1
%11 = OpTypePointer Private %10
 %3 = OpVariable %11 Private
 %4 = OpVariable %11 Private %3
```
gives me
> error: 90: OpVariable Initializer <id> '3' is not a constant.

from spirv-val

**Comment by dneto0** [comment]
Whoops. Agreed that's a problem.
