### ISSUE TITLE
Loop unrolling takes up to 16 min. for some UE5 shaders

### ISSUE THREAD

**Issue by LukasBanana** [KhronosGroup/SPIRV-Tools#4827]
Hi all,

We are currently investigating a shader compile regression for some of our compute shaders in Unreal Engine 5 that takes up to 16 min. and it seems that 99% of that time is due to the SPIRV-Tools loop unrolling pass; disabling just this one pass cuts down the time to mere seconds.
To be fair, those shaders are indeed pretty heavy and the one I'm currently looking at has 271 loops, all of which are fixed 8 iterations and pretty small though, like this one (as translated back to GLSL):
```c++
    for (uint _4556 = 0u; _4556 < 8u; )
    {
        _436[_4556] = _424[_4556] * _4554;
        _4556++;
        continue;
    }
```

I was hoping @s-perron might have some insight to help out here as he worked on the CFG traversal once to use structured order (see commit [545d158](https://github.com/KhronosGroup/SPIRV-Tools/commit/545d158a2ff9c03dfecadb2ef00a715d2740764a)). Using LLVM's default traversal via `ForEachBlockInReversePostOrder` roughly cuts down the time in half but this is still way longer than what the DXIL backend is doing. I also noticed that `ComputeStructuredOrder` builds up a linked list (`std::list`) with over 51k elements. Correct me if I'm wrong, but it looks like the loop unrolling pass does that for every single loop and I don't understand why there are so many elements necessary to unroll a tiny loop as shown above.

Hopefully we can identify some low hanging fruit and I'm happy to share some of these UE5 shaders, but would like to do that via email for license reasons.

Thank you
Laura

**Comment by LukasBanana** [comment]
@s-perron that would be great. Can you send me your email address please?

**Comment by s-perron** [comment]
I found the problem, and I believe I have a fix.  I'll open a PR in either today or tomorrow.

The unroll the loop, spirv-opt needs a list of the basic blocks in the loop in structured order.  The current code that computes the structured order for these blocks does not know it can stop at the merge block for the loop.  It will include every basic block in the function that can be reached from the loop header.  Since the function is larger, and gets larger after every loop is unrolled, this time it takes is noticeable.

The solution will be to add a new function that will also take an end block when computing the structured order.  Then the search can stop at the merge node.

**Comment by s-perron** [comment]
With this change, the compilation still seems a little slower than it should be, but it is much faster than it was.  I will probably not look into it any further.

**Comment by LukasBanana** [comment]
Thanks a lot Steven, we appreciate your effort.

**Comment by s-perron** [comment]
> Thank you very much Steven! What compilation time do we end up with that fix concretely?

You will want to measure it yourself.  We would have very different setups.  The numbers might not be directly comparable, but hopefully the gain will be similar.  I'm seeing it take about 1/3 of the time that it use to.  Hopefully it is around 5-6 mins for you.

**Comment by LukasBanana** [comment]
I did run some tests and it cuts down the time to about 8 min. which is roughly 40% of what it was before, so already a huge improvement. It seems to me that SPIRV-Tools doesn't perform as many constant folding techniques as the DXIL backend does, like `greaterLessThan` intrinsics etc., but that's something for a different ticket/PR and I'm looking into this myself right now.
Thanks again for your help @s-perron
