### ISSUE TITLE
Float values are too long.

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/SPIRV-Tools#4867]
This is an example of codegen, that is then transpiled over by spirv-cross to Metal.   The float values are way too long.  A fp32 which is what nearly all hw uses is at most 6 digits of precision, but this is written out to 32 digits.   Have an option for those rare people that use fp64 gpu ops and have at most %16g supported.  On mobile, we don't have fp64.   fp16 should be an even smaller number of digits.  Also stripping trailing zeroes on the mantissa and preceeding zeroes on the exponent would reduce file size and improve readability.

Current (32 digits)
1.0000000116860974230803549289703e-07

Expected:
1.0e-7

Another example.   Original code use 0.2 and 0.8 for the constants and they turn into these monsters.

 float noiseAo = mix(0.75, 0.5 + (0.5 * _noise), 0.20000000298023223876953125 + (0.800000011920928955078125 * direct));

**Comment by s-perron** [comment]
The spir-v binary is storing the value in binary using whatever bits are available to it. The decimal representation is generated by spirv-cross, so you would probably want to ask them for the feature.
