### ISSUE TITLE
Spirv Compliation Error: matrix with stride 8 not satisfying alignment to 16

### ISSUE THREAD

**Issue by HuYuxin** [KhronosGroup/SPIRV-Tools#4880]
After rolling this commit https://github.com/KhronosGroup/SPIRV-Tools/commit/4773879b6846930089fd9c2520662933e65e25ad into ANGLE, some tests failed with below spirv validation error:

member 1 is a matrix with stride 8 not satisfying alignment to 16.

The shader code that results in the above spirv validation error is:

```
Shader: 
struct Data {
    header : u32,
    @align(32) @size(16) field : mat2x2<f32>,
    footer : u32,
}

struct Input {
    header : u32,
    @align(32) data : Data,
    @align(16) footer : u32,
}

struct Output {
    data : mat2x2<f32>
}

struct Status {
    code : u32
}

@group(0) @binding(0) var<uniform> input : Input;
@group(0) @binding(1) var<storage, read_write> output : Output;
@group(0) @binding(2) var<storage, read_write> status : Status;

@compute @workgroup_size(1,1,1)
fn main() {
    if (input.header != 2441245540u) {
        status.code = 100u;
    } else if (input.footer != 422066020u) {
        status.code = 101u;
    } else if (input.data.header != 2695938208u) {
        status.code = 102u;
    } else if (input.data.footer != 1076895760u) {
        status.code = 103u;
    } else {
        status.code = 200u;
        output.data = input.data.field;
    }
}) 
```

I am wondering if we should update the shader code to pass the validation?

**Comment by alan-baker** [comment]
For clarification are you compiling WGSL to SPIR-V or GLSL? If so, it's a known issue (in Tint at least) that the representation of matrices might need to change when used in uniform buffers to satisfy this restriction. See http://crbug.com/tint/1632.

**Comment by s-perron** [comment]
The crbug that Alan referenced is closed, and I don't think there is much we can do anyway. I'll close this bug.
