### ISSUE TITLE
spirv-opt: debugprintf instrumentation reports "Mixed stage shader module not supported"

### ISSUE THREAD

**Issue by natevm** [KhronosGroup/SPIRV-Tools#4892]
This is a continuation of the issue over on the Vulkan Validation Layers repo here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4350

A quick summary is that I'd like to support printf with multiple entry points. This should be doable so long as no entry point calls a common function (which is true if --inline-entry-points-exhaustive is used, which is included by default as part of the -o0 flag).

I believe the code that needs changing is here: https://github.com/KhronosGroup/SPIRV-Tools/blob/0a43a84e02245cca40ce187d1e427a5d0b4f3d13/source/opt/instrument_pass.cpp#L968-L991

So, I believe the logic there should instead ask "do any entry points call a common function? if so, disable printf instrumentation."

@greg-lunarg does that seem right?

**Comment by greg-lunarg** [comment]
> @greg-lunarg does that seem right?

Yes.

**Comment by natevm** [comment]
Okay, cool. Then I might poke around here and see if I can detect common function calls. I'm a little unfamiliar with the code here, but I figure I should be able to work it out. If I can get that working, I can open a PR here. :)

**Comment by greg-lunarg** [comment]
There is a function that traverses the call tree of an entry point function. From that you can build a set of ids of functions that are called. From that, you can do an intersection on the function sets of two entry points.
