### ISSUE TITLE
OpEmitMeshTasksEXT is not considered a terminator instruction

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/SPIRV-Tools#4922]
The SPIR-V spec for mesh shaders states (https://github.com/KhronosGroup/SPIRV-Registry/commit/f7d7e01c18542b34c8ad4c87e751c0d29d6c1899#diff-9d8cf769182417e1989cb51f487a381c2f25f4a714b010b25318dc59578e23ccR160)

> *OpEmitMeshTasksEXT* must be the last instruction in a block.

This makes it a block-terminating opcode, but spirv-val does not treat it as such. It only validates glslang output which is currently invalid and follows up EmitMeshTasksEXT with OpReturn:

https://github.com/KhronosGroup/glslang/issues/3020

**Comment by pmistryNV** [comment]
I will fix this and make the instruction behave similar to other termination instruction which is defined in SPIRV spec section 2.2.5

**Comment by sjfricke** [comment]
@pmistryNV is #4923 not correct then?

**Comment by pmistryNV** [comment]
Yes that is a correct change, Thanks for pointing it out. It also needs an update in the spec https://github.com/KhronosGroup/SPIRV-Registry/pull/166 is under review
