### ISSUE TITLE
Check OpFunctionCall Function operand is an Id of an OpFunction in the same module

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#494]
See 2.16.1 universal rule.

**Comment by ehsannas** [comment]
@dneto0 I think this is covered by this line of code: 
https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/validate_id.cpp#L1490

**Comment by dneto0** [comment]
Indeed.   But just as important, it's covered by a test.  And even better that test checks the emitted message.

I found this one:
TEST_F(ValidateIdWithMessage, OpFunctionCallFunctionBad)
