### ISSUE TITLE
validate_mesh_shading.h missing?

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/SPIRV-Tools#4945]
After commit b53d7a8affabb230a47fb4123b040573a3062d4a, `validate_mesh_shading.cpp` has been added. However, in `BUILD.gn`, there is also a reference to `source/val/validate_mesh_shading.h`, which currently does not exist. This causes a compilation error in ANGLE rolls.

**Comment by aabdolrashidi** [comment]
@sjfricke

**Comment by jcgregorio** [comment]
This error is currently causing our roll of Vulkan into Skia to fail, so +1 for the attached PR.
