### ISSUE TITLE
Dead input elimination doesn't remove corresponding decorations

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/SPIRV-Tools#4949]
When a dead input is eliminated, if it was decorated (such as 'flat'), those decorations are still leftover in the SPIR-V, resulting in a validation error.

**Comment by Keenuts** [comment]
Hi @mbechard, thanks for the finding.
Would you have a sample shader to shader where you can reproduce this?

@greg-lunarg is that's something you could look into since you are actively working on those passes?

**Comment by greg-lunarg** [comment]
@mbechard  @Keenuts Yes, I will fix.

**Comment by greg-lunarg** [comment]
@mbechard Sorry I didn't see this until yesterday.

Is the problem when eliminating a whole variable, or when removing a component from an array or structure?

**Comment by mbechard** [comment]
It was when removing a a variable from a structure. For example I had a 'flat int' in my vertex->pixel struct that was removed by dead input elimination in the pixel shader, but the decoration remained in the SPIR-V.
However since GLSLang now has dead input elimination removed from the pixel shader pass, this isn't currently an issue. However I assume it'll resurface when cross-stage elimination is merged in.

**Comment by greg-lunarg** [comment]
> However I assume it'll resurface when cross-stage elimination is merged in.

Yes. I will fix.

**Comment by greg-lunarg** [comment]
Hmm. I am not seeing the problem with the latest ToT. Here is the frag shader:

```
#version 450

layout(location = 0) in Vertex
{
    vec4 Cd;
    flat int uv;
} iVert;

layout(location = 0) out vec4 fragColor;

void main()
{
    vec4 color = vec4(iVert.Cd);
    fragColor = color;
}

```

I then do:

```
glslangValidator.exe -V --target-env vulkan1.3 -o t.frag.spv t.frag
spirv-opt.exe --eliminate-dead-input-components -o t.frag.edic.spv t.frag.spv
spirv-opt.exe --eliminate-dead-code-aggressive -o t.frag.dce.spv t.frag.edic.spv
```

Both t.frag.edic.spv and t.frag.dce.spv validate without issue.

Let me know if I am not completely recreating your use case.

**Comment by mbechard** [comment]
Hmm ok, let me try and re-find the repro case.

**Comment by mbechard** [comment]
Unable to reproduce anymore, closing this
