### ISSUE TITLE
OSS-Fuzz: Stack-buffer-overflow in spvtools::opt::CompositeInsertToCompositeConstruct

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4953]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51764

@s-perron for info.

**Comment by eddyb** [comment]
Ran into a real-world instance of this and wanted to see if I could narrow it down.

Can confirm https://oss-fuzz.com/download?testcase_id=5667220419641344 reproduces with `spirv-opt -O`.
However, it doesn't reproduce with *just* `spirv-opt --simplify-instructions` (whereas my case does).

I then ran all the `-O` passes *except* `simplify-instructions`, which resulted in a `.spv` file about half the size and which *does* reproduce with just ``spirv-opt --simplify-instructions`.

After throwing all irrelevant instructions I could find, I reduced the actual composites and ended up with:
```llvm
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %1 "main"
               OpExecutionMode %1 OriginUpperLeft
       %uint = OpTypeInt 32 0
     %uint_2 = OpConstant %uint 2
  %_struct_4 = OpTypeStruct %uint %uint
%_arr__struct_4_uint_2 = OpTypeArray %_struct_4 %uint_2
          %6 = OpUndef %_arr__struct_4_uint_2
          %7 = OpUndef %_struct_4
       %void = OpTypeVoid
          %9 = OpTypeFunction %void
          %1 = OpFunction %void None %9
         %10 = OpLabel
         %11 = OpCompositeInsert %_arr__struct_4_uint_2 %uint_2 %6 0 0
         %12 = OpCompositeInsert %_arr__struct_4_uint_2 %7 %11 1
               OpReturn
               OpFunctionEnd
```

Can't think of any other way to shrink this, and replacing the array with an `OpTypeStruct` makes the crash go away.
