### ISSUE TITLE
OSS-Fuzz: Unexpected exit in spvtools::opt::analysis::TypeManager::GetTypeInstruction

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/SPIRV-Tools#4959]
In https://github.com/KhronosGroup/SPIRV-Tools/commit/f9bcc82ec730fd040325405a318919331a0be798 special code was added to the fuzzer to `exit(0)` if the optimizer ran out of IDs. This was to work around spurious fuzzing bugs. It looks like that code is now tripping fuzzer bugs of its own with an `unexpected exit` error.

See: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42589

@afd fyi

**Comment by s-perron** [comment]
The oss-fuzz issues has been closed. I'm not sure how it was resolved, but I do not want to put in more work to get around these types of errors.
