### ISSUE TITLE
False-positive in Windows binary distribution

### ISSUE THREAD

**Issue by Velocity-** [KhronosGroup/SPIRV-Tools#4964]
Even though it's a false positive (or at least, I assume so), I figured I'd share the issue at hand.

Binary was downloaded from the Windows badge on the README, which pointed to `https://storage.googleapis.com/spirv-tools/badges/build_link_windows_vs2017_release.html`, which redirected to `https://storage.googleapis.com/spirv-tools/artifacts/prod/graphics_shader_compiler/spirv-tools/windows-msvc-2017-release/continuous/1845/20221006-073536/install.zip`.

Windows Defender rejected the download with the following message:
![image](https://user-images.githubusercontent.com/3662930/194717284-482e1912-1a4c-48ad-95e0-d1bc327ab422.png)

However, none of the files in `install.zip` are flagged by ClamAV:
```
----------- SCAN SUMMARY -----------
Known viruses: 8639213
Engine version: 0.103.6
Scanned directories: 20
Scanned files: 47
Infected files: 0
Data scanned: 113.35 MB
Data read: 945.11 MB (ratio 0.12:1)
Time: 16.670 sec (0 m 16 s)
Start Date: 2022:10:08 16:14:36
End Date:   2022:10:08 16:14:53
```

For completeness, the archive is attached to this issue. `lib/` directory is removed to be within the `25MB` file limit.
SHA256: `773baa3e4d488574e900b1923373bc32b30577be9b041dc335c11329216d7cb0`

Attachment: [install.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/9739754/install.zip)

**Comment by dneto0** [comment]
Thanks for the heads up.
I'm not sure we can take action.

Our posted binaries are not extensively QA'd.  We encourage folks to build from source or to rely on their own system's package maintainers.

**Comment by s-perron** [comment]
I can reproduce if I download the link you provided, but not if I download the latest package. I'm guessing it was that we just happen to generate the bit pattern somewhere, and it is now gone. Thanks for the heads up.
