### ISSUE TITLE
[Instrumentation] buffer_reference to array with scalar block layout produces incorrect output, incorrect 'Device address out of bounds' errors

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#4992]
See for details: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4577

**Comment by greg-lunarg** [comment]
@s-perron Can you please assign this to @ncesario-lunarg ?

**Comment by greg-lunarg** [comment]
@ncesario-lunarg Indeed, @jeremyg-lunarg has significantly refactored inst_buff_addr_check_pass.cpp, including the GetTypeLength() function indicated as problematic in the original VVL issues. It now always returns 3 * elementSize for vec3 and does not round up to vec4 as it previously did which was causing the problem for scalar layout.

This is not actually "correct" for std140 and std430, but for the purposes of this module, it works for all block layouts including scalar. This is because the result of GetTypeLength() only comes into play for the last member of block. Previously, it was returning 4 * elementSize for vec3 which was causing a memory exception for scalar layout. Now it always returns 3 * elementSize. This is correct for scalar layouts. It is also "correct" for all other layouts because this code does not depend on correctly padding a trailing vec3 in a block and thus does not cause a problem for these layouts.

This is probably just as well since I don't think there is a way to detect scalar layout was used in the generation of a SPIR-V module. We would need to have VVL somehow tell us to use it.

While I have not extensively verified that inst_buff_addr_check_pass.cpp is doing the right thing for the original shader, I think it can be logically concluded that it will and the original problem has been fixed, and no new errors are caused by this change.

I.E. I think this problem is fixed.

**Comment by jeremyg-lunarg** [comment]
closing based on Greg's comment
