### ISSUE TITLE
Should v2022.3 and v2022.4 be listed on https://github.com/KhronosGroup/SPIRV-Tools/releases?

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/SPIRV-Tools#4993]
This is related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4826 It looks like some package maintainers use the releases page to determine which version of this library to distribute.  Currently the most recent release is v2022.2, but v2022.3 and v2022.4 have  been used to make Vulkan SDKs.  Shouldn't those tags be considered to be releases? Thanks!

**Comment by Keenuts** [comment]
Thanks for pointing out! Yes it should, that was a mistake.

**Comment by Keenuts** [comment]
added the releases! Sorry about that!

**Comment by jeremyg-lunarg** [comment]
Thank you!
