### ISSUE TITLE
Optimization pass doesn't seem to handle all conditions properly

### ISSUE THREAD

**Issue by sugoi1** [KhronosGroup/SPIRV-Tools#5005]
It looks like The fix for this [issue](https://github.com/KhronosGroup/SPIRV-Tools/issues/4996) didn't fix all the problems with the recent SPIR-V Tools changes. Here's the current issue:

When running [GLSLTest_ES3.AssignAssignmentToSwizzled/ES3_Vulkan_SwiftShader](https://ci.chromium.org/ui/p/chromium/builders/ci/linux-swangle-tot-swiftshader-x64/145079/overview), we still get a failure. The [GLSL shader](https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/tests/gl_tests/GLSLTest.cpp;l=9387) is fairly simple:
```
#version 300 es
precision highp float;
out vec4 my_FragColor;

uniform float uzero;

vec3 fun(float s, float v)
{
    vec3 r = vec3(0);
    if (s < 1.0) {
        r.x = r.y = r.z = v;
        return r;
    }
    return r;
}

void main()
{
    my_FragColor.a = 1.0;
    my_FragColor.rgb = fun(uzero, 1.0);
}
```

Here's the SPIR-V code, pre and post optimization:
[Post_op_spirv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/10107975/Post_op_spirv.txt)
[Pre_opt_spirv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/10107976/Pre_opt_spirv.txt)

The pre-optimized code contains a `OpFOrdLessThan` statement, which corresponds to the `if (s < 1.0) {` glsl statement above. The post optimization code appears to remove the entire `fun` function, leaving only an `OpPhi` statement, which doesn't yield the same result.

**Comment by spencer-lunarg** [comment]
while I have this part of the code cached in my head, I can take a look at it this week

**Comment by sugoi1** [comment]
Interesting note:
If I change:
`r.x = r.y = r.z = v;`
to
`r = vec3(v);`
then the `OpFOrdLessThan` statement no longer gets optimized out.

**Comment by sugoi1** [comment]
Friendly ping: This is starting to block quite a few projects, could this be prioritized, please?

**Comment by sugoi1** [comment]
And another SPIRV-Tools crash has been reported: https://crbug.com/1395415

**Comment by spencer-lunarg** [comment]
sorry @sugoi1 will look into today, got tied up last week

**Comment by spencer-lunarg** [comment]
Ok so the `--ccp` pass is the issue here (so indeed related to the other change) and breaking it down here are the before and after where it incorrectly sets the function (now inlined) return value to always be `vec3(0.0)`

[after_ccp.spvasm.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/10150158/after_ccp.spvasm.txt)
[before_ccp.spvasm.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/10150159/before_ccp.spvasm.txt)

Will add test and get a fix in now
