### ISSUE TITLE
CYGWIN support

### ISSUE THREAD

**Issue by Ethatron** [KhronosGroup/SPIRV-Tools#508]
It's trivial to support. Add this to CMakeLists.txt:

elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "CYGWIN")
  add_definitions(-DSPIRV_WINDOWS)

And then in "source/binary.cpp", kill the exotic strnlen:

      const size_t string_num_content_bytes =
          std::min(strlen(string), remaining_input_bytes);

**Comment by dneto0** [comment]
What is your configuration?
- what Cmake generator?  Unix makefiles?
- what compiler?  GCC 5.4.0 installed from within Cygwin?

**Comment by dneto0** [comment]
That replacement for strnlen is not safe in the way I want it to be.  Given malicious input, it could cause a buffer overrun.  I'll investigate an alternative.

**Comment by dneto0** [comment]
Hi @Ethatron: Are you using googletest under Cygwin?  I have not been able to make googletest work for me under Cygwin with GCC.  It won't pass its own self-tests, and it causes at least one crash in the tests for SPIRV-Tools.
See #510 for details.

Let me know if you have more success than I do.

**Comment by Ethatron** [comment]
@dneto0 The configuration was all "lastest" from cygwin: cmake from cygwin and latest gcc
I did only go for the "dis" command, and it worked AFAIR.
