### ISSUE TITLE
Redundant loads not eliminated

### ISSUE THREAD

**Issue by kuhar** [KhronosGroup/SPIRV-Tools#5086]
Hello,

I have a set of compute shaders that broadcast components of a loaded vector to calculate outer product. I'm surprised to see that that each 'broadcast' ends up generating 4 loads:    

GLSL repro:
```glsl
#version 450
layout(binding=0) buffer InputA { vec4 x[]; } inputA;
layout(binding=1) buffer InputB { vec4 x[]; } inputB;
layout(binding=2) buffer Output { vec4 x[]; } outputO;

void main() {
  vec4 A = vec4(inputA.x[0].x,inputA.x[0].x, inputA.x[0].x, inputA.x[0].x);
  vec4 B = inputB.x[0];
  outputO.x[0] = A * B;
}
```

SPIR-V repro:
```
; SPIR-V
; Version: 1.4
; Generator: Khronos SPIR-V Tools Assembler; 0
; Bound: 36
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %2 "main"
               OpExecutionMode %2 LocalSize 1 1 1
               OpDecorate %_runtimearr_v4float ArrayStride 16
               OpMemberDecorate %_struct_4 0 Offset 0
               OpDecorate %_struct_4 BufferBlock
               OpDecorate %5 DescriptorSet 0
               OpDecorate %5 Binding 0
               OpDecorate %_runtimearr_v4float_0 ArrayStride 16
               OpMemberDecorate %_struct_7 0 Offset 0
               OpDecorate %_struct_7 BufferBlock
               OpDecorate %8 DescriptorSet 0
               OpDecorate %8 Binding 1
               OpDecorate %_runtimearr_v4float_1 ArrayStride 16
               OpMemberDecorate %_struct_10 0 Offset 0
               OpDecorate %_struct_10 BufferBlock
               OpDecorate %11 DescriptorSet 0
               OpDecorate %11 Binding 2
       %void = OpTypeVoid
         %13 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_runtimearr_v4float = OpTypeRuntimeArray %v4float
  %_struct_4 = OpTypeStruct %_runtimearr_v4float
%_ptr_Uniform__struct_4 = OpTypePointer Uniform %_struct_4
          %5 = OpVariable %_ptr_Uniform__struct_4 Uniform
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
       %uint = OpTypeInt 32 0
     %uint_0 = OpConstant %uint 0
%_ptr_Uniform_float = OpTypePointer Uniform %float
%_runtimearr_v4float_0 = OpTypeRuntimeArray %v4float
  %_struct_7 = OpTypeStruct %_runtimearr_v4float_0
%_ptr_Uniform__struct_7 = OpTypePointer Uniform %_struct_7
          %8 = OpVariable %_ptr_Uniform__struct_7 Uniform
%_ptr_Uniform_v4float = OpTypePointer Uniform %v4float
%_runtimearr_v4float_1 = OpTypeRuntimeArray %v4float
 %_struct_10 = OpTypeStruct %_runtimearr_v4float_1
%_ptr_Uniform__struct_10 = OpTypePointer Uniform %_struct_10
         %11 = OpVariable %_ptr_Uniform__struct_10 Uniform
          %2 = OpFunction %void None %13
         %25 = OpLabel
         %26 = OpAccessChain %_ptr_Uniform_float %5 %int_0 %int_0 %uint_0
         %27 = OpLoad %float %26
         %28 = OpLoad %float %26
         %29 = OpLoad %float %26
         %30 = OpLoad %float %26
         %31 = OpCompositeConstruct %v4float %27 %28 %29 %30
         %32 = OpAccessChain %_ptr_Uniform_v4float %8 %int_0 %int_0
         %33 = OpLoad %v4float %32
         %34 = OpFMul %v4float %31 %33
         %35 = OpAccessChain %_ptr_Uniform_v4float %11 %int_0 %int_0
               OpStore %35 %34
               OpReturn
               OpFunctionEnd
```

Running `spirv-opt repro.spvasm -O -o -` does not eliminate loads `%28`-`%30` like I would expect. Is this simply a missing optimization, a more fundamental limitation, or am I holding it wrong?

**Comment by greg-lunarg** [comment]
This is surprising. I will investigate.

**Comment by greg-lunarg** [comment]
Thinking about this for three more minutes, this is not quite as surprising as I first thought.

FWIW, I wrote the initial implementation of store/load elimination, so I think I speak here with some authority.

In general, loads based on access chains require additional aliasing analysis to be sure their value is not changed by an intervening store. Buffers are a special case that do not require aliasing analysis because they are generally not both readable and writable in the same shader. But I don't recall writing or seeing such logic in the store/load elimination passes. I think in general only stores  and loads of OpVariables are currently eliminated.

I will finally add that I think that it is slightly unusual to see a reference like `inputA.x[0].x` replicated four times in a row in the same line. I know I would have captured `inputA.x[0].x` in a local temp and replicated the temp. The goal of spirv-opt was to optimize common code sequences. To spend time to improve such an uncommon code sequence would be very low priority in my mind unless your code base is full of such sequences.

I think I have answered your question, so will close. If you wish to re-open as a request for such sequences to be optimized, you are welcome, although I would consider such an issue as a request for enhancement rather than a bug fix.

**Comment by kuhar** [comment]
Thanks for looking into this, @greg-lunarg.

In my actual code, I do have a local variable but still end up with 4 loads: https://github.com/google/uVkCompute/blob/5b1be93cf6af0b2b88b57ad851e13fe5a3b30015/benchmarks/matmul/matmul_tiled_i32.glsl#L68.

(You can compile this with `glslc -S -O -fshader-stage=compute matmul_tiled_i32.glsl -o - -DTILE_M=8 -DTILE_N=64 -DTILE_K=8 -DWG_X=16 -DWG_Y=1`)

Introducing a local variable in the repro attached to the issue does solve the problem, so I guess it depends on whether you would consider this a shaderc issue or a common code sequence.

Feel free to re-close the issue.

**Comment by greg-lunarg** [comment]
Here is the loop you refer to in your last comment:

```
[[unroll]] for (uint i = 0; i < C_ROWS; ++i) {
      uint gi = gID.y * 8 + laneId.y + i * 1;
      uint gk = k / 4;
      [[unroll]] for (uint kk = 0; kk < 8 / 4; ++kk) {
        i32vec4 A = inputA.x[coordToOffset(gi, gk + kk, strideA / 4)];
        [[unroll]] for (uint j = 0; j < C_COLS; ++j) {
          C[i][j] += i32vec4(A.x, A.x, A.x, A.x) * (B[0 + 4 * kk][j]);
          C[i][j] += i32vec4(A.y, A.y, A.y, A.y) * (B[1 + 4 * kk][j]);
          C[i][j] += i32vec4(A.z, A.z, A.z, A.z) * (B[2 + 4 * kk][j]);
          C[i][j] += i32vec4(A.w, A.w, A.w, A.w) * (B[3 + 4 * kk][j]);
        }
      }
    }
```

There are four loads of C[i][j], but they cannot be merged because there are intervening stores to C[i][j] that need to be respected.

Still, I agree that asking the optimizer to eliminate all but one load and store of C[i][j] here is reasonable. While one could again argue that C[i][j] here could be scalarized by hand, it is entirely possible and common for such sequences to arise in the SPIR-V from optimizer unrolling.

So I think this is a valid request for enhancement.

**Comment by kuhar** [comment]
> There are four loads of C[i][j], but they cannot be merged because there are intervening stores to C[i][j] that need to be respected.

I meant the 4 loads of each `A.*` that feed into composite construct:
```
       %1779 = OpLoad %int %191                                                    
       %1781 = OpLoad %int %191      
       %1783 = OpLoad %int %191         
       %1785 = OpLoad %int %191      
       %1786 = OpCompositeConstruct %v4int %1779 %1781 %1783 %1785                 
       %1791 = OpIMul %v4int %1786 %714
       %1794 = OpIAdd %v4int %1758 %1791
       %1797 = OpLoad %int %213                                                    
       %1799 = OpLoad %int %213        
       %1801 = OpLoad %int %213         
       %1803 = OpLoad %int %213         
       %1804 = OpCompositeConstruct %v4int %1797 %1799 %1801 %1803
       %1809 = OpIMul %v4int %1804 %735                                            
       %1812 = OpIAdd %v4int %1794 %1809
       %1815 = OpLoad %int %235                                                    
       %1817 = OpLoad %int %235        
       %1819 = OpLoad %int %235         
       %1821 = OpLoad %int %235      
       %1822 = OpCompositeConstruct %v4int %1815 %1817 %1819 %1821                 
       %1827 = OpIMul %v4int %1822 %756
       %1830 = OpIAdd %v4int %1812 %1827
       %1833 = OpLoad %int %258                                                    
       %1835 = OpLoad %int %258        
       %1837 = OpLoad %int %258         
       %1839 = OpLoad %int %258         
       %1840 = OpCompositeConstruct %v4int %1833 %1835 %1837 %1839
       %1845 = OpIMul %v4int %1840 %777                                            
       %1848 = OpIAdd %v4int %1830 %1845
       %1864 = OpLoad %uint %143                                                   
       %1865 = OpIMul %uint %1864 %uint_8 
       %1867 = OpLoad %uint %146        
       %1868 = OpIAdd %uint %1865 %1867
       %1870 = OpIAdd %uint %1868 %uint_6                         
       %1877 = OpIMul %uint %172 %1870
       %1878 = OpIAdd %uint %1877 %154
       %1879 = OpAccessChain %_ptr_Uniform_v4int %168 %int_0 %1878
       %1880 = OpLoad %v4int %1879
               OpStore %164 %1880
```

**Comment by greg-lunarg** [comment]
If I compile your 2nd shader with glslangValidator -Os, the SPIR-V I get does not have these OpLoads. So I think the problem might be in the optimization recipe used by shaderc and/or spirv-opt for -O, rather than a defect in any of the passes.

**Comment by s-perron** [comment]
Most passes that deal with removing redundant load (local-single-store, ssa-rewrite, local-single-block-elim) work on function scope variables, maybe private storage class. There are the redundancy elimination passes, but they only work for read-only storage, and the first example is not considered read-only.

The loads in the second example are cause by the memory model capability/extension not being in the allow list of some of the passes. This should be an easier fix.

Which one do you really care about?
