### ISSUE TITLE
Add bot to test CYGWIN support.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#510]
Blocked by https://github.com/KhronosGroup/SPIRV-Tools/projects/2#card-1150608

**Comment by dneto0** [comment]
No longer blocked.

This would be an Appveyor configuration.  It has Cygwin installed, but it's not clear if Cygwin's GCC is installed.  Perhaps we should assume use MinGW?
It depends on what's desired for #508

**Comment by dneto0** [comment]
This Appveyor blog post explains what's installed with Cygwin: https://www.appveyor.com/updates/2015/05/30/
Yes, it includes g++

**Comment by dneto0** [comment]
I've made it a long way, but am blocked by a segfault when using mocking in a test.

* Had to work around the fact that googletest fails to compile under CYGWIN with G++ when using -std=c++11.  Need to use -std=gnu++11 instead.

* Test crashes (SEGV) at https://github.com/dneto0/SPIRV-Tools/blob/wip-support-cygwin-with-gmock/test/binary_parse_test.cpp#L235   I also crashes if I just invoke EXPECT_HEADER(1) at that line.  So it's seems intrinsically a problem with mocking, and not the code being tested, since we didn't get to it yet.

I'll pause at this point.

**Comment by dneto0** [comment]
gtest and gmock fail their own tests when I build them under CYGWIN with GCC.

```
cmake -G Ninja -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=RelWithDebInfo .. -Dgmock_build_tests=ON -Dgtest_Build_tests=ON
ninja
ctest --output-on-failure
```
yields these sugithmmary results:

**Comment by dneto0** [comment]
Blocked by CYGWIN support in gtest.
I should probably file an issue against googletest for this, or look for an existing issue.

**Comment by s-perron** [comment]
We cannot claim to support cygwin if our deps do not. I do not want to become the cygwin tester of abseil.

**Comment by s-perron** [comment]
This is what google projects usually support:

https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md
