### ISSUE TITLE
repair spv shader

### ISSUE THREAD

**Issue by BodinoMing** [KhronosGroup/SPIRV-Tools#5101]
Is there  any tool to change spir-v shader, so I can insert and delete some instructions

**Comment by s-perron** [comment]
The best you could do would be to disassemble (`spirv-dis`) the shader. Modify the assembly using your favorite text editor, and then reassemble using `spirv-as`.

```
spirv-dis t.spv -o t.spvasm
vim t.spvasm # Make the changes you want.
spirv-as t.spvasm -o t.spv --target-env spv1.1
```

Note that you might need a different target environment. You can get the right environment by looking at the top of t.spvasm that gives the spirv version that you want:

```
; SPIR-V
; Version: 1.6
; Generator: Khronos SPIR-V Tools Assembler; 0
; Bound: 14
; Schema: 0
```
