### ISSUE TITLE
CI-android & other google CI logs not readable for external contributors

### ISSUE THREAD

**Issue by Keenuts** [KhronosGroup/SPIRV-Tools#5160]
This CI logs are only readable for googlers. Which reduces it's utility.
Should be fixed.

**Comment by greg-lunarg** [comment]
@Keenuts Isn't this a bug?

**Comment by Keenuts** [comment]
Yeah, better label

**Comment by Keenuts** [comment]
Should be fixed now. Let me know if that's not the case (#5186)
