### ISSUE TITLE
Asserts in SpirvToolsAnalyzeDeadOutputStores() when using nonSemantic debug information

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/SPIRV-Tools#5163]
When using the SpirvToolsAnalyzeDeadOutputStores() workflow, the attached .spv which was generated with nonSemanticDebugInfo/Source = true will raise asserts in SpirvToolsAnalyzeDeadOutputStores(). The same source shader with generateDebugInfo = true, but nonSemantic* = false, will not raise asserts. Added .txt extension so github would let me post it.

Thanks
[preOpt2056924001632.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/11004349/preOpt2056924001632.spv.txt)

**Comment by greg-lunarg** [comment]
@jeremy-lunarg

**Comment by jeremy-lunarg** [comment]
@mbechard Just started looking at this. I think the fix is simple. Should have a PR up shortly.
