### ISSUE TITLE
‘TileImageEXT’ is not a member of ‘spv::StorageClass’ Build fail

### ISSUE THREAD

**Issue by romanstingler** [KhronosGroup/SPIRV-Tools#5197]
`/home/roman/.cache/yay/spirv-tools-git/src/SPIRV-Tools/source/val/validate_annotation.cpp: In function ‘spv_result_t spvtools::val::{anonymous}::ValidateDecorationTarget(spvtools::val::ValidationState_t&, spv::Decoration, const spvtools::val::Instruction*, const spvtools::val::Instruction*)’:
/home/roman/.cache/yay/spirv-tools-git/src/SPIRV-Tools/source/val/validate_annotation.cpp:206:38: error: ‘TileImageEXT’ is not a member of ‘spv::StorageClass’
  206 |             sc != spv::StorageClass::TileImageEXT) {
      |                                      ^~~~~~~~~~~~
make[2]: *** [source/CMakeFiles/SPIRV-Tools-shared.dir/build.make:474: source/CMakeFiles/SPIRV-Tools-shared.dir/val/validate_annotation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1091: source/CMakeFiles/SPIRV-Tools-shared.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
make: Leaving directory '/home/roman/.cache/yay/spirv-tools-git/src/build'
`

**Comment by vince6794** [comment]
Still have the same problem. 
Did you manage to solve it?

**Comment by romanstingler** [comment]
@vince6794 unfortunately not. I stopped trying to build it

**Comment by alan-baker** [comment]
Did you grab the updated SPIRV-Headers? When you sync to the listed deps does it still fail?

**Comment by vince6794** [comment]
As @alan-baker suggested
Installing `spirv-tools-git` solved the problem.
It's now correctly building

Thanks.

**Comment by s-perron** [comment]
What @alan-baker said.  Rerun `utils/git-sync-deps`, and it should be good.
