### ISSUE TITLE
Build SPIRV-Tools from source without Python

### ISSUE THREAD

**Issue by eugeneko** [KhronosGroup/SPIRV-Tools#5202]
The OSS project I am working on uses "build thirdparties from source" policy, but I don't want to introduce Python as build requirement either.
Is it viable to somehow pre-generate and deploy all the stuff generated via scripts? Any pitfalls?
I assume that any specific version of SPIRV-Tools+SPIRV-Headers will always yield the same artifacts, but maybe I am wrong and they are somehow compiler- or platform- dependent?

Also, would it be an acceptable PR if I made an option to cache codegen artifacts, or this project is not interested in supporting this usecase?

**Comment by eugeneko** [comment]
This is the draft of the solution I did for my project, in case someone have similar issue:

https://github.com/rbfx/SPIRV-Tools/commit/bf0d80190f38e36807b225cad1c7109c0fc570ab

I didn't test it much, but it works okay-ish.
Re-generation is ugly, I have to delete cache folder, configure, build, and configure again.
But when the cache folder is ready (which is *always* unless I update my thirdparties) it works fine.

**Comment by s-perron** [comment]
Sorry, but we are not interested in supporting this.

**Comment by eugeneko** [comment]
@s-perron That's understandable, I'll keep the branch in my fork alive if anyone ever needs this behavior.

**Comment by dneto0** [comment]
Thanks for asking in advance.  :-)
