### ISSUE TITLE
Support for arrays of textures and images in convert-to-sampled-image pass

### ISSUE THREAD

**Issue by Attractadore** [KhronosGroup/SPIRV-Tools#5213]
Currently, the convert-to-sampled-image pass only works for single samplers and images.
I would like to extend this pass to support arrays of samplers and images, as this is required for [[vk::combinedImageSampler]] support for arrays of samplers and textures in DXC, for which there has been community interest (https://github.com/microsoft/DirectXShaderCompiler/issues/4988, https://github.com/microsoft/DirectXShaderCompiler/issues/5092).

My vision for the feature is as follows:
* If both there is both a dynamic array of images and a dynamic array of samplers bound to the specified set + slot, combine them into a dynamic array of sampled images
* Same for fixed-sized arrays is their sizes match, otherwise it's an error
* If only an array of images samplers or and array of images is bound to the specified set + slot, convert it into an array of sampled images

**Comment by s-perron** [comment]
See https://github.com/microsoft/DirectXShaderCompiler/issues/5092 for plans on how this will be done.
