### ISSUE TITLE
Add Abseil as an external dependency for testing.

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#5233]
The latest version of RE2 depends on Abseil. We will have to start depending on Abseil if we are going to continue to update RE2.

For now, we cannot simply add Abseil as another source dependency because RE2 uses `find_package` to get Abseil, and we would prefer to avoid that if possible. See https://github.com/google/re2/issues/427.

In the short term we should,

- [x] Disable the auto roller or RE2.
- [x] Wait for RE2 to respond to the issue above.
- [x] Add Abseil as a dependency, and update RE2
- [x] Restart the autoroller for RE2.

**Comment by LW-archlinux** [comment]
Latest revision e0936b6 fails to build with this warning :

```
CMake Error at external/CMakeLists.txt:106 (add_subdirectory):
  add_subdirectory given source "abseil_cpp" which is not an existing
  directory.
```

Posting here seemed a better choice then opening  a new issue.

**Comment by s-perron** [comment]
Did you rerun git-sync-deps to checkout abseil in "external" directory?

**Comment by LW-archlinux** [comment]
No, didn't need that command at all sofar.

I recentIy took over maintenance for the [spirv-tools-git](https://aur.archlinux.org/packages/spirv-tools-git)  archlinux aur package.. Until now the only external component needed was SPIRV-Headers sources which was switched to be taken from /usr .

I did re-read the readme and noticed it mentions the urls & folder locations for several external components under "getting the source" .
  Will add them & abseil and report back.

**Comment by s-perron** [comment]
Are you building the spirv-tools tests? If you are not building the tests, then you should not need abseil.

**Comment by LW-archlinux** [comment]
I was building the tests, disabled now by adding `-D SPIRV_SKIP_TESTS=ON` .
The build now finishes succesfully.

Is running the tests important for end users ?

**Comment by s-perron** [comment]
> Is running the tests important for end users ?

That is a call you will have to make. You are distributing the package.

**Comment by LW-archlinux** [comment]
Added tests to the aur package, thanks for the help.
