### ISSUE TITLE
Optimization passes produce mismatching HLSL IO unless preserve_interface is true.

### ISSUE THREAD

**Issue by eugeneko** [KhronosGroup/SPIRV-Tools#5266]
I optimize shaders on individual basis, not as a program. Therefore I get mismatching in-out signatures for Vertex and Pixel shaders, unless I register passes myself with preserve_interface=true.

Is that intended behavior? If so, would you consider exposing preserve_interface=true in Register*Passes functions, so they are useable for people like me? I could make PR if that's okay.

**Comment by s-perron** [comment]
In what way do they mismatch? As long as the inputs to the pixel shader are a subset of the outputs of the vertex shader there is no problem. See https://github.com/KhronosGroup/SPIRV-Tools/pull/4629 for the reasons for that change.

We could create a way to expose it in the `Register*Passes` functions. However, because these are public interfaces you cannot change the interface, but you can add new ones. That is, you cannot add a bool parameter, even if it has a default value.

**Comment by eugeneko** [comment]
@s-perron I am sorry that I don't have an example at hand. I will share it as soon I can.

As far as I understand, HLSL generated by SPIRV-Cross generates IO interface using sequential indexes.

So, the outputs of vertex shader are TEXCOORD0..N, and the inputs of pixel shader are TEXCOORD0..N, and they are matched by index, because there is nothing else to match by.
When pixel shader "optimizes out" its inputs, the rest of inputs don't align anymore.
How would "subset matching" work in this case?

PS: I don't assign "layout location" in my GLSL source code.

**Comment by s-perron** [comment]
Okay, this looks like a bigger issues in how the various tools work together. I might want a full end-to-end example, so that we can correctly identify which tool is doing something wrong. In spir-v, the "location" decoration is what is used to match the IO interface. If spir-v cross is not considering the location when declaring the variables, that might be the problem. I would have to see what is happening to know for sure.

**Comment by eugeneko** [comment]
@s-perron okay I have an update.
Apparently, semantics are correctly mapped indeed. However, they are just irrelevant for DX11, and DX11 just maps input and output by index regardless of provided semantics. 

Vertex shader:
```
#version 450
layout(binding=1) uniform Camera
{
    mat4 cViewProj;
};
layout(binding=5) uniform Object
{
    mat4 cModel;
};

in vec4 iPos;
in vec2 iTexCoord;
in vec4 iColor;
// out vec4 vUnused; -- bad
out vec2 vTexCoord;
out vec4 vColor;
out vec4 vUnused;

void main()
{
    vec3 worldPos = (iPos * cModel).xyz;
    gl_Position = vec4(worldPos, 1.0) * cViewProj;

    vTexCoord = iTexCoord;
    vColor = iColor;
    vUnused = vec4(0.0, 0.0, 0.0, 0.0);
}
```

Pixel shader:
```
#version 450

layout(binding=0) uniform sampler2D sDiffMap;

// in vec4 vUnused; -- bad
in vec2 vTexCoord;
in vec4 vColor;
in vec4 vUnused;
out vec4 _fragData[1];

void main()
{
    vec4 diffInput = texture(sDiffMap, vTexCoord);
    if (diffInput.a < 0.5)
        discard;
    _fragData[0] = vColor * diffInput;
}
```

These shaders work as is, but if I move vUnused to be the first one, everything stops working with this error:

```
D3D11 ERROR: ID3D11DeviceContext::Draw: Vertex Shader - Pixel Shader linkage error: Signatures between stages are incompatible. Semantic 'TEXCOORD' is defined for mismatched hardware registers between the output stage and input stage. [ EXECUTION ERROR #343: DEVICE_SHADER_LINKAGE_REGISTERINDEX]
```

Generated HLSL vertex shader:
```
//  DIFFMAP URHO3D_USE_CBUFFERS VERTEXCOLOR
cbuffer Object : register(b5)
{
    row_major float4x4 _18_cModel : packoffset(c0);
};

cbuffer Camera : register(b1)
{
    row_major float4x4 _40_cViewProj : packoffset(c0);
};


static float4 gl_Position;
static float4 iPos;
static float2 vTexCoord;
static float2 iTexCoord;
static float4 vColor;
static float4 iColor;
static float4 vUnused;

struct SPIRV_Cross_Input
{
    float4 iPos : POSITION0;
    float2 iTexCoord : TEXCOORD0;
    float4 iColor : COLOR0;
};

struct SPIRV_Cross_Output
{
    float4 vUnused : TEXCOORD0;
    float2 vTexCoord : TEXCOORD1;
    float4 vColor : TEXCOORD2;
    float4 gl_Position : SV_Position;
};

#line 22 ""
void vert_main()
{
#line 22 ""
#line 23 ""
    gl_Position = mul(_40_cViewProj, float4(mul(_18_cModel, iPos).xyz, 1.0f));
#line 25 ""
    vTexCoord = iTexCoord;
#line 26 ""
    vColor = iColor;
#line 27 ""
    vUnused = 0.0f.xxxx;
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    iPos = stage_input.iPos;
    iTexCoord = stage_input.iTexCoord;
    iColor = stage_input.iColor;
    vert_main();
    SPIRV_Cross_Output stage_output;
    stage_output.gl_Position = gl_Position;
    stage_output.vTexCoord = vTexCoord;
    stage_output.vColor = vColor;
    stage_output.vUnused = vUnused;
    return stage_output;
}
```

Generated HLSL pixel shader:
```
Texture2D<float4> sDiffMap : register(t0);
SamplerState _sDiffMap_sampler : register(s0);

static float2 vTexCoord;
static float4 _fragData[1];
static float4 vColor;

struct SPIRV_Cross_Input
{
    float2 vTexCoord : TEXCOORD1;
    float4 vColor : TEXCOORD2;
};

struct SPIRV_Cross_Output
{
    float4 _fragData[1] : SV_Target0;
};

#line 41 ""
void frag_main()
{
#line 41 ""
    float4 _20 = sDiffMap.Sample(_sDiffMap_sampler, vTexCoord);
#line 42 ""
    if (_20.w < 0.5f)
    {
#line 43 ""
        discard;
    }
#line 44 ""
    _fragData[0] = vColor * _20;
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    vTexCoord = stage_input.vTexCoord;
    vColor = stage_input.vColor;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output._fragData = _fragData;
    return stage_output;
}
```

These shaders are passed to `D3DCompile` with `D3DCOMPILE_OPTIMIZATION_LEVEL3`.

**Comment by s-perron** [comment]
Yes that is the same problem that you are having. I think the best (only viable solution) is to not remove unused inputs. Then it becomes the responsibility of the shader writer to make sure that the inputs and outputs match across shader stages. Then spirv-cross should be able to create the same struct in the HLSL.

Please go ahead with the spirv-opt change discussed at the start.
