### ISSUE TITLE
Incorrect validation of OpPtrAccessChain  and OpInBoundsPtrAccessChain 

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-Tools#532]
For `OpPtrAccessChain` and `OpInBoundsPtrAccessChain` SPIR-V specification says that word count for these instructions is "5 + variable". It means that minimum size of the instruction is 5 words, i.e. these instructions without indexes are valid.
But in this case the validator reports "No Indexes were passed to OpInBoundsPtrAccessChain” error.
I think indexes operands for these 2 instructions should be optional.

[SPIRV to reproduce the problem](https://github.com/KhronosGroup/SPIRV-Tools/files/716849/tmp.zip)

**Comment by ehsannas** [comment]
Thanks Alexey for pointing this out. I will fix this shortly.

**Comment by dneto0** [comment]
I made https://github.com/KhronosGroup/SPIRV-Tools/pull/533 out of @ehsannas' change.
I reviewed it and pushed it into master.
