### ISSUE TITLE
spirv-val: Not handling arrays correctly for component word

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/SPIRV-Tools#5328]
```glsl
// Error
layout(location=0, component = 0) out float[8] x;
layout(location=1, component = 0) out float y;

// Error
layout(location=0, component = 0) out float[8] x;
layout(location=2, component = 0) out float y;

// No Error
layout(location=0, component = 0) out float[8] x;
layout(location=1, component = 1) out float y;
```

Seems the component being non-zero breaks the overlap check

**Comment by alan-baker** [comment]
From [location assignment](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#interfaces-iointerfaces-locations) in Vulkan:
> If a declared input or output is an array of size n and each element takes m Location slots, it will be assigned m × n consecutive Location slots starting with the specified Location.

`x` will consume 8 locations starting from 0 (float takes a single location). Within each location, it only consumes component 0. So `y` does not conflict with `x`. You should be able to does something like:
```
layout(location=0, component=0) out float[8] out1;
layout(location=0, component=1) out float[4] out2;
layout(location=4, component=1) out float[4] out3;
layout(location=0, component=2) out float64_t out4;
```
All components of location 0 are consumed. Components 0 and 1 of locations 1 through 7 are consumed.

**Comment by spencer-lunarg** [comment]
yes, sorry, I realize looking at now I just gave `float` ... idk why I viewed these as `vec4`
