### ISSUE TITLE
BUILD.gn missing the new trim_capabilities_pass.h/cpp files

### ISSUE THREAD

**Issue by romanl-g** [KhronosGroup/SPIRV-Tools#5350]
trim_capabilities_pass.h/cpp files added in
https://github.com/KhronosGroup/SPIRV-Tools/commit/35d8b05de4212276d03a5d67201398fd49849896
`trim_capabilities_pass.h` is included from `source/opt/passes.h` but the BUILD.gn wasn't updated which broke ANGLE tooling
```
 third_party/vulkan-deps/spirv-tools/src/source/opt/passes.h: Included file must be listed in the GN target or its public dependency: b\'source/opt/trim_capabilities_pass.h\'\nTraceback (most recent call last):\n  File "/b/s/w/ir/cache/builder/presubmit/angle/scripts/export_targets.py
```

**Comment by romanl-g** [comment]
@Keenuts

**Comment by Keenuts** [comment]
Arf, thanks for flagging. A CI should probably catch this kind of issues on our end.

**Comment by romanl-g** [comment]
Yeah that would be great. Are there no BUILD.gn builds on CI?

**Comment by Keenuts** [comment]
No... Shaderc's CI is using cmake, and the android one too.
Seems like only bazel and cmake are tested.
