### ISSUE TITLE
Invalid text-SPIR-V generated for StorageUniformBufferBlock16 / StorageBuffer16BitAccess.

### ISSUE THREAD

**Issue by Keenuts** [KhronosGroup/SPIRV-Tools#5354]
Reading: https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_16bit_storage.html

It seems that:
- StorageUniformBufferBlock16 capability is added by the SPV_KHR_16bit_storage for SPIR-V < 1.3
- It doesn't require/enable StorageBuffer16BitAccess
- **If** SPV_KHR_storage_buffer_storage_class is enabled, then StorageBuffer16BitAccess replaces StorageUniformBufferBlock16.

Assembling this module with `spirv-as --target-env spv1.1`
```python
            OpCapability Shader
            OpCapability Float16
            OpCapability StorageUniformBufferBlock16
            OpExtension "SPV_KHR_16bit_storage"
            OpMemoryModel Logical GLSL450
            OpEntryPoint GLCompute %2 "main"
            OpDecorate %struct BufferBlock
    %void = OpTypeVoid
    %half = OpTypeFloat 16
  %struct = OpTypeStruct %half
     %ptr = OpTypePointer Uniform %struct
       %1 = OpTypeFunction %void
       %2 = OpFunction %void None %1
       %3 = OpLabel
            OpReturn
            OpFunctionEnd
```

Yields the correct SPIR-V module:
 - the OpCapability is encoded as `2 17 4433` (size=2, opcode=17, capability=4433).

But when disassembling, the capability "StorageUniformBufferBlock16" becomes "StorageBuffer16BitAccess", but the header still marks SPIR-V 1.1.

This seems to be cause by multiple reasons:

SPIRV-Headers: the headers only has the 16bit_storage extension listed under StorageBuffer16BitAccess. From the spec, this seems wrong, as without the SPV_KHR_storage_buffer_class, this capability is not available.

But fixing the header is not enough:
The way the disassembler works is by using the generated grammar tables. Mostly using spvOperandTableNameLookup.
This function takes the SPIR-V environment as input, but doesn't know about the active extensions.
This means it takes the first entry matching the numerical ID 4433 (16BitAccess), and prints it.
What should be done instead is look at the enabled extensions, and depending on this, print the correct operand.

The generated binary is still correct, but this bug breaks some filecheck tests using the disassembler to check some capabilities.

**Comment by alan-baker** [comment]
The names are a matter of convenience only. The token numbers are the only thing that matters. The disassembler is meant to be as stateless as possible. I don't think we should complicate things by trying to pick the best spelling for a token number. The test issue is a minor inconvenience (in my opinion).

**Comment by dneto0** [comment]
Like @alan-baker said, the token numbers are normative.  The text format of SPIR-V is a convention and the strings are not what matters.

The diassembler takes the first name mentioned in the tables, and order is preserved when coming from the .json grammar file.

I don't want to complicate the assembler or the disassembler.

**Comment by dneto0** [comment]
> but this bug breaks some filecheck tests using the disassembler to check some capabilities.

The tests should be updated, with a comment about what's going on.

**Comment by Keenuts** [comment]
Hello!
Fine with this, makes sense to keep it simple. 😊
