### ISSUE TITLE
Enable OpenSSF Scorecard Action and Badge

### ISSUE THREAD

**Issue by joycebrum** [KhronosGroup/SPIRV-Tools#5369]
Hi! I'm Joyce again (#5324 and #5147) and I'd like to bring another security suggestion.

Enabling the [OpenSSF Scorecard Action](https://github.com/ossf/scorecard-action) can help on identifying best practices on supply chain security to work on. The action alerts appears on the Security Dashboard as can be either dismissed or addressed.

It is good to be aware of some security practices and to notified once a new security practice is stablished for open source projects.

Additionally it is also possible to include a badge that shows the result of the scorecard analysis and [link to a viewer with the outputs](https://securityscorecards.dev/viewer/?uri=github.com/KhronosGroup/SPIRV-Tools).
Example:
![image](https://github.com/KhronosGroup/SPIRV-Tools/assets/22223372/d12f33a8-e013-48cc-9a9f-97a797205e9c)

Let me know if you are interested in this action and/or badge and I'll submit a PR configuring it ASAP!

**Comment by s-perron** [comment]
This sound like a reasonable idea. We would accept a PR that enable these checks.
