### ISSUE TITLE
libSPIRV-Tools-opt.so contains reference to $srcdir

### ISSUE THREAD

**Issue by LW-archlinux** [KhronosGroup/SPIRV-Tools#5416]
spirv-tools rev https://github.com/KhronosGroup/SPIRV-Tools/commit/27673a054447e37810a38e7ce8d35a0a88af4a75

When building https://aur.archlinux.org/packages/spirv-tools-git namcap emits a warning

`==> WARNING: Package contains reference to $srcdir
usr/lib/libSPIRV-Tools-opt.so
`

adding `CMAKE_SKIP_INSTALL_RPATH=YES` or `CMAKE_SKIP_RPATH=YES` to the build options doesn't make a difference .

The mentioned library does contain a reference to a local file .
```
$ strings libSPIRV-Tools-opt.so | grep "home"
/home/panoramix/Documents/Aur/pkgbuilds/spirv-tools-git/src/SPIRV-Tools/source/opt/type_manager.cpp
$ 
```

**Comment by LW-archlinux** [comment]
I am building latest trunk main version. Tested 2022.4 & 2023.2 releases, they don't have this issue.

Will try to bisect, though changes in build deps makes this hard(er)

**Comment by s-perron** [comment]
I finally got back to this. I realized my problem. I was not building the shared libraries, so when I did `find . -name "*.so" | xargs strings | grep home` to search the shared libraries, it was not finding the libraries, and returning nothing.

I can now reproduce it. Now, I am able to see the string with the home directory in versions going back to v2021.1. Can you provide me with the exact cmake command you are using? There might still be some small differences.

**Comment by s-perron** [comment]
I found the source of one of the string. There are some error messages in type_manager.cpp that embed the full path of the file in the message using __FILE__. I have a patch to remove those.

I still see a string "${src_dir}/source:", and I am not sure where it is coming from.

**Comment by LW-archlinux** [comment]
Applying 212dd9247ad60d5dcd262e43c24ec92de1a8ef1d on top of c87755b does the job, no more references to /home folders.

Below are the cmake settings I used for reference

```
cmake_args=(
  -G "Unix Makefiles"
  -D CMAKE_BUILD_TYPE=Release
  -D CMAKE_INSTALL_PREFIX=/usr
  -D CMAKE_INSTALL_LIBDIR=lib
  -D SPIRV-Headers_SOURCE_DIR=/usr/
  -D BUILD_SHARED_LIBS=ON
  -D SPIRV_TOOLS_BUILD_STATIC=OFF
  -D SPIRV_WERROR=OFF
)
```

full invoiation : `cmake   -S SPIRV-Tools -B _build "${cmake_args[@]}" -Wno-dev`
