### ISSUE TITLE
Access chain load common subexpression elimination

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#542]
Child of https://github.com/KhronosGroup/SPIRV-Tools/issues/457

**Comment by dneto0** [comment]
WIP by @greg-lunarg

**Comment by dneto0** [comment]
WIP by @greg-lunarg

**Comment by greg-lunarg** [comment]
This work was (mostly) subsumed by the process described in #539. Technically, there is still a piece yet to do. It is possible that after the process in #539 is completed, there could be duplicate extracts which could be eliminated.

In the benchmark shader I work from, there seems to be little opportunity for this optimization, so it should probably be lowered in priority if not removed.

**Comment by dneto0** [comment]
Thanks for the update.  Agree we should close this.  Future improvements to be tracked separately.
