### ISSUE TITLE
New header file missing from BUILD.gn

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/SPIRV-Tools#5420]
Hello,
In a recent commit (1bc0e6f59abc3c9cd75f93baef47e9612a448045) , there is a new source file added for `spvtools_opt` in `BUILD.gn`:  `source/opt/invocation_interlock_placement_pass.cpp`
However, its corresponding header file (`invocation_interlock_placement_pass.h`) is missing from the BUILD file. This causes presubmit failures when we want to roll the new commit into our repo.

CC: @cassiebeckley

**Comment by cassiebeckley** [comment]
Thanks for catching that! #5421 should fix this.

**Comment by aabdolrashidi** [comment]
Thank you for the fix!
