### ISSUE TITLE
Strip unused capabilities (i.e. Float64, PhysicalStorageBuffer)

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/SPIRV-Tools#5425]
It has come to our attention that DXC likes to emit SPIR-V capabilities even if the code using them is not reachable, for example `Float64` being declared here even though nobody is using the `static double` we declared
https://godbolt.org/z/ca5M318GE

The reason we're filing this against SPIRV-Tools and not DXC is because we know DXC uses spv-opt to legalize the SPIR-V it emits, and we believe that the legalization should strip unused extensions and capabilities.

**Comment by cassiebeckley** [comment]
A capabilities trimming pass has been added recently: https://github.com/KhronosGroup/SPIRV-Tools/blob/main/source/opt/trim_capabilities_pass.cpp. This is now automatically called by DXC, and capabilities are being added on a case by case basis.

**Comment by devshgraphicsprogramming** [comment]
thats really cool, thank you!

**Comment by devshgraphicsprogramming** [comment]
I'd still request PhysicalStorageBuffer pointers (BDA) trimming cause it tends to disable/break Renderdoc's source-level debugging
