### ISSUE TITLE
This repository was stolen

### ISSUE THREAD

**Issue by imptype** [KhronosGroup/SPIRV-Tools#5456]
I don't know where to report this but this guy stole your repo https://github.com/v08nike/SPRIVE-Tools and it's not just a fork.

**Comment by dneto0** [comment]
I see.

As far as I can tell, it's still licensed under an open source license, and the copyright notices in the few files I checked were untouched.

They did go through the work to make it look like they committed all the code.  I guess they replayed history. Maybe they are trying to impress someone with that.

I'm not an IP lawyer, so I won't speculate much whether there is a trademark violation.  I'll tell Khronos about it.

**Comment by dneto0** [comment]
Thanks for letting us know.

I've notified Khronos Group admins, and posted an issue on the repo in question.  Closing.

**Comment by keryell** [comment]
Amazing. :-|

**Comment by outofcontrol** [comment]
The offending repository has been remove by GitHub: https://github.com/v08nike/SPRIVE-Tools

**Comment by dneto0** [comment]
Nice work!

If there is nothing left to do, can we close this issue again?
