### ISSUE TITLE
Workgroup Block without WorkgroupMemoryExplicitLayoutKHR don't require offset

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/SPIRV-Tools#5459]
I am still 100% how the `SPV_KHR_workgroup_memory_explicit_layout` extension effects the various layout rules, but removing the following capablilty sets the `bool workgroup` in `validate_decorations.cpp:1120` to be false and doesn't trigger the `isMissingOffsetInStruct` error. I am not sure if this is a bug or working as intended

```patch
               OpCapability Shader
-              OpCapability WorkgroupMemoryExplicitLayoutKHR
-              OpExtension "SPV_KHR_workgroup_memory_explicit_layout"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main" %_
               OpExecutionMode %main LocalSize 1 1 1
               OpDecorate %value SpecId 0
               OpDecorate %_arr_v4float_value ArrayStride 16
               OpMemberDecorate %X 1 Offset 128
               OpDecorate %X Block
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
      %value = OpSpecConstant %uint 1
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_arr_v4float_value = OpTypeArray %v4float %value
          %X = OpTypeStruct %_arr_v4float_value %v4float
%_ptr_Workgroup_X = OpTypePointer Workgroup %X
          %_ = OpVariable %_ptr_Workgroup_X Workgroup
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpReturn
               OpFunctionEnd
 ```
 
 also I noticed regardless if I have
 
 ```
  OpMemberDecorate %X 0 Offset 128
  OpMemberDecorate %X 1 Offset 128
  ```
  
  there is no error and not sure if Offset are allowed to overlap each other in a `Block`
  
  Happy to write the tests/PR, just want to confirm if this is a bug or not (cc @alan-baker )

**Comment by alan-baker** [comment]
If the validator catches it with the capability then most of the functionality is there. What seems missing is rejecting layouts where they are not allowed. For Vulkan, `UniformConstant`, `Private`, `Function`, `Input`, and `Output` never have layouts (not sure about ray tracing storage classes). `Workgroup` should only have layouts when they are block-decorated, which is only allowed with that capability.

The layout checking should catch that overlap.

**Comment by spencer-lunarg** [comment]
aww, ok make sense, will add the logic for case using `Block` workgroup without `WorkgroupMemoryExplicitLayoutKHR`
