### ISSUE TITLE
Capability Stripping Pass doesn't seem to strip Int16 or Float16

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/SPIRV-Tools#5464]
I made a mostly empty shader in HLSL
```cpp
[numthreads(WORKGROUP_SIZE,1,1)]
void main(uint32_t invIdx : SV_GroupIndex, uint32_t3 globalId : SV_DispatchThreadID)
{
	__gl_LocalInvocationIndex = invIdx;
	__gl_GlobalInvocationID = globalId;
}
```

which I compiled with the latest DXC (I also updated its SPIRV-Tools submodule).

The resulting SPIR-V contains extra capabilities it does not need, not filing against DXC because I know that DXC just spams capabilities and relies on capability stripping pass of SPIRV-Tools to get rid of what it doesn't use.

Here's the [compiled_spv.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/13245733/compiled_spv.zip)

**Comment by Keenuts** [comment]
Hi, thanks!

From the compiled code, I see DXC probably generated the capability because there is an int16/float16 in the included source, so at least it's not a regression 😊

Sent out #5519 to add those capabilities to the pass.
