### ISSUE TITLE
Does spirv-val make best effort to continue?

### ISSUE THREAD

**Issue by kbenzie** [KhronosGroup/SPIRV-Tools#547]
This is a question with no better home I know of.

What is the behaviour of `spirv-val` when a validation error is found? Does it;

1. Exit on finding the first validation error?
1. Make a best effort to continue validation?

The reason I ask is I intend to add support for running `spirv-val` whilst editing a `.spv` or `.spvasm` file in [vim-spirv](https://github.com/kbenzie/vim-spirv) by taking advantage of the [syntastic](https://github.com/vim-syntastic/syntastic) vim plugin. I don't think its onerous to only have one validation error reported at a time however reporting multiple validation errors at once is likely to provide the most value to the integration.

Related to kbenzie/vim-spirv#1.

Please feel free to close this once the answer has been provided.

**Comment by dneto0** [comment]
The validator exits after first failure.   In a few cases it's essential to guard later code that would otherwise crash etc.   But mainly it's done for simplicity.  It makes it easier to test too.  But I suppose  we could add a "keep going if you can" mode.
