### ISSUE TITLE
Add permissive mode which accepts nearly anything if an unrecognized extension is used. Uncertain whether this mode should be the default.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#549]

**Comment by ehsannas** [comment]
@dneto0 how do we know if an extension is "unrecognized" ?

**Comment by dneto0** [comment]
"Recognized by the validator" = there is code in the validator to accommodate that extension's changes to the validation rules.
Currently no extensions are recognized.  But there are extensions published on the SPIR-V registry:
https://www.khronos.org/registry/spir-v/

For example `SPV_KHR_shader_ballot` says its new features (a few more instructions, and a few enums) are enabled by a new capability, and that capabilty should only be recognized by current environments only when we additionally also see OpExtension "SPV_KHR_shader_ballot".   

Thankfully, the grammar file already is set up to automatically set up the dependency checks from enums to capabilities.
So, for example consider this example:
```
        OpCapability Shader
        OpCapability SubgroupBallotKHR
        OpMemoryModel Logical GLSL450
        OpEntryPoint Vertex %foo "foo"

%void = OpTypeVoid
%voidfn = OpTypeFunction %void
%bool = OpTypeBool
%true = OpConstantTrue %bool

%foo =  OpFunction %void None %voidfn

%entry = OpLabel
   %v = OpSubgroupBallotKHR %void  %true ; Right, shouldn't be void, but that's beside the point right now
        OpReturn

        OpFunctionEnd
```

The validator *allows* OpSubgroupBallotKHR to be used because it sees the corresponding capability SubgroupBallotKHR.  But if you comment out that capability declaration, then the validator complains, saying:

```
error: 10: Opcode SubgroupBallotKHR requires one of these capabilities: SubgroupBallotKHR
```
Excellent!

So the remaining piece is:  Unless an environment specifically has brought a particular capability into its core functionality, then use of that capability must be accompanied by a matching OpExtension instruction.    None of the current target environments include SPV_KHR_shader_ballot in core.  But a future environment, e.g. Vulkan20.0 could.

**Comment by dneto0** [comment]
Note that the JSON grammar file encodes the dependency from the capability to the extension name.
E.g. for SPV_KHR_shader_ballot: https://github.com/KhronosGroup/SPIRV-Headers/blob/master/include/spirv/1.0/spirv.core.grammar.json#L5101 

So we'd just need some general purpose code to use that in a check.

**Comment by dneto0** [comment]
Debate about how to expose this at the API level:
* https://github.com/KhronosGroup/SPIRV-Tools/pull/554#discussion_r100881139
* https://github.com/KhronosGroup/SPIRV-Tools/pull/554#discussion_r100904827

Basic question:  What optional behaviours should the validator have? How should they be exposed: brand new entry point for each? Or add an options mask?

**Comment by dneto0** [comment]
I recall that @kbenzie requested a "give me as many errors as you can" mode.  That's a candidate for an extra coarse-grain behaviour.

**Comment by dneto0** [comment]
There's also an open issue for parameterizing the validator limit checks.  https://github.com/KhronosGroup/SPIRV-Tools/issues/500 
This would argue toward a more general options argument, e.g. similar to Shaderc's compile options object.  See https://github.com/google/shaderc/blob/master/libshaderc/include/shaderc/shaderc.h#L217 and related API entry points.  That's more complex because the client has to manage the options object lifetime.

**Comment by ehsannas** [comment]
Given the discussion in the SPIR meeting, the consensus seems to be that the Validator should not skip many checks even if there exists an unrecognized extension. It is difficult to tell where the line should be drawn and how lenient the Validator should be. It could in fact create more confusion for its users. 
If the user needs the Validator to bypass certain checks for their extension, they could in fact contribute to the Validator so that it becomes "aware" of the extension. 
I am closing this issue. If, in the future, we see any significant reason for making a lenient Validator, we can reopen the issue.
