### ISSUE TITLE
Compilation error after removing stage-specific debug info

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/SPIRV-Tools#5500]
In https://github.com/KhronosGroup/SPIRV-Tools/commit/b5d60826e9d2ad130fd9eb140ea633c349159952, many stage-specific constants have been removed from `spirv-tools/instrument.hpp`. However, this results in compilation errors similar to below:
```
.../vulkan-validation-layers/src/layers/gpu_validation/gpu_error_message.cpp:31:26: error: use of undeclared identifier 'kInstCommonOutStageIdx'; did you mean 'gpuav::glsl::kInstCommonOutStageIdx'?
```

It seems that the file is trying to use the constants in `gpu_shaders/gpu_shaders_constants.h`. The error disappears when the affected constants in `gpu_error_message.cpp` are prefixed with `gpuav::glsl`.

CC: @jeremyg-lunarg

**Comment by jeremyg-lunarg** [comment]
Fixed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7062 which I just merged. Please reopen if you're still having problems after syncing to this change.

**Comment by aabdolrashidi** [comment]
Thank you! The compilation is now successful.
