### ISSUE TITLE
spirv-val reports OpName and OpLine as not same section

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/SPIRV-Tools#5513]
the following shader

```swift
           OpCapability Shader
           OpCapability Linkage
           OpMemoryModel Logical GLSL450
           OpModuleProcessed "this is too early"
           OpName %void "void"
           OpLine %1 7 19
           OpName %other "other"
```

produces `error:  Name is in an invalid layout section`

but to my understanding, both `OpName` and `OpLine` are both in `"class"  : "Debug",` in the grammar file and mixing and matching I wouldn't expect this error, unless I am reading the spec wrong 

cc @alan-baker

**Comment by alan-baker** [comment]
See [logical module layout](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_logical_layout_of_a_module) in the spec. In particular:
>7. These [debug](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Debug) instructions, which must be grouped in the following order:
>* All [OpString](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpString), [OpSourceExtension](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpSourceExtension), [OpSource](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpSource), and [OpSourceContinued](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpSourceContinued), without forward references.
>* All [OpName](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpName) and all [OpMemberName](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpMemberName).
>* All [OpModuleProcessed](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpModuleProcessed) instructions.
...
>9. All type declarations ([OpTypeXXX](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpTypeVoid) instructions), all [constant instructions](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#ConstantInstruction), and all global variable declarations (all [OpVariable](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpVariable) instructions whose [Storage Class](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Storage_Class) is not Function). This is the preferred location for [OpUndef](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpUndef) instructions, though they can also appear in function bodies. All operands in all these instructions must be declared before being used. Otherwise, they can be in any order. This section is the first section to allow use of:
>* [OpLine](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpLine) and [OpNoLine](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpNoLine) debug information.
>* [Non-semantic instructions](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#NonSemanticInstruction) with OpExtInst.

So `OpLine` can't be present until the type declaration section. When the validator sees OpLine it moves forward to that section which is why the error is that `OpName` is in the wrong section.

**Comment by spencer-lunarg** [comment]
ok, it says 

> These debug instructions

and not

> **The** debug instructions

so this seems fair to me, thanks for clarify, I have not caught that slight difference before
