### ISSUE TITLE
Need AppleSilicon or universal apps for all the spriv tools on macOS

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/SPIRV-Tools#5521]
Run "file *" on any of the tools directories, and note that the apps are all x64 code getting emulated through Rosetta.  This only has SSE4.2 support, and no f16c either.  

glslang:                       Mach-O 64-bit executable x86_64
glslangValidator:              Mach-O 64-bit executable x86_64
glslc:                         Mach-O 64-bit executable x86_64
spirv-cross:                   Mach-O 64-bit executable x86_64
spirv-dis:                     Mach-O 64-bit executable x86_64
spirv-opt:                     Mach-O 64-bit executable x86_64
spirv-val:                     Mach-O 64-bit executable x86_64

Note that we're just pulling executables from the VulkanSDK.   And not building from sources.

**Comment by alecazam** [comment]
cmake can be set to build these as universal apps.  But it builds 2 .o files, then lipo's them together into the universal app.

**Comment by s-perron** [comment]
This seems to be an issue for the Vulkan SDK. I'll assign to someone at LunarG. They take care of building. Since this is not an issue for spirv-tools, I will close the issue. Hopefully lunarg will be able to point you to the best place to make this request.

**Comment by richard-lunarg** [comment]
Just a note, all these binaries have been shipping in the VulkanSDK for some time now. The earliest I have archived locally is 1.3.236.0 and it shows all these binaries as universal (both x86_64 and arm64).

**Comment by alecazam** [comment]
Verified that we have universal apps from the VulkanSDK.  Might want to see if spirv-tools builds are universal.  One of my colleagues had checked in the versions from spirv tools, and then I told them to use the VulkanSDK builds.   Thanks!

**Comment by richard-lunarg** [comment]
Super!
