### ISSUE TITLE
New spriv-cross not transpiling to "void" vertex functions for SSBO usage

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/SPIRV-Tools#5525]
Old spriv-cross generated "vertex void" for SSBO, but new one always specifies "vertex vsmain_out".  The vsmain_out has a gl_position in it that isn't even set to anything.  We only set a VS and have no PS for MSL.   This throws off Metal since we set rasterizationEnabled to false, and it's confused by the VS having output.  The VS is writing to an SSBO, so doesn't need gl_position, and never uses it in the original source.

This one gens "vertex void"
Git commit: d385bf09 Timestamp: 2020-06-11T11:55:22
Usage: spirv-cross <...>

This one gens "vertex vsmain_out" where vsmain_out holds gl_position.
Git commit: 2de1265f Timestamp: 2023-10-24T17:50:38
Usage: spirv-cross <...>

**Comment by alecazam** [comment]
Seems to have changed somwhere in here.

https://github.com/KhronosGroup/SPIRV-Cross/issues/735

**Comment by s-perron** [comment]
@alecazam What do you expect to see from spirv-tools? This seems to be a spirv-cross issue, which is not part of this repository. Please reopen with something specific to spriv-tools if you need to.
