### ISSUE TITLE
Add a validator entry point that takes an opaque options object.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#557]
This is a stepping stone for supporting:
- parameterization of limit checks.  See issue #500
- adding a mode to provide as many error messages as possible

Should be similar to the shaderc_compiler_options object and its uses.  https://github.com/google/shaderc/blob/master/libshaderc/include/shaderc/shaderc.h#L217

**Comment by ehsannas** [comment]
I have some code that I can modify to serve this case

**Comment by dneto0** [comment]
Fixed by https://github.com/KhronosGroup/SPIRV-Tools/pull/558
