### ISSUE TITLE
[spirv-opt] Inlining pass generates OpVariable of PhysicalStorageBuffer pointer type without AliasedPointer decoration.

### ISSUE THREAD

**Issue by csyonghe** [KhronosGroup/SPIRV-Tools#5607]
If the source spirv contains a function that takes an AliasedPointer parameter, the `--inline-entry-points-exhaustive` pass generates a pointer-typed OpVariable without `AliasedPointer` decoration, which leads to validation error.

Steps to reproduce:
[test.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/14553298/test.zip)

Use the `test.spv` in test.zip file:

```shell
spirv-val test.spv       # passes validation
spirv-opt --inline-entry-points-exhaustive -o test-out.spv
spirv-val test-out.spv       # FAILS validation
```

`spirv-val` output:
```
error: line 121: OpVariable 131: expected AliasedPointer or RestrictPointer for PhysicalStorageBuffer pointer.
  %131 = OpVariable %_ptr_Function__ptr_PhysicalStorageBuffer_int Function
```

**Comment by jeremy-lunarg** [comment]
@dneto0 I believe @greg-lunarg worked on this. We'd be happy to look at this bug. Please assign to me if you'd like.

**Comment by jeremy-lunarg** [comment]
FYI, I have a fix for this incoming. Just wrapping up the test.
