### ISSUE TITLE
Compile-related issue: SPIRV-Headers not found

### ISSUE THREAD

**Issue by rubyFeedback** [KhronosGroup/SPIRV-Tools#5612]
So trying a stable release from the github page here, leads to:

    CMake Warning (dev) at CMakeLists.txt:241 (find_package):
      Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
      are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
      the cmake_policy command to set the policy and suppress this warning.

    Call Stack (most recent call first):
      CMakeLists.txt:251 (find_host_package)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.11.7", minimum required is "3") 
    CMake Error at external/CMakeLists.txt:49 (message):
      SPIRV-Headers was not found - please checkout a copy under external/.

Would it be possible to bundle the headers into the release as well?

Right now they are separate:

https://www.linuxfromscratch.org/blfs/view/svn/general/spirv-tools.html

https://www.linuxfromscratch.org/blfs/view/svn/general/spirv-headers.html

Not sure why. IMO it would be easier to bundle things into one area, and
then let people choose what they need on their own. I kind of expected
that the git clone checkout here at this webpage should work, but it evidently
depends on the headers, so I will install them next - but I am not sure this
is the way it should be, hence why I opened this issue. Thanks for reading.

PS: LLVM also has this problem: https://www.linuxfromscratch.org/blfs/view/svn/general/llvm.html

For some reason modern projects seem to want to split up things. Imagine if
this were the case with gcc, where we'd have to download 10 different
source tarballs ...

**Comment by cassiebeckley** [comment]
In order to build SPIRV-Tools, you need to download the dependencies by running `python3 utils/git-sync-deps`. You can find more information [in the README](https://github.com/KhronosGroup/SPIRV-Tools?tab=readme-ov-file#getting-the-source).
