### ISSUE TITLE
new release https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/vulkan-sdk-1.3.280.0/SPIRV-Tools-1.3.280.0.tar.gz

### ISSUE THREAD

**Issue by rubyFeedback** [KhronosGroup/SPIRV-Tools#5622]
There is a recent new release,
at:

https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/vulkan-sdk-1.3.280.0/SPIRV-Tools-1.3.280.0.tar.gz

but it is not mentioned in the main repository here, at:

https://github.com/KhronosGroup/SPIRV-Tools/releases

Not every visitor may see this. I only noticed because I follow the BLFS project and
the above .tar.gz appeared there, so I downloaded it. By the way, extracting the
.tar.gz archive yields a different name, which I think is incorrect packaging. The
general way to package something is:

    foobar-1.2.3/
    foobar-1.2.3.tar.gz

Everything else is IMO incorrect. Most programs follow that scheme.

**Comment by cassiebeckley** [comment]
The supported distribution for SPIRV-Tools is through the [LunarG Vulkan SDK](https://www.lunarg.com/vulkan-sdk/). LunarG does additional validation and may cherry pick bug fixes for the final release.
