### ISSUE TITLE
spirv-val false positive error

### ISSUE THREAD

**Issue by Vovan675** [KhronosGroup/SPIRV-Tools#5633]
I have error when validating shader code
```
Structure id 7 decorated as Block for variable in Uniform storage class must follow relaxed uniform buffer layout rules: member 2 at offset 1032 overlaps previous member ending at offset 1039
  %_struct_7 = OpTypeStruct %int %_arr_v2int_uint_64 %float
```
I am compiling shader

```
struct PSInput
{
    float4 position : SV_Position;
    float4 color    : COLOR0;
};

cbuffer shader_parameters {
	 int s_var1;
	 int2 s_arr[64]; // <-- invalid validating offset of this element
	 float s_var2;
};

float4 PSMain(PSInput input) : SV_Target0
{
    return input.color * input.color;
}
```

It produces me this asm:
```
OpDecorate %_arr_v2int_uint_64 ArrayStride 16
OpMemberDecorate %type_shader_parameters 0 Offset 0
OpMemberDecorate %type_shader_parameters 1 Offset 16
OpMemberDecorate %type_shader_parameters 2 Offset 1032 // <--- This offset is correct for dx layout and my app works nicely with it, except of validation error
OpDecorate %type_shader_parameters Block
```

I am compiling shader using DXC with "-spirv -fvk-use-dx-layout -O0" flags and trying to validate it using this code:
```
spv_context ctx = spvContextCreate(SPV_ENV_VULKAN_1_3);
spvtools::ValidatorOptions options;
options.SetRelaxBlockLayout(true);
options.SetFriendlyNames(false);
spv_const_binary_t binary {
  (const uint32_t *)shaderCode,
  shaderSize / sizeof(uint32_t)
};

spv_diagnostic diag = nullptr;
auto res = spvValidateWithOptions(ctx, options, &binary, &diag);
```

**Comment by alan-baker** [comment]
The problem here is placing `s_var2` at offset 1032. Vulkan has the following rule:
>If one of the conditions below applies
> * The storage class is Uniform, StorageBuffer, PhysicalStorageBuffer, ShaderRecordBufferKHR, or PushConstant, and the scalarBlockLayout feature is not enabled on the device.
> * The storage class is Workgroup, and either the struct member is not part of a Block or the workgroupMemoryExplicitLayoutScalarBlockLayout feature is not enabled on the device.
> * The storage class is any other storage class.

>the memory layout must also obey the following rules:
> * Vectors must not improperly straddle, as defined above.
> * The Offset decoration of a member must not place it between the end of a structure, an array or a matrix and the next multiple of the alignment of that structure, array or matrix.

The last bullet is being tripped. If you were to use `-scalar-block-layout` (or even `-uniform-buffer-standard-layout` I believe) it should validate successfully.

**Comment by Vovan675** [comment]
But when I am compiling shader using vkCreateShaderModule I have the same error. I can't enable `-scalar-block-layout` or `-uniform-buffer-standard-layout` because it called internally in validation layer. And what if I dont want to enable additional features? I dont think that I need them, because everything works correctly now I think

**Comment by alan-baker** [comment]
> But when I am compiling shader using vkCreateShaderModule I have the same error. I can't enable `-scalar-block-layout` or `-uniform-buffer-standard-layout` because it called internally in validation layer. And what if I dont want to enable additional features? I dont think that I need them, because everything works correctly now I think

The validation layers would pick the vulkan features and enable those setting appropriately. So if you requested either at device creation the layers should use them. Your app might work because the device supports the higher feature level. If you tried this on an old implementation it might not.

**Comment by Vovan675** [comment]
But do I really need to enable one of these features to truly support offsets like this on all devices?

**Comment by alan-baker** [comment]
Unfortunately, yes, I think so. Alternatively you reorder your structure definition.

**Comment by Vovan675** [comment]
Yep, I added uniform-buffer-standard-layout extension and now it validates and work fine. Thank you!
