### ISSUE TITLE
 How to compile on arm platform

### ISSUE THREAD

**Issue by gmnail** [KhronosGroup/SPIRV-Tools#5687]
How to compile on arm platform？

**Comment by s-perron** [comment]
The maintainers have not tried building on ARM. We would expect you can follow the standard cmake build instructions in the readme, but it is possible that the cmake files will have to be modified.  Can you please try cmake, and report the details of any failures:

https://github.com/KhronosGroup/SPIRV-Tools?tab=readme-ov-file#build

**Comment by richard-lunarg** [comment]
I've been able to build on Windows 11 ARM without changing the CMake files.
You need Visual Studio 2022, and install the Windows Universal build tools.
Open a native ARM64 Native Tools Command Prompt
Build as usual.
You an verify the build architecture with something like this:
dumpbin /headers SPIRV-Tools-opt.lib | more

Look at the top for:

FILE HEADER VALUES
            AA64 machine (ARM64)

**Comment by s-perron** [comment]
I'll consider the response from @richard-lunarg as the answer to the question.
