### ISSUE TITLE
Generator comment in spirv-dis output is failing to look up name from spir-v.xml

### ISSUE THREAD

**Issue by andfau-amd** [KhronosGroup/SPIRV-Tools#5717]
`spirv-dis` on [matmul.spv.zip](https://github.com/user-attachments/files/15888981/matmul.spv.zip) outputs text beginning like this for me:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos; 22
; Bound: 75
; Schema: 0
```

The `Generator:` line is very strange. Why doesn't it know what the generator is? 22 is a registered ID:

https://github.com/KhronosGroup/SPIRV-Headers/blob/2acb319af38d43be3ea76bfabf3998e5281d8d12/include/spirv/spir-v.xml#L75

I wondered if maybe SPIRV-Tools wasn't actually generating its lookup table from the xml, but no, I found the generated file in the build:

```
$ find . -name generators.inc
./build/generators.inc
```

And it does contain the relevant line:

```c
{22, "Google", "MLIR SPIR-V Serializer", "Google MLIR SPIR-V Serializer"},
```

So I'm not sure what's going on. Code bug? Build system issue?

# Reproduction steps

I'm using Ubuntu 22.04 LTS in WSL2 on Windows 11, if that helps.

```
$ git clone https://github.com/KhronosGroup/SPIRV-Tools.git
$ cd SPIRV-Tools/
$ git clone https://github.com/KhronosGroup/SPIRV-Headers.git external/spirv-headers
$ cmake -B build -S . -G Ninja
$ cmake --build build
$ build/tools/spirv-dis matmul.spv
```

**Comment by andfau-amd** [comment]
Found the bug:

```diff
diff --git a/source/disassemble.cpp b/source/disassemble.cpp
index aa20fab6..c9719062 100644
--- a/source/disassemble.cpp
+++ b/source/disassemble.cpp
@@ -650,7 +650,7 @@ void InstructionDisassembler::EmitHeaderVersion(uint32_t version) {

 void InstructionDisassembler::EmitHeaderGenerator(uint32_t generator) {
   const char* generator_tool =
-      spvGeneratorStr(SPV_GENERATOR_TOOL_PART(generator));
+      spvGeneratorStr(generator);
   stream_ << "; Generator: " << generator_tool;
   // For unknown tools, print the numeric tool value.
   if (0 == strcmp("Unknown", generator_tool)) {
```

I won't submit a patch for this, it can be a low-hanging fruit for anyone else who is interested.

**Comment by andfau-amd** [comment]
Huh, this dates to 200e89788, was this always broken or am I missing something? I could have sworn this used to work.

**Comment by s-perron** [comment]
I just did a hexdump of the spirv file you provided. The generator word is "16 00 00 00". This should be "00 00 16 00"  Spirv generated by DXC has "00 00 0E 00".

https://github.com/KhronosGroup/SPIRV-Headers/blob/3c355ec439dcf821c50fb4660ef0e50d19ae2b63/include/spirv/spir-v.xml#L35-L39

**Comment by andfau-amd** [comment]
I see, thanks for correcting my mistake.
