### ISSUE TITLE
spirv-tools build is failing for gcc 12.4

### ISSUE THREAD

**Issue by DeepeshvRajan** [KhronosGroup/SPIRV-Tools#5738]
When I compile spirv-tools with gcc 12.4 
I am getting this error

/stl_algobase.h:434:30: error: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' forming offset 8 is out of the bounds [0, 8] of object '<anonymous>' with type 'spvtools::val::BasicBlock* const [1]' [-Werror=array-bounds]

  434 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);

/spirv-tools/source/val/function.cpp:92:71: note: '<anonymous>' declared here

   92 |     continue_target_headers_[&continue_target_block] = {current_block_};
c
c1plus: all warnings being treated as errors

ninja: build stopped: subcommand failed.
WARNING: /spirv-tools:153 exit 1 from 'eval ${DESTDIR:+DESTDIR=${DESTDIR} }VERBOSE=1 cmake --build  "$@" -- ${EXTRA_OECMAKE_BUILD}'

**Comment by rwmacleod** [comment]
@DeepeshvRajan You should explain how to reproduce the error. The people working on this project may not know anything about building in Yocto. Please try to reproduce the error outsize of a Yocto build environment, perhaps using https://godbolt.org/ if you can come up with a simplified reproducer. https://stackoverflow.com/help/minimal-reproducible-example. Otherwise, use the spirv-tools git repo, checked out to the version used in Yocto and build gcc-12.4 on your host from source, install that in /tmp/local and setup your path to use that toolchain.

**Comment by rwmacleod** [comment]
Also, have you checked for commits to the releases/gcc-12 branch after the 12.4 tag, to see if this issue has already been fixed?

**Comment by s-perron** [comment]
Looking at the source code in SPIR-V tools, I do not see any problem with the source. The code is:

```
continue_target_headers_[&continue_target_block] = {current_block_};
```

Where `std::unordered_map<BasicBlock*, std::vector<BasicBlock*>>` is the type of `continue_target_headers_`. If there is an out of bounds access somewhere, it is a bug in the implementation of the stl or something in the compiler. I don't think we will look into it further unless you can show that our code is actually incorrect.

**Comment by rwmacleod** [comment]
@DeepeshvRajan has found a gcc regression that seems to only affect gcc-12.4. 
Deepest, please provide a very short summary and link to the gcc issue in case anyone else is affected.

**Comment by quanxianwang** [comment]
reproduce steps

steps to build IGC:
$ cd <workspace>
$ git clone https://github.com/intel/vc-intrinsics vc-intrinsics
$ git clone -b llvmorg-14.0.5 https://github.com/llvm/llvm-project llvm-project
$ git clone -b ocl-open-140 https://github.com/intel/opencl-clang llvm-project/llvm/projects/opencl-clang
$ git clone -b llvm_release_140 https://github.com/KhronosGroup/SPIRV-LLVM-Translator llvm-project/llvm/projects/llvm-spirv
$ git clone https://github.com/KhronosGroup/SPIRV-Tools.git SPIRV-Tools
$ git clone https://github.com/KhronosGroup/SPIRV-Headers.git SPIRV-Headers
$ git clone https://github.com/intel/intel-graphics-compiler igc
$ cd igc
$ mkdir build
$ cd build
$ cmake ../igc
$ cmake --build .


if I build SPRIV-Tools separately, it is ok.
If I build with IGC which using external SPIRV-Tools, SPIRV-Tools will fail.

**Comment by quanxianwang** [comment]
I come across the same build issue。
