### ISSUE TITLE
SPIRV-Tools-toolsTargets.cmake references spirv-objdump but the file does not exist

### ISSUE THREAD

**Issue by maarquitos14** [KhronosGroup/SPIRV-Tools#5742]
I have recently downloaded `[vulkansdk-linux-x86_64-1.3.283.0.tar.xz](https://sdk.lunarg.com/sdk/download/1.3.283.0/linux/vulkansdk-linux-x86_64-1.3.283.0.tar.xz)`. After that, I added the installation prefix to `CMAKE_PREFIX_PATH` and tried to build https://github.com/KhronosGroup/SPIRV-LLVM-Translator. 
```
export CMAKE_PREFIX_PATH=$PREFIX/vulkansdk/1.3.283.0/x86_64/
git clone https://github.com/KhronosGroup/SPIRV-LLVM-Translator
cd SPIRV-LLVM-Translator
mkdir build
cd build
cmake ..
```
However, this failed with the error message below:
```
-- Checking for one of the modules 'SPIRV-Tools'
CMake Error at $PREFIX/vulkansdk/1.3.283.0/x86_64/lib/cmake/SPIRV-Tools-tools/SPIRV-Tools-toolsTargets.cmake:100 (message):
  The imported target "spirv-objdump" references the file

     "$PREFIX/vulkansdk/1.3.283.0/x86_64/bin/spirv-objdump"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "$PREFIX/vulkansdk/1.3.283.0/x86_64/lib/cmake/SPIRV-Tools-tools/SPIRV-Tools-toolsTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  $PREFIX/vulkansdk/1.3.283.0/x86_64/lib/cmake/SPIRV-Tools-tools/SPIRV-Tools-toolsConfig.cmake:3 (include)
  CMakeLists.txt:120 (find_package)


-- Configuring incomplete, errors occurred!
```

I checked and indeed `SPIRV-Tools-toolsTargets.cmake` contains references to `spirv-objdump` but the binary is not present. Has the binary been removed from the release but the cmake file wasn't updated accordingly? Or should the binary exist?

**Comment by maarquitos14** [comment]
I have also opened the issue in VulkanTools repo (https://github.com/LunarG/VulkanTools/issues/2058). Feel free to close any of them it if it's not the right place.

**Comment by maarquitos14** [comment]
Also, removing all the occurrences of `spirv-objdump` in both `SPIRV-Tools-toolsTargets.cmake` and `SPIRV-Tools-toolsTargets-release.cmake` solves the issue.

**Comment by s-perron** [comment]
The problem is that the VulkanSDK does not include spirv-objdump in the SDK. We added this tools last year. I'll let LunarG know about this, and see what they want to do about it. I don't know if they'll want to change the SDK or try to do something with the cmake file.

**Comment by jeremyg-lunarg** [comment]
Off-github discussion concluded that this was an Vulkan SDK problem and it is being tracked as an issue there.
