### ISSUE TITLE
OpSampledImage extra validation check does not properly handle shadow samplers.

### ISSUE THREAD

**Issue by martin-ejdestig** [KhronosGroup/SPIRV-Tools#5770]
Noticed this when upgrading to Vulkan SDK 1.3.290 from 1.3.280 that Vulkan-ValidationLayers, that includes SPIRV-Tools with https://github.com/KhronosGroup/SPIRV-Tools/pull/5695 merged, started warning about:

```GLSL
layout(location = 0) out vec4 out_color;

layout(set = 0, binding = 3) uniform sampler shadow_linear_compare_sampler;
layout(set = 0, binding = 4) uniform texture2D shadow_map_atlas_directional;

void main()
{
    float x = texture(sampler2DShadow(shadow_map_atlas_directional, shadow_linear_compare_sampler), vec3(0.5));
    out_color = vec4(vec3(x), 1.0);
}
```

Error log message:

```
Expected Image to have the same type as Result Type Image
  %20 = OpSampledImage %19 %13 %17
. The Vulkan spec states: If pCode is a pointer to SPIR-V code, pCode must adhere to the validation rules described by the Validation Rules within a Module section of the SPIR-V Environment appendix (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08737)
```

Passing a `sampler` to `sampler2DShadow()` is valid though? Looks like it when reading GLSL 4.60.8 specification section 5.4.5. Texture-Combined Sampler Constructors. 

Test for it in glslang: https://github.com/KhronosGroup/glslang/blob/592de6cf78e0fb359fc3e2854c9dc0f3cf6d4820/Test/vulkan.frag#L25
glslang commit that made it valid: https://github.com/KhronosGroup/glslang/commit/7d4c9a07b52e27fa80bf321782f4ac27dd22dad3
glslang commit message links to: https://github.com/KhronosGroup/GLSL/pull/22
Original VVL issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8413

**Comment by alan-baker** [comment]
I think this comes down to the compiler (glslang in this case) not generating correct SPIR-V. Glslang should be declaring the image with a depth operand of either 1 or 2 in this case.

**Comment by arcady-lunarg** [comment]
This is a bug in glslang codegen, being tracked in this glslang issue: https://github.com/KhronosGroup/glslang/issues/3653
The GLSL construct is legal, it's just that the SPIR-V being generated by glslang is wrong.

**Comment by martin-ejdestig** [comment]
Closing since duplicated with #5781 .
