### ISSUE TITLE
Missed adding new source and header files in BUILD.gn

### ISSUE THREAD

**Issue by HuYuxin** [KhronosGroup/SPIRV-Tools#5792]
In this commit [b31baff4ee](https://github.com/KhronosGroup/SPIRV-Tools/commit/b31baff4ee91a982941ad2fc3adf973b3f8a2127), new files are added:

struct_packing_pass.cpp
struct_packing_pass.h

However, they are not added in the [BUILD.gn](https://github.com/KhronosGroup/SPIRV-Tools/blob/main/BUILD.gn). This causes the compilation errors when we try to merge this change to the projects that rely on BUILD.gn to compile.

Would you please make the change to add these files to the BUILD.gn? Thank you.

**Comment by s-perron** [comment]
Fixed with #5791.

**Comment by HuYuxin** [comment]
Thank you very much for the fix!
