### ISSUE TITLE
`OpBitfieldExtract` and `OpBitfieldInsert` no longer work for non-32-bit integer types

### ISSUE THREAD

**Issue by natevm** [KhronosGroup/SPIRV-Tools#5797]
This appears to be a "regression" of sorts caused by the following PR: https://github.com/KhronosGroup/SPIRV-Tools/pull/4758
The corresponding issue is here: https://github.com/KhronosGroup/glslang/issues/2737

For some context, I'd like to use `OpBitfieldExtract` and `OpBitfieldUInsert` to efficiently convert structures into their proper types while also utilizing the 128-byte / 256-byte cache line loads on NVIDIA / AMD GPUs. I have found these intrinsics yield substantial improvements to performance by reducing ALU pressure from the 64-bit logical operations otherwise required for emulating their behavior. 

So, something like, 
```
uint64_t4 data = Buffer.LoadAligned<uint64_t4>(...);
uint8_t A = bitfieldExtract(data.x, 0, 8);
uint8_t B = bitfieldExtract(data.x, 8, 8);
uint8_t C = bitfieldExtract(data.x, 16, 8);
uint16_t D = bitfieldExtract(data.x, 24, 16);
// and so on...
```

Beyond that, using the bitfield extraction Ops is important for performance when non-32-bit types are used in a structure where HLSL bitfields are used. 
```
struct {
    uint64_t A : 8;
    uint64_t B : 8;
    uint64_t C : 48;
};
```

Before PR#4758, this worked so long as `SpvCapabilityInt8` / `SpvCapabilityInt16` / `SpvCapabilityInt64` were requested. The various different overloads map to specialized NVIDIA hardware similar to NVIDIA's `bfe` and `bfi` PTX intrinsics.  

If I understand right, Samsung's hardware is unable to do ALU ops for non-32-bit types for bitfield insertion / extraction (including 16-bit and 8-bit types), hence PR #4758, but now, other IHVs which do support them are locked out from using these intrinsics. 

I'm finding this to be particularly problematic for `OpBitfieldExtract` and `OpBitfieldUInsert`, as these are most commonly used for converting from one integer width to another.

Could we re-enable these intrinsics for non-32-bit types if something like the corresponding SPV integer capability is requested?

**Comment by natevm** [comment]
I suppose an alternative way to frame this, is there a recommended approach for extracting bit fields for types other than 32-bit integers in SPV? I’m actually not sure what the driver does for 64-bit values, but perhaps certain IHVs are using two sequential 32-bit extract/insert routines and then augmenting the results with some 64-bit ALU ops…

**Comment by s-perron** [comment]
#4758 was not added because of any specific hardware. As stated on that PR, it is implementing a specific statement in the spec. Look for VUID-StandaloneSpirv-Base-04781 on https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap51.html.

If you want 64-bit integers supported for those instructions, you will have to get the Vulkan specification changed. Some type of extension or something.

**Comment by s-perron** [comment]
You could also avoid the validator, and just keep passing it to the driver. There is no guarantee it will work on all drivers.

**Comment by natevm** [comment]
> If you want 64-bit integers supported for those instructions, you will have to get the Vulkan specification changed. Some type of extension or something.

@s-perron Is there a particular repo you'd recommend I submit a feature request to? Or is this something that only IHVs have the ability to do?

**Comment by s-perron** [comment]
You can open an issue at https://github.com/KhronosGroup/Vulkan-Docs/issues.
