### ISSUE TITLE
Known extension list should be extracted from the SPIR-V JSON grammar file.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#583]

**Comment by antiagainst** [comment]
Isn't this a duplicate of #580?

**Comment by dneto0** [comment]
Ah yes.  I didn't see it in the Validator project.  It was in the General project.  :-)
Either way I'd like the job done.   I'll close #580 in favour of this one, since @atgoo already self-assigned this.

**Comment by dneto0** [comment]
Fixed by https://github.com/KhronosGroup/SPIRV-Tools/issues/580
