### ISSUE TITLE
unsupported SPIR-V version number 'unknown (66560)'

### ISSUE THREAD

**Issue by Pablou2902** [KhronosGroup/SPIRV-Tools#5834]
I was following this guide: https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_windows_gpu.md and everything worked as intented until I tried to follow the last example. When I try to compile it, I get the following error: 
![Screenshot Demo3](https://github.com/user-attachments/assets/47afed5c-4f25-4295-99e6-f2134adcfb02)
I've found almost no information about this specific bug. Is there any way to fix this?

**Comment by s-perron** [comment]
I'm not sure what the problem is. Do you have reason to believe this is a problem with spirv-tools? You are trying to use a different project, and I don't know if spirv-tools is used there. Have you tried opening an issue at https://github.com/intel-analytics/ipex-llm/issues?

**Comment by s-perron** [comment]
We need more information to know if there is anything we can do. I'll close for now. If more information is provided that points to a problem in spirv-tools, then we can reopen.
