### ISSUE TITLE
Avoid variables of class type with static duration:  Operand and opcode tables.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#584]
These are automatically generated from the JSON grammar files, but now use members of class type.

The solution is to replace the variables with functions that return a reference a function-scope static variable.   This defers construction until first use, and in C++11 is thread-safe.

**Comment by dneto0** [comment]
I think @antiagainst already did this.  Please confirm and close.

**Comment by antiagainst** [comment]
Yep, this is done via https://github.com/KhronosGroup/SPIRV-Tools/pull/830.
