### ISSUE TITLE
spriv-val: not catching out of bounds array reference

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/SPIRV-Tools#587]
The attached vertex shader contains the following sequence:

       %2594 = OpConstant %11 8
       %2845 = OpTypeArray %29 %2594
       %2846 = OpTypeArray %29 %2594
       %2847 = OpTypeArray %29 %2594
       %2848 = OpTypeArray %29 %2594
       %2849 = OpTypeArray %29 %2594
        %506 = OpTypeStruct %2845 %2846 %2847 %2848 %2849
      
       %12714 = OpLoad %506 %21402
       %7572 = OpCompositeExtract %29 %12714 0 1363

In the OpCompositeExtract the 1363 is out-of-bounds.  However, spirv-val does not catch this error.  This shader is crashing on an IHV driver due to the out-of-bounds.

For what it's worth, the bug in the SPIR-V was introduced by a bug in WIP spirv-opt changes, but it took us a long time to hunt down since the shader passed validation.  Could this check be added to spirv-val?

The file is located here (I could not figure out how to attach a .spv file to the issue): https://www.dropbox.com/s/m8kz7xcoy4eib11/shader_with_out_of_bounds_error.spv?dl=0

**Comment by dneto0** [comment]
Right.  The validator could do this.  It would need to track types, and then do bounds checking.
I'll add it to the Validator sub-project.   Another commonly requested validator check is basic type checking. That would share the common piece of more complete type tracking of SSA values.

About attaching samples:  Git allows you to attach .zip files.  
[shader_with_out_of_bounds_error.spv.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/847801/shader_with_out_of_bounds_error.spv.zip)

**Comment by dneto0** [comment]
Fixed by #1161 which has been merged into master
