### ISSUE TITLE
Missing support for disassembling vendor specific extensions (TimeAMD).

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/SPIRV-Tools#594]
Related issue: https://github.com/google/shaderc/issues/325

I looked around a bit and it seems related to `spvOpcodeString` not having it's tables set up for vendor extensions.

The offending shader compiled with `shaderc`

```
#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_AMD_gcn_shader : enable

void main() 
{
	uint64_t v = timeAMD();
}
```

**Comment by Jasper-Bekkers** [comment]
Hi David thanks for looking at this & the quick turnaround. After the shaderc issue I also run into this, when loading the SPIRV module with validation enabled:

`SPIR-V module not valid: Invalid extended instruction import 'SPV_AMD_gcn_shader'`

Does the above commit fix that as well?

**Comment by dneto0** [comment]
> SPIR-V module not valid: Invalid extended instruction import 'SPV_AMD_gcn_shader'

> Does the above commit fix that as well?

Yes.  The validator recognizes the extension, but does not check the specific rules.  For the example you gave, the SPIR-V module passes validation silently.
