### ISSUE TITLE
spirv-opt passes not being destructed

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#598]
It seems that when a PassManager is destructed, the passes added using AddPass are not being destructed.

This should be observable with any pass and any SPIR-V input using the command line interface.

I saw it with --fold_spec_const_op_composite.

The initial symptom was that we were seeing a fairly significant memory leak using MSVC CRT Leak Detection. The leaking memory was coming primarily from the (also non-destructed) def_use_manager_ in the (non-destructed) pass.

The symptom was also seen using the API interface.

I verified that destruct was not happening by creating destructors for PassManager and  FoldSpecConstantOpAndCompositePass and setting breakpoints in them.

**Comment by dneto0** [comment]
Taking a very quick look at this.
The code is relying on default destructors to destroy unique-pointers to various objects.  Those destructors should be generated by the compiler.  I added an explicit destructor to FoldSpecConstantOpAndCompositePass to have it print a message to stderr when it gets called.  It is getting called in my setup (Linux).  I have yet to try Windows.

**Comment by greg-lunarg** [comment]
Don't bother. I just fetched a fresh clone and tried it. The destructor is now called. The branch I am working on is a few months old. I need to rebase. Sorry for the interrupt.
