### ISSUE TITLE
Auto-run OpenCL CTS against validator

### ISSUE THREAD

**Issue by ehsannas** [KhronosGroup/SPIRV-Tools#599]
A while back I had introduced a behavior in the validator (issue #532 ) which passed all unit tests, and also validation passed on all Vulkan CTS as expected, but the issue was caught when someone ran the validator on OpenCL CTS.

we should have an automated flow which runs OpenCL CTS on spirv-tools commits to have better coverage.

**Comment by dneto0** [comment]
OpenCL CTS is developed in private.  So we can't use public CI for it.

**Comment by kpet** [comment]
The maintenance/development of the OpenCL CTS is moving to Github. This relates to https://github.com/KhronosGroup/OpenCL-CTS/issues/20.

**Comment by s-perron** [comment]
We will not do this as part of a presubmit. However, I believe it is done in other places for every update to spirv-tools. If we notice a failure, we will be able to hopefully get a quick fix.
