### ISSUE TITLE
Opt pass to flatten out group decoration

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/SPIRV-Tools#602]
In LoaderAndValidationLayers we're starting to see things targeting SPIRV which use decoration groups. We'd like to be able to run a SPIRV->SPIRV pass before our validation which flattens all the variation out to simple OpDecorate/OpMemberDecorate.

**Comment by dneto0** [comment]
Would you also be satisfied with an analysis that let you look up decorations affecting a target Id?

E.g.
``` 
     for ( auto& decoration : SpvAnalyzer.DecorationsTargeting(uint32_t target_id) ) {
         switch( decoration.type() ) {
          case OpDecorate:  ... inspect decoration and its potential operands;
          case OpMemberDecorate :  ... inspect member index, decoration and its potential operands;
         }
     }
```

**Comment by chrisforbes** [comment]
@dneto0, that would be fine too.

**Comment by dneto0** [comment]
I went with the option of transforming the SPIR-V module.  We don't have a public API for doing reflection or analysis. :-(
