### ISSUE TITLE
Tune data structures for speed.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#607]
E.g. The optimizer has unordered maps and std::list. These are probably bad for cache behaviour.
E.g. Replace unordered map, with using unordered map to generate unique indices, and then index into a vector.

**Comment by ratchetfreak** [comment]
If the number of elements isn't too large then a flat map (aka a `std::vector<std::pair<>>`) could also work.

**Comment by dneto0** [comment]
Agreed.  We'd want it to degrade gracefully as well.

The higher level thing is that really should measure before we tune for performance.  :-)

I'm gathering some private data sets to try various things.

**Comment by ratchetfreak** [comment]
as another option a `std::pair<std::vector<Key>, std::vector<Val>>` would have better cache performance for find when the Val is large.

**Comment by ratchetfreak** [comment]
Just speculation from my part.

**Comment by dj2** [comment]
K, I'm going to close this for now. Until we have concrete examples of the code being slow, there is a risk we're going to make things more complicated without any benefit.
