### ISSUE TITLE
Result id of OpDecorationGroup can only be used as the target of OpName, OpGroupDecorate, and OpGroupMemberDecorate

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#616]
I believe that's the right rule.  If it's not true then the "flatten decorations" optimization pass is incorrect.
https://github.com/KhronosGroup/SPIRV-Tools/pull/610

**Comment by jcaraban** [comment]
Seems to me, this issue requires a new OpDecorationGroup case in validation_id.cpp.
I will write ``bool idUsage::isValid<SpvOpDecorationGroup>( )`` and its corresponding tests.
anything else needed @dneto0 ?

**Comment by nsubtil** [comment]
@jcaraban @dneto0 can we close this issue now? Or is there still work left to do?

**Comment by jcaraban** [comment]
@dneto0 accepted the MR, so I think we can close.
