### ISSUE TITLE
Double case value use compile error

### ISSUE THREAD

**Issue by aarongreig** [KhronosGroup/SPIRV-Tools#620]
I'm building Windows 32-bit Debug with Visual Studio 2015 and getting a "case value already used" error at lines 201 and 205 of `enum_string_mapping.inc`. A git bisect shows this first happening at [this commit](https://github.com/KhronosGroup/SPIRV-Tools/commit/c804c125c568914aabf4d734cf85923611bdfd21)

**Comment by dneto0** [comment]
Agreed.  The enum generation code needs to be updated so it can handle the new case found in yesterday's update to SPIRV-Headers.
I have a fix.

**Comment by dneto0** [comment]
Will be fixed by https://github.com/KhronosGroup/SPIRV-Tools/pull/621

**Comment by dneto0** [comment]
Fixed by #621
