### ISSUE TITLE
inline-entry-points-all: forgets to delete names of Ids that go away

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#622]
Inliner forgets to delete OpName targeting the inlined return value of a called function.

Example input is below. In particular, `%foo_result` is the name given to the result of the function call.

```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main"
               OpName %main "main"
               OpName %main_entry "main_entry"
               OpName %foo_result "foo_result"
               OpName %void_fn "void_fn"
               OpName %foo "foo"
               OpName %foo_entry "foo_entry"
       %void = OpTypeVoid
    %void_fn = OpTypeFunction %void
        %foo = OpFunction %void None %void_fn
  %foo_entry = OpLabel
               OpReturn
               OpFunctionEnd
       %main = OpFunction %void None %void_fn
 %main_entry = OpLabel
 %foo_result = OpFunctionCall %void %foo
               OpReturn
               OpFunctionEnd
```

After running the inliner I get:

```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main"
               OpName %main "main"
               OpName %main_entry "main_entry"
               OpName %foo_result "foo_result"
               OpName %void_fn "void_fn"
               OpName %foo "foo"
               OpName %foo_entry "foo_entry"
       %void = OpTypeVoid
    %void_fn = OpTypeFunction %void
        %foo = OpFunction %void None %void_fn
  %foo_entry = OpLabel
               OpReturn
               OpFunctionEnd
       %main = OpFunction %void None %void_fn
 %main_entry = OpLabel
               OpReturn
               OpFunctionEnd
```
We still have the `OpName %foo_result` but that Id is no longer defined, and this module fails validation:

```
error: 19: The following forward referenced IDs have not been defined:
3[foo_result]
```

It's a bug, yes, but I don't think this is particularly high priority since I only encountered it with a hand-coded assembly module.

Cc @greg-lunarg

**Comment by greg-lunarg** [comment]
Is the "before" shader valid? foo is defined as a void function but it is called with a return value. The spec says that void functions do not return a value, but there does not appear to be a way to call a function without a return value. So that means that %foo_result's type is void. Is that valid? There doesn't seem to be validation rule that rules out values or variables from having type void. Should there be? My code had (apparently naively) assumed there wasn't a return value for void functions.

It seems that glslang does not (often? ever?) name the return id of a call (or any "temp" ids), so this shouldn't occur that often, as you noted.

I would like to wait for a reading on the long-term viability of return values on void function calls before I make a fix. OK?

**Comment by dneto0** [comment]
Calling a void function does generate an Id for its return value.  Yes, that's valid.  My example is strange only in that applies an OpName to it.

For example, given this vertex shader:

```
#version 150
void foo() {}

void main() { foo(); }
```
Glslang produces this when targeting Vulkan:

```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main"
               OpSource GLSL 150
               OpName %main "main"
               OpName %foo_ "foo("
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %main = OpFunction %void None %3
          %5 = OpLabel
          %8 = OpFunctionCall %void %foo_
               OpReturn
               OpFunctionEnd
       %foo_ = OpFunction %void None %3
          %7 = OpLabel
               OpReturn
               OpFunctionEnd
```

But yeah, this issue of stripping away the name is low priority since it _should_ be rare.

**Comment by dnovillo** [comment]
@s-perron is this still an issue?

**Comment by antiagainst** [comment]
@s-perron: ping.

**Comment by s-perron** [comment]
This is still a problem.  I'll look into it.
