### ISSUE TITLE
inline-entry-points-all: violates structured control flow rules when inlined function has early return

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#629]
The structured control flow rules say:

* the only blocks in a construct that can branch outside the construct are
  *  a block branching to the construct’s merge block
  *  a block branching from one case construct to another, for the same OpSwitch
  *  a continue block for the innermost loop it is nested inside of
  * a break block for the innermost loop it is nested inside of
  * a return block

When the inline-entry-points-all pass inlines a function that has early returns, it generates a new exit block, and those inlined returns become branches to that new block.   But these branches could be leaving a structured construct, yet the new exit block is neither the merge block or continue construct for any construct.

So the pass can take a valid SPIR-V module and turn it into an invalid one, by the existing structured control flow rules.

Here's a running example. Start with this vertex shader:
```
#version 450

int foo(int c) {
  if (c < 10) {
    if (c < 5) return 23;
  }
  return 42;
}

void main() {
  int x = 0;
  x = foo(x);
}
```
This compiles to
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main"
               OpSource GLSL 450
               OpName %main "main"
               OpName %foo_i1_ "foo(i1;"
               OpName %c "c"
               OpName %x "x"
               OpName %param "param"
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
          %8 = OpTypeFunction %int %_ptr_Function_int
     %int_10 = OpConstant %int 10
       %bool = OpTypeBool
      %int_5 = OpConstant %int 5
     %int_23 = OpConstant %int 23
     %int_42 = OpConstant %int 42
      %int_0 = OpConstant %int 0
       %main = OpFunction %void None %3
          %5 = OpLabel
          %x = OpVariable %_ptr_Function_int Function
      %param = OpVariable %_ptr_Function_int Function
               OpStore %x %int_0
         %31 = OpLoad %int %x
               OpStore %param %31
         %32 = OpFunctionCall %int %foo_i1_ %param
               OpStore %x %32
               OpReturn
               OpFunctionEnd
    %foo_i1_ = OpFunction %int None %8
          %c = OpFunctionParameter %_ptr_Function_int
         %11 = OpLabel
         %12 = OpLoad %int %c
         %15 = OpSLessThan %bool %12 %int_10
               OpSelectionMerge %17 None
               OpBranchConditional %15 %16 %17
         %16 = OpLabel
         %18 = OpLoad %int %c
         %20 = OpSLessThan %bool %18 %int_5
               OpSelectionMerge %22 None
               OpBranchConditional %20 %21 %22
         %21 = OpLabel
               OpReturnValue %int_23
         %22 = OpLabel
               OpBranch %17
         %17 = OpLabel
               OpReturnValue %int_42
               OpFunctionEnd
```
This is its control flow graph.

![x](https://cloud.githubusercontent.com/assets/13054574/25016057/824e7848-204c-11e7-8c96-ff5b142c2f71.png)

The early return occurs in block %21.  It escapes the structured selection headed by block %16.  

That's valid.

After running inline-entry-points-all we get
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main"
               OpSource GLSL 450
               OpName %main "main"
               OpName %foo_i1_ "foo(i1;"
               OpName %c "c"
               OpName %x "x"
               OpName %param "param"
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
          %8 = OpTypeFunction %int %_ptr_Function_int
     %int_10 = OpConstant %int 10
       %bool = OpTypeBool
      %int_5 = OpConstant %int 5
     %int_23 = OpConstant %int 23
     %int_42 = OpConstant %int 42
      %int_0 = OpConstant %int 0
       %main = OpFunction %void None %3
          %5 = OpLabel
         %33 = OpVariable %_ptr_Function_int Function
          %x = OpVariable %_ptr_Function_int Function
      %param = OpVariable %_ptr_Function_int Function
               OpStore %x %int_0
         %31 = OpLoad %int %x
               OpStore %param %31
         %34 = OpLoad %int %param
         %35 = OpSLessThan %bool %34 %int_10
               OpSelectionMerge %36 None
               OpBranchConditional %35 %37 %36
         %37 = OpLabel
         %38 = OpLoad %int %param
         %39 = OpSLessThan %bool %38 %int_5
               OpSelectionMerge %40 None
               OpBranchConditional %39 %41 %40
         %41 = OpLabel
               OpStore %33 %int_23
               OpBranch %42
         %40 = OpLabel
               OpBranch %36
         %36 = OpLabel
               OpStore %33 %int_42
               OpBranch %42
         %42 = OpLabel
         %32 = OpLoad %int %33
               OpStore %x %32
               OpReturn
               OpFunctionEnd
    %foo_i1_ = OpFunction %int None %8
          %c = OpFunctionParameter %_ptr_Function_int
         %11 = OpLabel
         %12 = OpLoad %int %c
         %15 = OpSLessThan %bool %12 %int_10
               OpSelectionMerge %17 None
               OpBranchConditional %15 %16 %17
         %16 = OpLabel
         %18 = OpLoad %int %c
         %20 = OpSLessThan %bool %18 %int_5
               OpSelectionMerge %22 None
               OpBranchConditional %20 %21 %22
         %21 = OpLabel
               OpReturnValue %int_23
         %22 = OpLabel
               OpBranch %17
         %17 = OpLabel
               OpReturnValue %int_42
               OpFunctionEnd
```
That has control flow graph:

![x inline](https://cloud.githubusercontent.com/assets/13054574/25016083/9e14878e-204c-11e7-9831-61f3cecee6c6.png)

This second module is invalid.   The correspondence is as follows:
*  block %37 is  the inlined form of block %16, the head of the inner structured selection construct
* block %40 is the inlined form of block %22, the merge block of the inner structured selection 
* block %41 is the inlined form of block %21
* block %42 is the newly created exit block made to accommodate the early return.

The problem is that:
* Block %41 is "in" the structured selection headed at %37 since it is dominated by header block %37 and not dominated by the corresponding merge block %40.
* Block %42 is not "in" the structured selection headed at %37 since %37 does not dominate %42.  There is another path from entry point block %5 to %42, via block %36.
* Therefore the branch from %41 to %42 is a branch from inside a structured selection to outside the structured selection.  It doesn't satisfy any of the permitted ways:
   * Block %42 is not the merge block or continue target for any structured construct
   * Block %42 is not the head of a case construct. (There is no OpSwitch)
   * The branch is not an OpReturn.

**Comment by dneto0** [comment]
Cc @greg-lunarg

**Comment by dneto0** [comment]
When making this example, I tried a simpler one where function foo did not have the outer "if" construct.  But then the result of inlining was valid because the newly created exit block *was* dominated by the header of the (one and only) selection block.  So the newly created exit block would be considered "in" the selection construct and the branch to it is not escaping anything.    It was surprising, but valid.

Cc @johnkslang on this issue, for general interest in this issue.

**Comment by dneto0** [comment]
The inliner is out of spec.

@greg-lunarg, @johnkslang have quickly discussed a few options to fix it.

Unfortunately, the validator currently does not catch this case.

Let's assume the spec remains unchanged.

First bucket of ideas is to avoid the problematic case:
* Avoid inlining when structured control flow is required *and*
   * The inlined function contains early returns.

From the observation in https://github.com/KhronosGroup/SPIRV-Tools/issues/629#issuecomment-293970360 we can permit inlining again if whenever an early return is dominated by a structured header block, then that structured header block is the entry point of the inlined function.  This avoids the "alternate path to exit" and hence the branch to the newly created exit block stays "inside" the structured construct.

Second bucket of ideas:
- wrap the body in a synthetic `if (true) { }` construct.  But that just adds more cases where the early return is escaping from an inner structured construct.
- wrap the body in a synthetic `do {  } while(false)`.  And then have the early return be a branch to the merge block of the synthetic loop.  But that only works if the early return is not itself in a nested loop. That's because the "break block" is only allowed to branch out to the merge block of the innermost containing loop.

**Comment by greg-lunarg** [comment]
As much as I would like it to be so, I am not sure the case of a single "if" construct is valid. By my reading the selection construct does not include the merge block or any blocks it dominates, including the "exit" block. So the branching to the "exit" block is still invalid, right?

**Comment by johnkslang** [comment]
Branching through multiple levels of nesting can certainly be done for

1. return statements, which exit all control flow

2. switch breaks, which exit up to the inner-most switch

3. loop breaks, which exit up to the inner-most loop

4. more? I assume this is the question, yes?  I can see the gray area here, and if this is the correct question, would like to dig deeper into it (including deeper understanding of the above discussion)

In the meantime, what's the status of an inliner policy?  We do not want to inline, say, medium--complex functions that are called from many locations.  It seems reasonable to include in the policy the black-listing of functions that have early returns inside of loops, or some rule to safe.

**Comment by dneto0** [comment]
> In the meantime, what's the status of an inliner policy? We do not want to inline, say, medium--complex functions that are called from many locations. It seems reasonable to include in the policy the black-listing of functions that have early returns inside of loops, or some rule to be safe.

I think functionality is concepturally layered. 

The lower level is pure mechanism.  Each transform pass in the SPIRV-Tools does a particular transform.   It does not care whether it's an "improvement".

The higher levels is about policy:  Selection, parameterization, and sequencing of transforms to achieve a particular optimization goal.

So far in SPIRV-Tools we have a few transforms that fall into the lower layer, and nothing that falls squarely  into the upper layer.

The inline-entry-points-all is pure mechanism. It intrinsically does not have an optimization goal.  A *user* of it is responsible for deciding whether it's a good idea to do.

**Comment by ratchetfreak** [comment]
As a mechanism fix we could add a pass to modify a function to have a single return. Those can always be easily inlined.

Then when the inliner discovers a return from a loop it can bail out and the user is then responsible for running the single return pass.

**Comment by greg-lunarg** [comment]
@johnkslang regarding inliner policy, I can look at how blacklisting early returns would effect the overall size for our client's shader set. It might be preferable to the cascading control flow required to simulate the branch in question. But being able to exhaustively inline entry points is still going to be attractive.

Might the SPIR-V WG consider allowing more liberal branching out of of a selection construct, say to any block which post-dominates the selection's merge block?

**Comment by johnkslang** [comment]
> Might the SPIR-V WG consider allowing more liberal branching out of of a selection construct, say to any block which post-dominates the selection's merge block?

I can imagine a future where we all agree that an exit from a selection exits multiple levels of nesting.  Needs discussion.

> ... policy...

Policy wise, I think the inliner is a dangerous thing if it only works exhaustively, especially if the point is to make things smaller.  Complex shaders will have functions that should not be inlined (both for size and performance).  

The default simple use a typical ISV will turn on should automatically not inline medium-large functions called from multiple places, due to the size increase and loss of information. This constitutes important information loss, which is against SPIR-V intent: It is bad both for SPIR-V as an interchange language, and bad for drivers blowing their instruction caches and not knowing there used to be a function call that would have helped.

We should only accept an exhaustive inliner if it is not the default inline policy, and one has to add an extra option (go out of their way) to enable it.  The starting position should be an inline that doesn't blow up code size and loose this information that could be critical to a driver for keeping instructions in cache.

**Comment by greg-lunarg** [comment]
@johnkslang I think we are on the same page. For now there are no "default" passes in spirv-opt, they all have to be explicitly enabled and the exhaustive inliner name "inline-entry-points-all" was meant to give the user the idea that the pass is exhaustive ("-all").

**Comment by johnkslang** [comment]
"entry-points" sounds like SPIR-V entry points.  Does it mean SPIR-V entry points, or does it mean function calls?  The option does not sound like an exhaustive inliner, it sounds like it applies to all the SPIR-V entry points in a module.  If it means "all function calls", should change to use SPIR-V terminology.

It would be better to a "safe inliner" show up first, rather than the more dangerous one.

**Comment by greg-lunarg** [comment]
Yes, we can possibly come up with an even better name. I will work with @dneto0 and you to come up with one we can all agree on.

Just to be clear, the current inliner only inlines function calls in entry point functions, and does so exhaustively until no function calls remain in any entry point functions.

**Comment by dneto0** [comment]
@ratchetfreak wrote
> As a mechanism fix we could add a pass to modify a function to have a single return. Those can always be easily inlined.

That's a good suggestion as it breaks the problem down into smaller pieces.  But I think the essence of the problem remains: The early returns pop out several nesting levels, which is what is not currently permitted via direct branch.  So the only valid solution is to use cascading control flow (e.g. introduce guard variables) that @greg-lunarg described in https://github.com/KhronosGroup/SPIRV-Tools/issues/629#issuecomment-294190000

**Comment by dneto0** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/pull/634 eliminated almost all bad cases, including all cases naturally generated by Glslang.

**Comment by dneto0** [comment]
@greg-lunarg fixed this with https://github.com/KhronosGroup/SPIRV-Tools/pull/647 

Thanks!
