### ISSUE TITLE
Feature request: add unroll optimization pass for OpLoopMerge

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/SPIRV-Tools#636]
SPIR-V has the Unroll option on OpLoopMerge which should inform the driver to unroll the loop.  However, there is some demand from ISVs that there be an optimization pass that could do this manually to make sure loop unrolling is absolutely forced.  This would not be something I would want spirv-opt to do by default, but perhaps an optional optimization pass when required.

**Comment by dneto0** [comment]
Thanks for the request.  I'll put it in the optimizer project list.

FYI: spirv-opt is modeled after LLVM's "opt" tool.  It provides mechanism, and the *user* decides what transforms to run, and in what order.  Nothing is run automatically.   It's meant as a toolbox for a higher order tool, or for manual experimentation.

**Comment by gwihlidal** [comment]
This would be a very appreciated optimization pass for us.

**Comment by dneto0** [comment]
I'm hearing more requests for this.  I'll coordinate with @greg-lunarg to make sure it happens.

**Comment by greg-lunarg** [comment]
Would be nice to have sample shader(s) along with the desired outcome for each. There are lot of possible kinds of loops and I want to make sure we concentrate on the exact loop forms of interest to get you solution(s) as quickly as possible. It would probably be sufficient and perhaps expedient to provide GLSL (or HLSL) here but whatever works to get the point across is fine.

**Comment by dneto0** [comment]
I believe we may have found someone to do this.   Stay tuned.

**Comment by s-perron** [comment]
@danginsburg The loop unrolling has just landed (#1230 and #1321).  It is not part of -O or -Os, but feel free to try it out and let us know of any problems.  We'll consider this done.  Open new issues for any bug or further requests.
