### ISSUE TITLE
Missing a couple of SpvCapability enum declarations

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Tools#641]
Is there a reason why `validation_state.cpp` references two `SpvCapability` values: `SpvCapabilityVariablePointers` and `SpvCapabilityVariablePointersStorageBuffer` that are not declared in the `SpvCapability` enum in `spirv.h`?

Am I missing something?

**Comment by dneto0** [comment]
Those two capabilities are recent additions to the public headers.  Get the latest SPIRV-Headers.

**Comment by billhollings** [comment]
@dneto0 

Ah...thanks. I had forgotten that the headers are sourced from another repo. All good now.
