### ISSUE TITLE
Multilib build issue with GCC-7.1.0

### ISSUE THREAD

**Issue by elkrejzi** [KhronosGroup/SPIRV-Tools#642]
When building Vulkan-LoaderAndValidationLayers-1.0.46.0 on Linux, SPIRV-Tools fails to build with the following error:

In file included from /sources/build/vulkan-loader/src/Vulkan-LoaderAndValidationLayers32-sdk-1.0.46.0/external/spirv-tools/source/opt/ir_loader.cpp:17:0:
/sources/build/vulkan-loader/src/Vulkan-LoaderAndValidationLayers32-sdk-1.0.46.0/external/spirv-tools/source/opt/log.h: In function 'void spvtools::Logf(const MessageConsumer&, spv_message_level_t, const char*, const spv_position_t&, const char*, Args&& ...) [with Args = {const SpvOp_&}]':
/sources/build/vulkan-loader/src/Vulkan-LoaderAndValidationLayers32-sdk-1.0.46.0/external/spirv-tools/source/opt/log.h:113:13: error: null destination pointer [-Werror=format-truncation=]
     snprintf(longer_message.data(), longer_message.size(), format,
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              std::forward<Args>(args)...);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is only true when building for 32 bit (gcc -m32). It builds fine for 64 bit using the same compiler. It built fine with GCC-6.3.0 previously.

**Comment by dneto0** [comment]
The compiler is warning on something it can't check correctly.  In fact the underlying code is ok, as it's the fallback case where we previously checked the return on a first-attempt snprintf.  But I can make GCC go quiet on this by handling the return value yet once more.

**Comment by elkrejzi** [comment]
See also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80655#c6

**Comment by dneto0** [comment]
I can't reproduce this with a locally-built GCC 7.1 on x86-64, including -m32.

However, I do have a patch ready that applies the advice given in the gcc bug report.

**Comment by dneto0** [comment]
@elkrejzi: please confirm that the issue is fixed for you.

**Comment by elkrejzi** [comment]
Confirmed. SPIRV-Tools git master builds fine.
