### ISSUE TITLE
Build failures due to dangling else

### ISSUE THREAD

**Issue by FireBurn** [KhronosGroup/SPIRV-Tools#643]
[ 67%] Building CXX object test/CMakeFiles/test_spirv_unit_tests.dir/opcode_table_get_test.cpp.o
/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_32.x86/external/spirv-tools/test/opt/set_spec_const_default_value_test.cpp: In member function ‘virtual void {anonymous}::DefaultValuesStringParsingTest_TestCase_Test::TestBody()’:
/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_32.x86/external/spirv-tools/test/opt/set_spec_const_default_value_test.cpp:45:8: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
     if (actual_map) EXPECT_THAT(*actual_map, Eq(tc.expected_map));
        ^

**Comment by FireBurn** [comment]
#644 Has been raised to fix this

**Comment by antiagainst** [comment]
#644 merged.
