### ISSUE TITLE
Compile Errors with GCC 7.1

### ISSUE THREAD

**Issue by FireBurn** [KhronosGroup/SPIRV-Tools#645]
Scanning dependencies of target test_spirv_unit_tests
[ 24%] Building CXX object test/CMakeFiles/test_spirv_unit_tests.dir/assembly_context_test.cpp.o
[ 24%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/build_module.cpp.o
[ 24%] Linking CXX executable spirv-val
In file included from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/test/parse_number_test.cpp:18:
/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                             ^~~
[ 24%] Built target spirv-val
Scanning dependencies of target test_string_utils
[ 24%] Building CXX object test/CMakeFiles/test_string_utils.dir/string_utils_test.cpp.o
[ 24%] Building CXX object tools/CMakeFiles/spirv-stats.dir/stats/stats_analyzer.cpp.o
In file included from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/test/log_test.cpp:15:
/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                             ^~~
[ 24%] Linking CXX executable spirv-cfg
[ 24%] Built target spirv-cfg
Scanning dependencies of target test_c_interface
[ 25%] Building CXX object test/CMakeFiles/test_c_interface.dir/c_interface_test.cpp.o
In file included from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/test/assembly_context_test.cpp:18:
/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                             ^~~
[ 25%] Linking CXX executable test_preserve_numeric_ids
[ 26%] Linking CXX executable test_diagnostic
[ 26%] Built target test_preserve_numeric_ids
[ 26%] Built target test_diagnostic
[ 26%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/compact_ids_pass.cpp.o
Scanning dependencies of target test_val_storage
[ 27%] Building CXX object test/val/CMakeFiles/test_val_storage.dir/val_storage_test.cpp.o
[ 28%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/def_use_manager.cpp.o
In file included from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/test/val/val_storage_test.cpp:21:
/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                             ^~~
[ 28%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/eliminate_dead_constant_pass.cpp.o
cc1plus: all warnings being treated as errors
make[2]: *** [test/CMakeFiles/test_log.dir/build.make:63: test/CMakeFiles/test_log.dir/log_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:972: test/CMakeFiles/test_log.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 28%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/flatten_decoration_pass.cpp.o
[ 29%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/function.cpp.o
[ 29%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/fold_spec_constant_op_and_composite_pass.cpp.o
[ 30%] Linking CXX executable spirv-stats
[ 30%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/freeze_spec_constant_value_pass.cpp.o
[ 30%] Built target spirv-stats
[ 31%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/inline_pass.cpp.o
cc1plus: all warnings being treated as errors
make[2]: *** [test/CMakeFiles/test_spirv_unit_tests.dir/build.make:63: test/CMakeFiles/test_spirv_unit_tests.dir/assembly_context_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:934: test/CMakeFiles/test_spirv_unit_tests.dir/all] Error 2
[ 31%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/instruction.cpp.o
[ 31%] Linking CXX executable test_string_utils
[ 31%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/ir_loader.cpp.o
[ 31%] Built target test_string_utils
[ 32%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/module.cpp.o
[ 32%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/set_spec_constant_default_value_pass.cpp.o
[ 32%] Linking CXX executable test_c_interface
[ 32%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/optimizer.cpp.o
[ 32%] Built target test_c_interface
[ 33%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/pass_manager.cpp.o
[ 33%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/strip_debug_info_pass.cpp.o
[ 34%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/types.cpp.o
[ 34%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/type_manager.cpp.o
[ 34%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/unify_const_pass.cpp.o
cc1plus: all warnings being treated as errors
make[2]: *** [test/CMakeFiles/test_parse_number.dir/build.make:63: test/CMakeFiles/test_parse_number.dir/parse_number_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:896: test/CMakeFiles/test_parse_number.dir/all] Error 2
[ 34%] Building CXX object test/val/CMakeFiles/test_val_storage.dir/__/unit_spirv.cpp.o
cc1plus: all warnings being treated as errors
make[2]: *** [test/val/CMakeFiles/test_val_storage.dir/build.make:63: test/val/CMakeFiles/test_val_storage.dir/val_storage_test.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/test/unit_spirv.cpp:17:
/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                             ^~~
[ 35%] Linking CXX static library libSPIRV-Tools-opt.a
[ 35%] Built target SPIRV-Tools-opt
cc1plus: all warnings being treated as errors
make[2]: *** [test/val/CMakeFiles/test_val_storage.dir/build.make:87: test/val/CMakeFiles/test_val_storage.dir/__/unit_spirv.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2046: test/val/CMakeFiles/test_val_storage.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
 * ERROR: media-libs/vulkan-loader-9999::FireBurn failed (compile phase):

**Comment by dneto0** [comment]
If I'm reading this correctly, the problem lies in googltest's googlemock component.  Have you filed a bug in upstream google/googletest?

**Comment by FireBurn** [comment]
I've not no, I wasn't sure if the issue was there, or just in the way you
were using googletest

**Comment by antiagainst** [comment]
Hey @FireBurn, is this still an issue for you with the latest googletest and SPIRV-Tools? Sorry I don't have an Linux box that can install GCC 7.1.

**Comment by FireBurn** [comment]
I switched back to GCC 6. GCC 7 was giving me too many issues in general

**Comment by antiagainst** [comment]
OK, thanks! I'll close this then.

**Comment by pierremoreau** [comment]
I just tried with the latest SPIRV-Tools and googletest, with GCC 7.2, and I get some conversion errors:
```
In file included from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /home/pmoreau/tmp/SPIRV-Tools/test/parse_number_test.cpp:18:
/home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                             ^~~
In file included from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /home/pmoreau/tmp/SPIRV-Tools/test/assembly_context_test.cpp:17:
/home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
In file included from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /home/pmoreau/tmp/SPIRV-Tools/test/diagnostic_test.cpp:18:
/home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                             ^~~
In file included from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /home/pmoreau/tmp/SPIRV-Tools/test/bit_stream.cpp:19:
/home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                             ^~~
In file included from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /home/pmoreau/tmp/SPIRV-Tools/test/huffman_codec.cpp:22:
/home/pmoreau/tmp/SPIRV-Tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
```

I might have a look at them; I tend to use clang over GCC, but it is pretty easy for me to switch between the two.

**Comment by antiagainst** [comment]
Cool, thanks @pierremoreau!

**Comment by pierremoreau** [comment]
It’s an issue within googletest: `typedef MatcherList<sizeof...(Args), Args...> MatcherListType;` passes a `size_t` as first template argument to `MatcherList` whereas it expects an `int`. Changing the definition of `MatcherList` to take a `size_t` as first template argument did let me build SPIRV-Tools without any other issues. I’ll ping the issue @FireBurn opened earlier.

**Comment by pierremoreau** [comment]
We should maybe reopen this issue until it is solved upstream?

**Comment by antiagainst** [comment]
@pierremoreau: I don't think so. Issues here should be for SPIRV-Tools. :)
