### ISSUE TITLE
Issue building under Clang

### ISSUE THREAD

**Issue by FireBurn** [KhronosGroup/SPIRV-Tools#652]
[ 44%] Building CXX object source/opt/CMakeFiles/SPIRV-Tools-opt.dir/module.cpp.o
[ 44%] Building CXX object test/CMakeFiles/test_spirv_unit_tests.dir/binary_strnlen_s_test.cpp.o
/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_32.x86/external/spirv-tools/source/opt/module.cpp:121:22: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
  auto write_inst = [this, binary, skip_nop](const Instruction* i) {
                     ^
1 error generated.
make[2]: *** [source/opt/CMakeFiles/SPIRV-Tools-opt.dir/build.make:351: source/opt/CMakeFiles/SPIRV-Tools-opt.dir/module.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:450: source/opt/CMakeFiles/SPIRV-Tools-opt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by dneto0** [comment]
Fixed with #653
