### ISSUE TITLE
spirv-val has inconsistent location reporting for errors

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/SPIRV-Tools#670]
Running spirv-val on a particular module I was looking at I got this:

```
info: 507: Duplicate non-aggregate type declarations are not allowed. Opcode: 32
error: 3095: The result pointer storage class and base pointer storage class in OpAccessChain do not match.
```

507 being the opcode index, and 3095 being the word count offset of the parameter in the OpAccessChain.

The latter I don't think is useful directly, but being able to identify the particular word is nice. I'd suggest that instead the opcode index should always be used since it's easy to look up in the spirv-dis output (apart from the comments at the start with the header, it's just the line number), and instead the error should be displayed something like `error: filename.spv:574:1: ...` similar to line:column numbers in compiler outputs.

As an aside, I didn't realise it was the opcode index until I looked at the source, although that's partly because one of them wasn't so I dismissed that possibility. It might be a good idea to explicitly call that out, and add an option to spirv-dis to display the opcode indices on the left-hand side similar to how it can display the word offset in hex as a comment on the right.

----

Extra bonus points if you used the disassembly to display context on what exactly is wrong, like this mockup:

```                                                                                 
output_dump.spv:507: info: Duplicate non-aggregate type declarations are not allowed.
%_ptr_Uniform_float_0 = OpTypePointer Uniform %float
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

output_dump.spv:431: note: First type declaration here
%_ptr_Uniform_float = OpTypePointer Uniform %float
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

output_dump.spv:574:1: error: The result pointer storage class and base pointer storage class in OpAccessChain do not match.
      %25242 = OpAccessChain %_ptr_Uniform_v4float %_entryPointOutput %uint_1
                             ~~~~~~~~~~~~~~~~~~~~~ ^^^^^^^^^^^^^^^^^^^^^^^^^^

output_dump.spv:422: note: %_ptr_Uniform_v4float declared here
%_ptr_Uniform_v4float = OpTypePointer Uniform %v4float
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

output_dump.spv:422: note: %_entryPointOutput declared here
%_entryPointOutput = OpVariable %_ptr_Output_VS_OUTPUT_0 Output
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


1 warning generated.
1 error generated.
```

**Comment by dneto0** [comment]
Thanks for the feedback.   The messages should be a lot better than they are.  It's good to know what you find more useful: the word offset or the opcode.    There are a handful of very low level failures in binary parsing that don't yet have an opcode in hand, but they should be the exception.

I'll add this issue to the general enhancements list.

**Comment by dneto0** [comment]
I prototyped something very simple yesterday, but I'm not particularly satisfied with it (and it also causes some test failures):    During instruction-by-instruction processing in the validator, if an error triggers then show the disassembled instruction right after the error.

Example:
```
$ spirv-dis --no-header y.spv
       %uint = OpTypeInt 32 0
               OpMemoryModel Logical Simple

$ spirv-val y.spv
error: 1: TypeInt cannot appear before the memory model instruction
%uint = OpTypeInt 32 0

```

It's a baby step to better messages.  Also it doesn't address your original request. :-(

Is this useful enough to include now? If so then I'll investigate the test failures.

**Comment by baldurk** [comment]
I think this is definitely a step in the right direction, the line should be (mostly) unique so apart from anything else it can still be used to ctrl-f to find the failing statement.

**Comment by dneto0** [comment]
With #1221 the validator will now print the disassembly of an offending instruction during its (essentially) first scan of the module.   It's a proper implementation of the idea from https://github.com/KhronosGroup/SPIRV-Tools/issues/670#issuecomment-327515131

After the initial scan, the validator's code is structured differently, counts differently, and other bad things.  Fixing that will take more work.

**Comment by dneto0** [comment]
(The spv_position_t concept has not changed since I took over this project, and that limits the amount of contextual information I can carry around without reworking a lot of code and introducing new entry points or concepts.  Sorry about that.)

**Comment by dj2** [comment]
I believe this should be pretty much done. The underlining of the exact error isn't done, but is also a lot harder to implement so I'm skipping it, if this is something you think is required please file a new bug so we can track the feature request.

We should be properly outputting line numbers and disassemblies now, if you see issues please let us know.
