### ISSUE TITLE
std::iterator will be deprecated in C++17

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#675]
As shown in http://en.cppreference.com/w/cpp/iterator/iterator. We use `std::iterator` in https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/iterator.h. Should investigate and migrate.

reported by @randomascii

**Comment by s-perron** [comment]
Fix by https://github.com/KhronosGroup/SPIRV-Tools/pull/4171.
