### ISSUE TITLE
Implement a linker for SPIR-V modules?

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-Tools#685]
Hello,

I have been working on a SPIR-V linker for [Mesa](https://www.mesa3d.org/), and thought that maybe it could live in SPIRV-Tools instead; I would then just link SPIRV-Tools to Mesa, like I already do to get the SPIR-V validator.
Would you be interested in having a linker here? (Or in SPIRV-LLVM, whichever place is the best fit for it.)

**Comment by dneto0** [comment]
Yes.  We'd be very interested in adding a linker to SPIRV-Tools.

A few of us have done an 90% job in a short time, but never got all the way to 100%.

It ought to reuse basic things like the binary parser.

**Comment by pierremoreau** [comment]
Is the code for any of those attempts available somewhere?
I have some code that does most of the job, but it does not remove names/types/decorations used by imported declarations, yet. This is only problematic for types, as the validator complains that some types are not the same, due to having different IDs.

I’ll try to reuse as much as I can. :-)

**Comment by dneto0** [comment]
Hey @AWoloszyn @antiagainst do you have your linker code lying around?

As always, remember the validator is not complete.   :-)
I'll still review carefully but will definitely be happy to review work-in-progress.

**Comment by antiagainst** [comment]
I don't think I've prototyped one... Or apparently I cannot find it anywhere.

I remember @AWoloszyn's implementation is based on Golang?

**Comment by pierremoreau** [comment]
Closing as this can be tracked in #693 now.
