### ISSUE TITLE
Validator fails to catch invalid input parameter types

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/SPIRV-Tools#694]
Hi,

the validator (with spir-v for vulkan 1.0 profile) fails to catch invalid input parameters, in our specific case it failed to report that OpAll only accepts boolean inputs.

**Comment by dneto0** [comment]
The validator is incomplete.  The backlog of missing functionality is captured in the validator project: https://github.com/KhronosGroup/SPIRV-Tools/projects/1

This issue is a special case of https://github.com/KhronosGroup/SPIRV-Tools/issues/696

**Comment by atgoo** [comment]
Fixed in https://github.com/KhronosGroup/SPIRV-Tools/pull/811
