### ISSUE TITLE
Eliminate unreachable blocks in a function:

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#702]
remove blocks that are not reachable from the entry point, nor are the merge block or continue target for any reachable loop header or selection header.
(From original #673)

**Comment by dneto0** [comment]
See note in AggressiveDCE:

> // Note: This function does not delete useless control structures. All
// existing control structures will remain. This can leave not-insignificant
// sequences of ultimately useless code.
// TODO(): Remove useless control constructs.

Eliminating unreachable blocks seems to be quite complementary.  For example, if code inside an unreachable block stores to a module-scope variable, then eliminating that block before running AggressiveDCE could allow AggressiveDCE to eliminate more code.   Also, it may be profitable to eliminate unreachable blocks after AggressiveDCE.

**Comment by dnovillo** [comment]
I've started working on this.

**Comment by dnovillo** [comment]
Fixed with #810.
