### ISSUE TITLE
Arithmetic absorption: add zero, multiply by 1.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#707]
Claimed opportunity in #664

**Comment by dnovillo** [comment]
IMO, these should be part of the folder in [source/opt/fold.cpp](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/fold.cpp)

**Comment by dnovillo** [comment]
I believe this is now done thanks to work by @s-perron.  Steven, could you confirm?

**Comment by s-perron** [comment]
@zeux implemented it in #1324.

**Comment by dnovillo** [comment]
Thanks.  Closing as resolved.
