### ISSUE TITLE
Convert if-then-else to OpSelect to collapse control flow.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#711]
E.g. example reduced from IfThenElse test in local_ssa_elim_test

if (c) { v = x; } else { v = y; } z = v;
Collapse to    z = OpSelect c x y

**Comment by alan-baker** [comment]
Found some examples in production shaders that would benefit from this opt and have started some initial work on it.

**Comment by alan-baker** [comment]
Committed in 2e93e806e454e2cfefabf217320038188c6c1fb6
