### ISSUE TITLE
Generalize --eliminate-local-multi-store / LocalMultiStoreElimPass so it works in the presence of common extensions.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#712]

**Comment by greg-lunarg** [comment]
I think I have this pass pretty well restricted now. It will only operate on variables which are only referenced by loads and stores.

It also will process code under all extensions except SPV_KHR_variable_pointers. Is this considered a "common" extension?

**Comment by greg-lunarg** [comment]
Are there other specific concerns?

**Comment by dneto0** [comment]
No concerns.  I'm just behind in marking things as "done".  :-(
