### ISSUE TITLE
Extend existing composite insert/extract elimination to image, storage buffer

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#713]

**Comment by dneto0** [comment]
WIP by @greg-lunarg , e.g. first step is https://github.com/KhronosGroup/SPIRV-Tools/pull/749

**Comment by s-perron** [comment]
I'm working on a value numbering based redundancy elimination.  This should be able to handle this. #960

**Comment by s-perron** [comment]
The value number work I did will not common loads from images when one of the parameter is the result of an OpSampledImage instruction.  This is because we will not common OpSampledImage instructions because they may end up in a different basic block from their use.

**Comment by s-perron** [comment]
We are not aware of a need for this.  We will close and open a new issue if we find an opportunity for this.
