### ISSUE TITLE
Strength reduction (PLACEHOLDER)

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#714]
E.g. integer divide by 8 becomes shift right by 3

**Comment by s-perron** [comment]
I've started working on this.  I'll be creating a new pass that will scan each instruction looking for these opportunities.  It should be easy enough to extend to other opportunities that look at a single instruction and those defining its operands.

**Comment by dneto0** [comment]
Multiply-by-power of 2 was handled by @s-perron's https://github.com/KhronosGroup/SPIRV-Tools/pull/815.

This issue will remain open as a PLACEHOLDER for other simple strength reductions.   I'll keep it open to list specific ideas, and to claim the work.
