### ISSUE TITLE
Promote suitable instructions to constant instruction

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#721]
For example, the following composite construct:

```llvm
[[d0:%\d+]] = OpCompositeConstruct %v3float %float_6 %float_7 %float_8
[[d1:%\d+]] = OpCompositeConstruct %v3float %float_9 %float_10 %float_11
[[d:%\d+]] = OpCompositeConstruct %mat2v3float [[d0]] [[d1]]
```

Could be turned into

```llvm
[[d0:%\d+]] = OpConstantComposite %v3float %float_6 %float_7 %float_8
[[d1:%\d+]] = OpConstantComposite %v3float %float_9 %float_10 %float_11
[[d:%\d+]] = OpConstantComposite %mat2v3float [[d0]] [[d1]]
```

This will further enable const folding passes.

**Comment by dneto0** [comment]
Ah, if making a composite out of only constants, then make the whole thing a constant.  Good idea.

**Comment by dneto0** [comment]
This is an "instcombine"-like optimization.

**Comment by antiagainst** [comment]
Yep. I am having this issue right now in spiregg codegen for variable initializers.

It seems the frontend lacks const folding support for HLSL specific types in DirectXShaderCompiler; so it ends up when we are generating intializers for some variables like vectors/matrices, we are always resolving to `OpStore`, even if the initializer is a constant.

**Comment by antiagainst** [comment]
And that seems suggesting another pass: using initializers to replace `OpStore`s. :)

**Comment by dneto0** [comment]
Can they go all the way to just an SSA  value and eliminate the local variable?  (Function storage class)?

@greg-lunarg contributed a number of passes recently that combine to do that.  E.g. see local_access_chain_convert_pass, local_single_block_elim_pass, local_ssa_elim_pass.    They have a few restrictions (e.g. they only work on entry point functions), but that could be generalized with some work.

**Comment by antiagainst** [comment]
True if not written to I think.

**Comment by dneto0** [comment]
Yes, there's a local_single_store_elim_pass  for when the store is written to only once.  Then all dominated loads can just use that one value.

**Comment by s-perron** [comment]
Done with #1283.
