### ISSUE TITLE
Replace zero-value constants with `OpConstantNull`

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#724]
For example, the following SPIR-V constant:

```llvm
[[vec:%\d+]] = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
[[mat:%\d+]] = OpConstantComposite %mat2v4float [[vec]] [[vec]]
```

Can be turned into

```llvm
[[mat:%\d+]] = OpConstantNull %mat2v4float
```

Shorter codegen; and I assume the performance should be at least on par?

**Comment by dnovillo** [comment]
This is folding plus constant propagation.

**Comment by s-perron** [comment]
There is not great value in doing this. We will not fix this.
