### ISSUE TITLE
Constant conditions not being turned to "true" or "false"

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Tools#731]
I have code that statically checks conditions in code. The resulting glsl obtained from optimized SPIRV, however, shows that these haven't been optimized. I end up with code like the following:

```
if (1.0 > 0.300000011920928955078125)
{
        _87 = vec4(1.0, 0.0, 0.0, 1.0);
}
else
{
        _87 = vec4(1.0, 1.0, 0.0, 1.0);
}
```

I don't know if this has been reported already but it would be really nice to support this. We rely on it a lot and our converted shaders end up very big, impacting load times.

**Comment by antiagainst** [comment]
Thanks for reporting, @redorav!

I think this is a concrete case for #709. It is currently not supported yet. And there are also lots of other optimization opportunities.

I'll keep this issue open until this special case is done. :)

**Comment by greg-lunarg** [comment]
Claimed.

**Comment by greg-lunarg** [comment]
I will actually write a framework that will support general constant folding. I will start by folding operations that result in booleans and add from there.

**Comment by antiagainst** [comment]
Just wanted to note that we've already gotten something that can aid folding constants: https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/fold_spec_constant_op_and_composite_pass.cpp

It would be nice if that code can be reused.

**Comment by dnovillo** [comment]
This should be handled by SSA-CCP (#889).  I'll make sure I handle this one as well.

**Comment by dnovillo** [comment]
4ba9dcc8 addresses this case but the folder still needs to be extended for floating point comparisons.  See #943.

**Comment by s-perron** [comment]
@redorav I believe most if this has been implemented in https://github.com/KhronosGroup/SPIRV-Tools/pull/1310.  Let me know if we can close this or if more work is needed.

**Comment by redorav** [comment]
@s-perron Sorry for not replying earlier, the work on opengl we were doing when I filed the bug has been parked for a while and I don't know when we'll resume it, but if at that point I find any issues I'll reopen. Thanks for the awesome work you're all doing.
