### ISSUE TITLE
validate_ssa.cpp not found?

### ISSUE THREAD

**Issue by drillsar** [KhronosGroup/SPIRV-Tools#734]
I am getting this error when updating Spirv-tools. Can someone point me to when and if this file was deleted? And the commit please?

**Comment by antiagainst** [comment]
This commit: https://github.com/KhronosGroup/SPIRV-Tools/commit/66c94928a324efd7d3c2d10817e8fb599096302b?

**Comment by drillsar** [comment]
Ok; now I am getting this error:
d:\xeniacopy\third_party\spirv-tools\source\ext_inst.cpp(39): fatal error C1083: Cannot open include file: 'glsl.std.45
0.insts-1.0.inc':

**Comment by pierremoreau** [comment]
If you haven’t done it already, try running `ccmake .` in your build folder, before rebuilding the project. I found it to be necessary when adding a new file to `CMakeLists.txt`, as it wouldn’t generate new rules for it otherwise.

**Comment by dneto0** [comment]
Were you ever able to build SPIRV-Tools?
Are you building in-tree or out of tree?  I always build out-of-tree.

I don't know how to help without knowing you got your sources or configured your build.

**Comment by antiagainst** [comment]
Closing since not hearing back for quite a while.
