### ISSUE TITLE
Support for unrolling of constant loops

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/SPIRV-Tools#758]
Hello. I suggest add support of unrolling constant loops if have no breaks and have not dynamic max value.

**Comment by capitalknew** [comment]
I suggest for it set unrolling limit flag (for example, unroll when looping ranged to N). Also, I suggest making unroll optimization of binary code (if SPIR-V compiled from GLSL code, not originally SPIR-V).

**Comment by dnovillo** [comment]
Seems to be a dup of #636

**Comment by s-perron** [comment]
Done with #1230.
