### ISSUE TITLE
Inliner: When cloning an OpPhi, ID of forward reference to a value is copied instead of taking next ID

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#782]
Example input:
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main"
               OpSource GLSL 450
               OpName %main "main"
               OpName %foo_ "foo("
               OpName %x "x"
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
          %7 = OpTypeFunction %int
       %bool = OpTypeBool
       %true = OpConstantTrue %bool
      %int_0 = OpConstant %int 0
%_ptr_Function_int = OpTypePointer Function %int
       %main = OpFunction %void None %3
          %5 = OpLabel
          %x = OpVariable %_ptr_Function_int Function
         %19 = OpFunctionCall %int %foo_
               OpStore %x %19
               OpReturn
               OpFunctionEnd


       %foo_ = OpFunction %int None %7
          %9 = OpLabel
          %a = OpCopyObject %int %int_0
               OpSelectionMerge %13 None
               OpBranchConditional %true %12 %13

         %13 = OpLabel
;;;; The ID for %b here isn't cloned in the inlined copy of this OpPhi. It's just copied.
     %result = OpPhi %int %a %9 %b %12
               OpReturnValue %result

         %12 = OpLabel
          %b = OpCopyObject %int %int_0
               OpBranch %13
               OpFunctionEnd
```
Running  spirv-opt --inline-entry-points-exhaustive on this yields:

```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main"
               OpSource GLSL 450
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpName %main "main"
               OpName %foo_ "foo("
               OpName %x "x"
       %void = OpTypeVoid
          %6 = OpTypeFunction %void
        %int = OpTypeInt 32 1
          %8 = OpTypeFunction %int
       %bool = OpTypeBool
       %true = OpConstantTrue %bool
      %int_1 = OpConstant %int 1
      %int_0 = OpConstant %int 0
%_ptr_Function_int = OpTypePointer Function %int
       %main = OpFunction %void None %6
         %14 = OpLabel
         %22 = OpVariable %_ptr_Function_int Function
          %x = OpVariable %_ptr_Function_int Function
         %23 = OpCopyObject %int %int_0
               OpSelectionMerge %24 None
               OpBranchConditional %true %25 %24
         %24 = OpLabel
         %26 = OpPhi %int %23 %14 %21 %25
               OpStore %22 %26
               OpBranch %27
         %25 = OpLabel
         %28 = OpCopyObject %int %int_0
               OpBranch %24
         %27 = OpLabel
         %15 = OpLoad %int %22
               OpStore %x %15
               OpReturn
               OpFunctionEnd
       %foo_ = OpFunction %int None %8
         %16 = OpLabel
         %17 = OpCopyObject %int %int_0
               OpSelectionMerge %18 None
               OpBranchConditional %true %19 %18
         %18 = OpLabel
         %20 = OpPhi %int %17 %16 %21 %19
               OpReturnValue %20
         %19 = OpLabel
         %21 = OpCopyObject %int %int_0
               OpBranch %18
               OpFunctionEnd

```
This fails validation with this message:
error: 50: In OpPhi instruction 26, ID 21 definition does not dominate its parent 25

The trouble is this instruction:
```
         %26 = OpPhi %int %23 %14 %21 %25
```
That %21 is a stale (copied) reference to an SSA name in the callee function, but should have been allocated a new ID.

The basic structure of the test case is like this:
```
int foo() {
  int result = 1;
  if (true) {
     result = 1;
  } 
  return result;
}   

void main() {
 int x = foo();
}
```
but with modifications: Using Phi instead of load/store, and the return block in foo appears before the "then" block.

**Comment by dneto0** [comment]
Cc: @greg-lunarg This is the reduced test case for the bug I mentioned earlier today.

I'm pretty sure the bug is in the 'default' case in InlinePass::GenInlineCode.  I'll be staring at it some more today.

**Comment by greg-lunarg** [comment]
First impression: I thought I had code to deal with forward references. Must have missed a case.

**Comment by greg-lunarg** [comment]
Yes, this doesn't look right. It is not doing anything in the case of non-label forward references.

Not sure why I didn't anticipate non-label fwd refs. You would get them with any loop.

**Comment by greg-lunarg** [comment]
Well, any loop with an induction value.

**Comment by greg-lunarg** [comment]
I have a handle on this if you want to pass it off.

**Comment by greg-lunarg** [comment]
First idea: before generating code, do pass through callee and map all result ids to new ids. Then remapping operand and result ids during generation is straightforward. No special casing of forward refs, labels, etc.

**Comment by dneto0** [comment]
Thanks for taking a look.  I haven't made any forward progress, and can't devote any more time to it in the next 20 hours.  You can have it.  :-)   I'll jump on any pull request you put up for it.

Your two-pass approach makes sense to me, and seems very durable / bullet proof.  

There might be interesting corner cases with things like function parameters, but the existing code skips over those as previously processed, and that is likely the same case here.

Also, it would be totally fair to err on the side of simplicity and allocate IDs that you might not use.  Gaps are perfectly ok.

Thinking about the impact on testing:  It might be a pain to update all the tests if the IDs become scrambled vs. the current test code.   You might be helped by the assembler's option to preserve numeric IDs:  SPV_TEXT_TO_BINARY_OPTION_PRESERVE_NUMERIC_IDS.  That might be useful in the test fixture used by the inliner tests.

**Comment by greg-lunarg** [comment]
Good catch on scrambling of ids. I used a slightly different approach than I first described, just capturing all result ids for the callee. I used them to identify forward references (instead of looking for labels). This kept the rest of the logic pretty similar and didn't scramble the ids in the tests.

**Comment by dneto0** [comment]
Fixed with https://github.com/KhronosGroup/SPIRV-Tools/pull/784
