### ISSUE TITLE
Validator doesn't check Sampled Type of OpTypeImage instruction

### ISSUE THREAD

**Issue by paniq** [KhronosGroup/SPIRV-Tools#785]
The [specs](https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#OpTypeImage) state that
> _Sampled Type_ is the type of the components that result from sampling or reading from this image type. Must be a scalar numerical type or `OpTypeVoid`.

which means that passing a vector type is illegal. Nevertheless the validator does ignore if a vector type is passed as _Sampled Type_.

**Comment by dneto0** [comment]
The validator is quite incomplete. I'll add this to the validator project.

**Comment by antiagainst** [comment]
I think we now have checks for it:

https://github.com/KhronosGroup/SPIRV-Tools/blob/8ba68fa9b94da071e879e3064adf8aaaea1a7051/source/validate_image.cpp#L607-L624
