### ISSUE TITLE
validator: ProcessExtensions quits early if it encounters a debug instruction

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#806]
The validator can fail to register an extension if a debug instruction appears before an OpExtension instruction

**Comment by atgoo** [comment]
Should the validator not fail this due to incorrect module layout?

**Comment by dneto0** [comment]
OpModuleProcessed is a debug instruction new in 1.1.  I've been convinced by @sheredom that there is no restriction on where it can be placed.  But perhaps that is debatable.

**Comment by dneto0** [comment]
SPIR WG agreed to restrict OpModuleProcessed to section 7 of the layout.
