### ISSUE TITLE
ValidationState_t::UseDefTracker::FindDef is a linear time lookup

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#81]
It's a very common operation. It should use a lower complexity (by op count) algorithm.

Secondarily, the FindUsesWithDefs is algorithmically inefficient, and perhaps could be fixed at the same time.

**Comment by dekimir** [comment]
Fixed via 4a722d80a62b1b1965a0b46f97edde3abbd4d2dd.
