### ISSUE TITLE
Need pass to eliminate dead types and global variables from module

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#833]
Once dead functions have been eliminated from a module, we will want to remove dead types and global variables.

We will also want to remove dead constants, but there is already a pass to remove dead constants from a module. It seems like we could leverage this code, especially for types as they have a similar recursive nature.

Probably want to eliminate dead variables before dead types as they may contain (ultimately dead) references to the types.

With dead function and constant elimination, this pass would eliminate the need to link spirv-remap into glslang, at least for the purposes of dead code elimination. In fact, the DCE capability of spirv-remap can probably be retired once this is implemented.

**Comment by antiagainst** [comment]
Dead type and dead constant removal is kinda dependent on each other since we need constants to define types and types to define constants sometimes. So it makes sense to combine them into one.

**Comment by dneto0** [comment]
@s-perron and @dnovillo are taking a look at overhauling / refactoring the IR classes, and will likely add a types-pool and constants-pool mechanism. That would likely subsume this specific feature.

**Comment by s-perron** [comment]
Yes making sure that unused types, variables, and constants will be part of the we are planning.  Given the way that these are represented, I think it should be part of the unified dead code elimination work we have discussed.

**Comment by dnovillo** [comment]
And, as I learned yesterday, names must be part of this too.  When a named
label is removed, for instance, its OpName must be removed or the code will
not validate.

David, does this happen to any other name too?

**Comment by alan-baker** [comment]
Handled by ADCE (via #1147)
