### ISSUE TITLE
Spec bug: OpConvertPtrToU wrong result type

### ISSUE THREAD

**Issue by atgoo** [KhronosGroup/SPIRV-Tools#837]
In the description of OpConvertPtrToU

Result Type must be a scalar **or vector** of integer type, whose Signedness operand is 0.
should be
Result Type must be a scalar of integer type, whose Signedness operand is 0.

**Comment by johnkslang** [comment]
SPIR-V specification issues should be submitted against the [SPIR-V headers project](https://github.com/KhronosGroup/SPIRV-Headers).
