### ISSUE TITLE
Validate OpBitCount ResultType component bit width.  Ensure they are wide enough to hold width of base as an unsigned value.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#843]
Fix the TODO in https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/validate_bitwise.cpp#L239

**Comment by jcaraban** [comment]
How can we possibly create a failing test for this requirement, if even the smallest unsigned integer (u8 = [0,256]) can always hold the width of the largest integer (64b < 256) ?

**Comment by dneto0** [comment]
Aw dang.   SPIR-V can be used with arbitrary bit widths.
But the validation rules say you *only* get certain bit widths unless you enable more by capabilities. And we don't have a capability for any larger than 64 bits.

So you're right, there's no use implementing the check right now.  :-(
Can you remove the TODO?  :-)

**Comment by dneto0** [comment]
Resolved by https://github.com/KhronosGroup/SPIRV-Tools/pull/851
