### ISSUE TITLE
DefUseManager does not scale well on large modules

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#846]
Analyzing a module with thousands of instructions is very slow.
E.g. see AppVeyor failures in #693 where it's taking more than 15 minutes to analyze a module with 65K instructions.

Manually sampling shows the slowness is in DefUseManager::AnalyzeDefUse, in AnalyzeInstDef -> CLearInst -> EraseUseRecordsOfOperandIds and thereabouts.

**Comment by dneto0** [comment]
FYI @s-perron for your consideration.   :-)

**Comment by dneto0** [comment]
Tiny progress with #848, getting 3x speed up on a module with ~65K instructions, on Windows debug build.

**Comment by s-perron** [comment]
The long running test is:

17 - spirv-tools-test_link_global_values_amount (Timeout)

**Comment by dneto0** [comment]
@s-perron is planning a refactor of the ir::Instruction class that will move responsibility of use-to-def mapping out of DefUseManager.  What remains is the def-to-use mapping, and that's the slow bit: it's based on std::list and scales very badly when there are many uses.  (E.g. think of 10K instructions resulting in uint result; then the uint type has 10K uses, and each lookup is linear time.)

I surveyed the existing usage pattern of DefUseManager::GetUses.   All the cases boil down to:
- detect whether an Id has any uses
- if so, do something for each use.
- that "something"  really does access the underlying instruction, e.g. inspecting the opcode.
- clients of DefUseManager ignore the operand_index field.  This is surprising.
   - the operand_index field is *only* used within DefUseManager::ReplaceAllUsesWith.  That itself could be eliminated by scanning over all operands that are of id type, an replacing those that match the 'before' value.

Therefore:
 - Internally for each Use we can just store the using instruction for each use rather than instruction and operand_index. (!)
 - We could replace the GetUses interface with 
      - a ForEachUser that iterates over all instruction that uses the given id (this is the common case)
      - a ForEachUse that iterates over all (instruction, operand_index) pairs.  (Which could be derived via scanning)

- The underlying storage could be an (ordered) std::set<Instruction*, Instruction*> mapping def instruction to use instruction, and where the less comparison is less on the instruction ids.  
   - The iteration over uses for a def would start use the lower_bound method to find first candidate iter, and then continue until you run off the end of the set or reach the next def instruction.
   - Maintenance operations have logarithmic operation complexity. (Though of course the cache behaviour could be not so great.)
- The distribution of number of uses per instruction could be very skewed so we could add a small-object optimization.   I expect something like a power law distribution.
    - An extreme case is an instruction which has no result id can't be used anywhere.
    - I imagine that most result ids are used at most twice.

**Comment by dneto0** [comment]
I haven't analyzed the unit tests for DefUseManager, but those would have to adjust in any case.

**Comment by dneto0** [comment]
Cc @greg-lunarg : I expect this scalability problem is a key driver of the slowness in your use cases.  When  we get to thousands of instructions per module, the DefUseManager blows up somewhat.

**Comment by greg-lunarg** [comment]
Does the 65K module come from an OGL or OCL shader?

**Comment by dneto0** [comment]
It was a test case for the linker.  https://github.com/KhronosGroup/SPIRV-Tools/pull/693 
So it's artificial, and as bad a case as you can get.
But I think if you're getting a few thousand instructions in a module then you'll start seeing some basic types being used many many times.  So it slows down but is at the annoying level rather than catastrophic.  But then you're also running 15 or so passes, and then the slowness scales linearly with number of passes.

**Comment by greg-lunarg** [comment]
I think the reforms you have outlined sound like a good start.

**Comment by atgoo** [comment]
What about this monstrosity:
unordered_multimap < def_inst , multimap<<use_opcode, use_inst>, operand_index> >
It allows to
- iterate over all uses as before
- iterate over all uses with a specific opcode
- delete instruction use in logarithmic time

**Comment by dneto0** [comment]
> What about this monstrosity:
unordered_multimap < def_inst , multimap<<use_opcode, use_inst>, operand_index> >

Yes, that would also work.  I was trying to stay away from too many containers, since I want to avoid space overhead and allocator work overhead.  

When destroying an instruction you already have to update each user (e.g. via ReplaceAllUsesWith), so there's already a step that is linear in the number of users.  Using std::set::erase(first, last) form the operation complexity is log(c.size()) + std::distance(first, last) which good.

I also forgot to mention the trick that when doing lower_bound and upper_bound for a given target ID, you need a key with a use instruction, but that can be an artificial "use" instruction that has result id 0.

**Comment by atgoo** [comment]
Yes, the key is (opcode, 0) for the lower bound of all uses with the opcode.

Then I talk about deletion of instruction I mean the deletion of the user, not the definition. That doesn't need to be linear, but currently probably is (you need to find the right Use entry in the list and delete it).

**Comment by dneto0** [comment]
> Then I talk about deletion of instruction I mean the deletion of the user, not the definition. That doesn't need to be linear, but currently probably is (you need to find the right Use entry in the list and delete it).

Right.  In my scheme deleting a user is num-distinct-used-ids * log(num instructions)

**Comment by alan-baker** [comment]
Working on this.

Both proposals would introduce non-determinism when iterating through uses. We cannot rely on the uses of a def having a result id. Instead, I will introduce an unique id to all instructions. This id will be generated by the IRContext. A side-effect of this is that all Instruction will require access to an IRContext at construction (the point will be cached in Instruction). A separate side effect is that all instruction will be strictly tied to an IRContext.

**Comment by dnovillo** [comment]
SGTM.  One thing we could allow for instructions that may be temporary is
to have the constructor accept a nil context.  Though, I'm not sure if this
is actually useful because as soon as the instruction is added to some
list, it will need a specific context.

**Comment by dneto0** [comment]
Fixed by #987

**Comment by dneto0** [comment]
Hey @greg-lunarg and I'd be interested in hearing if this makes your flows noticeably faster.
