### ISSUE TITLE
Add merge-return pass

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#857]
Transform each  reachable function so that:
- it has at most one basic block with an OpReturn or OpReturnValue
- that basic block post-dominates all reachable blocks (modulo those ending with OpKill)

Expose a general purpose helper function that does this transform on a single SPIR-V function.

Motivated by https://github.com/KhronosGroup/SPIRV-Tools/issues/850

**Comment by cwabbott0** [comment]
Btw, we already have a pass to do this in Mesa: https://cgit.freedesktop.org/mesa/mesa/tree/src/compiler/nir/nir_lower_returns.c -- feel free to steal the algorithm!

Note that what it's doing is more complicated than just wrapping the entire thing in a loop, and should generate better code in most cases, at least on Intel.

**Comment by s-perron** [comment]
@alan-baker is working on this.

**Comment by dneto0** [comment]
@s-perron is working on this
