### ISSUE TITLE
Tool request for SPIR-V reflector

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/SPIRV-Tools#859]
It would be useful to be able to get SPIR-V reflection information analogous to glslang reflection, but after optimization.  For example, having it on the SPIR-V would solve problems where glslang reflection reports a  texture active, but it then gets dead code eliminated and removed in a spirv-opt pass.  

The reflection interface in glslang is here: https://github.com/KhronosGroup/glslang/blob/2c9c2af64091da92833c6f457f3b043fd5aaf5c6/glslang/Public/ShaderLang.h#L619

In addition to those methods, the glslang::TType provides lots of extended reflection information.  Some of the information we use from that includes:
* TType::getQualifier()
* glslang::TQualifier::hasBinding() and glslang::TQualifier::layoutBinding
* glslang::TQualifier::hasSet() and glslang::TQualifier::layoutSet
* TType::getSampler()
* glslang::TSampler::isTexture() and glslang::TSampler::dim (for example for differentiating HLSL Buffer<> from regular texture)
* glslang::TSampler::isImage()
* glslang::TSampler::isSubpass()
* glslang::TSampler::isPureSampler()
* glslang::TQualifier::storage

A non-obvious one is TProgram::getUniformBlockCounterIndex() which is specifically about getting the hidden UAV counter buffer associated with a UAV in HLSL.

**Comment by dneto0** [comment]
I wrote some prototype code to scan an entry point's static call graph get info bout resources that entry point used.

* It extracts the Vulkan descriptor set and binding for each resource.
* It does not handle decoration groups
* The source-level name of a resource is not necessarily available.  Debug instructions could have been stripped.
* It is written to depend only on the binary parser callback interface.  I expect the job would be easier if we reused the machinery being developed inside the SPIRV-Tools optimizer.

* It's probably relatively easy to add some other things like layout and type information.  I haven't worked out the details.

**Comment by mbechard** [comment]
This is also very important to me. Does the reflection in SPIRV-cross solve this?

**Comment by danginsburg** [comment]
I think this tool probably does everything I originally asked for here:

https://github.com/chaoticbob/SPIRV-Reflect

We could close this bug.

**Comment by dneto0** [comment]
Sorry for the inattention on this.

We actually would like to pull SPIRV-Reflect into this repo and take over maintainership. 
There's a better shot that our team has more bandwidth to maintain it than @chaoticbob does.

**Comment by mbechard** [comment]
@dneto0, @s-perron  What is the status of this now. Are the reflection tools in SPRIV-Tool good enough that I can move away from SPIRV-reflect?
Thanks

**Comment by mbechard** [comment]
Looks like SPIRV-reflect was pulled into Khronos' organization. Does this mean it's the preferred tool to do reflection going forward? Will SPIRV-Cross be more feature complete? What's the suggested guidance?

**Comment by dj2** [comment]
I believe there are no plans to pull reflection into SPIRV-Tools at this point as SPIRV-Reflect has become its own Khronos project. 

You'll need to ask about SPIRV-Cross features on the github.com/KhronosGroup/SPIRV-Cross repo as that's a separate tool then SPIRV-Tools.
