### ISSUE TITLE
cmake_policy CMP0048

### ISSUE THREAD

**Issue by SWIFTingAround** [KhronosGroup/SPIRV-Tools#864]
When including this Project as subdirectory, cmake pushes a warning about the [CMP0048 Policy](https://cmake.org/cmake/help/latest/policy/CMP0048.html). This would be fixed when adding
```cmake
if (POLICY CMP0048)
  cmake_policy(SET CMP0048 NEW)
endif()
```
after `cmake_minimum_required(VERSION 2.8.12)`.

**Comment by dneto0** [comment]
Agree.
Basically, the CMake project directive now has the option to set version.
Since SPIRV-Tools does not set it, CMake issues a warning.
