### ISSUE TITLE
Add Travis config to check the Android build

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#871]
#861 adds an Android.mk to SPIRV-Tools.
So now the Travis-CI check should check the Android build.  That's the best way ensure it continues to work.
E.g. look to google/shaderc for an example of doing this.

**Comment by dneto0** [comment]
Right.  The Shaderc BUILD_NDK is building Shaderc using the same toolchain that the Android NDK build uses.  It's not checking the ndk-build flow.  :-(

**Comment by dneto0** [comment]
I think @antiagainst experimented with downloading the NDK to check this kind of thing.  But that's very heavyweight and possibly not worth the trouble.  I always check those flows whenever refreshing the Shaderc sources in the NDK itself.   So perhaps this is not worth it.

I'd like @antiagainst to confirm my memory here.

**Comment by antiagainst** [comment]
Yes, we do a fresh check out of Android NDK from https://github.com/urho3d/android-ndk (the repo is specifically for Travis CI use as per its description) for each build. It's heavyweight, but seems working reasonably well. Travis CI glitches we've encountered thus far are basically for macOS. No cases are related to downloading Android NDK that I can remember. And if you check the threads for a build job, the NDK one typically completes first. :)

We also use the same approach for testing glslang on Android (https://github.com/KhronosGroup/glslang/pull/889). So I think it should be fine to do something similar here.

And apparently Android NDK won't be preinstalled on Travis CI: https://github.com/travis-ci/travis-ci/issues/5395. We can do some caching, but I've never made that work previously.

**Comment by antiagainst** [comment]
But we are testing the CMake configuration for Android essentially for both glslang & shaderc, not Android.mk.

**Comment by antiagainst** [comment]
I think this is done via #897.
