### ISSUE TITLE
Capability validation code uses switch statements redundant with data already in the AssemblyGrammar

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#88]
Commit 61a62758 added a capability validation code that uses switch statements to get dependencies on capabilities.
All that data is already encoded in the AssemblyGrammar; see initialized tables in operand.cpp. 
Duplicating the tables is a bad idea for maintenance reasons.

**Comment by dekimir** [comment]
Fixed by 0c8bdfe163df0d118ef68cfa41e777e42339d412.
