### ISSUE TITLE
Implement Sparse Conditional Constant Propagation (SSA-CCP)

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#889]
This will implement the algorithm proposed in https://dl.acm.org/citation.cfm?id=103136.  This implementation has several pre-requisites:

- [x] Phi placement.  Although there is an implementation of Phi placement in local_ssa_elim_pass.cpp, it assumes structured control flow.  A more generalized form of Phi placement (i.e., pruned SSA form) may be required.
- [x] CFG edges.  Needed for the simulation done during constant propagation.
- [x] Propagation engine.  The propagation logic for SSA-CCP can be shared by other transformations (value range propagation, attribute and copy propagation).
- [x] Constant folding.  Some of the logic needed to fold integer constants exists in opt/fold.{cpp,h}.  More logic will need to be added to fold floating point.
- [ ] Control Flow cleanups.  In particular, straightening of conditional branches.  Constant propagation can convert predicates for conditional jumps into compile-time constant values 'true' or 'false'.  This allows CFG cleanups to completely remove the conditional branch.

I will be creating new issues for these pre-requisites and link them to this issue.

**Comment by dnovillo** [comment]
Fixed with 4ba9dcc8.  The remaining issue is being tracked in #1124.

**Comment by dneto0** [comment]
Reopening since the last step of CFG cleanups is still pending.

**Comment by dneto0** [comment]
Never mind. I see #1124 is open for the last bit
