### ISSUE TITLE
Get rid of SPV_VALIDATE_*_BITs

### ISSUE THREAD

**Issue by dekimir** [KhronosGroup/SPIRV-Tools#89]
Let's discuss whether and how we can get rid of these options.  I suspect that the vast majority of users doesn't need sophisticated ways to turn off certain validations.  Furthermore, the options are intertwined in unexpected ways -- for instance, multiple validations need `_.current_layout_section_`, but this is only computed when `SPV_VALIDATE_LAYOUT_BIT` is set.

Unit tests also shouldn't need fine-grained controls of this kind -- those that do aren't really _unit_ tests.  Moreover, it's fishy design to add so much API just for testing purposes.

My opinion is that we should eliminate these controls altogether, perform full validation always, and fix unit tests to have minimally invalid assembly or invoke only specific validations directly.

@umar456 @dneto0 @AWoloszyn ^^

**Comment by umar456** [comment]
I was planning on using spvBinaryParse like [this](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/validate.cpp#L325) and calling the passes individually. This should be easily generalizable in a fixture.

**Comment by umar456** [comment]
I tried a couple of approaches to get around this. One approach was to pass the `*Pass` function pointers to the `ValidateInstructions` function. Another was to ignore the errors based on the type of flags passed into the `ValidateState_t::diag` function. I don't think either of these approaches solved the problem we have been experiencing.

The only solution would be to parse the entire binary for each of the passes. This will allow us to test for each type of pass independently. This will obviously be slower but might solve this issue.

Thoughts?

**Comment by dekimir** [comment]
@umar456 I don't like the idea of needless repeated parsing.  Is it not possible to fix the test assemblies not to trigger unrelated validations?  A lot of the time it's something trivial, like missing `OpMemoryModel`.

**Comment by dekimir** [comment]
@umar456 is it OK if we assign this to someone on our team?

**Comment by umar456** [comment]
sure

**Comment by antiagainst** [comment]
In `master` as b6ccd0d89114d94026871edd31cf886280dad20a.
