### ISSUE TITLE
Add CFG edge data structure

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#894]
This is a pre-requisite for #889.  SSA-CCP traverses CFG edges to simulate execution and predicate evaluation.  This requires def-use edges (provided by the def-use manager) and CFG edges (currently built ad-hoc by passes that need them).

The work needed here would mostly re-factor the creation of CFG edges.

**Comment by dnovillo** [comment]
Implemented by #985.

**Comment by antiagainst** [comment]
#985 is merged. Should we close this?

**Comment by dnovillo** [comment]
Yes.  I was convinced I had closed it.  Thanks for the heads up.
