### ISSUE TITLE
Linker:  Incorrect handling of removal of FuncParamAttr when that is a grouped decoration

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#898]
RemoveLinkageSpecificInstructions has this code:
```
 // Remove FuncParamAttr decorations of imported functions' parameters.
  // From the SPIR-V specification, Sec. 2.13:
  //   When resolving imported functions, the Function Control and all Function
  //   Parameter Attributes are taken from the function definition, and not
  //   from the function declaration.
  for (const auto& linking_entry : linkings_to_do) {
    for (const auto parameter_id :
         linking_entry.imported_symbol.parameter_ids) {
      for (ir::Instruction* decoration :
           decoration_manager->GetDecorationsFor(parameter_id, false)) {
        switch (decoration->opcode()) {
          case SpvOpDecorate:
          case SpvOpMemberDecorate:
            if (decoration->GetSingleWordInOperand(1u) ==
                SpvDecorationFuncParamAttr)
              decoration->ToNop();
            break;
          default:
            break;
        }
      }
    }
  }
```

This does the wrong thing if the FuncParamAttr is on a grouped decoration, and that grouped decoration applies to other IDs.

E.g. 
   OpDecorate %group FuncParamAttr
   %group = OpDecorationGroup
   OpGroupDecorate %group  %a %b %c

If the above code is triggered on id %a, then it will change the OpDecorate to an OpNop and lose the effect of the decorations on %b and %c.

Thanks to @s-perron for asking the question that lead to this: The question is "Why does the decoration manager have a GetDecorationsFor overload that returns non-const Instruction pointers" ?

**Comment by pierremoreau** [comment]
Oops, my bad… that is completely wrong indeed. I am not entirely sure how this should be handle in this case: should the `DecorationManager` be extended to allow removing a specific decoration from an ID, or have some custom code in `RemoveLinkageSpecificInstructions`?

**Comment by dneto0** [comment]
No problem.  I missed it on code reviews. :-)

Good question on how to handle it.  Normally I'd say add a method to the decoration manager.  HOWEVER, updating instructions often involves updating bookkeeping in several different places.
For example, removing the group decoration from an ID should also update any life DefUseManagers.  But you don't want to couple everything to everything. 

You also don't want to make web of publish/subscribe relationships between managers.  That's really hard to trace and can kill performance.

For a long time it's been clear we need something like an "IRContext" that will handle all these details in consistent way. It would embed (by composition) a DefUseManager and a DecorationManager, and still allow those things to be unit-tested (at least in principle.)

But we're not there  yet (hopefully soon!).

....(thinks for a couple of minutes)...

I suggest you add a method to DecorationManager to kill a decoration (by enum) for an ID.  Perhaps it can take a change-notify callback std::function<void(ir::Instruction* inst, bool)> 
It is called on any instruction which is updated:   The callback is called before "inst" is updated, with the bool arg true.  For any instructions that were updated but still exist after the update, it's called again on that inst, but with bool arg false.
So:
   // Removed |decoration_kind| decorations targeting the given |target| id.
   // The |change_notify| callback is invoked on each decoration instruction that is updated:
   //  - before changing the instruction, with bool argument true
   //  - if the instruction still exists after the update, once again with bool argument false
   void RemoveDecoration(uint32_t target, uint32_t decoration_kind, std::function<void(ir::Instruction*, bool)> change_notify);

I think this lets us write nicer code.

I realize this doesn't quite fit the case of LinkageAttribute where you might want to remove the Import decoration but not an export decoration.    To be fully general you'd probably want to replace the second parameter with a predicate function to tell you when a decoration should be removed, e.g. 
   void RemoveDecorations(uint32_t target, std::function<bool(uint32_t decoration_kind, const std::vector<uint32_t>& decoration_args)> , .... change_notify);
  Where the predicate returns true if the decoration should be removed.

Let me know what you think.  :-)

**Comment by pierremoreau** [comment]
I was wondering as well how to keep both manager up-to-date, without connecting them together.

That method doesn’t need to remove groups, a later pass could take care of removing empty groups, but we still need to update the uses, so the callback thing is probably a good idea, at least until there is an “IRContext” or something similar. And that predicate seems to be a really good idea. 🙂
