### ISSUE TITLE
eliminate group-decorate-of-group-decorate case in DecorationManager

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#924]
We can remove https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/decoration_manager.cpp#L161 and 
https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/decoration_manager.cpp#L171 cases because in a valid SPIR-V module:

An OpDecorationGroup result-id can't be one of the targets for an OpGroupDecorate or OpGroupMemberDecorate.  An OpDecorationGroup can only be the target for OpDecorate and OpDecorateId.

We should remove the confusing code that tries to handle the invalid case.

**Comment by pierremoreau** [comment]
Where in the spec does it say that an OpDecorationGroup can only be used as a target to OpDecorate and OpDecorateId? I would love to get rid of group-decorate-of-group-decorate-of-group-decorate etc. cases, but I couldn’t find such restrictions in the spec.

**Comment by dneto0** [comment]
I'll see if I can recall the argument

From the OpDecorationGroup description:

> A collector for Decorations from OpDecorate and OpDecorateId instructions. All such decoration instructions targeting this OpDecorationGroup instruction must precede it. Subsequent OpGroupDecorate and OpGroupMemberDecorate instructions that consume this instruction’s Result <id> will apply these decorations to their targets.

From the first sentence, OpDecorate and OpDecorateId can target OpDecorationGroup.  Fine.
From the second, those OpDecorate and OpDecorateId must precede the targeted OpDecorationGroup.

I guess you're concerned about a situation where an OpGroupDecorate can use an OpDecorationGroup result id as a *Target* operand?  I interpret that as banned but I can see your concern.  Maybe I read the second sentence in the description without the "such", and so I'd get

> "All decoration instructions targeting this OpDecorationGroup instruction must precede it"

and I also further interpret that OpGroupDecorate (and member decorate) must follow the OpDecorationGroup it targets.

But I see your concern.  I'll take this to the SPIR working group.

**Comment by pierremoreau** [comment]
> I guess you're concerned about a situation where an OpGroupDecorate can use an OpDecorationGroup result id as a Target operand?

Right, for example would the following be allowed:
```
OpDecorate %1 Constant
%1 = OpDecorationGroup
OpDecorate %2 Restrict
OpGroupDecorate %1 %2
%2 = OpDecorationGroup
OpGroupDecorate %2 %3
%4 = OpTypeInt 32 0
%3 = OpVariable %4 UniformConstant
```

It’s true that “A collector for Decorations from OpDecorate and OpDecorateId instructions.” could imply that OpDecorate and OpDecorateId are the only instructions allowed to target an OpDecorationGroup result ID, but on the other hand from the OpGroupDecorate description:

> Targets is a list of \<id\>s to decorate with the groups of decorations.

so absolutely no restriction is made here about what the targets could be.

Thank you for bringing this up to the SPIR WG.

**Comment by pierremoreau** [comment]
@dneto0 Has there been any progress on this front?
I think I’ll send in some decoration manager rework, and we can remove the extra bits later on. (I have been holding on those changes mainly for lack of time for polishing them, than waiting for an answer.)
