### ISSUE TITLE
Capabilities Whitelist

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#936]
I think we need to create a Capability white list. Up to now we have been skating by just black-listing Capabilities we can't handle, most notably Addresses (non-logical addressing). But with SPIR-V 1.3 we will start seeing VariablePointers and VariablePointersStorageBuffer as part of core, and these capabilities will be problematic for a number of the spirv-opt passes as they are today.

In the past we decided that white-listing was the best way to deal with this type of problem and we already do white-listing of supported extensions.

**Comment by s-perron** [comment]
In general, adding an allows list usually means we have to update more often. Most new capabilities are fine, so I will leave it as is.
