### ISSUE TITLE
Unify all the implementations of HasOnlySupportedRefs()

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#939]
I have been trying to coalesce all the copies of the method HasOnlySupportedRefs() but I don't know how to deal with it:

1. The semantics of the method are vague.  What does it mean exactly to have or to be a "supported ref"?  One comment seems to imply that it's for loads and stores.  But the predicates in the implementations of this method also seem to check other random bits (like decorations or access chains).
2. There are 4 different implementations of this method: LocalAccessChainConvertPass::HasOnlySupportedRefs, LocalSingleStoreElimPass::HasOnlySupportedRefs, LocalSingleBlockLoadStoreElimPass::HasOnlySupportedRefs, and, MemPass::HasOnlySupportedRefs.
3. The first 3 implementations seem identical.  The implementation in MemPass is slightly different.

Ideally, we would have a single implementation in Pass or MemPass.  Or perhaps somewhere else like in class CFG?  Though, I think it makes the most sense inside Pass.

@greg-lunarg, could you take a look?  Thanks.

**Comment by greg-lunarg** [comment]
Yes.
