### ISSUE TITLE
CFG cleanup:  Replace OpPhi having one predecessor block with the value coming from that predecessor.

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#942]
DeadBranchElim does this optimization, and it's a nice cleanup.

In the same vein, OpPhi instructions with all identical operands should be removed.

**Comment by s-perron** [comment]
I believe this was done as part of https://github.com/KhronosGroup/SPIRV-Tools/pull/1173.  Note that CFG cleanup is not incorporated as part of dead branch elimination.

**Comment by s-perron** [comment]
The simplifier will also fold some of these as well.
