### ISSUE TITLE
Implement folding for floating point operations.

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#943]
The existing folder only handles integer arithmetic.  Support for floating point folding should follow the Vulkan spec (https://www.khronos.org/registry/vulkan/specs/1.0/pdf/vkspec.pdf)

**Comment by dnovillo** [comment]
Needed for #889

**Comment by antiagainst** [comment]
Folding of floating points can be tricky. I'd assume we should do this gradually by enabling easy cases first.

**Comment by dneto0** [comment]
The case in #731 should be safe.

As for general folding, Graphics environments assume "fast relaxed math" by default, but Kernel (OpenCL) is like C by default, and is much more careful.   Also, each environment can flip the behaviour via decorations.  
E.g. Graphics code can use NoContraction to prevent certain transforms. 
Kernel code can use FPFastMathMode to enable lots of stuff, including full fast-math mode.

**Comment by dnovillo** [comment]
#1182 has another example of floating point folding that should be handled (equality and inequality)

**Comment by zeux** [comment]
I was looking into this a bit. Are there any SPIRV attributes that actually prevent constant folding for floating point instructions? There are obviously complications for non-constant simplifications such as `a * 0.0` which can't be simplified to 0.0 unless fast-math is enabled; but folding `3.0 * 4.0` to `7.0` or `1.0 > 0.9` to `true` should always be safe and correct?

**Comment by zeux** [comment]
This is now partially addressed (105441360043248e91ec1c8b981f9541dab11083, 6669d8163dca26db521dfea477fd8589c47fb4c8) but still missing some operations (float->int conversion, mix, possibly others)

**Comment by s-perron** [comment]
@zeux Just saw the question from Jan 30.  For shaders, we only need to look at the non-contract decoration.  As for the rules on precision, we need to follow https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#spirvenv-precision-operation.

In particular, "NaNs may not be generated.  Instructions that operate on a NaN may not result in a NaN.".  So we can fold `a * 0.0` to `0.0`.

**Comment by zeux** [comment]
@s-perron Nice, thanks! This is basically `CanFoldFloatingPoint` in const_folding_rules.cpp; `a * 0.0` would be useful to fold to `0.0`, I've also noticed a few cases of `mix(a, b, 0.0)`/`mix(a, b, 1.0)` in our shaders which could be folded when contractions are enabled as well.

**Comment by s-perron** [comment]
A lot of folding has been added in the past two weeks.  @dnovillo Let us know if there is anything else you want done.  I think we can close this item and leave #709 to cover the rest.
