### ISSUE TITLE
Implement folding of constant extraction from constant vectors.

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#944]
For example, the folder should see the individual floating point constants in this code:

// Exmaple 2
#version 450

layout(location = 0)out float o;

void foo(float param[4])
{
}

void main()
{
        float i[4] = { 0.1, 0.2, 0.3, 0.4 };
        foo(i);
        o = i[0] + i[1] + i[2] + i[3];
}

Ideally, o should be folded into 1.0;

**Comment by dnovillo** [comment]
Needed for #889.

**Comment by s-perron** [comment]
Done with https://github.com/KhronosGroup/SPIRV-Tools/pull/1283.
