### ISSUE TITLE
Need legalization pass recipe in optimizer header

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#968]
Right now we have `RegisterPerformancePasses()` and `RegisterSizePasses()` in `optimizer.hpp`.

It would also be nice to have a `RegisterLegalizationPasses()` so that both glslang and spiregg can share the same source of truth. Right now they are separately encoded in both projects:

https://github.com/KhronosGroup/glslang/blob/4036ef154fb0e11a2b235afce3e9b3b819cf5fea/SPIRV/GlslangToSpv.cpp#L6060-L6071

https://github.com/Microsoft/DirectXShaderCompiler/blob/6788ebea4a3a4652d2b182ffe99bdd1bf3a1451c/tools/clang/lib/SPIRV/SPIRVEmitter.cpp#L185-L203

**Comment by dneto0** [comment]
#980 was merged
