### ISSUE TITLE
Validate SubpassData Dim case for OpTypeImage

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#972]
"If Dim is SubpassData, Sampled must be 2, Image Format must be Unknown, and the Execution Model must be Fragment."

**Comment by atgoo** [comment]
I haven't implemented validation rules OpTypeImage yet. It is not in the OpImageXXX section in the spec, so I wan't sure if I wanted to put it together with others.

**Comment by atgoo** [comment]
Was done in https://github.com/KhronosGroup/SPIRV-Tools/pull/1016
