### ISSUE TITLE
Implement scalar replacement

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#983]
In issue #539, it was suggested that we implement scalar replacement.  At the time, we decided to do a local access chain convert, which replaces loads and stores through access chain instruction with insert and extract instructions.  Then the chain of insert and extracts are simplified using the insert-extract elimination.

I believe we need to revisit this decision.  Below is an example that demonstrates the problems:

```
#version 430

layout(set = 0, binding = 1) uniform stuff { float refZ; } s;
float o;

void main()
{
    struct test {
       float constant;
       float dead;
       float inv;
       float bugger;
    } t;
    t.constant = 0.0;
    t.dead = s.refZ;
    t.inv = s.refZ;
    t.bugger = s.refZ;

    while(t.bugger != 0) {
      float const_temp = t.constant + 0.0;
      float inv_temp = t.inv + 1.0;
      t.bugger -= const_temp + inv_temp;

    }
    o = t.bugger;
    return;
}
```

All of the problems stem from the same issue: a property that is true for the member is not true for the whole structure.  That defeats passes that try to optimize based on that property.

Problem 1: We cannot eliminate dead code.  The store to t.dead will turn into an insert instruction that is not removed, even though the value is not used.  ADCE does not see this.

Problem 2: The value for const_temp will always be 0, and the add that uses it could be simplified.  The constant propagator will not be able to propagate this.  @dnovillo Please confirm.

Problem 3: inv_temp is loop invariant and its calculation could be moved out of the loop.  However standard commoning algorithms will be defeated because the input to the extract that feeds the add is not loop invariant.

Collectively, these three problems show the major drawback of the current method: insert and extract instructions will defeat standard algorithms, and either everything will have to be extended to see through them or we will have to have special passes to deal with them.

The other option is to do scalar replacement.  If we do this, very few insert and extract instructions will generated for structures.  They will still be there for vector and matrices, but we can deal with those in a more tactical way.  At the very least, I would like to open this up for discussion.

**Comment by s-perron** [comment]
Here is my suggestions on how to get this done:

1) Identify function scope variables whose only uses are in OpStore instructions, OpLoad instructions, and a least 1 OpAccessChain instruction.
2) All OpAccessChain instruction must have an OpConstant for the first index.

This will give the list of candidates to change.  The changes will need to rewrite the three instructions above.  Suppose we want to rewrite a variable "s".  We first rewrite all of the OpAccessChain instructions:

1) Let "c" be the constant index in the instruction.  If it has not already been created, create a new variable "s_c" (or whatever naming scheme is appropriate).
2) If the OpAccessChain instruction has only one index, replace all uses of the results of the OpAccessChain with uses of the "s_c", and delete the OpAccessChain instruction.
3) If the OpAccessChain instruction has more than one index, rewrite the instruction by replacing "s" with "s_c" and removing the first index.

Once all of the members are replaced, it is time to replace the loads and stores.

1) To replace a load of "s", we create loads of the individual members created above and combine them with an OpCompositeConstruct instruction.  If the OpCompositeConstruct  requires members for which there is no corresponding variable, create a new constant to be used in its place.

2) To replace a store to "s", do a number of OpCompositeExtract on the id to be stored to get the elements need to store to the variables created above.

Note that this will split up the loads and stores to "s" into multiple loads and store; however, because these are "local" variables, all of these instructions will be remove anyway.

**Comment by greg-lunarg** [comment]
A couple questions:

1) Can you point to a real live industrial-strength shader from a shipping product that contains the code above or anything like it?
2) If the answer to 1) is no, should we be making design judgments and decisions based on shaders that we are not sure have any basis in reality?

I have tried as much as possible to keep all my design decisions based on real shaders that I have gotten from teams that are trying to ship Vulkan codes. None of the codes I have seen so far do updates of struct members inside of tight loops.

Maybe there are good reasons to do SROA, but shouldn't they be grounded in real live shaders instead of made-up ones doing unrealistic things?

**Comment by s-perron** [comment]
Yes, I have based my comments on a specific example in a real life industrial-strength shader from a shipping product.  However, I cannot point you to it.

**Comment by greg-lunarg** [comment]
OK. Thanks. That is helpful to know.

I realize that you and the rest of the Google team have your agenda, and that is totally cool. I also realize that some of the design decisions that I have made may not align with yours.

But you should also realize that I have my agenda too, basically size reduction of SPIR-V. So please realize that when I see statements like "we need to revisit this decision", it makes me a little defensive and a little nervous.

My concern is that unbridled SROA will increase SPIR-V size, especially in the presence of control flow and phi functions.

So if you all want SROA for -O, that is cool, but I may need to do my own adaptation of it for -Os.

**Comment by dnovillo** [comment]
On Thu, Nov 30, 2017 at 1:57 PM, greg-lunarg <notifications@github.com>
wrote:

> So if you all want SROA for -O, that is cool, but I may need to do my own
> adaptation of it for -Os.
>

That is perfectly OK and that's the thinking behind -Oconfig=.  Separate
configurations of transformations may be required by different vendors,
different architectures and even different applications.  -O and -Os are
meant to be approximately useful for most situations in the intersection of
those 3.  However, we are very likely going to need -Oconfig= for some
specific cases.

When we start getting transformations that may need to be throttled
depending on the final target (e.g. loop unrolling), we can start using
-Oconfig= or even a future -march= option (a-la llvm/gcc).


Diego.

**Comment by s-perron** [comment]
@greg-lunarg Sure, I can probably tone down my language a little.  I'm not suggesting that we delete the stuff you did.  We should get something that we can experiment with and actually see what works better.  Then we can decide what works best for -O and -Os.  That is more what I mean by "rethink".

**Comment by greg-lunarg** [comment]
That's cool.

If your code indeed does have struct refs in tight loops, then yes, SROA could actually reduce your size. So it is something I need to consider for -Os. As Diego suggested on the other thread, we may need to enhance the way these optimizations are called and controlled.
